XCSF: act_integer.h File Reference
act_integer.h File Reference
integer action functions.
Functions
_Bool act_integer_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool act_integer_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool act_integer_mutate (const XCSF *xcsf, const CL *c)
int act_integer_compute (const XCSF *xcsf, const CL *c, const double *x)
void act_integer_copy (const XCSF *xcsf, CL *to, const CL *from)
void act_integer_cover (const XCSF *xcsf, const CL *c, const double *x, int action)
void act_integer_free (const XCSF *xcsf, const CL *c)
void act_integer_init (const XCSF *xcsf, CL *c)
void act_integer_print (const XCSF *xcsf, const CL *c)
void act_integer_rand (const XCSF *xcsf, const CL *c)
void act_integer_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
size_t act_integer_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t act_integer_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct ActVtbl const act_integer_vtbl
Integer action implemented functions.
Detailed Description
integer action functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file act_integer.h.
Function Documentation
act_integer_compute()
int act_integer_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 63 of file act_integer.c.
References CL::act.
act_integer_copy()
void act_integer_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 70 of file act_integer.c.
References CL::act.
act_integer_cover()
void act_integer_cover (const XCSF * xcsf, const CL * c, const double * x, int action)
Definition at line 92 of file act_integer.c.
References CL::act.
act_integer_crossover()
_Bool act_integer_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 33 of file act_integer.c.
act_integer_free()
void act_integer_free (const XCSF * xcsf, const CL * c)
Definition at line 99 of file act_integer.c.
act_integer_general()
_Bool act_integer_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 39 of file act_integer.c.
References CL::act.
act_integer_init()
void act_integer_init (const XCSF * xcsf, CL * c)
Definition at line 104 of file act_integer.c.
References CL::act, and act_integer_rand().
act_integer_load()
size_t act_integer_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 124 of file act_integer.c.
References CL::act.
act_integer_mutate()
_Bool act_integer_mutate (const XCSF * xcsf, const CL * c)
Definition at line 50 of file act_integer.c.
References CL::act, irand_uniform(), XCSF::num_actions, XCSF::P_MUTATION, and rand_uniform().
act_integer_print()
void act_integer_print (const XCSF * xcsf, const CL * c)
Definition at line 79 of file act_integer.c.
References CL::act.
act_integer_rand()
void act_integer_rand (const XCSF * xcsf, const CL * c)
Definition at line 86 of file act_integer.c.
References CL::act, irand_uniform(), and XCSF::num_actions.
Referenced by act_integer_init().
act_integer_save()
size_t act_integer_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 116 of file act_integer.c.
References CL::act.
act_integer_update()
void act_integer_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 111 of file act_integer.c.
Variable Documentation
act_integer_vtbl
struct ActVtbl const act_integer_vtbl static
Initial value:
= {
    &act_integer_general,
    &act_integer_crossover,
    &act_integer_mutate,
    &act_integer_compute,
    &act_integer_copy,
    &act_integer_cover,
    &act_integer_free,
    &act_integer_init,
    &act_integer_rand,
    &act_integer_print,
    &act_integer_update,
    &act_integer_save,
    &act_integer_load
}
Integer action implemented functions.
Definition at line 43 of file act_integer.h.
Referenced by action_set().