XCSF: act_integer.c File Reference
act_integer.c File Reference
integer action functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "xcsf.h"
#include "utils.h"
#include "action.h"
#include "act_integer.h"
Functions
_Bool act_integer_crossover (XCSF *xcsf, CL *c1, CL *c2)
_Bool act_integer_general (XCSF *xcsf, CL *c1, CL *c2)
_Bool act_integer_mutate (XCSF *xcsf, CL *c)
int act_integer_compute (XCSF *xcsf, CL *c, double *x)
void act_integer_copy (XCSF *xcsf, CL *to, CL *from)
void act_integer_print (XCSF *xcsf, CL *c)
void act_integer_rand (XCSF *xcsf, CL *c)
void act_integer_cover (XCSF *xcsf, CL *c, double *x, int action)
void act_integer_free (XCSF *xcsf, CL *c)
void act_integer_init (XCSF *xcsf, CL *c)
void act_integer_update (XCSF *xcsf, CL *c, double *x, double *y)
size_t act_integer_save (XCSF *xcsf, CL *c, FILE *fp)
size_t act_integer_load (XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
integer action functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file act_integer.c.
Function Documentation
act_integer_compute()
int act_integer_compute (XCSF * xcsf, CL * c, double * x)
Definition at line 60 of file act_integer.c.
References CL::action.
act_integer_copy()
void act_integer_copy (XCSF * xcsf, CL * to, CL * from)
Definition at line 66 of file act_integer.c.
References CL::action.
act_integer_cover()
void act_integer_cover (XCSF * xcsf, CL * c, double * x, int action)
Definition at line 83 of file act_integer.c.
References CL::action.
act_integer_crossover()
_Bool act_integer_crossover (XCSF * xcsf, CL * c1, CL * c2)
Definition at line 33 of file act_integer.c.
act_integer_free()
void act_integer_free (XCSF * xcsf, CL * c)
Definition at line 89 of file act_integer.c.
act_integer_general()
_Bool act_integer_general (XCSF * xcsf, CL * c1, CL * c2)
Definition at line 39 of file act_integer.c.
References CL::action.
act_integer_init()
void act_integer_init (XCSF * xcsf, CL * c)
Definition at line 94 of file act_integer.c.
act_integer_load()
size_t act_integer_load (XCSF * xcsf, CL * c, FILE * fp)
Definition at line 112 of file act_integer.c.
References CL::action.
act_integer_mutate()
_Bool act_integer_mutate (XCSF * xcsf, CL * c)
Definition at line 48 of file act_integer.c.
References CL::action, irand_uniform(), XCSF::num_actions, XCSF::P_MUTATION, and rand_uniform().
act_integer_print()
void act_integer_print (XCSF * xcsf, CL * c)
Definition at line 72 of file act_integer.c.
References CL::action.
act_integer_rand()
void act_integer_rand (XCSF * xcsf, CL * c)
Definition at line 78 of file act_integer.c.
References CL::action, irand_uniform(), and XCSF::num_actions.
act_integer_save()
size_t act_integer_save (XCSF * xcsf, CL * c, FILE * fp)
Definition at line 104 of file act_integer.c.
References CL::action.
act_integer_update()
void act_integer_update (XCSF * xcsf, CL * c, double * x, double * y)
Definition at line 99 of file act_integer.c.