XCSF: action.h File Reference
action.h File Reference
Interface for classifier actions.
Data Structures
struct ActVtbl
Action interface data structure.
Functions
void action_set (const XCSF *xcsf, CL *c)
Sets a classifier's action functions to the implementations.
static size_t act_save (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the action to a binary file.
static size_t act_load (const XCSF *xcsf, CL *c, FILE *fp)
Reads the action from a binary file.
static _Bool act_general (const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the action of classifier c1 is more general than c2.
static _Bool act_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier action crossover.
static _Bool act_mutate (const XCSF *xcsf, const CL *c)
Performs classifier action mutation.
static int act_compute (const XCSF *xcsf, const CL *c, const double *x)
Computes the current classifier action using the input.
static void act_copy (const XCSF *xcsf, CL *to, const CL *from)
Copies the action from one classifier to another.
static void act_cover (const XCSF *xcsf, const CL *c, const double *x, int action)
Generates an action that matches the specified value.
static void act_free (const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier action.
static void act_init (const XCSF *xcsf, CL *c)
Initialises a classifier's action.
static void act_rand (const XCSF *xcsf, const CL *c)
Randomises a classifier's action.
static void act_print (const XCSF *xcsf, const CL *c)
Prints the classifier action.
static void act_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Updates the classifier's action.
Detailed Description
Interface for classifier actions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file action.h.
Function Documentation
act_compute()
static int act_compute (const XCSF * xcsf, const CL * c, const double * x) inline static
Computes the current classifier action using the input.
Parameters
xcsf The XCSF data structure.
c The classifier calculating the action.
x The input state.
Returns
The classifier's action.
Definition at line 109 of file action.h.
References ActVtbl::act_impl_compute, and CL::act_vptr.
Referenced by cl_action().
act_copy()
static void act_copy (const XCSF * xcsf, CL * to, const CL * from) inline static
Copies the action from one classifier to another.
Parameters
xcsf The XCSF data structure.
to The destination classifier.
from The source classifier.
Definition at line 119 of file action.h.
References ActVtbl::act_impl_copy, and CL::act_vptr.
Referenced by cl_copy().
act_cover()
static void act_cover (const XCSF * xcsf, const CL * c, const double * x, int action) inline static
Generates an action that matches the specified value.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is being covered.
x The input state to cover.
action The action to cover.
Definition at line 130 of file action.h.
References ActVtbl::act_impl_cover, and CL::act_vptr.
Referenced by cl_cover().
act_crossover()
static _Bool act_crossover (const XCSF * xcsf, const CL * c1, const CL * c2) inline static
Performs classifier action crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier whose action is being crossed.
c2 The second classifier whose action is being crossed.
Returns
Whether any alterations were made.
Definition at line 88 of file action.h.
References ActVtbl::act_impl_crossover, and CL::act_vptr.
Referenced by cl_crossover().
act_free()
static void act_free (const XCSF * xcsf, const CL * c) inline static
Frees the memory used by the classifier action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be freed.
Definition at line 139 of file action.h.
References ActVtbl::act_impl_free, and CL::act_vptr.
Referenced by cl_free().
act_general()
static _Bool act_general (const XCSF * xcsf, const CL * c1, const CL * c2) inline static
Returns whether the action of classifier c1 is more general than c2.
Parameters
xcsf The XCSF data structure.
c1 The classifier whose action is tested to be more general.
c2 The classifier whose action is tested to be more specific.
Returns
Whether the action of c1 is more general than c2.
Definition at line 77 of file action.h.
References ActVtbl::act_impl_general, and CL::act_vptr.
Referenced by cl_general().
act_init()
static void act_init (const XCSF * xcsf, CL * c) inline static
Initialises a classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be initialised.
Definition at line 148 of file action.h.
References ActVtbl::act_impl_init, and CL::act_vptr.
Referenced by cl_rand().
act_load()
static size_t act_load (const XCSF * xcsf, CL * c, FILE * fp) inline static
Reads the action from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 66 of file action.h.
References ActVtbl::act_impl_load, and CL::act_vptr.
Referenced by cl_load().
act_mutate()
static _Bool act_mutate (const XCSF * xcsf, const CL * c) inline static
Performs classifier action mutation.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is being mutated.
Returns
Whether any alterations were made.
Definition at line 98 of file action.h.
References ActVtbl::act_impl_mutate, and CL::act_vptr.
Referenced by cl_mutate().
act_print()
static void act_print (const XCSF * xcsf, const CL * c) inline static
Prints the classifier action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be printed.
Definition at line 166 of file action.h.
References ActVtbl::act_impl_print, and CL::act_vptr.
Referenced by cl_print().
act_rand()
static void act_rand (const XCSF * xcsf, const CL * c) inline static
Randomises a classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be randomised.
Definition at line 157 of file action.h.
References ActVtbl::act_impl_rand, and CL::act_vptr.
act_save()
static size_t act_save (const XCSF * xcsf, const CL * c, FILE * fp) inline static
Writes the action to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 55 of file action.h.
References ActVtbl::act_impl_save, and CL::act_vptr.
Referenced by cl_save().
act_update()
static void act_update (const XCSF * xcsf, const CL * c, const double * x, const double * y) inline static
Updates the classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be updated.
x The input state.
y The payoff value.
Definition at line 177 of file action.h.
References ActVtbl::act_impl_update, and CL::act_vptr.
Referenced by cl_update().
action_set()
void action_set (const XCSF * xcsf, CL * c)
Sets a classifier's action functions to the implementations.
Parameters
xcsf The XCSF data structure.
c The classifier to set.
Definition at line 38 of file action.c.
References act_integer_vtbl, XCSF::ACT_TYPE, ACT_TYPE_INTEGER, and CL::act_vptr.
Referenced by cl_load(), and cl_rand().