XCSF: blas.h File Reference
blas.h File Reference
Basic linear algebra functions.
Functions
void blas_gemm (int TA, int TB, int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double BETA, double *C, int ldc)
Performs the matrix-matrix multiplication: .
void blas_axpy (int N, double ALPHA, const double *X, int INCX, double *Y, int INCY)
Multiplies the vector X by the scalar ALPHA and adds it to the vector Y.
void blas_scal (int N, double ALPHA, double *X, int INCX)
Scales the vector X by the scalar ALPHA and overwrites it with the result.
void blas_fill (int N, double ALPHA, double *X, int INCX)
Fills the vector X with the value ALPHA.
double blas_dot (int N, const double *X, int INCX, const double *Y, int INCY)
Computes the dot product of two vectors.
Detailed Description
Basic linear algebra functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file blas.h.
Function Documentation
blas_axpy()
void blas_axpy (int N, double ALPHA, const double * X, int INCX, double * Y, int INCY)
Multiplies the vector X by the scalar ALPHA and adds it to the vector Y.
Parameters
N The number of elements in vectors X and Y.
ALPHA Scalar used for multiplication.
X Vector with N elements.
INCX Stride between consecutive elements of X.
Y Vector with N elements.
INCY Stride between consecutive elements of Y.
Definition at line 140 of file blas.c.
Referenced by neural_layer_connected_backward(), neural_layer_connected_update(), pred_nlms_update(), and pred_rls_update().
blas_dot()
double blas_dot (int N, const double * X, int INCX, const double * Y, int INCY)
Computes the dot product of two vectors.
Parameters
N The number of elements in vectors X and Y.
X Vector with N elements.
INCX Stride between consecutive elements of X.
Y Vector with N elements.
INCY Stride between consecutive elements of Y.
Returns
The resulting dot product.
Definition at line 184 of file blas.c.
Referenced by pred_nlms_compute(), pred_nlms_update(), pred_rls_compute(), and pred_rls_update().
blas_fill()
void blas_fill (int N, double ALPHA, double * X, int INCX)
Fills the vector X with the value ALPHA.
Parameters
N The number of elements in vector X.
ALPHA The value to fill the vector.
X Vector with N elements.
INCX Stride between consecutive elements of X.
Definition at line 168 of file blas.c.
Referenced by pred_nlms_init(), and pred_rls_init().
blas_gemm()
void blas_gemm (int TA, int TB, int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double BETA, double * C, int ldc)
Performs the matrix-matrix multiplication: .
Parameters
TA Operation op(A) that is non- or (conj.) transpose.
TB Operation op(B) that is non- or (conj.) transpose.
M Number of rows of matrix op(A) and C.
N Number of columns of matrix op(B) and C.
K Number of columns of op(A) and rows of op(B).
ALPHA Scalar used for multiplication.
A Array of dimension lda × K with lda >= max(1,M) if TA=0 and lda × M with lda >= max(1,K) otherwise.
lda Leading dimension of two-dimensional array used to store the matrix A.
B Array of dimension ldb × N with ldb >= max(1,K) if TB=0 and ldb × K with ldb >= max(1,N) otherwise.
ldb Leading dimension of two-dimensional array used to store matrix B.
BETA Scalar used for multiplication.
C Array of dimension ldc × N with ldc >= max(1,M).
ldc Leading dimension of a two-dimensional array used to store the matrix C.
Definition at line 106 of file blas.c.
References gemm_nn(), gemm_nt(), gemm_tn(), and gemm_tt().
Referenced by neural_layer_connected_backward(), neural_layer_connected_forward(), and pred_rls_update().
blas_scal()
void blas_scal (int N, double ALPHA, double * X, int INCX)
Scales the vector X by the scalar ALPHA and overwrites it with the result.
Parameters
N The number of elements in vector X.
ALPHA Scalar used for multiplication.
X Vector with N elements.
INCX Stride between consecutive elements of X.
Definition at line 154 of file blas.c.
Referenced by neural_layer_connected_update(), and pred_rls_update().