XCSF: blas.c File Reference
blas.c File Reference
Basic linear algebra functions.
#include <stdio.h>
#include <stdlib.h>
Functions
static void gemm_nn (int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double *C, int ldc)
static void gemm_nt (int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double *C, int ldc)
static void gemm_tn (int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double *C, int ldc)
static void gemm_tt (int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double *C, int ldc)
static void gemm_cpu (int TA, int TB, int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double BETA, double *C, int ldc)
static void axpy_cpu (int N, double ALPHA, const double *X, int INCX, double *Y, int INCY)
static void scal_cpu (int N, double ALPHA, double *X, int INCX)
static void fill_cpu (int N, double ALPHA, double *X, int INCX)
static double dot_cpu (int N, const double *X, int INCX, const double *Y, int INCY)
void blas_gemm (int TA, int TB, int M, int N, int K, double ALPHA, const double *A, int lda, const double *B, int ldb, double BETA, double *C, int ldc)
void blas_axpy (int N, double ALPHA, const double *X, int INCX, double *Y, int INCY)
void blas_scal (int N, double ALPHA, double *X, int INCX)
void blas_fill (int N, double ALPHA, double *X, int INCX)
double blas_dot (int N, const double *X, int INCX, const double *Y, int INCY)
Detailed Description
Basic linear algebra functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file blas.c.
Function Documentation
axpy_cpu()
static void axpy_cpu (int N, double ALPHA, const double * X, int INCX, double * Y, int INCY) static
Definition at line 118 of file blas.c.
Referenced by blas_axpy().
blas_axpy()
void blas_axpy (int N, double ALPHA, const double * X, int INCX, double * Y, int INCY)
Definition at line 162 of file blas.c.
References axpy_cpu().
Referenced by neural_layer_connected_backward(), neural_layer_connected_update(), and pred_rls_update().
blas_dot()
double blas_dot (int N, const double * X, int INCX, const double * Y, int INCY)
Definition at line 177 of file blas.c.
References dot_cpu().
Referenced by pred_rls_update().
blas_fill()
void blas_fill (int N, double ALPHA, double * X, int INCX)
Definition at line 172 of file blas.c.
References fill_cpu().
blas_gemm()
void blas_gemm (int TA, int TB, int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double BETA, double * C, int ldc)
Definition at line 148 of file blas.c.
References gemm_cpu(), and gemm_gpu().
Referenced by neural_layer_connected_backward(), neural_layer_connected_forward(), and pred_rls_update().
blas_scal()
void blas_scal (int N, double ALPHA, double * X, int INCX)
Definition at line 167 of file blas.c.
References scal_cpu().
Referenced by neural_layer_connected_update().
dot_cpu()
static double dot_cpu (int N, const double * X, int INCX, const double * Y, int INCY) static
Definition at line 139 of file blas.c.
Referenced by blas_dot().
fill_cpu()
static void fill_cpu (int N, double ALPHA, double * X, int INCX) static
Definition at line 132 of file blas.c.
Referenced by blas_fill().
gemm_cpu()
static void gemm_cpu (int TA, int TB, int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double BETA, double * C, int ldc) static
Definition at line 93 of file blas.c.
References gemm_nn(), gemm_nt(), gemm_tn(), and gemm_tt().
Referenced by blas_gemm().
gemm_nn()
static void gemm_nn (int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double * C, int ldc) static
Definition at line 31 of file blas.c.
Referenced by gemm_cpu().
gemm_nt()
static void gemm_nt (int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double * C, int ldc) static
Definition at line 46 of file blas.c.
Referenced by gemm_cpu().
gemm_tn()
static void gemm_tn (int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double * C, int ldc) static
Definition at line 62 of file blas.c.
Referenced by gemm_cpu().
gemm_tt()
static void gemm_tt (int M, int N, int K, double ALPHA, const double * A, int lda, const double * B, int ldb, double * C, int ldc) static
Definition at line 77 of file blas.c.
Referenced by gemm_cpu().
scal_cpu()
static void scal_cpu (int N, double ALPHA, double * X, int INCX) static
Definition at line 125 of file blas.c.
Referenced by blas_scal().