XCSF: cl.c File Reference
cl.c File Reference
Functions operating on classifiers.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "loss.h"
#include "sam.h"
#include "condition.h"
#include "prediction.h"
#include "action.h"
#include "cl.h"
Functions
static double cl_update_err (const XCSF *xcsf, CL *c, const double *y)
Updates the error of the classifier using the payoff.
static double cl_update_size (const XCSF *xcsf, CL *c, double num_sum)
Updates the set size estimate for the classifier.
void cl_init (const XCSF *xcsf, CL *c, int size, int time)
Initialises a new classifier.
void cl_copy (const XCSF *xcsf, CL *to, const CL *from)
Copies the condition, action, and prediction from one classifier to another.
void cl_cover (const XCSF *xcsf, CL *c, const double *x, int action)
Covers the condition and action for a classifier.
void cl_rand (const XCSF *xcsf, CL *c)
Initialises random actions, conditions and predictions.
double cl_del_vote (const XCSF *xcsf, const CL *c, double avg_fit)
Returns the deletion vote of the classifier.
double cl_acc (const XCSF *xcsf, const CL *c)
Returns the accuracy of the classifier.
void cl_update (const XCSF *xcsf, CL *c, const double *x, const double *y, int set_num, _Bool cur)
Updates the classifier's parameters as well as condition, action, and prediction depending on the knowledge representation.
void cl_update_fit (const XCSF *xcsf, CL *c, double acc_sum, double acc)
Updates the fitness of the classifier.
void cl_free (const XCSF *xcsf, CL *c)
Frees the memory used by the classifier.
void cl_print (const XCSF *xcsf, const CL *c, _Bool printc, _Bool printa, _Bool printp)
Prints the classifier.
_Bool cl_match (const XCSF *xcsf, CL *c, const double *x)
Calculates whether the classifier matches the input.
double cl_mfrac (const XCSF *xcsf, const CL *c)
Returns the fraction of observed inputs matched by the classifier.
_Bool cl_m (const XCSF *xcsf, const CL *c)
Returns whether the classifier matched the most recent input.
int cl_action (const XCSF *xcsf, CL *c, const double *x)
Computes the current classifier action using the input.
const double * cl_predict (const XCSF *xcsf, const CL *c, const double *x)
Computes the current classifier payoff prediction using the input.
_Bool cl_subsumer (const XCSF *xcsf, const CL *c)
Returns whether the classifier is a potential subsumer.
_Bool cl_general (const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether classifier c1 is more general than c2.
_Bool cl_mutate (XCSF *xcsf, const CL *c)
Performs classifier mutation.
_Bool cl_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier crossover.
double cl_mutation_rate (const XCSF *xcsf, const CL *c, int m)
Returns the classifier self-adaptive mutation rate.
int cl_cond_size (const XCSF *xcsf, const CL *c)
Returns the size of the classifier condition.
int cl_pred_size (const XCSF *xcsf, const CL *c)
Returns the size of the classifier prediction.
size_t cl_save (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the classifier to a binary file.
size_t cl_load (const XCSF *xcsf, CL *c, FILE *fp)
Reads the classifier from a binary file.
Detailed Description
Functions operating on classifiers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file cl.c.
Function Documentation
cl_acc()
double cl_acc (const XCSF * xcsf, const CL * c)
Returns the accuracy of the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier.
Returns
The classifier's accuracy.
Definition at line 137 of file cl.c.
References XCSF::ALPHA, XCSF::EPS_0, CL::err, and XCSF::NU.
Referenced by clset_update_fit().
cl_action()
int cl_action (const XCSF * xcsf, CL * c, const double * x)
Computes the current classifier action using the input.
Parameters
xcsf The XCSF data structure.
c The classifier calculating the action.
x The input state.
Returns
The classifier's action.
Definition at line 317 of file cl.c.
References act_compute(), and CL::action.
Referenced by clset_match().
cl_cond_size()
int cl_cond_size (const XCSF * xcsf, const CL * c)
Returns the size of the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition size to return.
Returns
The size of the condition.
Definition at line 430 of file cl.c.
References cond_size().
Referenced by clset_mean_cond_size(), and clset_pop_roulette().
cl_copy()
void cl_copy (const XCSF * xcsf, CL * to, const CL * from)
Copies the condition, action, and prediction from one classifier to another.
Parameters
xcsf The XCSF data structure.
to The destination classifier.
from The source classifier.
Definition at line 71 of file cl.c.
References act_copy(), CL::act_vptr, cond_copy(), CL::cond_vptr, CL::mu, pred_copy(), pred_init(), XCSF::PRED_RESET, CL::pred_vptr, and sam_copy().
Referenced by ea().
cl_cover()
void cl_cover (const XCSF * xcsf, CL * c, const double * x, int action)
Covers the condition and action for a classifier.
Parameters
xcsf The XCSF data structure.
c The classifier being covered.
x The input state to cover.
action The action to cover.
Definition at line 94 of file cl.c.
References act_cover(), cl_rand(), and cond_cover().
Referenced by clset_cover().
cl_crossover()
_Bool cl_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Performs classifier crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier being crossed.
c2 The second classifier being crossed.
Returns
Whether any alterations were made.
Definition at line 400 of file cl.c.
References act_crossover(), cond_crossover(), and pred_crossover().
Referenced by ea().
cl_del_vote()
double cl_del_vote (const XCSF * xcsf, const CL * c, double avg_fit)
Returns the deletion vote of the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to calculate the deletion vote.
avg_fit The population mean fitness.
Returns
The classifier's deletion vote.
Definition at line 123 of file cl.c.
References XCSF::DELTA, CL::exp, CL::fit, CL::num, CL::size, and XCSF::THETA_DEL.
Referenced by clset_pop_roulette().
cl_free()
void cl_free (const XCSF * xcsf, CL * c)
Frees the memory used by the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to free.
Definition at line 224 of file cl.c.
References act_free(), cond_free(), CL::mu, pred_free(), CL::prediction, and sam_free().
Referenced by clset_kill(), ea_add(), and ea_subsume().
cl_general()
_Bool cl_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Returns whether classifier c1 is more general than c2.
Parameters
xcsf The XCSF data structure.
c1 The classifier tested to be more general.
c2 The classifier tested to be more specific.
Returns
Whether c1 is more general than c2.
Definition at line 356 of file cl.c.
References act_general(), and cond_general().
Referenced by clset_subsumption(), and ea_subsume().
cl_init()
void cl_init (const XCSF * xcsf, CL * c, int size, int time)
Initialises a new classifier.
Parameters
xcsf The XCSF data structure.
c The classifier data structure to initialise.
size The initial set size value.
time The current number of XCSF learning trials.
Definition at line 48 of file cl.c.
References CL::action, CL::age, CL::err, CL::exp, CL::fit, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, CL::m, CL::mtotal, CL::mu, CL::num, XCSF::num_y_vars, CL::prediction, sam_init(), CL::size, and CL::time.
Referenced by clset_cover(), clset_pop_init(), and ea().
cl_load()
size_t cl_load (const XCSF * xcsf, CL * c, FILE * fp)
Reads the classifier from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier to load.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 481 of file cl.c.
References act_load(), CL::action, action_set(), CL::age, cond_load(), condition_set(), CL::err, CL::exp, CL::fit, CL::m, CL::mtotal, CL::mu, CL::num, XCSF::num_y_vars, pred_load(), CL::prediction, prediction_set(), XCSF::SAM_NUM, CL::size, and CL::time.
Referenced by clset_pop_load().
cl_m()
_Bool cl_m (const XCSF * xcsf, const CL * c)
Returns whether the classifier matched the most recent input.
Parameters
xcsf The XCSF data structure.
c The classifier to match.
Returns
Whether the classifier matched the most recent input.
Definition at line 304 of file cl.c.
References CL::m.
Referenced by clset_match().
cl_match()
_Bool cl_match (const XCSF * xcsf, CL * c, const double * x)
Calculates whether the classifier matches the input.
Parameters
xcsf The XCSF data structure.
c The classifier to match.
x The input state.
Returns
Whether the classifier matches the input.
Definition at line 273 of file cl.c.
References CL::age, cond_match(), CL::m, and CL::mtotal.
Referenced by clset_match().
cl_mfrac()
double cl_mfrac (const XCSF * xcsf, const CL * c)
Returns the fraction of observed inputs matched by the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to match.
Returns
The fraction of matching inputs.
Definition at line 289 of file cl.c.
References CL::age, and CL::mtotal.
Referenced by cl_print(), and clset_mfrac().
cl_mutate()
_Bool cl_mutate (XCSF * xcsf, const CL * c)
Performs classifier mutation.
Parameters
xcsf The XCSF data structure.
c The classifier being mutated.
Returns
Whether any alterations were made.
Definition at line 370 of file cl.c.
References act_mutate(), cond_mutate(), XCSF::E_MUTATION, XCSF::F_MUTATION, CL::mu, XCSF::P_MUTATION, pred_mutate(), XCSF::S_MUTATION, and XCSF::SAM_NUM.
Referenced by ea().
cl_mutation_rate()
double cl_mutation_rate (const XCSF * xcsf, const CL * c, int m)
Returns the classifier self-adaptive mutation rate.
Parameters
xcsf The XCSF data structure.
c The classifier whose rate to return.
m Which mutation rate to return.
Returns
The current mutation rate.
Definition at line 418 of file cl.c.
References CL::mu.
Referenced by clset_mean_mut().
cl_pred_size()
int cl_pred_size (const XCSF * xcsf, const CL * c)
Returns the size of the classifier prediction.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction size to return.
Returns
The size of the prediction.
Definition at line 441 of file cl.c.
References pred_size().
Referenced by clset_mean_pred_size(), and clset_pop_roulette().
cl_predict()
const double* cl_predict (const XCSF * xcsf, const CL * c, const double * x)
Computes the current classifier payoff prediction using the input.
Parameters
xcsf The XCSF data structure.
c The classifier making the prediction.
x The input state.
Returns
The classifier's payoff predictions.
Definition at line 330 of file cl.c.
References pred_compute().
Referenced by cl_update(), clset_pred(), and pa_build().
cl_print()
void cl_print (const XCSF * xcsf, const CL * c, _Bool printc, _Bool printa, _Bool printp)
Prints the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to print.
printc Whether to print the condition.
printa Whether to print the action.
printp Whether to print the prediction.
Definition at line 242 of file cl.c.
References act_print(), CL::age, cl_mfrac(), cond_print(), CL::err, CL::exp, CL::fit, CL::mu, CL::num, pred_print(), sam_print(), CL::size, and CL::time.
Referenced by clset_print().
cl_rand()
void cl_rand (const XCSF * xcsf, CL * c)
Initialises random actions, conditions and predictions.
Parameters
xcsf The XCSF data structure.
c The classifier being randomly initialised.
Definition at line 106 of file cl.c.
References act_init(), action_set(), cond_init(), condition_set(), pred_init(), and prediction_set().
Referenced by cl_cover(), and clset_pop_init().
cl_save()
size_t cl_save (const XCSF * xcsf, const CL * c, FILE * fp)
Writes the classifier to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier to save.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 453 of file cl.c.
References act_save(), CL::action, CL::age, cond_save(), CL::err, CL::exp, CL::fit, CL::m, CL::mtotal, CL::mu, CL::num, XCSF::num_y_vars, pred_save(), CL::prediction, XCSF::SAM_NUM, CL::size, and CL::time.
Referenced by clset_pop_save().
cl_subsumer()
_Bool cl_subsumer (const XCSF * xcsf, const CL * c)
Returns whether the classifier is a potential subsumer.
Parameters
xcsf The XCSF data structure.
c The classifier to print.
Returns
Whether the classifier is an eligible subsumer.
Definition at line 341 of file cl.c.
References XCSF::EPS_0, CL::err, CL::exp, and XCSF::THETA_SUB.
Referenced by clset_subsumption(), and ea_subsume().
cl_update()
void cl_update (const XCSF * xcsf, CL * c, const double * x, const double * y, int set_num, _Bool cur)
Updates the classifier's parameters as well as condition, action, and prediction depending on the knowledge representation.
Parameters
xcsf The XCSF data structure.
c The classifier to update.
x The input state.
y The payoff value.
set_num The number of micro-classifiers in the set.
cur Whether the payoff is for the current or previous state.
Definition at line 155 of file cl.c.
References act_update(), cl_predict(), cl_update_err(), cl_update_size(), cond_update(), CL::exp, and pred_update().
Referenced by clset_update().
cl_update_err()
static double cl_update_err (const XCSF * xcsf, CL * c, const double * y) static
Updates the error of the classifier using the payoff.
Precondition
Classifier prediction must have been updated for the input state.
Parameters
xcsf The XCSF data structure.
c The classifier to update.
y The payoff value.
Returns
Error multiplied by numerosity.
Definition at line 177 of file cl.c.
References XCSF::BETA, CL::err, CL::exp, XCSF::loss_ptr, CL::num, and CL::prediction.
Referenced by cl_update().
cl_update_fit()
void cl_update_fit (const XCSF * xcsf, CL * c, double acc_sum, double acc)
Updates the fitness of the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to update.
acc_sum The sum of all the accuracies in the set.
acc The accuracy of the classifier.
Definition at line 196 of file cl.c.
References XCSF::BETA, CL::fit, and CL::num.
Referenced by clset_update_fit().
cl_update_size()
static double cl_update_size (const XCSF * xcsf, CL * c, double num_sum) static
Updates the set size estimate for the classifier.
Parameters
xcsf The XCSF data structure.
c The classifier to update.
num_sum The number of micro-classifiers in the set.
Returns
Set size multiplied by numerosity.
Definition at line 208 of file cl.c.
References XCSF::BETA, CL::exp, CL::num, and CL::size.
Referenced by cl_update().