XCSF: XCS Class Reference
XCS Class Reference
Public Member Functions
XCS (int x_dim, int n_actions, _Bool multistep)
Constructor for single-step reinforcement learning.
XCS (int x_dim, int y_dim)
Constructor for supervised learning with default config.
XCS (int x_dim, int y_dim, const char *filename)
Constructor for supervised learning with a specified config.
void xcs_init (const char *filename)
Initialises python XCS structure.
double version ()
size_t save (char *fname)
size_t load (char *fname)
void print_pop (_Bool printc, _Bool printa, _Bool printp)
void single_reset ()
int single_decision (py::array_t< double > input, _Bool explore)
void single_update (double reward)
double single_error (double reward)
double fit (py::array_t< double > train_X, py::array_t< double > train_Y, _Bool shuffle)
double fit (py::array_t< double > train_X, py::array_t< double > train_Y, py::array_t< double > test_X, py::array_t< double > test_Y, _Bool shuffle)
py::array_t< double > predict (py::array_t< double > x)
double score (py::array_t< double > test_X, py::array_t< double > test_Y)
py::list get_cond_num_neurons ()
py::list get_cond_max_neurons ()
py::list get_pred_num_neurons ()
py::list get_pred_max_neurons ()
int get_omp_num_threads ()
_Bool get_pop_init ()
int get_max_trials ()
int get_perf_trials ()
int get_pop_max_size ()
int get_loss_func ()
double get_alpha ()
double get_beta ()
double get_delta ()
double get_eps_0 ()
double get_err_reduc ()
double get_fit_reduc ()
double get_init_error ()
double get_init_fitness ()
double get_nu ()
int get_m_probation ()
int get_theta_del ()
int get_act_type ()
int get_cond_type ()
int get_pred_type ()
double get_p_crossover ()
double get_theta_ea ()
int get_lambda ()
int get_ea_select_type ()
double get_ea_select_size ()
int get_sam_type ()
double get_max_con ()
double get_min_con ()
double get_cond_smin ()
double get_cond_bits ()
_Bool get_cond_evolve_weights ()
_Bool get_cond_evolve_neurons ()
_Bool get_cond_evolve_functions ()
int get_cond_output_activation ()
int get_cond_hidden_activation ()
int get_pred_output_activation ()
int get_pred_hidden_activation ()
double get_pred_momentum ()
_Bool get_pred_evolve_weights ()
_Bool get_pred_evolve_neurons ()
_Bool get_pred_evolve_functions ()
_Bool get_pred_evolve_eta ()
_Bool get_pred_sgd_weights ()
_Bool get_pred_reset ()
int get_max_neuron_mod ()
int get_dgp_num_nodes ()
_Bool get_reset_states ()
int get_max_k ()
int get_max_t ()
int get_gp_num_cons ()
int get_gp_init_depth ()
double get_pred_eta ()
double get_cond_eta ()
double get_pred_x0 ()
double get_pred_rls_scale_factor ()
double get_pred_rls_lambda ()
int get_theta_sub ()
_Bool get_ea_subsumption ()
_Bool get_set_subsumption ()
int get_pop_size ()
int get_pop_num ()
int get_time ()
double get_x_dim ()
double get_y_dim ()
double get_n_actions ()
double get_pop_mean_cond_size ()
double get_pop_mean_pred_size ()
double get_pop_mean_pred_eta (int layer)
double get_pop_mean_pred_neurons (int layer)
double get_pop_mean_pred_layers ()
double get_msetsize ()
double get_mfrac ()
int get_teletransportation ()
double get_gamma ()
double get_p_explore ()
void set_omp_num_threads (int a)
void set_cond_num_neurons (py::list &a)
void set_cond_max_neurons (py::list &a)
void set_pred_num_neurons (py::list &a)
void set_pred_max_neurons (py::list &a)
void set_pop_init (_Bool a)
void set_max_trials (int a)
void set_perf_trials (int a)
void set_pop_max_size (int a)
void set_loss_func (int a)
void set_alpha (double a)
void set_beta (double a)
void set_delta (double a)
void set_eps_0 (double a)
void set_err_reduc (double a)
void set_fit_reduc (double a)
void set_init_error (double a)
void set_init_fitness (double a)
void set_nu (double a)
void set_m_probation (int a)
void set_theta_del (int a)
void set_act_type (int a)
void set_cond_type (int a)
void set_pred_type (int a)
void set_p_crossover (double a)
void set_theta_ea (double a)
void set_lambda (int a)
void set_ea_select_type (int a)
void set_ea_select_size (double a)
void set_sam_type (int a)
void set_max_con (double a)
void set_min_con (double a)
void set_cond_smin (double a)
void set_cond_bits (double a)
void set_cond_evolve_weights (_Bool a)
void set_cond_evolve_neurons (_Bool a)
void set_cond_evolve_functions (_Bool a)
void set_cond_output_activation (int a)
void set_cond_hidden_activation (int a)
void set_pred_output_activation (int a)
void set_pred_hidden_activation (int a)
void set_pred_momentum (double a)
void set_pred_evolve_weights (_Bool a)
void set_pred_evolve_neurons (_Bool a)
void set_pred_evolve_functions (_Bool a)
void set_pred_evolve_eta (_Bool a)
void set_pred_sgd_weights (_Bool a)
void set_pred_reset (_Bool a)
void set_max_neuron_mod (int a)
void set_dgp_num_nodes (int a)
void set_reset_states (_Bool a)
void set_max_k (int a)
void set_max_t (int a)
void set_gp_num_cons (int a)
void set_gp_init_depth (int a)
void set_pred_eta (double a)
void set_cond_eta (double a)
void set_pred_x0 (double a)
void set_pred_rls_scale_factor (double a)
void set_pred_rls_lambda (double a)
void set_theta_sub (int a)
void set_ea_subsumption (_Bool a)
void set_set_subsumption (_Bool a)
void set_teletransportation (int a)
void set_gamma (double a)
void set_p_explore (double a)
Private Attributes
XCSF xcs
XCSF data structure.
double * state
Current input state for RL.
int action
Current action for RL.
INPUT * train_data
Current training data for supervised learning.
INPUT * test_data
Currrent test data for supervised learning.
Detailed Description
Definition at line 52 of file pybind_wrapper.cpp.
Constructor & Destructor Documentation
XCS() [1/3]
XCS::XCS (int x_dim, int n_actions, _Bool multistep) inline
Constructor for single-step reinforcement learning.
Definition at line 65 of file pybind_wrapper.cpp.
References XCSF::n_actions, pa_init(), XCSF::x_dim, xcs_init(), xcs_single_init(), and XCSF::y_dim.
XCS() [2/3]
XCS::XCS (int x_dim, int y_dim) inline
Constructor for supervised learning with default config.
Definition at line 79 of file pybind_wrapper.cpp.
XCS() [3/3]
XCS::XCS (int x_dim, int y_dim, const char * filename) inline
Constructor for supervised learning with a specified config.
Definition at line 84 of file pybind_wrapper.cpp.
References XCSF::n_actions, XCSF::x_dim, xcs_init(), and XCSF::y_dim.
Member Function Documentation
fit() [1/2]
double XCS::fit (py::array_t< double > train_X, py::array_t< double > train_Y, _Bool shuffle) inline
Definition at line 155 of file pybind_wrapper.cpp.
References clset_pop_init(), INPUT::n_samples, XCSF::time, INPUT::x, INPUT::x_dim, xcsf_fit(), INPUT::y, and INPUT::y_dim.
Referenced by pybind11_init_xcsf().
fit() [2/2]
double XCS::fit (py::array_t< double > train_X, py::array_t< double > train_Y, py::array_t< double > test_X, py::array_t< double > test_Y, _Bool shuffle) inline
Definition at line 177 of file pybind_wrapper.cpp.
References clset_pop_init(), INPUT::n_samples, XCSF::time, INPUT::x, INPUT::x_dim, xcsf_fit(), INPUT::y, and INPUT::y_dim.
get_act_type()
int XCS::get_act_type () inline
Definition at line 304 of file pybind_wrapper.cpp.
References XCSF::ACT_TYPE.
Referenced by pybind11_init_xcsf().
get_alpha()
double XCS::get_alpha () inline
Definition at line 293 of file pybind_wrapper.cpp.
References XCSF::ALPHA.
Referenced by pybind11_init_xcsf().
get_beta()
double XCS::get_beta () inline
Definition at line 294 of file pybind_wrapper.cpp.
References XCSF::BETA.
Referenced by pybind11_init_xcsf().
get_cond_bits()
double XCS::get_cond_bits () inline
Definition at line 316 of file pybind_wrapper.cpp.
References XCSF::COND_BITS.
Referenced by pybind11_init_xcsf().
get_cond_eta()
double XCS::get_cond_eta () inline
Definition at line 339 of file pybind_wrapper.cpp.
References XCSF::COND_ETA.
Referenced by pybind11_init_xcsf().
get_cond_evolve_functions()
_Bool XCS::get_cond_evolve_functions () inline
Definition at line 319 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_FUNCTIONS.
Referenced by pybind11_init_xcsf().
get_cond_evolve_neurons()
_Bool XCS::get_cond_evolve_neurons () inline
Definition at line 318 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_NEURONS.
Referenced by pybind11_init_xcsf().
get_cond_evolve_weights()
_Bool XCS::get_cond_evolve_weights () inline
Definition at line 317 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_WEIGHTS.
Referenced by pybind11_init_xcsf().
get_cond_hidden_activation()
int XCS::get_cond_hidden_activation () inline
Definition at line 321 of file pybind_wrapper.cpp.
References XCSF::COND_HIDDEN_ACTIVATION.
Referenced by pybind11_init_xcsf().
get_cond_max_neurons()
py::list XCS::get_cond_max_neurons () inline
Definition at line 260 of file pybind_wrapper.cpp.
References XCSF::COND_MAX_NEURONS, and MAX_LAYERS.
Referenced by pybind11_init_xcsf().
get_cond_num_neurons()
py::list XCS::get_cond_num_neurons () inline
Definition at line 251 of file pybind_wrapper.cpp.
References XCSF::COND_NUM_NEURONS, and MAX_LAYERS.
Referenced by pybind11_init_xcsf().
get_cond_output_activation()
int XCS::get_cond_output_activation () inline
Definition at line 320 of file pybind_wrapper.cpp.
References XCSF::COND_OUTPUT_ACTIVATION.
Referenced by pybind11_init_xcsf().
get_cond_smin()
double XCS::get_cond_smin () inline
Definition at line 315 of file pybind_wrapper.cpp.
References XCSF::COND_SMIN.
Referenced by pybind11_init_xcsf().
get_cond_type()
int XCS::get_cond_type () inline
Definition at line 305 of file pybind_wrapper.cpp.
References XCSF::COND_TYPE.
Referenced by pybind11_init_xcsf().
get_delta()
double XCS::get_delta () inline
Definition at line 295 of file pybind_wrapper.cpp.
References XCSF::DELTA.
Referenced by pybind11_init_xcsf().
get_dgp_num_nodes()
int XCS::get_dgp_num_nodes () inline
Definition at line 332 of file pybind_wrapper.cpp.
References XCSF::DGP_NUM_NODES.
Referenced by pybind11_init_xcsf().
get_ea_select_size()
double XCS::get_ea_select_size () inline
Definition at line 311 of file pybind_wrapper.cpp.
References XCSF::EA_SELECT_SIZE.
Referenced by pybind11_init_xcsf().
get_ea_select_type()
int XCS::get_ea_select_type () inline
Definition at line 310 of file pybind_wrapper.cpp.
References XCSF::EA_SELECT_TYPE.
Referenced by pybind11_init_xcsf().
get_ea_subsumption()
_Bool XCS::get_ea_subsumption () inline
Definition at line 344 of file pybind_wrapper.cpp.
References XCSF::EA_SUBSUMPTION.
Referenced by pybind11_init_xcsf().
get_eps_0()
double XCS::get_eps_0 () inline
Definition at line 296 of file pybind_wrapper.cpp.
References XCSF::EPS_0.
Referenced by pybind11_init_xcsf().
get_err_reduc()
double XCS::get_err_reduc () inline
Definition at line 297 of file pybind_wrapper.cpp.
References XCSF::ERR_REDUC.
Referenced by pybind11_init_xcsf().
get_fit_reduc()
double XCS::get_fit_reduc () inline
Definition at line 298 of file pybind_wrapper.cpp.
References XCSF::FIT_REDUC.
Referenced by pybind11_init_xcsf().
get_gamma()
double XCS::get_gamma () inline
Definition at line 360 of file pybind_wrapper.cpp.
References XCSF::GAMMA.
Referenced by pybind11_init_xcsf().
get_gp_init_depth()
int XCS::get_gp_init_depth () inline
Definition at line 337 of file pybind_wrapper.cpp.
References XCSF::GP_INIT_DEPTH.
Referenced by pybind11_init_xcsf().
get_gp_num_cons()
int XCS::get_gp_num_cons () inline
Definition at line 336 of file pybind_wrapper.cpp.
References XCSF::GP_NUM_CONS.
Referenced by pybind11_init_xcsf().
get_init_error()
double XCS::get_init_error () inline
Definition at line 299 of file pybind_wrapper.cpp.
References XCSF::INIT_ERROR.
Referenced by pybind11_init_xcsf().
get_init_fitness()
double XCS::get_init_fitness () inline
Definition at line 300 of file pybind_wrapper.cpp.
References XCSF::INIT_FITNESS.
Referenced by pybind11_init_xcsf().
get_lambda()
int XCS::get_lambda () inline
Definition at line 309 of file pybind_wrapper.cpp.
References XCSF::LAMBDA.
Referenced by pybind11_init_xcsf().
get_loss_func()
int XCS::get_loss_func () inline
Definition at line 292 of file pybind_wrapper.cpp.
References XCSF::LOSS_FUNC.
Referenced by pybind11_init_xcsf().
get_m_probation()
int XCS::get_m_probation () inline
Definition at line 302 of file pybind_wrapper.cpp.
References XCSF::M_PROBATION.
Referenced by pybind11_init_xcsf().
get_max_con()
double XCS::get_max_con () inline
Definition at line 313 of file pybind_wrapper.cpp.
References XCSF::COND_MAX.
Referenced by pybind11_init_xcsf().
get_max_k()
int XCS::get_max_k () inline
Definition at line 334 of file pybind_wrapper.cpp.
References XCSF::MAX_K.
Referenced by pybind11_init_xcsf().
get_max_neuron_mod()
int XCS::get_max_neuron_mod () inline
Definition at line 331 of file pybind_wrapper.cpp.
References XCSF::MAX_NEURON_MOD.
Referenced by pybind11_init_xcsf().
get_max_t()
int XCS::get_max_t () inline
Definition at line 335 of file pybind_wrapper.cpp.
References XCSF::MAX_T.
Referenced by pybind11_init_xcsf().
get_max_trials()
int XCS::get_max_trials () inline
Definition at line 289 of file pybind_wrapper.cpp.
References XCSF::MAX_TRIALS.
Referenced by pybind11_init_xcsf().
get_mfrac()
double XCS::get_mfrac () inline
Definition at line 358 of file pybind_wrapper.cpp.
References XCSF::mfrac.
Referenced by pybind11_init_xcsf().
get_min_con()
double XCS::get_min_con () inline
Definition at line 314 of file pybind_wrapper.cpp.
References XCSF::COND_MIN.
Referenced by pybind11_init_xcsf().
get_msetsize()
double XCS::get_msetsize () inline
Definition at line 357 of file pybind_wrapper.cpp.
References XCSF::msetsize.
Referenced by pybind11_init_xcsf().
get_n_actions()
double XCS::get_n_actions () inline
Definition at line 351 of file pybind_wrapper.cpp.
References XCSF::n_actions.
Referenced by pybind11_init_xcsf().
get_nu()
double XCS::get_nu () inline
Definition at line 301 of file pybind_wrapper.cpp.
References XCSF::NU.
Referenced by pybind11_init_xcsf().
get_omp_num_threads()
int XCS::get_omp_num_threads () inline
Definition at line 287 of file pybind_wrapper.cpp.
References XCSF::OMP_NUM_THREADS.
Referenced by pybind11_init_xcsf().
get_p_crossover()
double XCS::get_p_crossover () inline
Definition at line 307 of file pybind_wrapper.cpp.
References XCSF::P_CROSSOVER.
Referenced by pybind11_init_xcsf().
get_p_explore()
double XCS::get_p_explore () inline
Definition at line 361 of file pybind_wrapper.cpp.
References XCSF::P_EXPLORE.
Referenced by pybind11_init_xcsf().
get_perf_trials()
int XCS::get_perf_trials () inline
Definition at line 290 of file pybind_wrapper.cpp.
References XCSF::PERF_TRIALS.
Referenced by pybind11_init_xcsf().
get_pop_init()
_Bool XCS::get_pop_init () inline
Definition at line 288 of file pybind_wrapper.cpp.
References XCSF::POP_INIT.
Referenced by pybind11_init_xcsf().
get_pop_max_size()
int XCS::get_pop_max_size () inline
Definition at line 291 of file pybind_wrapper.cpp.
References XCSF::POP_SIZE.
Referenced by pybind11_init_xcsf().
get_pop_mean_cond_size()
double XCS::get_pop_mean_cond_size () inline
Definition at line 352 of file pybind_wrapper.cpp.
References clset_mean_cond_size(), and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_mean_pred_eta()
double XCS::get_pop_mean_pred_eta (int layer) inline
Definition at line 354 of file pybind_wrapper.cpp.
References clset_mean_eta(), and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_mean_pred_layers()
double XCS::get_pop_mean_pred_layers () inline
Definition at line 356 of file pybind_wrapper.cpp.
References clset_mean_layers(), and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_mean_pred_neurons()
double XCS::get_pop_mean_pred_neurons (int layer) inline
Definition at line 355 of file pybind_wrapper.cpp.
References clset_mean_neurons(), and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_mean_pred_size()
double XCS::get_pop_mean_pred_size () inline
Definition at line 353 of file pybind_wrapper.cpp.
References clset_mean_pred_size(), and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_num()
int XCS::get_pop_num () inline
Definition at line 347 of file pybind_wrapper.cpp.
References SET::num, and XCSF::pset.
Referenced by pybind11_init_xcsf().
get_pop_size()
int XCS::get_pop_size () inline
Definition at line 346 of file pybind_wrapper.cpp.
References XCSF::pset, and SET::size.
Referenced by pybind11_init_xcsf().
get_pred_eta()
double XCS::get_pred_eta () inline
Definition at line 338 of file pybind_wrapper.cpp.
References XCSF::PRED_ETA.
Referenced by pybind11_init_xcsf().
get_pred_evolve_eta()
_Bool XCS::get_pred_evolve_eta () inline
Definition at line 328 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_ETA.
Referenced by pybind11_init_xcsf().
get_pred_evolve_functions()
_Bool XCS::get_pred_evolve_functions () inline
Definition at line 327 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_FUNCTIONS.
Referenced by pybind11_init_xcsf().
get_pred_evolve_neurons()
_Bool XCS::get_pred_evolve_neurons () inline
Definition at line 326 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_NEURONS.
Referenced by pybind11_init_xcsf().
get_pred_evolve_weights()
_Bool XCS::get_pred_evolve_weights () inline
Definition at line 325 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_WEIGHTS.
Referenced by pybind11_init_xcsf().
get_pred_hidden_activation()
int XCS::get_pred_hidden_activation () inline
Definition at line 323 of file pybind_wrapper.cpp.
References XCSF::PRED_HIDDEN_ACTIVATION.
Referenced by pybind11_init_xcsf().
get_pred_max_neurons()
py::list XCS::get_pred_max_neurons () inline
Definition at line 278 of file pybind_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_MAX_NEURONS.
Referenced by pybind11_init_xcsf().
get_pred_momentum()
double XCS::get_pred_momentum () inline
Definition at line 324 of file pybind_wrapper.cpp.
References XCSF::PRED_MOMENTUM.
Referenced by pybind11_init_xcsf().
get_pred_num_neurons()
py::list XCS::get_pred_num_neurons () inline
Definition at line 269 of file pybind_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_NUM_NEURONS.
Referenced by pybind11_init_xcsf().
get_pred_output_activation()
int XCS::get_pred_output_activation () inline
Definition at line 322 of file pybind_wrapper.cpp.
References XCSF::PRED_OUTPUT_ACTIVATION.
Referenced by pybind11_init_xcsf().
get_pred_reset()
_Bool XCS::get_pred_reset () inline
Definition at line 330 of file pybind_wrapper.cpp.
References XCSF::PRED_RESET.
Referenced by pybind11_init_xcsf().
get_pred_rls_lambda()
double XCS::get_pred_rls_lambda () inline
Definition at line 342 of file pybind_wrapper.cpp.
References XCSF::PRED_RLS_LAMBDA.
Referenced by pybind11_init_xcsf().
get_pred_rls_scale_factor()
double XCS::get_pred_rls_scale_factor () inline
Definition at line 341 of file pybind_wrapper.cpp.
References XCSF::PRED_RLS_SCALE_FACTOR.
Referenced by pybind11_init_xcsf().
get_pred_sgd_weights()
_Bool XCS::get_pred_sgd_weights () inline
Definition at line 329 of file pybind_wrapper.cpp.
References XCSF::PRED_SGD_WEIGHTS.
Referenced by pybind11_init_xcsf().
get_pred_type()
int XCS::get_pred_type () inline
Definition at line 306 of file pybind_wrapper.cpp.
References XCSF::PRED_TYPE.
Referenced by pybind11_init_xcsf().
get_pred_x0()
double XCS::get_pred_x0 () inline
Definition at line 340 of file pybind_wrapper.cpp.
References XCSF::PRED_X0.
Referenced by pybind11_init_xcsf().
get_reset_states()
_Bool XCS::get_reset_states () inline
Definition at line 333 of file pybind_wrapper.cpp.
References XCSF::RESET_STATES.
Referenced by pybind11_init_xcsf().
get_sam_type()
int XCS::get_sam_type () inline
Definition at line 312 of file pybind_wrapper.cpp.
References XCSF::SAM_TYPE.
Referenced by pybind11_init_xcsf().
get_set_subsumption()
_Bool XCS::get_set_subsumption () inline
Definition at line 345 of file pybind_wrapper.cpp.
References XCSF::SET_SUBSUMPTION.
Referenced by pybind11_init_xcsf().
get_teletransportation()
int XCS::get_teletransportation () inline
Definition at line 359 of file pybind_wrapper.cpp.
References XCSF::TELETRANSPORTATION.
Referenced by pybind11_init_xcsf().
get_theta_del()
int XCS::get_theta_del () inline
Definition at line 303 of file pybind_wrapper.cpp.
References XCSF::THETA_DEL.
Referenced by pybind11_init_xcsf().
get_theta_ea()
double XCS::get_theta_ea () inline
Definition at line 308 of file pybind_wrapper.cpp.
References XCSF::THETA_EA.
Referenced by pybind11_init_xcsf().
get_theta_sub()
int XCS::get_theta_sub () inline
Definition at line 343 of file pybind_wrapper.cpp.
References XCSF::THETA_SUB.
Referenced by pybind11_init_xcsf().
get_time()
int XCS::get_time () inline
Definition at line 348 of file pybind_wrapper.cpp.
References XCSF::time.
Referenced by pybind11_init_xcsf().
get_x_dim()
double XCS::get_x_dim () inline
Definition at line 349 of file pybind_wrapper.cpp.
References XCSF::x_dim.
Referenced by pybind11_init_xcsf().
get_y_dim()
double XCS::get_y_dim () inline
Definition at line 350 of file pybind_wrapper.cpp.
References XCSF::y_dim.
Referenced by pybind11_init_xcsf().
load()
size_t XCS::load (char * fname) inline
Definition at line 117 of file pybind_wrapper.cpp.
References xcsf_load().
Referenced by pybind11_init_xcsf().
predict()
py::array_t<double> XCS::predict (py::array_t< double > x) inline
Definition at line 220 of file pybind_wrapper.cpp.
References xcsf_predict(), and XCSF::y_dim.
Referenced by pybind11_init_xcsf().
print_pop()
void XCS::print_pop (_Bool printc, _Bool printa, _Bool printp) inline
Definition at line 119 of file pybind_wrapper.cpp.
References xcsf_print_pop().
Referenced by pybind11_init_xcsf().
save()
size_t XCS::save (char * fname) inline
Definition at line 116 of file pybind_wrapper.cpp.
References xcsf_save().
Referenced by pybind11_init_xcsf().
score()
double XCS::score (py::array_t< double > test_X, py::array_t< double > test_Y) inline
Definition at line 233 of file pybind_wrapper.cpp.
References INPUT::n_samples, INPUT::x, INPUT::x_dim, xcsf_score(), INPUT::y, and INPUT::y_dim.
Referenced by pybind11_init_xcsf().
set_act_type()
void XCS::set_act_type (int a) inline
Definition at line 421 of file pybind_wrapper.cpp.
References XCSF::ACT_TYPE.
Referenced by pybind11_init_xcsf().
set_alpha()
void XCS::set_alpha (double a) inline
Definition at line 410 of file pybind_wrapper.cpp.
References XCSF::ALPHA.
Referenced by pybind11_init_xcsf().
set_beta()
void XCS::set_beta (double a) inline
Definition at line 411 of file pybind_wrapper.cpp.
References XCSF::BETA.
Referenced by pybind11_init_xcsf().
set_cond_bits()
void XCS::set_cond_bits (double a) inline
Definition at line 433 of file pybind_wrapper.cpp.
References XCSF::COND_BITS.
Referenced by pybind11_init_xcsf().
set_cond_eta()
void XCS::set_cond_eta (double a) inline
Definition at line 456 of file pybind_wrapper.cpp.
References XCSF::COND_ETA.
Referenced by pybind11_init_xcsf().
set_cond_evolve_functions()
void XCS::set_cond_evolve_functions (_Bool a) inline
Definition at line 436 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_FUNCTIONS.
Referenced by pybind11_init_xcsf().
set_cond_evolve_neurons()
void XCS::set_cond_evolve_neurons (_Bool a) inline
Definition at line 435 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_NEURONS.
Referenced by pybind11_init_xcsf().
set_cond_evolve_weights()
void XCS::set_cond_evolve_weights (_Bool a) inline
Definition at line 434 of file pybind_wrapper.cpp.
References XCSF::COND_EVOLVE_WEIGHTS.
Referenced by pybind11_init_xcsf().
set_cond_hidden_activation()
void XCS::set_cond_hidden_activation (int a) inline
Definition at line 438 of file pybind_wrapper.cpp.
References XCSF::COND_HIDDEN_ACTIVATION.
Referenced by pybind11_init_xcsf().
set_cond_max_neurons()
void XCS::set_cond_max_neurons (py::list & a) inline
Definition at line 381 of file pybind_wrapper.cpp.
References XCSF::COND_MAX_NEURONS, and MAX_LAYERS.
Referenced by pybind11_init_xcsf().
set_cond_num_neurons()
void XCS::set_cond_num_neurons (py::list & a) inline
Definition at line 373 of file pybind_wrapper.cpp.
References XCSF::COND_NUM_NEURONS, and MAX_LAYERS.
Referenced by pybind11_init_xcsf().
set_cond_output_activation()
void XCS::set_cond_output_activation (int a) inline
Definition at line 437 of file pybind_wrapper.cpp.
References XCSF::COND_OUTPUT_ACTIVATION.
Referenced by pybind11_init_xcsf().
set_cond_smin()
void XCS::set_cond_smin (double a) inline
Definition at line 432 of file pybind_wrapper.cpp.
References XCSF::COND_SMIN.
Referenced by pybind11_init_xcsf().
set_cond_type()
void XCS::set_cond_type (int a) inline
Definition at line 422 of file pybind_wrapper.cpp.
References XCSF::COND_TYPE.
Referenced by pybind11_init_xcsf().
set_delta()
void XCS::set_delta (double a) inline
Definition at line 412 of file pybind_wrapper.cpp.
References XCSF::DELTA.
Referenced by pybind11_init_xcsf().
set_dgp_num_nodes()
void XCS::set_dgp_num_nodes (int a) inline
Definition at line 449 of file pybind_wrapper.cpp.
References XCSF::DGP_NUM_NODES.
Referenced by pybind11_init_xcsf().
set_ea_select_size()
void XCS::set_ea_select_size (double a) inline
Definition at line 428 of file pybind_wrapper.cpp.
References XCSF::EA_SELECT_SIZE.
Referenced by pybind11_init_xcsf().
set_ea_select_type()
void XCS::set_ea_select_type (int a) inline
Definition at line 427 of file pybind_wrapper.cpp.
References XCSF::EA_SELECT_TYPE.
Referenced by pybind11_init_xcsf().
set_ea_subsumption()
void XCS::set_ea_subsumption (_Bool a) inline
Definition at line 461 of file pybind_wrapper.cpp.
References XCSF::EA_SUBSUMPTION.
Referenced by pybind11_init_xcsf().
set_eps_0()
void XCS::set_eps_0 (double a) inline
Definition at line 413 of file pybind_wrapper.cpp.
References XCSF::EPS_0.
Referenced by pybind11_init_xcsf().
set_err_reduc()
void XCS::set_err_reduc (double a) inline
Definition at line 414 of file pybind_wrapper.cpp.
References XCSF::ERR_REDUC.
Referenced by pybind11_init_xcsf().
set_fit_reduc()
void XCS::set_fit_reduc (double a) inline
Definition at line 415 of file pybind_wrapper.cpp.
References XCSF::FIT_REDUC.
Referenced by pybind11_init_xcsf().
set_gamma()
void XCS::set_gamma (double a) inline
Definition at line 464 of file pybind_wrapper.cpp.
References XCSF::GAMMA.
Referenced by pybind11_init_xcsf().
set_gp_init_depth()
void XCS::set_gp_init_depth (int a) inline
Definition at line 454 of file pybind_wrapper.cpp.
References XCSF::GP_INIT_DEPTH.
Referenced by pybind11_init_xcsf().
set_gp_num_cons()
void XCS::set_gp_num_cons (int a) inline
Definition at line 453 of file pybind_wrapper.cpp.
References XCSF::GP_NUM_CONS.
Referenced by pybind11_init_xcsf().
set_init_error()
void XCS::set_init_error (double a) inline
Definition at line 416 of file pybind_wrapper.cpp.
References XCSF::INIT_ERROR.
Referenced by pybind11_init_xcsf().
set_init_fitness()
void XCS::set_init_fitness (double a) inline
Definition at line 417 of file pybind_wrapper.cpp.
References XCSF::INIT_FITNESS.
Referenced by pybind11_init_xcsf().
set_lambda()
void XCS::set_lambda (int a) inline
Definition at line 426 of file pybind_wrapper.cpp.
References XCSF::LAMBDA.
Referenced by pybind11_init_xcsf().
set_loss_func()
void XCS::set_loss_func (int a) inline
Definition at line 409 of file pybind_wrapper.cpp.
References XCSF::LOSS_FUNC, and loss_set_func().
Referenced by pybind11_init_xcsf().
set_m_probation()
void XCS::set_m_probation (int a) inline
Definition at line 419 of file pybind_wrapper.cpp.
References XCSF::M_PROBATION.
Referenced by pybind11_init_xcsf().
set_max_con()
void XCS::set_max_con (double a) inline
Definition at line 430 of file pybind_wrapper.cpp.
References XCSF::COND_MAX.
Referenced by pybind11_init_xcsf().
set_max_k()
void XCS::set_max_k (int a) inline
Definition at line 451 of file pybind_wrapper.cpp.
References XCSF::MAX_K.
Referenced by pybind11_init_xcsf().
set_max_neuron_mod()
void XCS::set_max_neuron_mod (int a) inline
Definition at line 448 of file pybind_wrapper.cpp.
References XCSF::MAX_NEURON_MOD.
Referenced by pybind11_init_xcsf().
set_max_t()
void XCS::set_max_t (int a) inline
Definition at line 452 of file pybind_wrapper.cpp.
References XCSF::MAX_T.
Referenced by pybind11_init_xcsf().
set_max_trials()
void XCS::set_max_trials (int a) inline
Definition at line 406 of file pybind_wrapper.cpp.
References XCSF::MAX_TRIALS.
Referenced by pybind11_init_xcsf().
set_min_con()
void XCS::set_min_con (double a) inline
Definition at line 431 of file pybind_wrapper.cpp.
References XCSF::COND_MIN.
Referenced by pybind11_init_xcsf().
set_nu()
void XCS::set_nu (double a) inline
Definition at line 418 of file pybind_wrapper.cpp.
References XCSF::NU.
Referenced by pybind11_init_xcsf().
set_omp_num_threads()
void XCS::set_omp_num_threads (int a) inline
Definition at line 365 of file pybind_wrapper.cpp.
References XCSF::OMP_NUM_THREADS.
Referenced by pybind11_init_xcsf().
set_p_crossover()
void XCS::set_p_crossover (double a) inline
Definition at line 424 of file pybind_wrapper.cpp.
References XCSF::P_CROSSOVER.
Referenced by pybind11_init_xcsf().
set_p_explore()
void XCS::set_p_explore (double a) inline
Definition at line 465 of file pybind_wrapper.cpp.
References XCSF::P_EXPLORE.
Referenced by pybind11_init_xcsf().
set_perf_trials()
void XCS::set_perf_trials (int a) inline
Definition at line 407 of file pybind_wrapper.cpp.
References XCSF::PERF_TRIALS.
Referenced by pybind11_init_xcsf().
set_pop_init()
void XCS::set_pop_init (_Bool a) inline
Definition at line 405 of file pybind_wrapper.cpp.
References XCSF::POP_INIT.
Referenced by pybind11_init_xcsf().
set_pop_max_size()
void XCS::set_pop_max_size (int a) inline
Definition at line 408 of file pybind_wrapper.cpp.
References XCSF::POP_SIZE.
Referenced by pybind11_init_xcsf().
set_pred_eta()
void XCS::set_pred_eta (double a) inline
Definition at line 455 of file pybind_wrapper.cpp.
References XCSF::PRED_ETA.
Referenced by pybind11_init_xcsf().
set_pred_evolve_eta()
void XCS::set_pred_evolve_eta (_Bool a) inline
Definition at line 445 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_ETA.
Referenced by pybind11_init_xcsf().
set_pred_evolve_functions()
void XCS::set_pred_evolve_functions (_Bool a) inline
Definition at line 444 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_FUNCTIONS.
Referenced by pybind11_init_xcsf().
set_pred_evolve_neurons()
void XCS::set_pred_evolve_neurons (_Bool a) inline
Definition at line 443 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_NEURONS.
Referenced by pybind11_init_xcsf().
set_pred_evolve_weights()
void XCS::set_pred_evolve_weights (_Bool a) inline
Definition at line 442 of file pybind_wrapper.cpp.
References XCSF::PRED_EVOLVE_WEIGHTS.
Referenced by pybind11_init_xcsf().
set_pred_hidden_activation()
void XCS::set_pred_hidden_activation (int a) inline
Definition at line 440 of file pybind_wrapper.cpp.
References XCSF::PRED_HIDDEN_ACTIVATION.
Referenced by pybind11_init_xcsf().
set_pred_max_neurons()
void XCS::set_pred_max_neurons (py::list & a) inline
Definition at line 397 of file pybind_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_MAX_NEURONS.
Referenced by pybind11_init_xcsf().
set_pred_momentum()
void XCS::set_pred_momentum (double a) inline
Definition at line 441 of file pybind_wrapper.cpp.
References XCSF::PRED_MOMENTUM.
Referenced by pybind11_init_xcsf().
set_pred_num_neurons()
void XCS::set_pred_num_neurons (py::list & a) inline
Definition at line 389 of file pybind_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_NUM_NEURONS.
Referenced by pybind11_init_xcsf().
set_pred_output_activation()
void XCS::set_pred_output_activation (int a) inline
Definition at line 439 of file pybind_wrapper.cpp.
References XCSF::PRED_OUTPUT_ACTIVATION.
Referenced by pybind11_init_xcsf().
set_pred_reset()
void XCS::set_pred_reset (_Bool a) inline
Definition at line 447 of file pybind_wrapper.cpp.
References XCSF::PRED_RESET.
Referenced by pybind11_init_xcsf().
set_pred_rls_lambda()
void XCS::set_pred_rls_lambda (double a) inline
Definition at line 459 of file pybind_wrapper.cpp.
References XCSF::PRED_RLS_LAMBDA.
Referenced by pybind11_init_xcsf().
set_pred_rls_scale_factor()
void XCS::set_pred_rls_scale_factor (double a) inline
Definition at line 458 of file pybind_wrapper.cpp.
References XCSF::PRED_RLS_SCALE_FACTOR.
Referenced by pybind11_init_xcsf().
set_pred_sgd_weights()
void XCS::set_pred_sgd_weights (_Bool a) inline
Definition at line 446 of file pybind_wrapper.cpp.
References XCSF::PRED_SGD_WEIGHTS.
Referenced by pybind11_init_xcsf().
set_pred_type()
void XCS::set_pred_type (int a) inline
Definition at line 423 of file pybind_wrapper.cpp.
References XCSF::PRED_TYPE.
Referenced by pybind11_init_xcsf().
set_pred_x0()
void XCS::set_pred_x0 (double a) inline
Definition at line 457 of file pybind_wrapper.cpp.
References XCSF::PRED_X0.
Referenced by pybind11_init_xcsf().
set_reset_states()
void XCS::set_reset_states (_Bool a) inline
Definition at line 450 of file pybind_wrapper.cpp.
References XCSF::RESET_STATES.
Referenced by pybind11_init_xcsf().
set_sam_type()
void XCS::set_sam_type (int a) inline
Definition at line 429 of file pybind_wrapper.cpp.
References XCSF::SAM_TYPE.
Referenced by pybind11_init_xcsf().
set_set_subsumption()
void XCS::set_set_subsumption (_Bool a) inline
Definition at line 462 of file pybind_wrapper.cpp.
References XCSF::SET_SUBSUMPTION.
Referenced by pybind11_init_xcsf().
set_teletransportation()
void XCS::set_teletransportation (int a) inline
Definition at line 463 of file pybind_wrapper.cpp.
References XCSF::TELETRANSPORTATION.
Referenced by pybind11_init_xcsf().
set_theta_del()
void XCS::set_theta_del (int a) inline
Definition at line 420 of file pybind_wrapper.cpp.
References XCSF::THETA_DEL.
Referenced by pybind11_init_xcsf().
set_theta_ea()
void XCS::set_theta_ea (double a) inline
Definition at line 425 of file pybind_wrapper.cpp.
References XCSF::THETA_EA.
Referenced by pybind11_init_xcsf().
set_theta_sub()
void XCS::set_theta_sub (int a) inline
Definition at line 460 of file pybind_wrapper.cpp.
References XCSF::THETA_SUB.
Referenced by pybind11_init_xcsf().
single_decision()
int XCS::single_decision (py::array_t< double > input, _Bool explore) inline
Definition at line 134 of file pybind_wrapper.cpp.
References action, XCSF::train, and xcs_single_decision().
Referenced by pybind11_init_xcsf().
single_error()
double XCS::single_error (double reward) inline
Definition at line 148 of file pybind_wrapper.cpp.
References xcs_single_error().
Referenced by pybind11_init_xcsf().
single_reset()
void XCS::single_reset () inline
Definition at line 126 of file pybind_wrapper.cpp.
References clset_pop_init(), XCSF::time, and xcs_single_free().
Referenced by pybind11_init_xcsf().
single_update()
void XCS::single_update (double reward) inline
Definition at line 143 of file pybind_wrapper.cpp.
References xcs_single_update().
Referenced by pybind11_init_xcsf().
version()
double XCS::version () inline
Definition at line 115 of file pybind_wrapper.cpp.
References xcsf_version().
Referenced by pybind11_init_xcsf().
xcs_init()
void XCS::xcs_init (const char * filename) inline
Initialises python XCS structure.
Definition at line 95 of file pybind_wrapper.cpp.
References config_init(), INPUT::n_samples, INPUT::x, INPUT::x_dim, xcsf_init(), INPUT::y, and INPUT::y_dim.
Referenced by XCS().
Field Documentation
action
int XCS::action private
Current action for RL.
Definition at line 57 of file pybind_wrapper.cpp.
Referenced by single_decision().
state
double* XCS::state private
Current input state for RL.
Definition at line 56 of file pybind_wrapper.cpp.
test_data
INPUT* XCS::test_data private
Currrent test data for supervised learning.
Definition at line 59 of file pybind_wrapper.cpp.
train_data
INPUT* XCS::train_data private
Current training data for supervised learning.
Definition at line 58 of file pybind_wrapper.cpp.
xcs
XCSF XCS::xcs private
XCSF data structure.
Definition at line 55 of file pybind_wrapper.cpp.
The documentation for this class was generated from the following file:
pybind_wrapper.cpp