XCSF: clset.c File Reference
clset.c File Reference
Functions operating on sets of classifiers.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "clset.h"
#include "prediction.h"
#include "pred_neural.h"
Macros
#define MAX_COVER 1000000
maximum number of covering attempts
Functions
static _Bool clset_action_covered (const XCSF *xcsf, const SET *set, int action)
Returns whether an action is covered by the set.
static double clset_total_time (const XCSF *xcsf, const SET *set)
Calculates the total time stamps of classifiers in the set.
static void clset_cover (XCSF *xcsf, SET *mset, SET *kset, const double *x, _Bool *act_covered)
Ensures all possible actions are covered by the match set.
static void clset_pop_del (XCSF *xcsf, SET *kset)
Deletes a single classifier from the population set.
static void clset_subsumption (XCSF *xcsf, SET *set, SET *kset)
Performs set subsumption.
static void clset_update_fit (const XCSF *xcsf, const SET *set)
Updates the fitness of classifiers in the set.
void clset_pop_init (XCSF *xcsf)
Initialises a new population set.
void clset_init (const XCSF *xcsf, SET *set)
Initialises a new set.
void clset_pop_enforce_limit (XCSF *xcsf, SET *kset)
Enforces the maximum population size limit.
void clset_match (XCSF *xcsf, SET *mset, SET *kset, const double *x)
Constructs the match set.
void clset_pred (const XCSF *xcsf, const SET *set, const double *x, double *p)
Calculates the set mean fitness weighted prediction.
void clset_action (const XCSF *xcsf, const SET *mset, SET *aset, int action)
Constructs the action set.
void clset_add (const XCSF *xcsf, SET *set, CL *c)
Adds a classifier to the set.
void clset_update (XCSF *xcsf, SET *set, SET *kset, const double *x, const double *y, _Bool curr)
Provides reinforcement to the set and performs set subsumption.
void clset_validate (const XCSF *xcsf, SET *set)
Removes classifiers with 0 numerosity from the set.
void clset_print (const XCSF *xcsf, const SET *set, _Bool printc, _Bool printa, _Bool printp)
Prints the classifiers in the set.
void clset_set_times (const XCSF *xcsf, const SET *set)
Sets the time stamps for classifiers in the set.
double clset_total_fit (const XCSF *xcsf, const SET *set)
Calculates the total fitness of classifiers in the set.
double clset_mean_time (const XCSF *xcsf, const SET *set)
Calculates the mean time stamp of classifiers in the set.
void clset_free (const XCSF *xcsf, SET *set)
Frees the set, but not the classifiers.
void clset_kill (const XCSF *xcsf, SET *set)
Frees the set and the classifiers.
size_t clset_pop_save (const XCSF *xcsf, FILE *fp)
Writes the population set to a binary file.
size_t clset_pop_load (XCSF *xcsf, FILE *fp)
Reads the population set from a binary file.
double clset_mean_mut (const XCSF *xcsf, const SET *set, int m)
Calculates the mean mutation rate of classifiers in the set.
double clset_mean_cond_size (const XCSF *xcsf, const SET *set)
Calculates the mean condition size of classifiers in the set.
double clset_mean_pred_size (const XCSF *xcsf, const SET *set)
Calculates the mean prediction size of classifiers in the set.
double clset_mean_inputs_matched (const XCSF *xcsf, const SET *set)
Calculates the mean fraction of inputs matched by classifiers.
double clset_mean_eta (const XCSF *xcsf, const SET *set, int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
Detailed Description
Functions operating on sets of classifiers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file clset.c.
Macro Definition Documentation
MAX_COVER
#define MAX_COVER 1000000
maximum number of covering attempts
Definition at line 37 of file clset.c.
Referenced by clset_cover().
Function Documentation
clset_action()
void clset_action (const XCSF * xcsf, const SET * mset, SET * aset, int action)
Constructs the action set.
Parameters
xcsf The XCSF data structure.
mset The match set.
aset The action set.
action The action used to build the set.
Definition at line 299 of file clset.c.
References clset_add(), SET::list, and CLIST::next.
Referenced by xcs_multi_trial(), and xcs_single_update().
clset_action_covered()
static _Bool clset_action_covered (const XCSF * xcsf, const SET * set, int action) static
Returns whether an action is covered by the set.
Parameters
xcsf The XCSF data structure.
set The set to check (typically the match set).
action The action to check.
Returns
Whether the action is covered.
Definition at line 315 of file clset.c.
References CLIST::next.
Referenced by clset_cover().
clset_add()
void clset_add (const XCSF * xcsf, SET * set, CL * c)
Adds a classifier to the set.
Parameters
xcsf The XCSF data structure.
set The set to add the classifier.
c The classifier to add.
Definition at line 332 of file clset.c.
References CL::size.
Referenced by clset_action(), clset_cover(), clset_match(), clset_pop_del(), clset_pop_init(), clset_pop_load(), clset_subsumption(), ea_add(), and ea_subsume().
clset_cover()
static void clset_cover (XCSF * xcsf, SET * mset, SET * kset, const double * x, _Bool * act_covered) static
Ensures all possible actions are covered by the match set.
Parameters
xcsf The XCSF data structure.
mset The match set.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
act_covered Array indicating whether each action is covered by the set.
Definition at line 203 of file clset.c.
References cl_cover(), cl_init(), clset_action_covered(), clset_add(), clset_pop_enforce_limit(), clset_validate(), MAX_COVER, SET::num, XCSF::num_actions, XCSF::pset, SET::size, and XCSF::time.
Referenced by clset_match().
clset_free()
void clset_free (const XCSF * xcsf, SET * set)
Frees the set, but not the classifiers.
Parameters
xcsf The XCSF data structure.
set The set to free.
Definition at line 550 of file clset.c.
References CLIST::next.
Referenced by XCS::single_reset(), xcs_multi_trial(), xcs_single_trial(), xcsf_learn_trial(), xcsf_predict(), xcsf_print_match_set(), and xcsf_test_trial().
clset_init()
void clset_init (const XCSF * xcsf, SET * set)
Initialises a new set.
Parameters
xcsf The XCSF data structure.
set The set to be initialised.
Definition at line 71 of file clset.c.
Referenced by clset_pop_init(), clset_pop_load(), XCS::single_reset(), XCS::xcs_init(), xcs_multi_trial(), xcs_single_trial(), xcsf_learn_trial(), xcsf_load(), xcsf_predict(), xcsf_print_match_set(), and xcsf_test_trial().
clset_kill()
void clset_kill (const XCSF * xcsf, SET * set)
Frees the set and the classifiers.
Parameters
xcsf The XCSF data structure.
set The set to free.
Definition at line 566 of file clset.c.
References CLIST::cl, cl_free(), and CLIST::next.
Referenced by main(), XCS::single_reset(), xcs_multi_trial(), xcs_single_trial(), xcsf_learn_trial(), xcsf_load(), xcsf_predict(), xcsf_print_match_set(), and xcsf_test_trial().
clset_match()
void clset_match (XCSF * xcsf, SET * mset, SET * kset, const double * x)
Constructs the match set.
Parameters
xcsf The XCSF data structure.
mset The match set.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
Processes the matching conditions for each classifier in the population. Adds each matching classifier to the match set. Performs covering if any actions are not covered.
Definition at line 156 of file clset.c.
References cl_action(), cl_m(), cl_match(), clset_add(), clset_cover(), SET::list, CLIST::next, XCSF::num_actions, XCSF::pset, and SET::size.
Referenced by xcs_multi_trial(), xcs_single_decision(), xcsf_learn_trial(), xcsf_predict(), xcsf_print_match_set(), and xcsf_test_trial().
clset_mean_cond_size()
double clset_mean_cond_size (const XCSF * xcsf, const SET * set)
Calculates the mean condition size of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean condition size.
Returns
The mean condition size of classifiers in the set.
Definition at line 651 of file clset.c.
References cl_cond_size(), and CLIST::next.
Referenced by XCS::get_pop_mean_cond_size().
clset_mean_eta()
double clset_mean_eta (const XCSF * xcsf, const SET * set, int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean prediction layer ETA.
layer The neural network layer to calculate the mean ETA.
Returns
The mean prediction layer ETA of classifiers in the set.
Definition at line 706 of file clset.c.
References CLIST::next, and pred_neural_eta().
Referenced by XCS::get_pop_mean_pred_eta().
clset_mean_inputs_matched()
double clset_mean_inputs_matched (const XCSF * xcsf, const SET * set)
Calculates the mean fraction of inputs matched by classifiers.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean prediction size.
Returns
The mean fraction of inputs matched.
Definition at line 685 of file clset.c.
References CLIST::next.
Referenced by XCS::get_mfrac().
clset_mean_mut()
double clset_mean_mut (const XCSF * xcsf, const SET * set, int m)
Calculates the mean mutation rate of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean mutation rate.
m Which mutation rate to average.
Returns
The mean mutation rate of classifiers in the set.
Definition at line 623 of file clset.c.
References cl_mutation_rate(), XCSF::E_MUTATION, XCSF::F_MUTATION, CLIST::next, XCSF::P_MUTATION, XCSF::S_MUTATION, and XCSF::SAM_NUM.
Referenced by disp_perf1(), disp_perf2(), XCS::get_pop_mean_mu(), and gplot_free().
clset_mean_pred_size()
double clset_mean_pred_size (const XCSF * xcsf, const SET * set)
Calculates the mean prediction size of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean prediction size.
Returns
The mean prediction size of classifiers in the set.
Definition at line 668 of file clset.c.
References cl_pred_size(), and CLIST::next.
Referenced by XCS::get_pop_mean_pred_size().
clset_mean_time()
double clset_mean_time (const XCSF * xcsf, const SET * set)
Calculates the mean time stamp of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean time.
Returns
The mean time of classifiers in the set.
Definition at line 540 of file clset.c.
References clset_total_time().
Referenced by ea().
clset_pop_del()
static void clset_pop_del (XCSF * xcsf, SET * kset) static
Deletes a single classifier from the population set.
Parameters
xcsf The XCSF data structure.
kset A set to store deleted macro-classifiers for later memory removal.
Selects two classifiers using roulete wheel selection with the deletion vote and deletes the one with the largest condition + prediction length. For fixed-length representations this is the same as one roulete spin.
Definition at line 88 of file clset.c.
References CLIST::cl, cl_cond_size(), cl_del_vote(), cl_pred_size(), clset_add(), clset_total_fit(), SET::list, CLIST::next, CL::num, SET::num, XCSF::pset, rand_uniform(), and SET::size.
Referenced by clset_pop_enforce_limit().
clset_pop_enforce_limit()
void clset_pop_enforce_limit (XCSF * xcsf, SET * kset)
Enforces the maximum population size limit.
Parameters
xcsf The XCSF data structure.
kset A set to store deleted macro-classifiers for later memory removal.
Definition at line 138 of file clset.c.
References clset_pop_del(), SET::num, XCSF::POP_SIZE, and XCSF::pset.
Referenced by clset_cover(), and ea().
clset_pop_init()
void clset_pop_init (XCSF * xcsf)
Initialises a new population set.
Parameters
xcsf The XCSF data structure.
Definition at line 50 of file clset.c.
References cl_init(), cl_rand(), clset_add(), clset_init(), XCSF::msetsize, SET::num, XCSF::POP_INIT, XCSF::POP_SIZE, XCSF::pset, and XCSF::time.
Referenced by XCS::fit(), main(), and XCS::single_reset().
clset_pop_load()
size_t clset_pop_load (XCSF * xcsf, FILE * fp)
Reads the population set from a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 600 of file clset.c.
References cl_load(), clset_add(), clset_init(), and XCSF::pset.
Referenced by xcsf_load().
clset_pop_save()
size_t clset_pop_save (const XCSF * xcsf, FILE * fp)
Writes the population set to a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 583 of file clset.c.
References cl_save(), SET::list, CLIST::next, SET::num, XCSF::pset, and SET::size.
Referenced by xcsf_save().
clset_pred()
void clset_pred (const XCSF * xcsf, const SET * set, const double * x, double * p)
Calculates the set mean fitness weighted prediction.
Parameters
xcsf The XCSF data structure.
set The set to calculate the prediction.
x The input state.
p The predictions (set by this function).
Definition at line 254 of file clset.c.
References CLIST::cl, cl_predict(), CL::fit, CLIST::next, and XCSF::num_y_vars.
Referenced by xcsf_learn_trial(), xcsf_predict(), and xcsf_test_trial().
clset_print()
void clset_print (const XCSF * xcsf, const SET * set, _Bool printc, _Bool printa, _Bool printp)
Prints the classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to print.
printc Whether to print the conditions.
printa Whether to print the actions.
printp Whether to print the predictions.
Definition at line 483 of file clset.c.
References cl_print(), and CLIST::next.
Referenced by xcsf_print_match_set(), and xcsf_print_pop().
clset_set_times()
void clset_set_times (const XCSF * xcsf, const SET * set)
Sets the time stamps for classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to update the time stamps.
Definition at line 495 of file clset.c.
References CLIST::next, and XCSF::time.
Referenced by ea().
clset_subsumption()
static void clset_subsumption (XCSF * xcsf, SET * set, SET * kset) static
Performs set subsumption.
Parameters
xcsf The XCSF data structure.
set The set to perform subsumption.
kset A set to store deleted macro-classifiers for later memory removal.
Definition at line 413 of file clset.c.
References CLIST::cl, cl_general(), cl_subsumer(), clset_add(), clset_validate(), CLIST::next, CL::num, and XCSF::pset.
Referenced by clset_update().
clset_total_fit()
double clset_total_fit (const XCSF * xcsf, const SET * set)
Calculates the total fitness of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the total fitness.
Returns
The total fitness of classifiers in the set.
Definition at line 508 of file clset.c.
References CLIST::next.
Referenced by clset_pop_del(), and ea_select_parents().
clset_total_time()
static double clset_total_time (const XCSF * xcsf, const SET * set) static
Calculates the total time stamps of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the total time.
Returns
The total time of classifiers in the set.
Definition at line 524 of file clset.c.
References CLIST::next, and XCSF::time.
Referenced by clset_mean_time().
clset_update()
void clset_update (XCSF * xcsf, SET * set, SET * kset, const double * x, const double * y, _Bool curr)
Provides reinforcement to the set and performs set subsumption.
Parameters
xcsf The XCSF data structure.
set The set to provide reinforcement.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
y The payoff from the environment.
curr Whether the update is for the current or previous state.
Definition at line 359 of file clset.c.
References cl_update(), clset_subsumption(), clset_update_fit(), CLIST::next, and XCSF::SET_SUBSUMPTION.
Referenced by xcs_multi_trial(), xcs_single_update(), and xcsf_learn_trial().
clset_update_fit()
static void clset_update_fit (const XCSF * xcsf, const SET * set) static
Updates the fitness of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to update.
Definition at line 388 of file clset.c.
References cl_acc(), cl_update_fit(), and CLIST::next.
Referenced by clset_update().
clset_validate()
void clset_validate (const XCSF * xcsf, SET * set)
Removes classifiers with 0 numerosity from the set.
Parameters
xcsf The XCSF data structure.
set The set to validate.
Definition at line 446 of file clset.c.
References CLIST::cl, CLIST::next, and CL::num.
Referenced by clset_cover(), clset_subsumption(), and xcs_multi_trial().