XCSF: clset.h File Reference
clset.h File Reference
Functions operating on sets of classifiers.
Functions
double clset_mean_cond_size (const XCSF *xcsf, const SET *set)
Calculates the mean condition size of classifiers in the set.
double clset_mean_eta (const XCSF *xcsf, const SET *set, int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
double clset_mean_layers (const XCSF *xcsf, const SET *set)
Calculates the mean number of prediction layers in the set.
double clset_mean_mut (const XCSF *xcsf, const SET *set, int m)
Calculates the mean mutation rate of classifiers in the set.
double clset_mean_neurons (const XCSF *xcsf, const SET *set, int layer)
Calculates the mean number of prediction neurons for a given layer.
double clset_mean_pred_size (const XCSF *xcsf, const SET *set)
Calculates the mean prediction size of classifiers in the set.
double clset_mean_time (const XCSF *xcsf, const SET *set)
Calculates the mean time stamp of classifiers in the set.
double clset_mfrac (const XCSF *xcsf)
Returns the fraction of inputs matched by the most general rule with error below EPS_0. If no rules below EPS_0, the lowest error rule is used.
double clset_total_fit (const XCSF *xcsf, const SET *set)
Calculates the total fitness of classifiers in the set.
size_t clset_pop_load (XCSF *xcsf, FILE *fp)
Reads the population set from a binary file.
size_t clset_pop_save (const XCSF *xcsf, FILE *fp)
Writes the population set to a binary file.
void clset_action (const XCSF *xcsf, const SET *mset, SET *aset, int action)
Constructs the action set.
void clset_add (const XCSF *xcsf, SET *set, CL *c)
Adds a classifier to the set.
void clset_free (const XCSF *xcsf, SET *set)
Frees the set, but not the classifiers.
void clset_init (const XCSF *xcsf, SET *set)
Initialises a new set.
void clset_kill (const XCSF *xcsf, SET *set)
Frees the set and the classifiers.
void clset_match (XCSF *xcsf, SET *mset, SET *kset, const double *x)
Constructs the match set.
void clset_pop_enforce_limit (XCSF *xcsf, SET *kset)
Enforces the maximum population size limit.
void clset_pop_init (XCSF *xcsf)
Initialises a new population set.
void clset_pred (const XCSF *xcsf, const SET *set, const double *x, double *p)
Calculates the set mean fitness weighted prediction.
void clset_print (const XCSF *xcsf, const SET *set, _Bool printc, _Bool printa, _Bool printp)
Prints the classifiers in the set.
void clset_set_times (const XCSF *xcsf, const SET *set)
Sets the time stamps for classifiers in the set.
void clset_update (XCSF *xcsf, SET *set, SET *kset, const double *x, const double *y, _Bool curr)
Provides reinforcement to the set and performs set subsumption.
void clset_validate (const XCSF *xcsf, SET *set)
Removes classifiers with 0 numerosity from the set.
Detailed Description
Functions operating on sets of classifiers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file clset.h.
Function Documentation
clset_action()
void clset_action (const XCSF * xcsf, const SET * mset, SET * aset, int action)
Constructs the action set.
Parameters
xcsf The XCSF data structure.
mset The match set.
aset The action set.
action The action used to build the set.
Definition at line 342 of file clset.c.
References clset_add(), SET::list, and CLIST::next.
Referenced by xcs_multi_trial(), and xcs_single_update().
clset_add()
void clset_add (const XCSF * xcsf, SET * set, CL * c)
Adds a classifier to the set.
Parameters
xcsf The XCSF data structure.
set The set to add the classifier.
c The classifier to add.
Definition at line 375 of file clset.c.
References CL::size.
Referenced by clset_action(), clset_cover(), clset_match(), clset_pop_del(), clset_pop_init(), clset_pop_load(), clset_subsumption(), ea_add(), and ea_subsume().
clset_free()
void clset_free (const XCSF * xcsf, SET * set)
Frees the set, but not the classifiers.
Parameters
xcsf The XCSF data structure.
set The set to free.
Definition at line 592 of file clset.c.
References CLIST::next.
Referenced by XCS::single_reset(), xcs_multi_trial(), xcs_single_trial(), and xcsf_trial().
clset_init()
void clset_init (const XCSF * xcsf, SET * set)
Initialises a new set.
Parameters
xcsf The XCSF data structure.
set The set to be initialised.
Definition at line 75 of file clset.c.
Referenced by clset_pop_init(), clset_pop_load(), XCS::single_reset(), XCS::xcs_init(), xcs_multi_trial(), xcs_single_trial(), xcsf_load(), and xcsf_trial().
clset_kill()
void clset_kill (const XCSF * xcsf, SET * set)
Frees the set and the classifiers.
Parameters
xcsf The XCSF data structure.
set The set to free.
Definition at line 608 of file clset.c.
References CLIST::cl, cl_free(), and CLIST::next.
Referenced by main(), XCS::single_reset(), xcs_multi_trial(), xcs_single_trial(), xcsf_load(), and xcsf_trial().
clset_match()
void clset_match (XCSF * xcsf, SET * mset, SET * kset, const double * x)
Constructs the match set.
Parameters
xcsf The XCSF data structure.
mset The match set.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
Processes the matching conditions for each classifier in the population. Adds each matching classifier to the match set. Performs covering if any actions are not covered.
Definition at line 196 of file clset.c.
References cl_action(), cl_m(), cl_match(), clset_add(), clset_cover(), clset_mfrac(), SET::list, XCSF::mfrac, XCSF::msetsize, CLIST::next, XCSF::num_actions, XCSF::PERF_AVG_TRIALS, XCSF::pset, and SET::size.
Referenced by xcs_multi_trial(), xcs_single_decision(), and xcsf_trial().
clset_mean_cond_size()
double clset_mean_cond_size (const XCSF * xcsf, const SET * set)
Calculates the mean condition size of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean condition size.
Returns
The mean condition size of classifiers in the set.
Definition at line 693 of file clset.c.
References cl_cond_size(), and CLIST::next.
Referenced by XCS::get_pop_mean_cond_size().
clset_mean_eta()
double clset_mean_eta (const XCSF * xcsf, const SET * set, int layer)
Calculates the mean prediction layer ETA of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean.
layer The neural network layer position.
Returns
The mean prediction layer ETA of classifiers in the set.
Definition at line 763 of file clset.c.
References CLIST::next, and pred_neural_eta().
Referenced by XCS::get_pop_mean_pred_eta().
clset_mean_layers()
double clset_mean_layers (const XCSF * xcsf, const SET * set)
Calculates the mean number of prediction layers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean.
Returns
The mean number of layers.
Definition at line 798 of file clset.c.
References CLIST::next, and pred_neural_layers().
Referenced by XCS::get_pop_mean_pred_layers().
clset_mean_mut()
double clset_mean_mut (const XCSF * xcsf, const SET * set, int m)
Calculates the mean mutation rate of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean mutation rate.
m Which mutation rate to average.
Returns
The mean mutation rate of classifiers in the set.
Definition at line 665 of file clset.c.
References cl_mutation_rate(), XCSF::E_MUTATION, XCSF::F_MUTATION, CLIST::next, XCSF::P_MUTATION, XCSF::S_MUTATION, and XCSF::SAM_NUM.
Referenced by disp_perf1(), disp_perf2(), XCS::get_pop_mean_mu(), and gplot_free().
clset_mean_neurons()
double clset_mean_neurons (const XCSF * xcsf, const SET * set, int layer)
Calculates the mean number of prediction neurons for a given layer.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean.
layer The neural network layer position.
Returns
The mean number of neurons in the layer.
Definition at line 781 of file clset.c.
References CLIST::next, and pred_neural_neurons().
Referenced by XCS::get_pop_mean_pred_neurons().
clset_mean_pred_size()
double clset_mean_pred_size (const XCSF * xcsf, const SET * set)
Calculates the mean prediction size of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean prediction size.
Returns
The mean prediction size of classifiers in the set.
Definition at line 710 of file clset.c.
References cl_pred_size(), and CLIST::next.
Referenced by XCS::get_pop_mean_pred_size().
clset_mean_time()
double clset_mean_time (const XCSF * xcsf, const SET * set)
Calculates the mean time stamp of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the mean time.
Returns
The mean time of classifiers in the set.
Definition at line 582 of file clset.c.
References clset_total_time().
Referenced by ea().
clset_mfrac()
double clset_mfrac (const XCSF * xcsf)
Returns the fraction of inputs matched by the most general rule with error below EPS_0. If no rules below EPS_0, the lowest error rule is used.
Parameters
xcsf The XCSF data structure.
Returns
The fraction of inputs matched.
Definition at line 727 of file clset.c.
References XCSF::BETA, cl_mfrac(), SET::list, CLIST::next, and XCSF::pset.
Referenced by clset_match().
clset_pop_enforce_limit()
void clset_pop_enforce_limit (XCSF * xcsf, SET * kset)
Enforces the maximum population size limit.
Parameters
xcsf The XCSF data structure.
kset A set to store deleted macro-classifiers for later memory removal.
Definition at line 178 of file clset.c.
References clset_pop_del(), SET::num, XCSF::POP_SIZE, and XCSF::pset.
Referenced by clset_cover(), and ea().
clset_pop_init()
void clset_pop_init (XCSF * xcsf)
Initialises a new population set.
Parameters
xcsf The XCSF data structure.
Definition at line 53 of file clset.c.
References cl_init(), cl_rand(), clset_add(), clset_init(), XCSF::mfrac, XCSF::msetsize, SET::num, XCSF::POP_INIT, XCSF::POP_SIZE, XCSF::pset, and XCSF::time.
Referenced by XCS::fit(), main(), and XCS::single_reset().
clset_pop_load()
size_t clset_pop_load (XCSF * xcsf, FILE * fp)
Reads the population set from a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 642 of file clset.c.
References cl_load(), clset_add(), clset_init(), and XCSF::pset.
Referenced by xcsf_load().
clset_pop_save()
size_t clset_pop_save (const XCSF * xcsf, FILE * fp)
Writes the population set to a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 625 of file clset.c.
References cl_save(), SET::list, CLIST::next, SET::num, XCSF::pset, and SET::size.
Referenced by xcsf_save().
clset_pred()
void clset_pred (const XCSF * xcsf, const SET * set, const double * x, double * p)
Calculates the set mean fitness weighted prediction.
Parameters
xcsf The XCSF data structure.
set The set to calculate the prediction.
x The input state.
p The predictions (set by this function).
Definition at line 297 of file clset.c.
References CLIST::cl, cl_predict(), CL::fit, CLIST::next, and XCSF::num_y_vars.
Referenced by xcsf_trial().
clset_print()
void clset_print (const XCSF * xcsf, const SET * set, _Bool printc, _Bool printa, _Bool printp)
Prints the classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to print.
printc Whether to print the conditions.
printa Whether to print the actions.
printp Whether to print the predictions.
Definition at line 525 of file clset.c.
References cl_print(), and CLIST::next.
Referenced by xcsf_print_pop().
clset_set_times()
void clset_set_times (const XCSF * xcsf, const SET * set)
Sets the time stamps for classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to update the time stamps.
Definition at line 537 of file clset.c.
References CLIST::next, and XCSF::time.
Referenced by ea().
clset_total_fit()
double clset_total_fit (const XCSF * xcsf, const SET * set)
Calculates the total fitness of classifiers in the set.
Parameters
xcsf The XCSF data structure.
set The set to calculate the total fitness.
Returns
The total fitness of classifiers in the set.
Definition at line 550 of file clset.c.
References CLIST::next.
Referenced by clset_pop_roulette(), and ea_select_parents().
clset_update()
void clset_update (XCSF * xcsf, SET * set, SET * kset, const double * x, const double * y, _Bool curr)
Provides reinforcement to the set and performs set subsumption.
Parameters
xcsf The XCSF data structure.
set The set to provide reinforcement.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
y The payoff from the environment.
curr Whether the update is for the current or previous state.
Definition at line 402 of file clset.c.
References cl_update(), clset_subsumption(), clset_update_fit(), CLIST::next, and XCSF::SET_SUBSUMPTION.
Referenced by xcs_multi_trial(), xcs_single_update(), and xcsf_trial().
clset_validate()
void clset_validate (const XCSF * xcsf, SET * set)
Removes classifiers with 0 numerosity from the set.
Parameters
xcsf The XCSF data structure.
set The set to validate.
Definition at line 488 of file clset.c.
References CLIST::cl, CLIST::next, and CL::num.
Referenced by clset_cover(), clset_subsumption(), and xcs_multi_trial().