XCSF: cond_neural.h File Reference
cond_neural.h File Reference
Multi-layer perceptron neural network condition functions.
Functions
_Bool cond_neural_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool cond_neural_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_neural_match (const XCSF *xcsf, CL *c, const double *x)
_Bool cond_neural_mutate (const XCSF *xcsf, CL *c)
void cond_neural_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_neural_cover (const XCSF *xcsf, CL *c, const double *x)
void cond_neural_free (const XCSF *xcsf, const CL *c)
void cond_neural_init (const XCSF *xcsf, CL *c)
void cond_neural_print (const XCSF *xcsf, const CL *c)
void cond_neural_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
int cond_neural_size (const XCSF *xcsf, const CL *c)
size_t cond_neural_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_neural_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const cond_neural_vtbl
Multi-layer perceptron neural network condition implemented functions.
Detailed Description
Multi-layer perceptron neural network condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file cond_neural.h.
Function Documentation
cond_neural_copy()
void cond_neural_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 100 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_copy().
cond_neural_cover()
void cond_neural_cover (const XCSF * xcsf, CL * c, const double * x)
Definition at line 114 of file cond_neural.c.
References cond_neural_match(), and cond_neural_rand().
cond_neural_crossover()
_Bool cond_neural_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 145 of file cond_neural.c.
cond_neural_free()
void cond_neural_free (const XCSF * xcsf, const CL * c)
Definition at line 93 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_free().
cond_neural_general()
_Bool cond_neural_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 151 of file cond_neural.c.
cond_neural_init()
void cond_neural_init (const XCSF * xcsf, CL * c)
Definition at line 50 of file cond_neural.c.
References CL::cond, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX_HIDDEN_NEURONS, XCSF::COND_NUM_HIDDEN_NEURONS, irand_uniform(), LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, LOGISTIC, neural_init(), neural_layer_connected_init(), neural_layer_insert(), and XCSF::num_x_vars.
cond_neural_load()
size_t cond_neural_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 176 of file cond_neural.c.
References CL::cond, and neural_load().
cond_neural_match()
_Bool cond_neural_match (const XCSF * xcsf, CL * c, const double * x)
Definition at line 126 of file cond_neural.c.
References CL::cond, CL::m, COND_NEURAL::net, neural_output(), and neural_propagate().
Referenced by cond_neural_cover().
cond_neural_mutate()
_Bool cond_neural_mutate (const XCSF * xcsf, CL * c)
Definition at line 139 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_mutate().
cond_neural_print()
void cond_neural_print (const XCSF * xcsf, const CL * c)
Definition at line 157 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_print().
cond_neural_save()
size_t cond_neural_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 169 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_save().
cond_neural_size()
int cond_neural_size (const XCSF * xcsf, const CL * c)
Definition at line 163 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_size().
cond_neural_update()
void cond_neural_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 121 of file cond_neural.c.
Variable Documentation
cond_neural_vtbl
struct CondVtbl const cond_neural_vtbl static
Initial value:
= {
    &cond_neural_crossover,
    &cond_neural_general,
    &cond_neural_match,
    &cond_neural_mutate,
    &cond_neural_copy,
    &cond_neural_cover,
    &cond_neural_free,
    &cond_neural_init,
    &cond_neural_print,
    &cond_neural_update,
    &cond_neural_size,
    &cond_neural_save,
    &cond_neural_load
}
Multi-layer perceptron neural network condition implemented functions.
Definition at line 43 of file cond_neural.h.
Referenced by condition_set().