XCSF: cond_rectangle.h File Reference
cond_rectangle.h File Reference
Hyperrectangle condition functions.
Data Structures
struct COND_RECTANGLE
Hyperrectangle condition data structure.
Typedefs
typedef struct COND_RECTANGLE COND_RECTANGLE
Hyperrectangle condition data structure.
Functions
_Bool cond_rectangle_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_rectangle_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_rectangle_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_rectangle_mutate (const XCSF *xcsf, const CL *c)
void cond_rectangle_copy (const XCSF *xcsf, CL *dest, const CL *src)
void cond_rectangle_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_rectangle_free (const XCSF *xcsf, const CL *c)
void cond_rectangle_init (const XCSF *xcsf, CL *c)
void cond_rectangle_print (const XCSF *xcsf, const CL *c)
void cond_rectangle_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
int cond_rectangle_size (const XCSF *xcsf, const CL *c)
size_t cond_rectangle_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_rectangle_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const cond_rectangle_vtbl
Hyperrectangle condition implemented functions.
Detailed Description
Hyperrectangle condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file cond_rectangle.h.
Typedef Documentation
COND_RECTANGLE
typedef struct COND_RECTANGLE COND_RECTANGLE
Hyperrectangle condition data structure.
Function Documentation
cond_rectangle_copy()
void cond_rectangle_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 64 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::mu, N_MU, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_cover()
void cond_rectangle_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 77 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, rand_uniform(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_crossover()
_Bool cond_rectangle_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 118 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::P_CROSSOVER, rand_uniform(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_free()
void cond_rectangle_free (const XCSF * xcsf, const CL * c)
Definition at line 54 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::mu, and COND_RECTANGLE::spread.
cond_rectangle_general()
_Bool cond_rectangle_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 163 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_init()
void cond_rectangle_init (const XCSF * xcsf, CL * c)
Definition at line 40 of file cond_rectangle.c.
References CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, N_MU, rand_uniform(), sam_init(), and XCSF::x_dim.
cond_rectangle_load()
size_t cond_rectangle_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 206 of file cond_rectangle.c.
References CL::cond, N_MU, and XCSF::x_dim.
cond_rectangle_match()
_Bool cond_rectangle_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 97 of file cond_rectangle.c.
References cond_rectangle_dist().
cond_rectangle_mutate()
_Bool cond_rectangle_mutate (const XCSF * xcsf, const CL * c)
Definition at line 142 of file cond_rectangle.c.
References COND_RECTANGLE::center, clamp(), CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, COND_RECTANGLE::mu, N_MU, rand_normal(), sam_adapt(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_print()
void cond_rectangle_print (const XCSF * xcsf, const CL * c)
Definition at line 179 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_save()
size_t cond_rectangle_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 196 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::mu, N_MU, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_size()
int cond_rectangle_size (const XCSF * xcsf, const CL * c)
Definition at line 190 of file cond_rectangle.c.
References XCSF::x_dim.
cond_rectangle_update()
void cond_rectangle_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 86 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::COND_ETA, and XCSF::x_dim.
Variable Documentation
cond_rectangle_vtbl
struct CondVtbl const cond_rectangle_vtbl static
Initial value:
= {
    &cond_rectangle_crossover,
    &cond_rectangle_general,
    &cond_rectangle_match,
    &cond_rectangle_mutate,
    &cond_rectangle_copy,
    &cond_rectangle_cover,
    &cond_rectangle_free,
    &cond_rectangle_init,
    &cond_rectangle_print,
    &cond_rectangle_update,
    &cond_rectangle_size,
    &cond_rectangle_save,
    &cond_rectangle_load
}
Hyperrectangle condition implemented functions.
Definition at line 52 of file cond_rectangle.h.
Referenced by condition_set().