XCSF: cond_rectangle.c File Reference
cond_rectangle.c File Reference
Hyperrectangle condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "sam.h"
#include "cl.h"
#include "condition.h"
#include "cond_rectangle.h"
Data Structures
struct COND_RECTANGLE
Hyperrectangle condition data structure.
Macros
#define N_MU 1
Number of hyperrectangle mutation rates.
Typedefs
typedef struct COND_RECTANGLE COND_RECTANGLE
Hyperrectangle condition data structure.
Functions
static double cond_rectangle_dist (const XCSF *xcsf, const CL *c, const double *x)
void cond_rectangle_init (const XCSF *xcsf, CL *c)
void cond_rectangle_free (const XCSF *xcsf, const CL *c)
void cond_rectangle_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_rectangle_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_rectangle_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool cond_rectangle_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_rectangle_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_rectangle_mutate (const XCSF *xcsf, const CL *c)
_Bool cond_rectangle_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void cond_rectangle_print (const XCSF *xcsf, const CL *c)
int cond_rectangle_size (const XCSF *xcsf, const CL *c)
size_t cond_rectangle_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_rectangle_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Hyperrectangle condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file cond_rectangle.c.
Macro Definition Documentation
N_MU
#define N_MU 1
Number of hyperrectangle mutation rates.
Definition at line 36 of file cond_rectangle.c.
Referenced by cond_rectangle_copy(), cond_rectangle_init(), cond_rectangle_load(), cond_rectangle_mutate(), and cond_rectangle_save().
Typedef Documentation
COND_RECTANGLE
typedef struct COND_RECTANGLE COND_RECTANGLE
Hyperrectangle condition data structure.
Function Documentation
cond_rectangle_copy()
void cond_rectangle_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 71 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::mu, N_MU, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_cover()
void cond_rectangle_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 83 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, rand_uniform(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_crossover()
_Bool cond_rectangle_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 124 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::P_CROSSOVER, rand_uniform(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_dist()
static double cond_rectangle_dist (const XCSF * xcsf, const CL * c, const double * x) static
Definition at line 111 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::spread, and XCSF::x_dim.
Referenced by cond_rectangle_match().
cond_rectangle_free()
void cond_rectangle_free (const XCSF * xcsf, const CL * c)
Definition at line 62 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, and COND_RECTANGLE::spread.
cond_rectangle_general()
_Bool cond_rectangle_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 169 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_init()
void cond_rectangle_init (const XCSF * xcsf, CL * c)
Definition at line 49 of file cond_rectangle.c.
References CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, N_MU, rand_uniform(), sam_init(), and XCSF::x_dim.
cond_rectangle_load()
size_t cond_rectangle_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 212 of file cond_rectangle.c.
References CL::cond, N_MU, and XCSF::x_dim.
cond_rectangle_match()
_Bool cond_rectangle_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 103 of file cond_rectangle.c.
References cond_rectangle_dist().
cond_rectangle_mutate()
_Bool cond_rectangle_mutate (const XCSF * xcsf, const CL * c)
Definition at line 148 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, constrain(), COND_RECTANGLE::mu, N_MU, rand_normal(), sam_adapt(), COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_print()
void cond_rectangle_print (const XCSF * xcsf, const CL * c)
Definition at line 185 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_save()
size_t cond_rectangle_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 202 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, COND_RECTANGLE::mu, N_MU, COND_RECTANGLE::spread, and XCSF::x_dim.
cond_rectangle_size()
int cond_rectangle_size (const XCSF * xcsf, const CL * c)
Definition at line 196 of file cond_rectangle.c.
References XCSF::x_dim.
cond_rectangle_update()
void cond_rectangle_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 92 of file cond_rectangle.c.
References COND_RECTANGLE::center, CL::cond, XCSF::COND_ETA, and XCSF::x_dim.