XCSF: cond_gp.c File Reference
cond_gp.c File Reference
Tree GP condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "condition.h"
#include "cond_gp.h"
#include "gp.h"
Data Structures
struct COND_GP
Tree GP condition data structure.
Typedefs
typedef struct COND_GP COND_GP
Tree GP condition data structure.
Functions
static void cond_gp_rand (const XCSF *xcsf, const CL *c)
void cond_gp_init (const XCSF *xcsf, CL *c)
void cond_gp_free (const XCSF *xcsf, const CL *c)
void cond_gp_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_gp_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_gp_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool cond_gp_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_gp_mutate (const XCSF *xcsf, const CL *c)
_Bool cond_gp_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_gp_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void cond_gp_print (const XCSF *xcsf, const CL *c)
int cond_gp_size (const XCSF *xcsf, const CL *c)
size_t cond_gp_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_gp_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Tree GP condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file cond_gp.c.
Typedef Documentation
COND_GP
typedef struct COND_GP COND_GP
Tree GP condition data structure.
Function Documentation
cond_gp_copy()
void cond_gp_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 59 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_copy().
cond_gp_cover()
void cond_gp_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 74 of file cond_gp.c.
References cond_gp_match(), and cond_gp_rand().
cond_gp_crossover()
_Bool cond_gp_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 111 of file cond_gp.c.
References CL::cond, COND_GP::gp, XCSF::P_CROSSOVER, rand_uniform(), and tree_crossover().
cond_gp_free()
void cond_gp_free (const XCSF * xcsf, const CL * c)
Definition at line 52 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_free().
cond_gp_general()
_Bool cond_gp_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 124 of file cond_gp.c.
cond_gp_init()
void cond_gp_init (const XCSF * xcsf, CL * c)
Definition at line 45 of file cond_gp.c.
References CL::cond, and tree_rand().
cond_gp_load()
size_t cond_gp_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 152 of file cond_gp.c.
References CL::cond, and tree_load().
cond_gp_match()
_Bool cond_gp_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 86 of file cond_gp.c.
References CL::cond, COND_GP::gp, GP_TREE::p, and tree_eval().
Referenced by cond_gp_cover().
cond_gp_mutate()
_Bool cond_gp_mutate (const XCSF * xcsf, const CL * c)
Definition at line 99 of file cond_gp.c.
References CL::cond, COND_GP::gp, XCSF::P_MUTATION, rand_uniform(), and tree_mutate().
cond_gp_print()
void cond_gp_print (const XCSF * xcsf, const CL * c)
Definition at line 130 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_print().
cond_gp_rand()
static void cond_gp_rand (const XCSF * xcsf, const CL * c) static
Definition at line 67 of file cond_gp.c.
References CL::cond, COND_GP::gp, tree_free(), and tree_rand().
Referenced by cond_gp_cover().
cond_gp_save()
size_t cond_gp_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 145 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_save().
cond_gp_size()
int cond_gp_size (const XCSF * xcsf, const CL * c)
Definition at line 138 of file cond_gp.c.
References CL::cond, COND_GP::gp, and GP_TREE::len.
cond_gp_update()
void cond_gp_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 81 of file cond_gp.c.