XCSF: condition.h File Reference
condition.h File Reference
Interface for classifier conditions.
Data Structures
struct CondVtbl
Condition interface data structure.
Functions
void condition_set (const XCSF *xcsf, CL *c)
Sets a classifier's condition functions to the implementations.
static size_t cond_save (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the condition to a binary file.
static size_t cond_load (const XCSF *xcsf, CL *c, FILE *fp)
Reads the condition from a binary file.
static int cond_size (const XCSF *xcsf, const CL *c)
Returns the size of the classifier condition.
static void cond_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Updates the classifier's condition.
static _Bool cond_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier condition crossover.
static _Bool cond_general (const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the condition of classifier c1 is more general than c2.
static _Bool cond_match (const XCSF *xcsf, const CL *c, const double *x)
Calculates whether the condition matches the input.
static _Bool cond_mutate (const XCSF *xcsf, const CL *c)
Performs classifier condition mutation.
static void cond_copy (const XCSF *xcsf, CL *dest, const CL *src)
Copies the condition from one classifier to another.
static void cond_cover (const XCSF *xcsf, const CL *c, const double *x)
Generates a condition that matches the current input.
static void cond_free (const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier condition.
static void cond_init (const XCSF *xcsf, CL *c)
Initialises a classifier's condition.
static void cond_print (const XCSF *xcsf, const CL *c)
Prints the classifier condition.
Detailed Description
Interface for classifier conditions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file condition.h.
Function Documentation
cond_copy()
static void cond_copy (const XCSF * xcsf, CL * dest, const CL * src) inline static
Copies the condition from one classifier to another.
Parameters
xcsf The XCSF data structure.
dest The destination classifier.
src The source classifier.
Definition at line 140 of file condition.h.
References CondVtbl::cond_impl_copy, and CL::cond_vptr.
Referenced by cl_copy().
cond_cover()
static void cond_cover (const XCSF * xcsf, const CL * c, const double * x) inline static
Generates a condition that matches the current input.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is being covered.
x The input state to cover.
Definition at line 150 of file condition.h.
References CondVtbl::cond_impl_cover, and CL::cond_vptr.
Referenced by cl_cover().
cond_crossover()
static _Bool cond_crossover (const XCSF * xcsf, const CL * c1, const CL * c2) inline static
Performs classifier condition crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier whose condition is being crossed.
c2 The second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 98 of file condition.h.
References CondVtbl::cond_impl_crossover, and CL::cond_vptr.
Referenced by cl_crossover().
cond_free()
static void cond_free (const XCSF * xcsf, const CL * c) inline static
Frees the memory used by the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be freed.
Definition at line 159 of file condition.h.
References CondVtbl::cond_impl_free, and CL::cond_vptr.
Referenced by cl_free().
cond_general()
static _Bool cond_general (const XCSF * xcsf, const CL * c1, const CL * c2) inline static
Returns whether the condition of classifier c1 is more general than c2.
Parameters
xcsf The XCSF data structure.
c1 The classifier whose condition is tested to be more general.
c2 The classifier whose condition is tested to be more specific.
Returns
Whether the condition of c1 is more general than c2.
Definition at line 109 of file condition.h.
References CondVtbl::cond_impl_general, and CL::cond_vptr.
Referenced by cl_general().
cond_init()
static void cond_init (const XCSF * xcsf, CL * c) inline static
Initialises a classifier's condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be initialised.
Definition at line 168 of file condition.h.
References CondVtbl::cond_impl_init, and CL::cond_vptr.
Referenced by cl_rand().
cond_load()
static size_t cond_load (const XCSF * xcsf, CL * c, FILE * fp) inline static
Reads the condition from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 66 of file condition.h.
References CondVtbl::cond_impl_load, and CL::cond_vptr.
Referenced by cl_load().
cond_match()
static _Bool cond_match (const XCSF * xcsf, const CL * c, const double * x) inline static
Calculates whether the condition matches the input.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition to match.
x The input state.
Returns
Whether the condition matches the input.
Definition at line 120 of file condition.h.
References CondVtbl::cond_impl_match, and CL::cond_vptr.
Referenced by cl_match().
cond_mutate()
static _Bool cond_mutate (const XCSF * xcsf, const CL * c) inline static
Performs classifier condition mutation.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 130 of file condition.h.
References CondVtbl::cond_impl_mutate, and CL::cond_vptr.
Referenced by cl_mutate().
cond_print()
static void cond_print (const XCSF * xcsf, const CL * c) inline static
Prints the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be printed.
Definition at line 177 of file condition.h.
References CondVtbl::cond_impl_print, and CL::cond_vptr.
Referenced by cl_print().
cond_save()
static size_t cond_save (const XCSF * xcsf, const CL * c, FILE * fp) inline static
Writes the condition to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 55 of file condition.h.
References CondVtbl::cond_impl_save, and CL::cond_vptr.
Referenced by cl_save().
cond_size()
static int cond_size (const XCSF * xcsf, const CL * c) inline static
Returns the size of the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition size to return.
Returns
The size of the condition.
Definition at line 76 of file condition.h.
References CondVtbl::cond_impl_size, and CL::cond_vptr.
Referenced by cl_cond_size().
cond_update()
static void cond_update (const XCSF * xcsf, const CL * c, const double * x, const double * y) inline static
Updates the classifier's condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be updated.
x The input state.
y The payoff value.
Definition at line 87 of file condition.h.
References CondVtbl::cond_impl_update, and CL::cond_vptr.
Referenced by cl_update().
condition_set()
void condition_set (const XCSF * xcsf, CL * c)
Sets a classifier's condition functions to the implementations.
Parameters
xcsf The XCSF data structure.
c The classifier to set.
Definition at line 50 of file condition.c.
References CL::act_vptr, cond_dgp_vtbl, cond_dummy_vtbl, cond_ellipsoid_vtbl, cond_gp_vtbl, cond_neural_vtbl, cond_rectangle_vtbl, cond_ternary_vtbl, XCSF::COND_TYPE, COND_TYPE_DGP, COND_TYPE_DUMMY, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, CL::cond_vptr, rule_dgp_act_vtbl, rule_dgp_cond_vtbl, rule_neural_act_vtbl, rule_neural_cond_vtbl, RULE_TYPE_DGP, and RULE_TYPE_NEURAL.
Referenced by cl_load(), and cl_rand().