XCSF: cond_ellipsoid.c File Reference
cond_ellipsoid.c File Reference
Hyperellipsoid condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "condition.h"
#include "cond_ellipsoid.h"
Data Structures
struct COND_ELLIPSOID
Hyperellipsoid condition data structure.
Typedefs
typedef struct COND_ELLIPSOID COND_ELLIPSOID
Hyperellipsoid condition data structure.
Functions
static double cond_ellipsoid_dist (const XCSF *xcsf, CL *c, const double *x)
void cond_ellipsoid_init (const XCSF *xcsf, CL *c)
void cond_ellipsoid_free (const XCSF *xcsf, CL *c)
void cond_ellipsoid_copy (const XCSF *xcsf, CL *to, CL *from)
void cond_ellipsoid_cover (const XCSF *xcsf, CL *c, const double *x)
void cond_ellipsoid_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
_Bool cond_ellipsoid_match (const XCSF *xcsf, CL *c, const double *x)
_Bool cond_ellipsoid_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool cond_ellipsoid_mutate (const XCSF *xcsf, CL *c)
_Bool cond_ellipsoid_general (const XCSF *xcsf, CL *c1, CL *c2)
void cond_ellipsoid_print (const XCSF *xcsf, CL *c)
int cond_ellipsoid_size (const XCSF *xcsf, CL *c)
size_t cond_ellipsoid_save (const XCSF *xcsf, CL *c, FILE *fp)
size_t cond_ellipsoid_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Hyperellipsoid condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file cond_ellipsoid.c.
Typedef Documentation
COND_ELLIPSOID
typedef struct COND_ELLIPSOID COND_ELLIPSOID
Hyperellipsoid condition data structure.
Function Documentation
cond_ellipsoid_copy()
void cond_ellipsoid_copy (const XCSF * xcsf, CL * to, CL * from)
Definition at line 66 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, and COND_ELLIPSOID::spread.
cond_ellipsoid_cover()
void cond_ellipsoid_cover (const XCSF * xcsf, CL * c, const double * x)
Definition at line 77 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, XCSF::num_x_vars, rand_uniform(), and COND_ELLIPSOID::spread.
cond_ellipsoid_crossover()
_Bool cond_ellipsoid_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 119 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, XCSF::P_CROSSOVER, rand_uniform(), and COND_ELLIPSOID::spread.
cond_ellipsoid_dist()
static double cond_ellipsoid_dist (const XCSF * xcsf, CL * c, const double * x) static
Definition at line 108 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, and COND_ELLIPSOID::spread.
Referenced by cond_ellipsoid_match().
cond_ellipsoid_free()
void cond_ellipsoid_free (const XCSF * xcsf, CL * c)
Definition at line 57 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, and COND_ELLIPSOID::spread.
cond_ellipsoid_general()
_Bool cond_ellipsoid_general (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 165 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, and COND_ELLIPSOID::spread.
cond_ellipsoid_init()
void cond_ellipsoid_init (const XCSF * xcsf, CL * c)
Definition at line 45 of file cond_ellipsoid.c.
References CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, XCSF::num_x_vars, and rand_uniform().
cond_ellipsoid_load()
size_t cond_ellipsoid_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 208 of file cond_ellipsoid.c.
References CL::cond, and XCSF::num_x_vars.
cond_ellipsoid_match()
_Bool cond_ellipsoid_match (const XCSF * xcsf, CL * c, const double * x)
Definition at line 97 of file cond_ellipsoid.c.
References cond_ellipsoid_dist(), and CL::m.
cond_ellipsoid_mutate()
_Bool cond_ellipsoid_mutate (const XCSF * xcsf, CL * c)
Definition at line 143 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, constrain(), XCSF::num_x_vars, rand_normal(), XCSF::S_MUTATION, and COND_ELLIPSOID::spread.
cond_ellipsoid_print()
void cond_ellipsoid_print (const XCSF * xcsf, CL * c)
Definition at line 182 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, and COND_ELLIPSOID::spread.
cond_ellipsoid_save()
size_t cond_ellipsoid_save (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 199 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::num_x_vars, and COND_ELLIPSOID::spread.
cond_ellipsoid_size()
int cond_ellipsoid_size (const XCSF * xcsf, CL * c)
Definition at line 193 of file cond_ellipsoid.c.
References XCSF::num_x_vars.
cond_ellipsoid_update()
void cond_ellipsoid_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 86 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_ETA, and XCSF::num_x_vars.