XCSF: cond_neural.c File Reference
cond_neural.c File Reference
Multi-layer perceptron neural network condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "neural_activations.h"
#include "neural.h"
#include "neural_layer.h"
#include "neural_layer_connected.h"
#include "neural_layer_dropout.h"
#include "condition.h"
#include "cond_neural.h"
Data Structures
struct COND_NEURAL
Multi-layer perceptron neural network condition data structure.
Typedefs
typedef struct COND_NEURAL COND_NEURAL
Multi-layer perceptron neural network condition data structure.
Functions
static void cond_neural_rand (const XCSF *xcsf, const CL *c)
static uint32_t cond_neural_lopt (const XCSF *xcsf)
void cond_neural_init (const XCSF *xcsf, CL *c)
void cond_neural_free (const XCSF *xcsf, const CL *c)
void cond_neural_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_neural_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_neural_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool cond_neural_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_neural_mutate (const XCSF *xcsf, const CL *c)
_Bool cond_neural_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_neural_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void cond_neural_print (const XCSF *xcsf, const CL *c)
int cond_neural_size (const XCSF *xcsf, const CL *c)
size_t cond_neural_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_neural_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Multi-layer perceptron neural network condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file cond_neural.c.
Typedef Documentation
COND_NEURAL
typedef struct COND_NEURAL COND_NEURAL
Multi-layer perceptron neural network condition data structure.
Function Documentation
cond_neural_copy()
void cond_neural_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 104 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_copy().
cond_neural_cover()
void cond_neural_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 118 of file cond_neural.c.
References cond_neural_match(), and cond_neural_rand().
cond_neural_crossover()
_Bool cond_neural_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 148 of file cond_neural.c.
cond_neural_free()
void cond_neural_free (const XCSF * xcsf, const CL * c)
Definition at line 97 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_free().
cond_neural_general()
_Bool cond_neural_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 154 of file cond_neural.c.
cond_neural_init()
void cond_neural_init (const XCSF * xcsf, CL * c)
Definition at line 51 of file cond_neural.c.
References CL::cond, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX_HIDDEN_NEURONS, cond_neural_lopt(), XCSF::COND_NUM_HIDDEN_NEURONS, irand_uniform(), LAYER_EVOLVE_NEURONS, LOGISTIC, neural_init(), neural_layer_connected_init(), neural_layer_insert(), and XCSF::num_x_vars.
cond_neural_load()
size_t cond_neural_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 179 of file cond_neural.c.
References CL::cond, and neural_load().
cond_neural_lopt()
static uint32_t cond_neural_lopt (const XCSF * xcsf) static
Definition at line 82 of file cond_neural.c.
References XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, and LAYER_EVOLVE_WEIGHTS.
Referenced by cond_neural_init().
cond_neural_match()
_Bool cond_neural_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 130 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, neural_output(), and neural_propagate().
Referenced by cond_neural_cover().
cond_neural_mutate()
_Bool cond_neural_mutate (const XCSF * xcsf, const CL * c)
Definition at line 142 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_mutate().
cond_neural_print()
void cond_neural_print (const XCSF * xcsf, const CL * c)
Definition at line 160 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_print().
cond_neural_rand()
static void cond_neural_rand (const XCSF * xcsf, const CL * c) static
Definition at line 112 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_rand().
Referenced by cond_neural_cover().
cond_neural_save()
size_t cond_neural_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 172 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_save().
cond_neural_size()
int cond_neural_size (const XCSF * xcsf, const CL * c)
Definition at line 166 of file cond_neural.c.
References CL::cond, COND_NEURAL::net, and neural_size().
cond_neural_update()
void cond_neural_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 125 of file cond_neural.c.