XCSF: cond_gp.h File Reference
cond_gp.h File Reference
Tree GP condition functions.
Functions
_Bool cond_gp_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_gp_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_gp_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_gp_mutate (const XCSF *xcsf, const CL *c)
void cond_gp_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_gp_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_gp_free (const XCSF *xcsf, const CL *c)
void cond_gp_init (const XCSF *xcsf, CL *c)
void cond_gp_print (const XCSF *xcsf, const CL *c)
void cond_gp_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
int cond_gp_size (const XCSF *xcsf, const CL *c)
size_t cond_gp_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_gp_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const cond_gp_vtbl
Tree GP condition implemented functions.
Detailed Description
Tree GP condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file cond_gp.h.
Function Documentation
cond_gp_copy()
void cond_gp_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 60 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_copy().
cond_gp_cover()
void cond_gp_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 75 of file cond_gp.c.
References cond_gp_match(), and cond_gp_rand().
cond_gp_crossover()
_Bool cond_gp_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 104 of file cond_gp.c.
References CL::cond, COND_GP::gp, XCSF::P_CROSSOVER, rand_uniform(), and tree_crossover().
cond_gp_free()
void cond_gp_free (const XCSF * xcsf, const CL * c)
Definition at line 53 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_free().
cond_gp_general()
_Bool cond_gp_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 115 of file cond_gp.c.
cond_gp_init()
void cond_gp_init (const XCSF * xcsf, CL * c)
Definition at line 46 of file cond_gp.c.
References CL::cond, and tree_rand().
cond_gp_load()
size_t cond_gp_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 143 of file cond_gp.c.
References CL::cond, and tree_load().
cond_gp_match()
_Bool cond_gp_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 87 of file cond_gp.c.
References CL::cond, COND_GP::gp, GP_TREE::p, and tree_eval().
Referenced by cond_gp_cover().
cond_gp_mutate()
_Bool cond_gp_mutate (const XCSF * xcsf, const CL * c)
Definition at line 98 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_mutate().
cond_gp_print()
void cond_gp_print (const XCSF * xcsf, const CL * c)
Definition at line 121 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_print().
cond_gp_save()
size_t cond_gp_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 136 of file cond_gp.c.
References CL::cond, COND_GP::gp, and tree_save().
cond_gp_size()
int cond_gp_size (const XCSF * xcsf, const CL * c)
Definition at line 129 of file cond_gp.c.
References CL::cond, COND_GP::gp, and GP_TREE::len.
cond_gp_update()
void cond_gp_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 82 of file cond_gp.c.
Variable Documentation
cond_gp_vtbl
struct CondVtbl const cond_gp_vtbl static
Initial value:
= {
    &cond_gp_crossover,
    &cond_gp_general,
    &cond_gp_match,
    &cond_gp_mutate,
    &cond_gp_copy,
    &cond_gp_cover,
    &cond_gp_free,
    &cond_gp_init,
    &cond_gp_print,
    &cond_gp_update,
    &cond_gp_size,
    &cond_gp_save,
    &cond_gp_load
}
Tree GP condition implemented functions.
Definition at line 43 of file cond_gp.h.
Referenced by condition_set().