XCSF: cond_dgp.c File Reference
cond_dgp.c File Reference
Dynamical GP graph condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "xcsf.h"
#include "utils.h"
#include "sam.h"
#include "dgp.h"
#include "cl.h"
#include "condition.h"
#include "cond_dgp.h"
Data Structures
struct COND_DGP
Dynamical GP graph condition data structure.
Typedefs
typedef struct COND_DGP COND_DGP
Dynamical GP graph condition data structure.
Functions
static void cond_dgp_rand (const XCSF *xcsf, const CL *c)
void cond_dgp_init (const XCSF *xcsf, CL *c)
void cond_dgp_free (const XCSF *xcsf, const CL *c)
void cond_dgp_copy (const XCSF *xcsf, CL *dest, const CL *src)
void cond_dgp_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_dgp_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool cond_dgp_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_dgp_mutate (const XCSF *xcsf, const CL *c)
_Bool cond_dgp_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_dgp_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void cond_dgp_print (const XCSF *xcsf, const CL *c)
int cond_dgp_size (const XCSF *xcsf, const CL *c)
size_t cond_dgp_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_dgp_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Dynamical GP graph condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file cond_dgp.c.
Typedef Documentation
COND_DGP
typedef struct COND_DGP COND_DGP
Dynamical GP graph condition data structure.
Function Documentation
cond_dgp_copy()
void cond_dgp_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 59 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, graph_copy(), graph_init(), and GRAPH::n.
cond_dgp_cover()
void cond_dgp_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 74 of file cond_dgp.c.
References cond_dgp_match(), and cond_dgp_rand().
cond_dgp_crossover()
_Bool cond_dgp_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 102 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_crossover().
cond_dgp_free()
void cond_dgp_free (const XCSF * xcsf, const CL * c)
Definition at line 52 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_free().
cond_dgp_general()
_Bool cond_dgp_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 109 of file cond_dgp.c.
cond_dgp_init()
void cond_dgp_init (const XCSF * xcsf, CL * c)
Definition at line 44 of file cond_dgp.c.
References CL::cond, XCSF::DGP_NUM_NODES, graph_init(), and graph_rand().
cond_dgp_load()
size_t cond_dgp_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 136 of file cond_dgp.c.
References CL::cond, and graph_load().
cond_dgp_match()
_Bool cond_dgp_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 86 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, graph_output(), and graph_update().
Referenced by cond_dgp_cover().
cond_dgp_mutate()
_Bool cond_dgp_mutate (const XCSF * xcsf, const CL * c)
Definition at line 96 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_mutate().
cond_dgp_print()
void cond_dgp_print (const XCSF * xcsf, const CL * c)
Definition at line 115 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_print().
cond_dgp_rand()
static void cond_dgp_rand (const XCSF * xcsf, const CL * c) static
Definition at line 68 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_rand().
Referenced by cond_dgp_cover().
cond_dgp_save()
size_t cond_dgp_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 129 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_save().
cond_dgp_size()
int cond_dgp_size (const XCSF * xcsf, const CL * c)
Definition at line 122 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and GRAPH::n.
cond_dgp_update()
void cond_dgp_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 81 of file cond_dgp.c.