XCSF: cond_dgp.h File Reference
cond_dgp.h File Reference
Dynamical GP graph condition functions.
Functions
_Bool cond_dgp_crossover (XCSF *xcsf, CL *c1, CL *c2)
_Bool cond_dgp_general (XCSF *xcsf, CL *c1, CL *c2)
_Bool cond_dgp_match (XCSF *xcsf, CL *c, double *x)
_Bool cond_dgp_mutate (XCSF *xcsf, CL *c)
void cond_dgp_copy (XCSF *xcsf, CL *to, CL *from)
void cond_dgp_cover (XCSF *xcsf, CL *c, double *x)
void cond_dgp_free (XCSF *xcsf, CL *c)
void cond_dgp_init (XCSF *xcsf, CL *c)
void cond_dgp_print (XCSF *xcsf, CL *c)
void cond_dgp_update (XCSF *xcsf, CL *c, double *x, double *y)
int cond_dgp_size (XCSF *xcsf, CL *c)
size_t cond_dgp_save (XCSF *xcsf, CL *c, FILE *fp)
size_t cond_dgp_load (XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const cond_dgp_vtbl
Dynamical GP graph condition implemented functions.
Detailed Description
Dynamical GP graph condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2019.
Definition in file cond_dgp.h.
Function Documentation
cond_dgp_copy()
void cond_dgp_copy (XCSF * xcsf, CL * to, CL * from)
Definition at line 60 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, graph_copy(), graph_init(), and GRAPH::n.
cond_dgp_cover()
void cond_dgp_cover (XCSF * xcsf, CL * c, double * x)
Definition at line 75 of file cond_dgp.c.
References cond_dgp_match(), and cond_dgp_rand().
cond_dgp_crossover()
_Bool cond_dgp_crossover (XCSF * xcsf, CL * c1, CL * c2)
Definition at line 106 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_crossover().
cond_dgp_free()
void cond_dgp_free (XCSF * xcsf, CL * c)
Definition at line 53 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_free().
cond_dgp_general()
_Bool cond_dgp_general (XCSF * xcsf, CL * c1, CL * c2)
Definition at line 113 of file cond_dgp.c.
References CL::exp, CL::mhist, and XCSF::THETA_SUB.
cond_dgp_init()
void cond_dgp_init (XCSF * xcsf, CL * c)
Definition at line 45 of file cond_dgp.c.
References CL::cond, XCSF::DGP_NUM_NODES, graph_init(), and graph_rand().
cond_dgp_load()
size_t cond_dgp_load (XCSF * xcsf, CL * c, FILE * fp)
Definition at line 149 of file cond_dgp.c.
References CL::cond, and graph_load().
cond_dgp_match()
_Bool cond_dgp_match (XCSF * xcsf, CL * c, double * x)
Definition at line 87 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, graph_output(), graph_update(), and CL::m.
Referenced by cond_dgp_cover().
cond_dgp_mutate()
_Bool cond_dgp_mutate (XCSF * xcsf, CL * c)
Definition at line 100 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_mutate().
cond_dgp_print()
void cond_dgp_print (XCSF * xcsf, CL * c)
Definition at line 128 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_print().
cond_dgp_save()
size_t cond_dgp_save (XCSF * xcsf, CL * c, FILE * fp)
Definition at line 142 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and graph_save().
cond_dgp_size()
int cond_dgp_size (XCSF * xcsf, CL * c)
Definition at line 135 of file cond_dgp.c.
References CL::cond, COND_DGP::dgp, and GRAPH::n.
cond_dgp_update()
void cond_dgp_update (XCSF * xcsf, CL * c, double * x, double * y)
Definition at line 82 of file cond_dgp.c.
Variable Documentation
cond_dgp_vtbl
struct CondVtbl const cond_dgp_vtbl static
Initial value:
= {
    &cond_dgp_crossover,
    &cond_dgp_general,
    &cond_dgp_match,
    &cond_dgp_mutate,
    &cond_dgp_copy,
    &cond_dgp_cover,
    &cond_dgp_free,
    &cond_dgp_init,
    &cond_dgp_print,
    &cond_dgp_update,
    &cond_dgp_size,
    &cond_dgp_save,
    &cond_dgp_load
}
Dynamical GP graph condition implemented functions.
Definition at line 43 of file cond_dgp.h.
Referenced by condition_set().