XCSF: cond_ternary.c File Reference
cond_ternary.c File Reference
Ternary condition functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "condition.h"
#include "cond_ternary.h"
Data Structures
struct COND_TERNARY
Ternary condition data structure.
Macros
#define P_DONTCARE 0.5
Don't care probability in randomisation and covering.
#define DONT_CARE '#'
Don't care symbol.
Typedefs
typedef struct COND_TERNARY COND_TERNARY
Ternary condition data structure.
Functions
static void cond_ternary_rand (const XCSF *xcsf, const CL *c)
void cond_ternary_init (const XCSF *xcsf, CL *c)
void cond_ternary_free (const XCSF *xcsf, const CL *c)
void cond_ternary_copy (const XCSF *xcsf, CL *to, const CL *from)
void cond_ternary_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_ternary_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool cond_ternary_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_ternary_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_ternary_mutate (const XCSF *xcsf, const CL *c)
_Bool cond_ternary_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void cond_ternary_print (const XCSF *xcsf, const CL *c)
int cond_ternary_size (const XCSF *xcsf, const CL *c)
size_t cond_ternary_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_ternary_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Ternary condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Binarises inputs.
Definition in file cond_ternary.c.
Macro Definition Documentation
DONT_CARE
#define DONT_CARE '#'
Don't care symbol.
Definition at line 37 of file cond_ternary.c.
Referenced by cond_ternary_cover(), cond_ternary_general(), cond_ternary_match(), cond_ternary_mutate(), and cond_ternary_rand().
P_DONTCARE
#define P_DONTCARE 0.5
Don't care probability in randomisation and covering.
Definition at line 36 of file cond_ternary.c.
Referenced by cond_ternary_cover(), and cond_ternary_rand().
Typedef Documentation
COND_TERNARY
typedef struct COND_TERNARY COND_TERNARY
Ternary condition data structure.
Function Documentation
cond_ternary_copy()
void cond_ternary_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 85 of file cond_ternary.c.
References CL::cond, COND_TERNARY::len, and COND_TERNARY::string.
cond_ternary_cover()
void cond_ternary_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 96 of file cond_ternary.c.
References CL::cond, XCSF::COND_BITS, DONT_CARE, float_to_binary(), XCSF::num_x_vars, P_DONTCARE, rand_uniform(), and COND_TERNARY::string.
cond_ternary_crossover()
_Bool cond_ternary_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 134 of file cond_ternary.c.
References CL::cond, COND_TERNARY::len, XCSF::P_CROSSOVER, rand_uniform(), and COND_TERNARY::string.
cond_ternary_free()
void cond_ternary_free (const XCSF * xcsf, const CL * c)
Definition at line 77 of file cond_ternary.c.
References CL::cond, and COND_TERNARY::string.
cond_ternary_general()
_Bool cond_ternary_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 175 of file cond_ternary.c.
References CL::cond, DONT_CARE, COND_TERNARY::len, and COND_TERNARY::string.
cond_ternary_init()
void cond_ternary_init (const XCSF * xcsf, CL * c)
Definition at line 49 of file cond_ternary.c.
References CL::cond, XCSF::COND_BITS, cond_ternary_rand(), and XCSF::num_x_vars.
cond_ternary_load()
size_t cond_ternary_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 221 of file cond_ternary.c.
References CL::cond.
cond_ternary_match()
_Bool cond_ternary_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 118 of file cond_ternary.c.
References CL::cond, XCSF::COND_BITS, DONT_CARE, float_to_binary(), XCSF::num_x_vars, and COND_TERNARY::string.
cond_ternary_mutate()
_Bool cond_ternary_mutate (const XCSF * xcsf, const CL * c)
Definition at line 152 of file cond_ternary.c.
References CL::cond, DONT_CARE, COND_TERNARY::len, XCSF::P_MUTATION, rand_uniform(), and COND_TERNARY::string.
cond_ternary_print()
void cond_ternary_print (const XCSF * xcsf, const CL * c)
Definition at line 193 of file cond_ternary.c.
References CL::cond, COND_TERNARY::len, and COND_TERNARY::string.
cond_ternary_rand()
static void cond_ternary_rand (const XCSF * xcsf, const CL * c) static
Definition at line 58 of file cond_ternary.c.
References CL::cond, DONT_CARE, COND_TERNARY::len, P_DONTCARE, rand_uniform(), and COND_TERNARY::string.
Referenced by cond_ternary_init().
cond_ternary_save()
size_t cond_ternary_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 211 of file cond_ternary.c.
References CL::cond, COND_TERNARY::len, and COND_TERNARY::string.
cond_ternary_size()
int cond_ternary_size (const XCSF * xcsf, const CL * c)
Definition at line 204 of file cond_ternary.c.
References CL::cond, and COND_TERNARY::len.
cond_ternary_update()
void cond_ternary_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 113 of file cond_ternary.c.