XCSF: cond_ellipsoid.h File Reference
cond_ellipsoid.h File Reference
Hyperellipsoid condition functions.
Functions
_Bool cond_ellipsoid_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_ellipsoid_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool cond_ellipsoid_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool cond_ellipsoid_mutate (const XCSF *xcsf, const CL *c)
void cond_ellipsoid_copy (const XCSF *xcsf, CL *dest, const CL *src)
void cond_ellipsoid_cover (const XCSF *xcsf, const CL *c, const double *x)
void cond_ellipsoid_free (const XCSF *xcsf, const CL *c)
void cond_ellipsoid_init (const XCSF *xcsf, CL *c)
void cond_ellipsoid_print (const XCSF *xcsf, const CL *c)
void cond_ellipsoid_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
int cond_ellipsoid_size (const XCSF *xcsf, const CL *c)
size_t cond_ellipsoid_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t cond_ellipsoid_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const cond_ellipsoid_vtbl
Hyperellipsoid condition implemented functions.
Detailed Description
Hyperellipsoid condition functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file cond_ellipsoid.h.
Function Documentation
cond_ellipsoid_copy()
void cond_ellipsoid_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 71 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, COND_ELLIPSOID::mu, N_MU, COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_cover()
void cond_ellipsoid_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 83 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, rand_uniform(), COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_crossover()
_Bool cond_ellipsoid_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 122 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::P_CROSSOVER, rand_uniform(), COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_free()
void cond_ellipsoid_free (const XCSF * xcsf, const CL * c)
Definition at line 62 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, and COND_ELLIPSOID::spread.
cond_ellipsoid_general()
_Bool cond_ellipsoid_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 167 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_init()
void cond_ellipsoid_init (const XCSF * xcsf, CL * c)
Definition at line 49 of file cond_ellipsoid.c.
References CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, XCSF::COND_SMIN, N_MU, rand_uniform(), sam_init(), and XCSF::x_dim.
cond_ellipsoid_load()
size_t cond_ellipsoid_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 210 of file cond_ellipsoid.c.
References CL::cond, N_MU, and XCSF::x_dim.
cond_ellipsoid_match()
_Bool cond_ellipsoid_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 103 of file cond_ellipsoid.c.
References cond_ellipsoid_dist().
cond_ellipsoid_mutate()
_Bool cond_ellipsoid_mutate (const XCSF * xcsf, const CL * c)
Definition at line 146 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_MAX, XCSF::COND_MIN, constrain(), COND_ELLIPSOID::mu, N_MU, rand_normal(), sam_adapt(), COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_print()
void cond_ellipsoid_print (const XCSF * xcsf, const CL * c)
Definition at line 183 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_save()
size_t cond_ellipsoid_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 200 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, COND_ELLIPSOID::mu, N_MU, COND_ELLIPSOID::spread, and XCSF::x_dim.
cond_ellipsoid_size()
int cond_ellipsoid_size (const XCSF * xcsf, const CL * c)
Definition at line 194 of file cond_ellipsoid.c.
References XCSF::x_dim.
cond_ellipsoid_update()
void cond_ellipsoid_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 92 of file cond_ellipsoid.c.
References COND_ELLIPSOID::center, CL::cond, XCSF::COND_ETA, and XCSF::x_dim.
Variable Documentation
cond_ellipsoid_vtbl
struct CondVtbl const cond_ellipsoid_vtbl static
Initial value:
= {
    &cond_ellipsoid_crossover,
    &cond_ellipsoid_general,
    &cond_ellipsoid_match,
    &cond_ellipsoid_mutate,
    &cond_ellipsoid_copy,
    &cond_ellipsoid_cover,
    &cond_ellipsoid_free,
    &cond_ellipsoid_init,
    &cond_ellipsoid_print,
    &cond_ellipsoid_update,
    &cond_ellipsoid_size,
    &cond_ellipsoid_save,
    &cond_ellipsoid_load
}
Hyperellipsoid condition implemented functions.
Definition at line 43 of file cond_ellipsoid.h.
Referenced by condition_set().