XCSF: config.c File Reference
config.c File Reference
Configuration file handling functions.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <inttypes.h>
#include <errno.h>
#include "xcsf.h"
#include "gp.h"
#include "config.h"
#include "loss.h"
Macros
#define ARRAY_DELIM ","
Delimeter for config arrays.
#define MAXLEN 127
Maximum config file line length to read.
#define BASE 10
Decimal numbers.
Functions
static void config_get_ints (char *str, int *val)
Reads a csv list of ints into an array.
static void config_newnvpair (XCSF *xcsf, const char *param)
Adds a parameter to the list.
static void config_process (XCSF *xcsf, const char *configline)
Parses a line of the config file and adds to the list.
static void config_read (XCSF *xcsf, const char *filename)
Reads the specified configuration file.
static void config_trim (char *s)
Removes tabs/spaces/lf/cr.
static void params_cl_action (XCSF *xcsf, const char *name, const char *value)
Sets classifier action parameters.
static void params_cl_condition (XCSF *xcsf, const char *name, char *value)
Sets classifier condition parameters.
static void params_cl_general (XCSF *xcsf, const char *name, const char *value)
Sets general classifier parameters.
static void params_cl_prediction (XCSF *xcsf, const char *name, char *value)
Sets classifier prediction parameters.
static void params_ea (XCSF *xcsf, const char *name, const char *value)
Sets evolutionary algorithm parameters.
static void params_general (XCSF *xcsf, const char *name, const char *value)
Sets general XCSF parameters.
static void params_multistep (XCSF *xcsf, const char *name, const char *value)
Sets multistep experiment parameters.
static void params_subsumption (XCSF *xcsf, const char *name, const char *value)
Sets subsumption parameters.
static void config_defaults (XCSF *xcsf)
Initialises default XCSF parameters.
static void defaults_cl_action (XCSF *xcsf)
Initialises default classifier action parameters.
static void defaults_cl_condition (XCSF *xcsf)
Initialises default classifier condition parameters.
static void defaults_cl_general (XCSF *xcsf)
Initialises default general classifier parameters.
static void defaults_cl_prediction (XCSF *xcsf)
Initialises default classifier prediction parameters.
static void defaults_ea (XCSF *xcsf)
Initialises default evolutionary algorithm parameters.
static void defaults_general (XCSF *xcsf)
Initialises default XCSF general parameters.
static void defaults_multistep (XCSF *xcsf)
Initialises default multistep parameters.
static void defaults_subsumption (XCSF *xcsf)
Initialises default subsumption parameters.
static void print_params_cl_action (const XCSF *xcsf)
Prints XCSF action parameters.
static void print_params_cl_condition (const XCSF *xcsf)
Prints XCSF condtion parameters.
static void print_params_cl_general (const XCSF *xcsf)
Prints XCSF general classifier parameters.
static void print_params_cl_prediction (const XCSF *xcsf)
Prints XCSF prediction parameters.
static void print_params_ea (const XCSF *xcsf)
Prints XCSF evolutionary algorithm parameters.
static void print_params_general (const XCSF *xcsf)
Prints XCSF general parameters.
static void print_params_multistep (const XCSF *xcsf)
Prints XCSF multistep parameters.
static void print_params_subsumption (const XCSF *xcsf)
Prints XCSF subsumption parameters.
void config_init (XCSF *xcsf, const char *filename)
Initialises global constants and reads the specified configuration file.
void config_free (const XCSF *xcsf)
Frees all global constants.
static void param_add (XCSF *xcsf, const char *name, char *value)
Sets specified parameter.
void config_print (const XCSF *xcsf)
Prints all XCSF parameters.
Detailed Description
Configuration file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file config.c.
Macro Definition Documentation
ARRAY_DELIM
#define ARRAY_DELIM ","
Delimeter for config arrays.
Definition at line 39 of file config.c.
Referenced by config_get_ints().
BASE
#define BASE 10
Decimal numbers.
Definition at line 41 of file config.c.
Referenced by config_get_ints(), params_cl_action(), params_cl_condition(), params_cl_general(), params_cl_prediction(), params_ea(), params_general(), params_multistep(), and params_subsumption().
MAXLEN
#define MAXLEN 127
Maximum config file line length to read.
Definition at line 40 of file config.c.
Referenced by config_newnvpair(), config_process(), and config_read().
Function Documentation
config_defaults()
static void config_defaults (XCSF * xcsf) static
Initialises default XCSF parameters.
Definition at line 568 of file config.c.
References defaults_cl_action(), defaults_cl_condition(), defaults_cl_general(), defaults_cl_prediction(), defaults_ea(), defaults_general(), defaults_multistep(), and defaults_subsumption().
Referenced by config_init().
config_free()
void config_free (const XCSF * xcsf)
Frees all global constants.
Parameters
xcsf The XCSF data structure.
Definition at line 100 of file config.c.
References tree_free_cons().
Referenced by main().
config_get_ints()
static void config_get_ints (char * str, int * val) static
Reads a csv list of ints into an array.
Parameters
str String list of values.
val An integer array (set by this function).
Definition at line 457 of file config.c.
References ARRAY_DELIM, and BASE.
Referenced by params_cl_condition(), and params_cl_prediction().
config_init()
void config_init (XCSF * xcsf, const char * filename)
Initialises global constants and reads the specified configuration file.
Parameters
xcsf The XCSF data structure.
filename The name of the config file to read.
Definition at line 82 of file config.c.
References config_defaults(), config_read(), loss_set_func(), XCSF::OMP_NUM_THREADS, and tree_init_cons().
Referenced by main(), and XCS::xcs_init().
config_newnvpair()
static void config_newnvpair (XCSF * xcsf, const char * param) static
Adds a parameter to the list.
Parameters
xcsf The XCSF data structure.
param The parameter to add.
Definition at line 488 of file config.c.
References MAXLEN, and param_add().
Referenced by config_process().
config_print()
void config_print (const XCSF * xcsf)
Prints all XCSF parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 710 of file config.c.
References print_params_cl_action(), print_params_cl_condition(), print_params_cl_general(), print_params_cl_prediction(), print_params_ea(), print_params_general(), print_params_multistep(), and print_params_subsumption().
Referenced by XCS::print_params().
config_process()
static void config_process (XCSF * xcsf, const char * configline) static
Parses a line of the config file and adds to the list.
Parameters
xcsf The XCSF data structure.
configline A single line of the configuration file.
Definition at line 526 of file config.c.
References config_newnvpair(), and MAXLEN.
Referenced by config_read().
config_read()
static void config_read (XCSF * xcsf, const char * filename) static
Reads the specified configuration file.
Parameters
xcsf The XCSF data structure.
filename The name of the configuration file.
Definition at line 548 of file config.c.
References config_process(), config_trim(), and MAXLEN.
Referenced by config_init().
config_trim()
static void config_trim (char * s) static
Removes tabs/spaces/lf/cr.
Parameters
s The line to trim.
Definition at line 474 of file config.c.
Referenced by config_read().
defaults_cl_action()
static void defaults_cl_action (XCSF * xcsf) static
Initialises default classifier action parameters.
Definition at line 701 of file config.c.
References XCSF::ACT_TYPE.
Referenced by config_defaults().
defaults_cl_condition()
static void defaults_cl_condition (XCSF * xcsf) static
Initialises default classifier condition parameters.
Definition at line 647 of file config.c.
References XCSF::COND_BITS, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_ACTIVATION, XCSF::COND_MAX, XCSF::COND_MAX_NEURONS, XCSF::COND_MIN, XCSF::COND_NUM_NEURONS, XCSF::COND_OUTPUT_ACTIVATION, XCSF::COND_SMIN, XCSF::COND_TYPE, XCSF::DGP_NUM_NODES, XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, XCSF::MAX_K, MAX_LAYERS, XCSF::MAX_NEURON_MOD, XCSF::MAX_T, and XCSF::RESET_STATES.
Referenced by config_defaults().
defaults_cl_general()
static void defaults_cl_general (XCSF * xcsf) static
Initialises default general classifier parameters.
Definition at line 606 of file config.c.
References XCSF::ALPHA, XCSF::BETA, XCSF::DELTA, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::FIT_REDUC, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, and XCSF::THETA_DEL.
Referenced by config_defaults().
defaults_cl_prediction()
static void defaults_cl_prediction (XCSF * xcsf) static
Initialises default classifier prediction parameters.
Definition at line 676 of file config.c.
References MAX_LAYERS, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_ACTIVATION, XCSF::PRED_MAX_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_NEURONS, XCSF::PRED_OUTPUT_ACTIVATION, XCSF::PRED_RESET, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, and XCSF::PRED_X0.
Referenced by config_defaults().
defaults_ea()
static void defaults_ea (XCSF * xcsf) static
Initialises default evolutionary algorithm parameters.
Definition at line 634 of file config.c.
References XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::LAMBDA, XCSF::P_CROSSOVER, XCSF::SAM_TYPE, and XCSF::THETA_EA.
Referenced by config_defaults().
defaults_general()
static void defaults_general (XCSF * xcsf) static
Initialises default XCSF general parameters.
Definition at line 583 of file config.c.
References XCSF::LOSS_FUNC, XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by config_defaults().
defaults_multistep()
static void defaults_multistep (XCSF * xcsf) static
Initialises default multistep parameters.
Definition at line 596 of file config.c.
References XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by config_defaults().
defaults_subsumption()
static void defaults_subsumption (XCSF * xcsf) static
Initialises default subsumption parameters.
Definition at line 624 of file config.c.
References XCSF::EA_SUBSUMPTION, XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by config_defaults().
param_add()
static void param_add (XCSF * xcsf, const char * name, char * value) static
Sets specified parameter.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 111 of file config.c.
References params_cl_action(), params_cl_condition(), params_cl_general(), params_cl_prediction(), params_ea(), params_general(), params_multistep(), and params_subsumption().
Referenced by config_newnvpair().
params_cl_action()
static void params_cl_action (XCSF * xcsf, const char * name, const char * value) static
Sets classifier action parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 444 of file config.c.
References XCSF::ACT_TYPE, and BASE.
Referenced by param_add().
params_cl_condition()
static void params_cl_condition (XCSF * xcsf, const char * name, char * value) static
Sets classifier condition parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 280 of file config.c.
References BASE, XCSF::COND_BITS, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_ACTIVATION, XCSF::COND_MAX, XCSF::COND_MAX_NEURONS, XCSF::COND_MIN, XCSF::COND_NUM_NEURONS, XCSF::COND_OUTPUT_ACTIVATION, XCSF::COND_SMIN, XCSF::COND_TYPE, config_get_ints(), XCSF::DGP_NUM_NODES, XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, XCSF::MAX_K, MAX_LAYERS, XCSF::MAX_NEURON_MOD, XCSF::MAX_T, and XCSF::RESET_STATES.
Referenced by param_add().
params_cl_general()
static void params_cl_general (XCSF * xcsf, const char * name, const char * value) static
Sets general classifier parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 236 of file config.c.
References XCSF::ALPHA, BASE, XCSF::BETA, XCSF::DELTA, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::FIT_REDUC, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, and XCSF::THETA_DEL.
Referenced by param_add().
params_cl_prediction()
static void params_cl_prediction (XCSF * xcsf, const char * name, char * value) static
Sets classifier prediction parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 365 of file config.c.
References BASE, config_get_ints(), MAX_LAYERS, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_ACTIVATION, XCSF::PRED_MAX_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_NEURONS, XCSF::PRED_OUTPUT_ACTIVATION, XCSF::PRED_RESET, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, and XCSF::PRED_X0.
Referenced by param_add().
params_ea()
static void params_ea (XCSF * xcsf, const char * name, const char * value) static
Sets evolutionary algorithm parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 207 of file config.c.
References BASE, XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::LAMBDA, XCSF::P_CROSSOVER, XCSF::SAM_TYPE, and XCSF::THETA_EA.
Referenced by param_add().
params_general()
static void params_general (XCSF * xcsf, const char * name, const char * value) static
Sets general XCSF parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 129 of file config.c.
References BASE, XCSF::LOSS_FUNC, XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by param_add().
params_multistep()
static void params_multistep (XCSF * xcsf, const char * name, const char * value) static
Sets multistep experiment parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 161 of file config.c.
References BASE, XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by param_add().
params_subsumption()
static void params_subsumption (XCSF * xcsf, const char * name, const char * value) static
Sets subsumption parameters.
Parameters
xcsf The XCSF data structure.
name Parameter name.
value Parameter value.
Definition at line 181 of file config.c.
References BASE, XCSF::EA_SUBSUMPTION, XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by param_add().
print_params_cl_action()
static void print_params_cl_action (const XCSF * xcsf) static
Prints XCSF action parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 877 of file config.c.
References XCSF::ACT_TYPE.
Referenced by config_print().
print_params_cl_condition()
static void print_params_cl_condition (const XCSF * xcsf) static
Prints XCSF condtion parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 799 of file config.c.
References XCSF::COND_BITS, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_ACTIVATION, XCSF::COND_MAX, XCSF::COND_MAX_NEURONS, XCSF::COND_MIN, XCSF::COND_NUM_NEURONS, XCSF::COND_OUTPUT_ACTIVATION, XCSF::COND_SMIN, XCSF::COND_TYPE, XCSF::DGP_NUM_NODES, XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, XCSF::MAX_K, MAX_LAYERS, XCSF::MAX_NEURON_MOD, XCSF::MAX_T, and XCSF::RESET_STATES.
Referenced by config_print().
print_params_cl_general()
static void print_params_cl_general (const XCSF * xcsf) static
Prints XCSF general classifier parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 753 of file config.c.
References XCSF::ALPHA, XCSF::BETA, XCSF::DELTA, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::FIT_REDUC, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::M_PROBATION, XCSF::NU, and XCSF::THETA_DEL.
Referenced by config_print().
print_params_cl_prediction()
static void print_params_cl_prediction (const XCSF * xcsf) static
Prints XCSF prediction parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 839 of file config.c.
References MAX_LAYERS, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_ACTIVATION, XCSF::PRED_MAX_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_NEURONS, XCSF::PRED_OUTPUT_ACTIVATION, XCSF::PRED_RESET, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, and XCSF::PRED_X0.
Referenced by config_print().
print_params_ea()
static void print_params_ea (const XCSF * xcsf) static
Prints XCSF evolutionary algorithm parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 785 of file config.c.
References XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::LAMBDA, XCSF::P_CROSSOVER, XCSF::SAM_TYPE, and XCSF::THETA_EA.
Referenced by config_print().
print_params_general()
static void print_params_general (const XCSF * xcsf) static
Prints XCSF general parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 727 of file config.c.
References XCSF::LOSS_FUNC, XCSF::MAX_TRIALS, XCSF::OMP_NUM_THREADS, XCSF::PERF_TRIALS, XCSF::POP_INIT, and XCSF::POP_SIZE.
Referenced by config_print().
print_params_multistep()
static void print_params_multistep (const XCSF * xcsf) static
Prints XCSF multistep parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 742 of file config.c.
References XCSF::GAMMA, XCSF::P_EXPLORE, and XCSF::TELETRANSPORTATION.
Referenced by config_print().
print_params_subsumption()
static void print_params_subsumption (const XCSF * xcsf) static
Prints XCSF subsumption parameters.
Parameters
xcsf The XCSF data structure.
Definition at line 772 of file config.c.
References XCSF::EA_SUBSUMPTION, XCSF::SET_SUBSUMPTION, and XCSF::THETA_SUB.
Referenced by config_print().