XCSF: config.h File Reference
config.h File Reference
Config file handling functions.
Functions
void constants_init (XCSF *xcsf, const char *filename)
Initialises global constants and reads the specified configuration file.
void constants_free (XCSF *xcsf)
Frees all global constants.
Detailed Description
Config file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file config.h.
Function Documentation
constants_free()
void constants_free (XCSF * xcsf)
Frees all global constants.
Parameters
xcsf The XCSF data structure.
Definition at line 182 of file config.c.
References tree_free_cons().
Referenced by main().
constants_init()
void constants_init (XCSF * xcsf, const char * filename)
Initialises global constants and reads the specified configuration file.
Parameters
xcsf The XCSF data structure.
filename The name of the config file to read.
Definition at line 59 of file config.c.
References XCSF::ACT_TYPE, XCSF::ALPHA, XCSF::BETA, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX_HIDDEN_NEURONS, XCSF::COND_NUM_HIDDEN_NEURONS, XCSF::COND_TYPE, XCSF::DELTA, XCSF::DGP_NUM_NODES, XCSF::E_MUTATION, XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::EA_SUBSUMPTION, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::F_MUTATION, XCSF::FIT_REDUC, XCSF::GAMMA, getvalue(), XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, init_config(), XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LAMBDA, XCSF::LOSS_FUNC, loss_set_func(), XCSF::MAX_CON, XCSF::MAX_K, XCSF::MAX_T, XCSF::MAX_TRIALS, XCSF::MIN_CON, XCSF::NU, XCSF::OMP_NUM_THREADS, XCSF::P_CROSSOVER, XCSF::P_EXPLORE, XCSF::P_MUTATION, XCSF::PERF_AVG_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_NEURON_ACTIVATION, XCSF::PRED_MAX_HIDDEN_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_HIDDEN_NEURONS, XCSF::PRED_RESET, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, XCSF::PRED_X0, XCSF::RESET_STATES, XCSF::S_MUTATION, XCSF::SAM_MIN, XCSF::SAM_NUM, XCSF::SAM_TYPE, XCSF::SET_SUBSUMPTION, XCSF::TELETRANSPORTATION, XCSF::THETA_DEL, XCSF::THETA_EA, XCSF::THETA_SUB, tidyup(), and tree_init_cons().
Referenced by main(), and XCS::XCS().