XCSF: cuda.h File Reference
cuda.h File Reference
General CUDA functions.
#include <cuda_runtime.h>
Macros
#define BLOCK_SIZE 1024
#define CUDA_CALL(x) { cudaError_t cuda_error__ = (x); if(cuda_error__) { printf("CUDA error: " #x " returned \"%s\"\n", cudaGetErrorString(cuda_error__)); } }
Functions
double * cuda_make_array (double *x, size_t n, const cudaStream_t *stream)
int cuda_get_device ()
void cuda_free (double *x_gpu)
void cuda_info ()
void cuda_destroy_stream (cudaStream_t *stream)
void cuda_create_stream (cudaStream_t *stream)
void cuda_memset (double *x_gpu, int value, size_t n, const cudaStream_t *stream)
void cuda_pull_array (double *x_gpu, double *x, size_t n, const cudaStream_t *stream)
void cuda_push_array (double *x_gpu, double *x, size_t n, const cudaStream_t *stream)
void cuda_set_device (int n)
Detailed Description
General CUDA functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file cuda.h.
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE 1024
Definition at line 28 of file cuda.h.
CUDA_CALL
#define CUDA_CALL (x) { cudaError_t cuda_error__ = (x); if(cuda_error__) { printf("CUDA error: " #x " returned \"%s\"\n", cudaGetErrorString(cuda_error__)); } }
Definition at line 30 of file cuda.h.
Function Documentation
cuda_create_stream()
void cuda_create_stream (cudaStream_t * stream)
Referenced by pred_rls_init().
cuda_destroy_stream()
void cuda_destroy_stream (cudaStream_t * stream)
Referenced by pred_rls_free().
cuda_free()
void cuda_free (double * x_gpu)
Referenced by pred_rls_free().
cuda_get_device()
int cuda_get_device ()
cuda_info()
void cuda_info ()
cuda_make_array()
double* cuda_make_array (double * x, size_t n, const cudaStream_t * stream)
Referenced by pred_rls_init().
cuda_memset()
void cuda_memset (double * x_gpu, int value, size_t n, const cudaStream_t * stream)
cuda_pull_array()
void cuda_pull_array (double * x_gpu, double * x, size_t n, const cudaStream_t * stream)
Referenced by pred_rls_update().
cuda_push_array()
void cuda_push_array (double * x_gpu, double * x, size_t n, const cudaStream_t * stream)
Referenced by pred_rls_update().
cuda_set_device()
void cuda_set_device (int n)