XCSF: dgp.c File Reference
dgp.c File Reference
An implementation of dynamical GP graphs with fuzzy activation functions.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "xcsf.h"
#include "utils.h"
#include "sam.h"
#include "dgp.h"
Macros
#define NUM_FUNC 3
Number of selectable node functions.
Functions
static const char * function_string (int function)
Returns the name of a specified node function.
static double node_activate (int function, const double *inputs, int k)
Returns the result from applying a specified activation function.
static void synchronous_update (const XCSF *xcsf, const GRAPH *dgp, const double *inputs)
Performs a synchronous update.
static int random_connection (int n_nodes, int n_inputs)
Returns a random connection.
void graph_init (const XCSF *xcsf, GRAPH *dgp, int n)
Initialises a new DGP graph.
void graph_copy (const XCSF *xcsf, GRAPH *dest, const GRAPH *src)
Copies a DGP graph.
double graph_output (const XCSF *xcsf, const GRAPH *dgp, int i)
Returns the current state of a specified node in the graph.
void graph_reset (const XCSF *xcsf, const GRAPH *dgp)
Resets the states to their initial state.
void graph_rand (const XCSF *xcsf, GRAPH *dgp)
Randomises a specified DGP graph.
void graph_update (const XCSF *xcsf, const GRAPH *dgp, const double *inputs)
Updates a DGP graph T cycles.
void graph_print (const XCSF *xcsf, const GRAPH *dgp)
Prints a DGP graph.
void graph_free (const XCSF *xcsf, const GRAPH *dgp)
Frees a DGP graph.
_Bool graph_mutate (const XCSF *xcsf, GRAPH *dgp)
Mutates a specified DGP graph.
_Bool graph_crossover (const XCSF *xcsf, GRAPH *dgp1, GRAPH *dgp2)
Performs uniform crossover with two DGP graphs.
size_t graph_save (const XCSF *xcsf, const GRAPH *dgp, FILE *fp)
Writes DGP graph to a binary file.
size_t graph_load (const XCSF *xcsf, GRAPH *dgp, FILE *fp)
Reads DGP graph from a binary file.
Detailed Description
An implementation of dynamical GP graphs with fuzzy activation functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file dgp.c.
Macro Definition Documentation
NUM_FUNC
#define NUM_FUNC 3
Number of selectable node functions.
Definition at line 33 of file dgp.c.
Referenced by graph_mutate(), and graph_rand().
Function Documentation
function_string()
static const char * function_string (int function) static
Returns the name of a specified node function.
Parameters
function The node function.
Returns
The name of the node function.
Definition at line 307 of file dgp.c.
Referenced by graph_print().
graph_copy()
void graph_copy (const XCSF * xcsf, GRAPH * dest, const GRAPH * src)
Copies a DGP graph.
Parameters
xcsf The XCSF data structure.
dest The destination DGP graph.
src The source DGP graph.
Definition at line 66 of file dgp.c.
References GRAPH::connectivity, DGP_N_MU, GRAPH::function, GRAPH::initial_state, GRAPH::klen, GRAPH::mu, GRAPH::n, GRAPH::state, and GRAPH::t.
Referenced by cond_dgp_copy(), and rule_dgp_cond_copy().
graph_crossover()
_Bool graph_crossover (const XCSF * xcsf, GRAPH * dgp1, GRAPH * dgp2)
Performs uniform crossover with two DGP graphs.
Parameters
xcsf The XCSF data structure.
dgp1 The first DGP graph to perform crossover.
dgp2 The second DGP graph to perform crossover.
Returns
Whether crossover was performed.
Definition at line 261 of file dgp.c.
Referenced by cond_dgp_crossover(), and rule_dgp_cond_crossover().
graph_free()
void graph_free (const XCSF * xcsf, const GRAPH * dgp)
Frees a DGP graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to be freed.
Definition at line 202 of file dgp.c.
References GRAPH::connectivity, GRAPH::function, GRAPH::initial_state, GRAPH::state, GRAPH::tmp_input, and GRAPH::tmp_state.
Referenced by cond_dgp_free(), and rule_dgp_cond_free().
graph_init()
void graph_init (const XCSF * xcsf, GRAPH * dgp, int n)
Initialises a new DGP graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to initialise.
n The the number of nodes in the graph.
Definition at line 46 of file dgp.c.
References GRAPH::connectivity, DGP_N_MU, GRAPH::function, GRAPH::initial_state, GRAPH::klen, XCSF::MAX_K, GRAPH::mu, GRAPH::n, sam_init(), GRAPH::state, GRAPH::t, GRAPH::tmp_input, and GRAPH::tmp_state.
Referenced by cond_dgp_copy(), cond_dgp_init(), rule_dgp_cond_copy(), and rule_dgp_cond_init().
graph_load()
size_t graph_load (const XCSF * xcsf, GRAPH * dgp, FILE * fp)
Reads DGP graph from a binary file.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to load.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 348 of file dgp.c.
References GRAPH::connectivity, DGP_N_MU, GRAPH::function, GRAPH::initial_state, GRAPH::klen, XCSF::MAX_K, GRAPH::mu, GRAPH::n, GRAPH::state, GRAPH::t, GRAPH::tmp_input, and GRAPH::tmp_state.
Referenced by cond_dgp_load(), and rule_dgp_cond_load().
graph_mutate()
_Bool graph_mutate (const XCSF * xcsf, GRAPH * dgp)
Mutates a specified DGP graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to be mutated.
Returns
Whether any alterations were made.
Definition at line 219 of file dgp.c.
References GRAPH::connectivity, DGP_N_MU, GRAPH::function, irand_uniform(), GRAPH::klen, XCSF::MAX_T, GRAPH::mu, GRAPH::n, NUM_FUNC, rand_uniform(), random_connection(), sam_adapt(), GRAPH::t, and XCSF::x_dim.
Referenced by cond_dgp_mutate(), and rule_dgp_cond_mutate().
graph_output()
double graph_output (const XCSF * xcsf, const GRAPH * dgp, int i)
Returns the current state of a specified node in the graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to output.
i Which node within the graph to output.
Returns
The current state of the specified node.
Definition at line 86 of file dgp.c.
References GRAPH::state.
Referenced by cond_dgp_match(), rule_dgp_act_compute(), and rule_dgp_cond_match().
graph_print()
void graph_print (const XCSF * xcsf, const GRAPH * dgp)
Prints a DGP graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to print.
Definition at line 182 of file dgp.c.
References GRAPH::connectivity, GRAPH::function, function_string(), GRAPH::initial_state, XCSF::MAX_K, GRAPH::n, GRAPH::state, and GRAPH::t.
Referenced by cond_dgp_print(), and rule_dgp_cond_print().
graph_rand()
void graph_rand (const XCSF * xcsf, GRAPH * dgp)
Randomises a specified DGP graph.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to randomise.
Definition at line 110 of file dgp.c.
References GRAPH::connectivity, GRAPH::function, GRAPH::initial_state, irand_uniform(), GRAPH::klen, XCSF::MAX_T, GRAPH::n, NUM_FUNC, rand_uniform(), random_connection(), GRAPH::state, GRAPH::t, and XCSF::x_dim.
Referenced by cond_dgp_cover(), cond_dgp_init(), rule_dgp_act_cover(), and rule_dgp_cond_init().
graph_reset()
void graph_reset (const XCSF * xcsf, const GRAPH * dgp)
Resets the states to their initial state.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to reset.
Definition at line 97 of file dgp.c.
References GRAPH::initial_state, GRAPH::n, and GRAPH::state.
Referenced by graph_update().
graph_save()
size_t graph_save (const XCSF * xcsf, const GRAPH * dgp, FILE * fp)
Writes DGP graph to a binary file.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to save.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 326 of file dgp.c.
References GRAPH::connectivity, DGP_N_MU, GRAPH::function, GRAPH::initial_state, GRAPH::klen, GRAPH::mu, GRAPH::n, GRAPH::state, and GRAPH::t.
Referenced by cond_dgp_save(), and rule_dgp_cond_save().
graph_update()
void graph_update (const XCSF * xcsf, const GRAPH * dgp, const double * inputs)
Updates a DGP graph T cycles.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to update.
inputs The inputs to the graph.
Definition at line 144 of file dgp.c.
References graph_reset(), XCSF::RESET_STATES, synchronous_update(), and GRAPH::t.
Referenced by cond_dgp_match(), and rule_dgp_cond_match().
node_activate()
static double node_activate (int function, const double * inputs, int k) static
Returns the result from applying a specified activation function.
Parameters
function The activation function to apply.
inputs The input to the activation function.
k The number of inputs to the activation function.
Returns
The result from applying the activation function.
Definition at line 274 of file dgp.c.
References clamp().
Referenced by synchronous_update().
random_connection()
static int random_connection (int n_nodes, int n_inputs) static
Returns a random connection.
Parameters
n_nodes The number of nodes in the graph.
n_inputs The number of external inputs to the graph.
Definition at line 128 of file dgp.c.
References irand_uniform(), and rand_uniform().
Referenced by graph_mutate(), and graph_rand().
synchronous_update()
static void synchronous_update (const XCSF * xcsf, const GRAPH * dgp, const double * inputs) static
Performs a synchronous update.
Parameters
xcsf The XCSF data structure.
dgp The DGP graph to update.
inputs The inputs to the graph.
Definition at line 160 of file dgp.c.
References GRAPH::connectivity, GRAPH::function, XCSF::MAX_K, GRAPH::n, node_activate(), GRAPH::state, GRAPH::tmp_input, GRAPH::tmp_state, and XCSF::x_dim.
Referenced by graph_update().