XCSF: ea.c File Reference
ea.c File Reference
Evolutionary algorithm functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "clset.h"
#include "ea.h"
#include "sam.h"
Macros
#define EA_SELECT_ROULETTE 0
#define EA_SELECT_TOURNAMENT 1
Functions
static CL * ea_select_rw (const XCSF *xcsf, const SET *set, double fit_sum)
Selects a classifier from the set via roulete wheel.
static CL * ea_select_tournament (const XCSF *xcsf, const SET *set)
Selects a classifier from the set via tournament.
static void ea_subsume (XCSF *xcsf, CL *c, CL *c1p, CL *c2p, const SET *set)
Performs evolutionary algorithm subsumption.
static void ea_select_parents (const XCSF *xcsf, const SET *set, CL **c1p, CL **c2p)
Selects two parents.
static void ea_init_offspring (const XCSF *xcsf, const CL *c1p, const CL *c2p, CL *c1, CL *c2, _Bool cmod)
Initialises offspring error and fitness.
static void ea_add (XCSF *xcsf, const SET *set, CL *c1p, CL *c2p, CL *c1, _Bool cmod, _Bool mmod)
Adds offspring to the population.
void ea (XCSF *xcsf, const SET *set)
Executes the evolutionary algorithm (EA).
Detailed Description
Evolutionary algorithm functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file ea.c.
Macro Definition Documentation
EA_SELECT_ROULETTE
#define EA_SELECT_ROULETTE 0
Definition at line 35 of file ea.c.
Referenced by ea_select_parents().
EA_SELECT_TOURNAMENT
#define EA_SELECT_TOURNAMENT 1
Definition at line 36 of file ea.c.
Function Documentation
ea()
void ea (XCSF * xcsf, const SET * set)
Executes the evolutionary algorithm (EA).
Parameters
xcsf The XCSF data structure.
set The set in which to run the EA.
Definition at line 50 of file ea.c.
References cl_copy(), cl_crossover(), cl_init(), cl_mutate(), clset_mean_time(), clset_pop_enforce_limit(), clset_set_times(), ea_add(), ea_init_offspring(), ea_select_parents(), XCSF::LAMBDA, CL::size, XCSF::THETA_EA, CL::time, and XCSF::time.
Referenced by xcs_multi_trial(), xcs_single_update(), and xcs_supervised_trial().
ea_add()
static void ea_add (XCSF * xcsf, const SET * set, CL * c1p, CL * c2p, CL * c1, _Bool cmod, _Bool mmod) static
Adds offspring to the population.
Parameters
xcsf The XCSF data structure.
set The set in which the EA is being run.
c1p First parent classifier.
c2p Second parent classifier.
c1 The offspring classifier to add.
cmod Whether crossover modified the offspring.
mmod Whether mutation modified the offspring.
Definition at line 121 of file ea.c.
References cl_free(), clset_add(), ea_subsume(), XCSF::EA_SUBSUMPTION, CL::num, SET::num, and XCSF::pset.
Referenced by ea().
ea_init_offspring()
static void ea_init_offspring (const XCSF * xcsf, const CL * c1p, const CL * c2p, CL * c1, CL * c2, _Bool cmod) static
Initialises offspring error and fitness.
Parameters
xcsf The XCSF data structure.
c1p First parent classifier.
c2p Second parent classifier.
c1 The first offspring classifier to initialise.
c2 The second offspring classifier to initialise.
cmod Whether crossover modified the offspring.
Definition at line 93 of file ea.c.
References CL::err, XCSF::ERR_REDUC, CL::fit, XCSF::FIT_REDUC, and CL::num.
Referenced by ea().
ea_select_parents()
static void ea_select_parents (const XCSF * xcsf, const SET * set, CL ** c1p, CL ** c2p) static
Selects two parents.
Parameters
xcsf The XCSF data structure.
set The set in which the EA is being run.
c1p First parent classifier (set by this function).
c2p Second parent classifier (set by this function).
Definition at line 187 of file ea.c.
References clset_total_fit(), EA_SELECT_ROULETTE, ea_select_rw(), ea_select_tournament(), and XCSF::EA_SELECT_TYPE.
Referenced by ea().
ea_select_rw()
static CL * ea_select_rw (const XCSF * xcsf, const SET * set, double fit_sum) static
Selects a classifier from the set via roulete wheel.
Parameters
xcsf The XCSF data structure.
set The set to select from.
fit_sum The sum of all the fitnesses in the set.
Returns
A pointer to the selected classifier.
Definition at line 207 of file ea.c.
References CLIST::cl, CL::fit, CLIST::next, and rand_uniform().
Referenced by ea_select_parents().
ea_select_tournament()
static CL * ea_select_tournament (const XCSF * xcsf, const SET * set) static
Selects a classifier from the set via tournament.
Parameters
xcsf The XCSF data structure.
set The set to select from.
Returns
A pointer to the selected classifier.
Definition at line 226 of file ea.c.
References XCSF::EA_SELECT_SIZE, CL::fit, CLIST::next, and rand_uniform().
Referenced by ea_select_parents().
ea_subsume()
static void ea_subsume (XCSF * xcsf, CL * c, CL * c1p, CL * c2p, const SET * set) static
Performs evolutionary algorithm subsumption.
Parameters
xcsf The XCSF data structure.
c The offspring classifier to attempt to subsume.
c1p First parent classifier.
c2p Second parent classifier.
set The set in which the EA is being run.
Definition at line 144 of file ea.c.
References CLIST::cl, cl_free(), cl_general(), cl_subsumer(), clset_add(), irand_uniform(), CLIST::next, CL::num, SET::num, and XCSF::pset.
Referenced by ea_add().