XCSF: /home/unknown/work/current/xcsf/xcsf/ea.h File Reference
ea.h File Reference
Evolutionary algorithm functions.
Functions
void ea (XCSF *xcsf, SET *set, SET *kset)
Executes the evolutionary algorithm (EA).
Detailed Description
Evolutionary algorithm functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file ea.h.
Function Documentation
ea()
void ea (XCSF * xcsf, SET * set, SET * kset)
Executes the evolutionary algorithm (EA).
Parameters
xcsf The XCSF data structure.
set The set in which to run the EA.
kset A set to store deleted macro-classifiers for later memory removal.
Definition at line 48 of file ea.c.
References cl_copy(), cl_crossover(), cl_free(), cl_init(), cl_mutate(), EA_SELECT_ROULETTE, ea_select_rw(), ea_select_tournament(), XCSF::EA_SELECT_TYPE, ea_subsume(), XCSF::EA_SUBSUMPTION, CL::err, XCSF::ERR_REDUC, CL::fit, XCSF::FIT_REDUC, XCSF::LAMBDA, CL::mu, CL::num, SET::num, pop_enforce_limit(), XCSF::pset, sam_adapt(), set_add(), set_mean_time(), set_times(), set_total_fit(), CL::size, XCSF::THETA_EA, CL::time, and XCSF::time.
Referenced by xcsf_learn_trial().