XCSF: env_csv.h File Reference
env_csv.h File Reference
CSV input file handling functions.
Functions
void env_csv_input_read (char *infile, INPUT *train_data, INPUT *test_data)
Parses specified csv files into training and testing data sets.
void env_csv_input_free (INPUT *data)
Frees an input data structure.
Detailed Description
CSV input file handling functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file env_csv.h.
Function Documentation
env_csv_input_free()
void env_csv_input_free (INPUT * data)
Frees an input data structure.
Parameters
data The input data structure to free.
Definition at line 116 of file env_csv.c.
References INPUT::x, and INPUT::y.
Referenced by regression().
env_csv_input_read()
void env_csv_input_read (char * infile, INPUT * train_data, INPUT * test_data)
Parses specified csv files into training and testing data sets.
Parameters
infile The base name of the csv files to read.
train_data The data structure to load the training data.
test_data The data structure to load the testing data.
Expects an identical number of x and y rows.
Definition at line 49 of file env_csv.c.
References env_csv_read(), MAX_NAME, INPUT::rows, INPUT::x, INPUT::x_cols, INPUT::y, and INPUT::y_cols.
Referenced by regression().