XCSF: env_maze.h File Reference
env_maze.h File Reference
The discrete maze problem environment module.
Functions
_Bool env_maze_isreset (const XCSF *xcsf)
Returns whether the maze needs to be reset.
_Bool env_maze_multistep (const XCSF *xcsf)
Returns whether the environment is a multistep problem.
double env_maze_execute (const XCSF *xcsf, int action)
Executes the specified action and returns the payoff.
double env_maze_maxpayoff (const XCSF *xcsf)
Returns the maximum payoff value possible in the maze.
const double * env_maze_get_state (const XCSF *xcsf)
Returns the current animat perceptions in the maze.
void env_maze_free (const XCSF *xcsf)
Frees the maze environment.
void env_maze_init (XCSF *xcsf, const char *filename)
Initialises a maze environment from a specified file.
void env_maze_reset (const XCSF *xcsf)
Resets the animat to a random empty position in the maze.
Variables
static struct EnvVtbl const env_maze_vtbl
Maze environment implemented functions.
Detailed Description
The discrete maze problem environment module.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file env_maze.h.
Function Documentation
env_maze_execute()
double env_maze_execute (const XCSF * xcsf, int action)
Executes the specified action and returns the payoff.
Parameters
xcsf The XCSF data structure.
action The action to perform.
Returns
The payoff from performing the action.
Definition at line 226 of file env_maze.c.
References XCSF::env, env_maze_print(), MAX_PAYOFF, ENV_MAZE::maze, MAZE_DEBUG, ENV_MAZE::reset, XCSF::train, x_moves, ENV_MAZE::xpos, ENV_MAZE::xsize, y_moves, ENV_MAZE::ypos, and ENV_MAZE::ysize.
env_maze_free()
void env_maze_free (const XCSF * xcsf)
Frees the maze environment.
Parameters
xcsf The XCSF data structure.
Definition at line 133 of file env_maze.c.
References XCSF::env, and ENV_MAZE::state.
env_maze_get_state()
const double* env_maze_get_state (const XCSF * xcsf)
Returns the current animat perceptions in the maze.
Parameters
xcsf The XCSF data structure.
Returns
The current animat perceptions.
Definition at line 175 of file env_maze.c.
References XCSF::env, env_maze_sensor(), ENV_MAZE::maze, ENV_MAZE::state, ENV_MAZE::xpos, ENV_MAZE::xsize, ENV_MAZE::ypos, and ENV_MAZE::ysize.
env_maze_init()
void env_maze_init (XCSF * xcsf, const char * fname)
Initialises a maze environment from a specified file.
Parameters
xcsf The XCSF data structure.
fname The file name of the specified maze environment.
Definition at line 86 of file env_maze.c.
References XCSF::env, MAX_SIZE, ENV_MAZE::maze, XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, ENV_MAZE::state, ENV_MAZE::xsize, and ENV_MAZE::ysize.
Referenced by env_init().
env_maze_isreset()
_Bool env_maze_isreset (const XCSF * xcsf)
Returns whether the maze needs to be reset.
Parameters
xcsf The XCSF data structure.
Returns
Whether the maze needs to be reset.
Definition at line 164 of file env_maze.c.
References XCSF::env, and ENV_MAZE::reset.
env_maze_maxpayoff()
double env_maze_maxpayoff (const XCSF * xcsf)
Returns the maximum payoff value possible in the maze.
Parameters
xcsf The XCSF data structure.
Returns
The maximum payoff.
Definition at line 268 of file env_maze.c.
References MAX_PAYOFF.
env_maze_multistep()
_Bool env_maze_multistep (const XCSF * xcsf)
Returns whether the environment is a multistep problem.
Parameters
xcsf The XCSF data structure.
Returns
True
Definition at line 279 of file env_maze.c.
env_maze_reset()
void env_maze_reset (const XCSF * xcsf)
Resets the animat to a random empty position in the maze.
Parameters
xcsf The XCSF data structure.
Definition at line 144 of file env_maze.c.
References XCSF::env, env_maze_print(), irand_uniform(), ENV_MAZE::maze, MAZE_DEBUG, ENV_MAZE::reset, XCSF::train, ENV_MAZE::xpos, ENV_MAZE::xsize, ENV_MAZE::ypos, and ENV_MAZE::ysize.
Variable Documentation
env_maze_vtbl
struct EnvVtbl const env_maze_vtbl static
Initial value:
= {
    &env_maze_isreset,
    &env_maze_multistep,
    &env_maze_execute,
    &env_maze_maxpayoff,
    &env_maze_get_state,
    &env_maze_free,
    &env_maze_reset
}
Maze environment implemented functions.
Definition at line 38 of file env_maze.h.
Referenced by env_init().