XCSF: env_maze.c File Reference
env_maze.c File Reference
The discrete maze problem environment module.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <errno.h>
#include "xcsf.h"
#include "utils.h"
#include "env.h"
#include "env_maze.h"
Data Structures
struct ENV_MAZE
Maze environment data structure.
Macros
#define MAZE_DEBUG false
Whether to print the state of the maze during exploitation.
#define MAX_SIZE 50
The maximum width/height of a maze.
#define MAX_PAYOFF 1.0
The payoff provided at a food position.
Typedefs
typedef struct ENV_MAZE ENV_MAZE
Maze environment data structure.
Functions
static void env_maze_print (const XCSF *xcsf)
Prints the current state of the maze environment.
static double env_maze_sensor (const XCSF *xcsf, char s)
Returns a float encoding of a sensor perception.
void env_maze_init (XCSF *xcsf, const char *fname)
Initialises a maze environment from a specified file.
void env_maze_free (const XCSF *xcsf)
Frees the maze environment.
void env_maze_reset (const XCSF *xcsf)
Resets the animat to a random empty position in the maze.
_Bool env_maze_isreset (const XCSF *xcsf)
Returns whether the maze needs to be reset.
const double * env_maze_get_state (const XCSF *xcsf)
Returns the current animat perceptions in the maze.
double env_maze_execute (const XCSF *xcsf, int action)
Executes the specified action and returns the payoff.
double env_maze_maxpayoff (const XCSF *xcsf)
Returns the maximum payoff value possible in the maze.
_Bool env_maze_multistep (const XCSF *xcsf)
Returns whether the environment is a multistep problem.
Variables
static const int x_moves [] ={ 0, +1, +1, +1, 0, -1, -1, -1}
Possible maze moves on x-axis.
static const int y_moves [] ={-1, -1, 0, +1, +1, +1, 0, -1}
Possible maze moves on y-axis.
Detailed Description
The discrete maze problem environment module.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Reads in the chosen maze from a file where each entry specifies a distinct position in the maze. The maze is toroidal and if the animat reaches one edge it can reenter the maze from the other side. Obstacles are coded as 'O' and 'Q', empty positions as '*', and food as 'F' or 'G'. The 8 adjacent cells are perceived (encoded as reals) and 8 movements are possible to the adjacent cells (if not blocked.) The animat is initially placed at a random empty position. The goal is to find the shortest path to the food.
Some mazes require a form of memory to be solved optimally. The optimal average number of steps for each maze is:
Woods 1: 1.7
Woods 2: 1.7
Woods 14: 9.5
Maze 4: 3.5
Maze 5: 4.61
Maze 6: 5.19
Maze 7: 4.33
Maze 10: 5.11
Woods 101: 2.9
Woods 101 1/2: 3.1
Woods 102: 3.31
Definition in file env_maze.c.
Macro Definition Documentation
MAX_PAYOFF
#define MAX_PAYOFF 1.0
The payoff provided at a food position.
Definition at line 60 of file env_maze.c.
Referenced by env_maze_execute(), and env_maze_maxpayoff().
MAX_SIZE
#define MAX_SIZE 50
The maximum width/height of a maze.
Definition at line 59 of file env_maze.c.
Referenced by env_maze_init().
MAZE_DEBUG
#define MAZE_DEBUG false
Whether to print the state of the maze during exploitation.
Definition at line 58 of file env_maze.c.
Referenced by env_maze_execute(), and env_maze_reset().
Typedef Documentation
ENV_MAZE
typedef struct ENV_MAZE ENV_MAZE
Maze environment data structure.
Function Documentation
env_maze_execute()
double env_maze_execute (const XCSF * xcsf, int action)
Executes the specified action and returns the payoff.
Parameters
xcsf The XCSF data structure.
action The action to perform.
Returns
The payoff from performing the action.
Definition at line 226 of file env_maze.c.
References XCSF::env, env_maze_print(), MAX_PAYOFF, ENV_MAZE::maze, MAZE_DEBUG, ENV_MAZE::reset, XCSF::train, x_moves, ENV_MAZE::xpos, ENV_MAZE::xsize, y_moves, ENV_MAZE::ypos, and ENV_MAZE::ysize.
env_maze_free()
void env_maze_free (const XCSF * xcsf)
Frees the maze environment.
Parameters
xcsf The XCSF data structure.
Definition at line 133 of file env_maze.c.
References XCSF::env, and ENV_MAZE::state.
env_maze_get_state()
const double* env_maze_get_state (const XCSF * xcsf)
Returns the current animat perceptions in the maze.
Parameters
xcsf The XCSF data structure.
Returns
The current animat perceptions.
Definition at line 175 of file env_maze.c.
References XCSF::env, env_maze_sensor(), ENV_MAZE::maze, ENV_MAZE::state, ENV_MAZE::xpos, ENV_MAZE::xsize, ENV_MAZE::ypos, and ENV_MAZE::ysize.
env_maze_init()
void env_maze_init (XCSF * xcsf, const char * fname)
Initialises a maze environment from a specified file.
Parameters
xcsf The XCSF data structure.
fname The file name of the specified maze environment.
Definition at line 86 of file env_maze.c.
References XCSF::env, MAX_SIZE, ENV_MAZE::maze, XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, ENV_MAZE::state, ENV_MAZE::xsize, and ENV_MAZE::ysize.
Referenced by env_init().
env_maze_isreset()
_Bool env_maze_isreset (const XCSF * xcsf)
Returns whether the maze needs to be reset.
Parameters
xcsf The XCSF data structure.
Returns
Whether the maze needs to be reset.
Definition at line 164 of file env_maze.c.
References XCSF::env, and ENV_MAZE::reset.
env_maze_maxpayoff()
double env_maze_maxpayoff (const XCSF * xcsf)
Returns the maximum payoff value possible in the maze.
Parameters
xcsf The XCSF data structure.
Returns
The maximum payoff.
Definition at line 268 of file env_maze.c.
References MAX_PAYOFF.
env_maze_multistep()
_Bool env_maze_multistep (const XCSF * xcsf)
Returns whether the environment is a multistep problem.
Parameters
xcsf The XCSF data structure.
Returns
True
Definition at line 279 of file env_maze.c.
env_maze_print()
static void env_maze_print (const XCSF * xcsf) static
Prints the current state of the maze environment.
Parameters
xcsf The XCSF data structure.
Definition at line 289 of file env_maze.c.
References XCSF::env, ENV_MAZE::maze, ENV_MAZE::xpos, ENV_MAZE::xsize, ENV_MAZE::ypos, and ENV_MAZE::ysize.
Referenced by env_maze_execute(), and env_maze_reset().
env_maze_reset()
void env_maze_reset (const XCSF * xcsf)
Resets the animat to a random empty position in the maze.
Parameters
xcsf The XCSF data structure.
Definition at line 144 of file env_maze.c.
References XCSF::env, env_maze_print(), irand_uniform(), ENV_MAZE::maze, MAZE_DEBUG, ENV_MAZE::reset, XCSF::train, ENV_MAZE::xpos, ENV_MAZE::xsize, ENV_MAZE::ypos, and ENV_MAZE::ysize.
env_maze_sensor()
static double env_maze_sensor (const XCSF * xcsf, char s) static
Returns a float encoding of a sensor perception.
Parameters
xcsf The XCSF data structure.
s The char value of the sensor.
Returns
A float encoding of the sensor.
Definition at line 203 of file env_maze.c.
Referenced by env_maze_get_state().
Variable Documentation
x_moves
const int x_moves[] ={ 0, +1, +1, +1, 0, -1, -1, -1} static
Possible maze moves on x-axis.
Definition at line 61 of file env_maze.c.
Referenced by env_maze_execute().
y_moves
const int y_moves[] ={-1, -1, 0, +1, +1, +1, 0, -1} static
Possible maze moves on y-axis.
Definition at line 62 of file env_maze.c.
Referenced by env_maze_execute().