XCSF: gp.h File Reference
gp.h File Reference
An implementation of GP trees based upon TinyGP.
Data Structures
struct GP_TREE
GP tree data structure.
Typedefs
typedef struct GP_TREE GP_TREE
GP tree data structure.
Functions
void tree_free_cons (const XCSF *xcsf)
Frees the constants shared among all GP trees.
void tree_init_cons (XCSF *xcsf)
Initialises the constants shared among all GP trees.
void tree_free (const XCSF *xcsf, const GP_TREE *gp)
Frees a GP tree.
void tree_rand (const XCSF *xcsf, GP_TREE *gp)
Creates a random GP tree.
void tree_copy (const XCSF *xcsf, GP_TREE *to, const GP_TREE *from)
Copies a GP tree.
int tree_print (const XCSF *xcsf, const GP_TREE *gp, int p)
Prints a GP tree.
double tree_eval (const XCSF *xcsf, GP_TREE *gp, const double *x)
Evaluates a GP tree.
void tree_crossover (const XCSF *xcsf, GP_TREE *p1, GP_TREE *p2)
Performs sub-tree crossover.
void tree_mutate (const XCSF *xcsf, const GP_TREE *gp, double rate)
Performs point mutation on a GP tree.
size_t tree_save (const XCSF *xcsf, const GP_TREE *gp, FILE *fp)
Writes the GP tree to a binary file.
size_t tree_load (const XCSF *xcsf, GP_TREE *gp, FILE *fp)
Reads a GP tree from a binary file.
Detailed Description
An implementation of GP trees based upon TinyGP.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file gp.h.
Typedef Documentation
GP_TREE
typedef struct GP_TREE GP_TREE
GP tree data structure.
Function Documentation
tree_copy()
void tree_copy (const XCSF * xcsf, GP_TREE * to, const GP_TREE * from)
Copies a GP tree.
Parameters
xcsf The XCSF data structure.
to The destination GP tree.
from The source GP tree.
Definition at line 232 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_copy().
tree_crossover()
void tree_crossover (const XCSF * xcsf, GP_TREE * p1, GP_TREE * p2)
Performs sub-tree crossover.
Parameters
xcsf The XCSF data structure.
p1 The first GP tree to perform crossover.
p2 The second GP tree to perform crossover.
Definition at line 247 of file gp.c.
References irand_uniform(), GP_TREE::len, GP_TREE::tree, tree_free(), and tree_traverse().
Referenced by cond_gp_crossover().
tree_eval()
double tree_eval (const XCSF * xcsf, GP_TREE * gp, const double * x)
Evaluates a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to evaluate.
x The input state.
Returns
The result from evaluating the GP tree.
Definition at line 152 of file gp.c.
References ADD, DIV, XCSF::gp_cons, XCSF::GP_NUM_CONS, GP_NUM_FUNC, MUL, GP_TREE::p, SUB, GP_TREE::tree, and tree_eval().
Referenced by cond_gp_match(), and tree_eval().
tree_free()
void tree_free (const XCSF * xcsf, const GP_TREE * gp)
Frees a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to free.
Definition at line 90 of file gp.c.
References GP_TREE::tree.
Referenced by cond_gp_free(), cond_gp_rand(), and tree_crossover().
tree_free_cons()
void tree_free_cons (const XCSF * xcsf)
Frees the constants shared among all GP trees.
Parameters
xcsf The XCSF data structure.
Definition at line 64 of file gp.c.
References XCSF::gp_cons.
Referenced by config_free().
tree_init_cons()
void tree_init_cons (XCSF * xcsf)
Initialises the constants shared among all GP trees.
Parameters
xcsf The XCSF data structure.
Definition at line 52 of file gp.c.
References XCSF::COND_MAX, XCSF::COND_MIN, XCSF::gp_cons, XCSF::GP_NUM_CONS, and rand_uniform().
Referenced by config_init().
tree_load()
size_t tree_load (const XCSF * xcsf, GP_TREE * gp, FILE * fp)
Reads a GP tree from a binary file.
Parameters
xcsf The XCSF data structure.
gp The GP tree to load.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 345 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_load().
tree_mutate()
void tree_mutate (const XCSF * xcsf, const GP_TREE * gp, double rate)
Performs point mutation on a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to be mutated.
rate The per allele rate of mutation.
Definition at line 279 of file gp.c.
References XCSF::GP_NUM_CONS, GP_NUM_FUNC, irand_uniform(), GP_TREE::len, XCSF::num_x_vars, rand_uniform(), and GP_TREE::tree.
Referenced by cond_gp_mutate().
tree_print()
int tree_print (const XCSF * xcsf, const GP_TREE * gp, int p)
Prints a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to print.
p The position from which to traverse (start at 0).
Returns
The position after traversal.
Definition at line 193 of file gp.c.
References ADD, DIV, XCSF::gp_cons, XCSF::GP_NUM_CONS, GP_NUM_FUNC, MUL, SUB, GP_TREE::tree, and tree_print().
Referenced by cond_gp_print(), and tree_print().
tree_rand()
void tree_rand (const XCSF * xcsf, GP_TREE * gp)
Creates a random GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree being randomised.
Definition at line 74 of file gp.c.
References XCSF::GP_INIT_DEPTH, GP_MAX_LEN, GP_TREE::len, GP_TREE::tree, and tree_grow().
Referenced by cond_gp_init(), and cond_gp_rand().
tree_save()
size_t tree_save (const XCSF * xcsf, const GP_TREE * gp, FILE * fp)
Writes the GP tree to a binary file.
Parameters
xcsf The XCSF data structure.
gp The GP tree to save.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 328 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_save().