XCSF: mt19937-64.c File Reference
mt19937-64.c File Reference
Mersenne Twister 64-bit pseudorandom number generator.
#include <stdio.h>
#include "mt64.h"
Macros
#define NN 312
#define MM 156
#define MATRIX_A 0xB5026F5AA96619E9ULL
#define UM 0xFFFFFFFF80000000ULL /* Most significant 33 bits */
#define LM 0x7FFFFFFFULL /* Least significant 31 bits */
Functions
void init_genrand64 (unsigned long long seed)
void init_by_array64 (unsigned long long init_key[], unsigned long long key_length)
unsigned long long genrand64_int64 (void)
long long genrand64_int63 (void)
double genrand64_real1 (void)
double genrand64_real2 (void)
double genrand64_real3 (void)
Variables
static unsigned long long mt [312]
static int mti = 312 +1
Detailed Description
Mersenne Twister 64-bit pseudorandom number generator.
Author
Takuji Nishimura
Makoto Matsumoto
Copyright
The Authors.
Date
2004/9/29
Definition in file mt19937-64.c.
Macro Definition Documentation
LM
#define LM 0x7FFFFFFFULL /* Least significant 31 bits */
Definition at line 72 of file mt19937-64.c.
Referenced by genrand64_int64().
MATRIX_A
#define MATRIX_A 0xB5026F5AA96619E9ULL
Definition at line 70 of file mt19937-64.c.
Referenced by genrand64_int64().
MM
#define MM 156
Definition at line 69 of file mt19937-64.c.
Referenced by genrand64_int64().
NN
#define NN 312
Definition at line 68 of file mt19937-64.c.
Referenced by genrand64_int64(), init_by_array64(), and init_genrand64().
UM
#define UM 0xFFFFFFFF80000000ULL /* Most significant 33 bits */
Definition at line 71 of file mt19937-64.c.
Referenced by genrand64_int64().
Function Documentation
genrand64_int63()
long long genrand64_int63 (void)
Definition at line 156 of file mt19937-64.c.
References genrand64_int64().
genrand64_int64()
unsigned long long genrand64_int64 (void)
Definition at line 117 of file mt19937-64.c.
References init_genrand64(), LM, MATRIX_A, MM, mt, mti, NN, and UM.
Referenced by genrand64_int63(), genrand64_real1(), genrand64_real2(), and genrand64_real3().
genrand64_real1()
double genrand64_real1 (void)
Definition at line 162 of file mt19937-64.c.
References genrand64_int64().
Referenced by drand().
genrand64_real2()
double genrand64_real2 (void)
Definition at line 168 of file mt19937-64.c.
References genrand64_int64().
genrand64_real3()
double genrand64_real3 (void)
Definition at line 174 of file mt19937-64.c.
References genrand64_int64().
init_by_array64()
void init_by_array64 (unsigned long long init_key[], unsigned long long key_length)
Definition at line 91 of file mt19937-64.c.
References init_genrand64(), mt, and NN.
init_genrand64()
void init_genrand64 (unsigned long long seed)
Definition at line 81 of file mt19937-64.c.
References mt, mti, and NN.
Referenced by genrand64_int64(), init_by_array64(), and random_init().
Variable Documentation
mt
unsigned long long mt[312] static
Definition at line 76 of file mt19937-64.c.
Referenced by genrand64_int64(), init_by_array64(), and init_genrand64().
mti
int mti = 312 +1 static
Definition at line 78 of file mt19937-64.c.
Referenced by genrand64_int64(), and init_genrand64().