XCSF: mt64.h File Reference
mt64.h File Reference
Mersenne Twister 64-bit pseudorandom number generator.
Functions
void init_genrand64 (unsigned long long seed)
void init_by_array64 (const unsigned long long init_key[], unsigned long long key_length)
unsigned long long genrand64_int64 (void)
long long genrand64_int63 (void)
double genrand64_real1 (void)
double genrand64_real2 (void)
double genrand64_real3 (void)
Detailed Description
Mersenne Twister 64-bit pseudorandom number generator.
Author
Takuji Nishimura
Makoto Matsumoto
Copyright
The Authors.
Date
2004/9/29
Definition in file mt64.h.
Function Documentation
genrand64_int63()
long long genrand64_int63 (void)
Definition at line 157 of file mt19937-64.c.
References genrand64_int64().
genrand64_int64()
unsigned long long genrand64_int64 (void)
Definition at line 124 of file mt19937-64.c.
References init_genrand64(), LM, MATRIX_A, MM, mt, mti, NN, and UM.
Referenced by genrand64_int63(), genrand64_real1(), genrand64_real2(), and genrand64_real3().
genrand64_real1()
double genrand64_real1 (void)
Definition at line 163 of file mt19937-64.c.
References genrand64_int64().
Referenced by drand().
genrand64_real2()
double genrand64_real2 (void)
Definition at line 169 of file mt19937-64.c.
References genrand64_int64().
genrand64_real3()
double genrand64_real3 (void)
Definition at line 175 of file mt19937-64.c.
References genrand64_int64().
init_by_array64()
void init_by_array64 (const unsigned long long init_key[], unsigned long long key_length)
Definition at line 91 of file mt19937-64.c.
References init_genrand64(), mt, and NN.
init_genrand64()
void init_genrand64 (unsigned long long seed)
Definition at line 80 of file mt19937-64.c.
References mt, mti, and NN.
Referenced by genrand64_int64(), init_by_array64(), and random_init().