XCSF: neural_activations.c File Reference
neural_activations.c File Reference
Neural network activation functions.
#include <stdlib.h>
#include <stdio.h>
#include "utils.h"
#include "neural_activations.h"
Functions
double neural_activate (int a, double x)
Returns the result from applying a specified activation function.
double neural_gradient (int a, double x)
Returns the derivative from applying a specified activation function.
const char * neural_activation_string (int a)
Returns the name of a specified activation function.
void neural_activate_array (double *state, double *output, int n, int a)
Applies a specified activation function to an array.
void neural_gradient_array (const double *state, double *delta, int n, int a)
Applies a specified gradient function to an array.
Detailed Description
Neural network activation functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2012–2020.
Definition in file neural_activations.c.
Function Documentation
neural_activate()
double neural_activate (int a, double x)
Returns the result from applying a specified activation function.
Parameters
a The activation function to apply.
x The input to the activation function.
Returns
The result from applying the activation function.
Definition at line 35 of file neural_activations.c.
References COS, cos_activate(), GAUSSIAN, gaussian_activate(), LEAKY, leaky_activate(), LINEAR, linear_activate(), LOGGY, loggy_activate(), LOGISTIC, logistic_activate(), RELU, relu_activate(), SELU, selu_activate(), SIN, sin_activate(), SOFT_PLUS, soft_plus_activate(), TANH, and tanh_activate().
Referenced by neural_activate_array().
neural_activate_array()
void neural_activate_array (double * state, double * output, int n, int a)
Applies a specified activation function to an array.
Parameters
state The neuron states.
output The neuron outputs (set by this function).
n The length of the input array.
a The activation function.
Definition at line 113 of file neural_activations.c.
References constrain(), neural_activate(), NEURON_MAX_STATE, and NEURON_MIN_STATE.
Referenced by neural_layer_connected_forward().
neural_activation_string()
const char* neural_activation_string (int a)
Returns the name of a specified activation function.
Parameters
a The activation function.
Returns
The name of the activation function.
Definition at line 86 of file neural_activations.c.
References COS, GAUSSIAN, LEAKY, LINEAR, LOGGY, LOGISTIC, RELU, SELU, SIN, SOFT_PLUS, and TANH.
Referenced by neural_layer_connected_print().
neural_gradient()
double neural_gradient (int a, double x)
Returns the derivative from applying a specified activation function.
Parameters
a The activation function applied.
x The input to the activation function.
Returns
The derivative from applying the activation function.
Definition at line 61 of file neural_activations.c.
References COS, cos_gradient(), GAUSSIAN, gaussian_gradient(), LEAKY, leaky_gradient(), LINEAR, linear_gradient(), LOGGY, loggy_gradient(), LOGISTIC, logistic_gradient(), RELU, relu_gradient(), SELU, selu_gradient(), SIN, sin_gradient(), SOFT_PLUS, soft_plus_gradient(), TANH, and tanh_gradient().
Referenced by neural_gradient_array().
neural_gradient_array()
void neural_gradient_array (const double * state, double * delta, int n, int a)
Applies a specified gradient function to an array.
Parameters
state The neuron states.
delta The neuron gradients (set by this function).
n The length of the input array.
a The activation function.
Definition at line 128 of file neural_activations.c.
References neural_gradient().
Referenced by neural_layer_connected_backward().