XCSF: neural_layer_connected.c File Reference
neural_layer_connected.c File Reference
An implementation of a fully-connected layer of perceptrons.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include "xcsf.h"
#include "utils.h"
#include "blas.h"
#include "sam.h"
#include "neural_activations.h"
#include "neural.h"
#include "neural_layer.h"
#include "neural_layer_connected.h"
Macros
#define N_MU 4
Number of mutation rates applied.
#define ETA_MAX 0.1
Maximum gradient descent rate.
#define ETA_MIN 0.0001
Minimum gradient descent rate.
Functions
static _Bool mutate_eta (LAYER *l, double mu)
static _Bool mutate_neurons (const XCSF *xcsf, LAYER *l, double mu)
static _Bool mutate_weights (const LAYER *l, double mu)
static _Bool mutate_functions (LAYER *l, double mu)
static void neuron_add (LAYER *l, int n)
static void neuron_remove (LAYER *l, int n)
LAYER * neural_layer_connected_init (const XCSF *xcsf, int in, int n_init, int n_max, int f, uint32_t o)
LAYER * neural_layer_connected_copy (const XCSF *xcsf, const LAYER *src)
void neural_layer_connected_free (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_rand (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_forward (const XCSF *xcsf, const LAYER *l, const double *input)
void neural_layer_connected_backward (const XCSF *xcsf, const LAYER *l, const NET *net)
void neural_layer_connected_update (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_resize (const XCSF *xcsf, LAYER *l, const LAYER *prev)
_Bool neural_layer_connected_mutate (const XCSF *xcsf, LAYER *l)
double * neural_layer_connected_output (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_print (const XCSF *xcsf, const LAYER *l, _Bool print_weights)
size_t neural_layer_connected_save (const XCSF *xcsf, const LAYER *l, FILE *fp)
size_t neural_layer_connected_load (const XCSF *xcsf, LAYER *l, FILE *fp)
Detailed Description
An implementation of a fully-connected layer of perceptrons.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file neural_layer_connected.c.
Macro Definition Documentation
ETA_MAX
#define ETA_MAX 0.1
Maximum gradient descent rate.
Definition at line 39 of file neural_layer_connected.c.
Referenced by mutate_eta(), and neural_layer_connected_init().
ETA_MIN
#define ETA_MIN 0.0001
Minimum gradient descent rate.
Definition at line 40 of file neural_layer_connected.c.
Referenced by mutate_eta(), and neural_layer_connected_init().
N_MU
#define N_MU 4
Number of mutation rates applied.
Definition at line 38 of file neural_layer_connected.c.
Referenced by neural_layer_connected_copy(), neural_layer_connected_init(), neural_layer_connected_load(), neural_layer_connected_mutate(), and neural_layer_connected_save().
Function Documentation
mutate_eta()
static _Bool mutate_eta (LAYER * l, double mu) static
Definition at line 233 of file neural_layer_connected.c.
References constrain(), LAYER::eta, ETA_MAX, ETA_MIN, and rand_normal().
Referenced by neural_layer_connected_mutate().
mutate_functions()
static _Bool mutate_functions (LAYER * l, double mu) static
Definition at line 366 of file neural_layer_connected.c.
References LAYER::function, irand_uniform(), NUM_ACTIVATIONS, and rand_uniform().
Referenced by neural_layer_connected_mutate().
mutate_neurons()
static _Bool mutate_neurons (const XCSF * xcsf, LAYER * l, double mu) static
Definition at line 244 of file neural_layer_connected.c.
References irand_uniform(), XCSF::MAX_NEURON_MOD, LAYER::max_outputs, LAYER::n_outputs, neuron_add(), neuron_remove(), and rand_uniform().
Referenced by neural_layer_connected_mutate().
mutate_weights()
static _Bool mutate_weights (const LAYER * l, double mu) static
Definition at line 346 of file neural_layer_connected.c.
References LAYER::biases, LAYER::n_outputs, LAYER::n_weights, rand_normal(), and LAYER::weights.
Referenced by neural_layer_connected_mutate().
neural_layer_connected_backward()
void neural_layer_connected_backward (const XCSF * xcsf, const LAYER * l, const NET * net)
Definition at line 148 of file neural_layer_connected.c.
References LAYER::bias_updates, blas_axpy(), blas_gemm(), NET::delta, LAYER::delta, LAYER::function, NET::input, LAYER_SGD_WEIGHTS, LAYER::n_inputs, LAYER::n_outputs, neural_gradient_array(), LAYER::options, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_copy()
LAYER* neural_layer_connected_copy (const XCSF * xcsf, const LAYER * src)
Definition at line 81 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::eta, LAYER::function, LAYER::layer_type, LAYER::layer_vptr, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_forward()
void neural_layer_connected_forward (const XCSF * xcsf, const LAYER * l, const double * input)
Definition at line 132 of file neural_layer_connected.c.
References LAYER::biases, blas_gemm(), LAYER::function, LAYER::n_inputs, LAYER::n_outputs, neural_activate_array(), LAYER::output, LAYER::state, and LAYER::weights.
neural_layer_connected_free()
void neural_layer_connected_free (const XCSF * xcsf, const LAYER * l)
Definition at line 108 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::mu, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_init()
LAYER* neural_layer_connected_init (const XCSF * xcsf, int in, int n_init, int n_max, int f, uint32_t o)
Definition at line 49 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, CONNECTED, LAYER::delta, LAYER::eta, ETA_MAX, ETA_MIN, LAYER::function, layer_connected_vtbl, LAYER_EVOLVE_ETA, LAYER::layer_type, LAYER::layer_vptr, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, XCSF::PRED_ETA, rand_normal(), rand_uniform(), sam_init(), LAYER::state, LAYER::weight_updates, and LAYER::weights.
Referenced by cond_neural_init(), pred_neural_expand(), pred_neural_init(), and rule_neural_cond_init().
neural_layer_connected_load()
size_t neural_layer_connected_load (const XCSF * xcsf, LAYER * l, FILE * fp)
Definition at line 423 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::eta, LAYER::function, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_mutate()
_Bool neural_layer_connected_mutate (const XCSF * xcsf, LAYER * l)
Definition at line 214 of file neural_layer_connected.c.
References LAYER_EVOLVE_ETA, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, LAYER::mu, mutate_eta(), mutate_functions(), mutate_neurons(), mutate_weights(), N_MU, LAYER::options, and sam_adapt().
neural_layer_connected_output()
double* neural_layer_connected_output (const XCSF * xcsf, const LAYER * l)
Definition at line 378 of file neural_layer_connected.c.
References LAYER::output.
neural_layer_connected_print()
void neural_layer_connected_print (const XCSF * xcsf, const LAYER * l, _Bool print_weights)
Definition at line 384 of file neural_layer_connected.c.
References LAYER::biases, LAYER::function, LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, neural_activation_string(), and LAYER::weights.
neural_layer_connected_rand()
void neural_layer_connected_rand (const XCSF * xcsf, const LAYER * l)
Definition at line 121 of file neural_layer_connected.c.
References LAYER::biases, LAYER::n_outputs, LAYER::n_weights, rand_normal(), and LAYER::weights.
neural_layer_connected_resize()
void neural_layer_connected_resize (const XCSF * xcsf, LAYER * l, const LAYER * prev)
Definition at line 186 of file neural_layer_connected.c.
References LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, rand_normal(), LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_save()
size_t neural_layer_connected_save (const XCSF * xcsf, const LAYER * l, FILE * fp)
Definition at line 404 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::eta, LAYER::function, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_update()
void neural_layer_connected_update (const XCSF * xcsf, const LAYER * l)
Definition at line 176 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, blas_axpy(), blas_scal(), LAYER::eta, LAYER_SGD_WEIGHTS, LAYER::n_outputs, LAYER::n_weights, LAYER::options, XCSF::PRED_MOMENTUM, LAYER::weight_updates, and LAYER::weights.
neuron_add()
static void neuron_add (LAYER * l, int n) static
Definition at line 274 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, LAYER::output, rand_normal(), LAYER::state, LAYER::weight_updates, and LAYER::weights.
Referenced by mutate_neurons().
neuron_remove()
static void neuron_remove (LAYER * l, int n) static
Definition at line 314 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
Referenced by mutate_neurons().