XCSF: neural_layer.h File Reference
neural_layer.h File Reference
Interface for neural network layers.
#include <stdint.h>
Data Structures
struct LAYER
Neural network layer data structure.
struct LayerVtbl
Neural network layer interface data structure.
Macros
#define CONNECTED 0
#define DROPOUT 1
#define NOISE 2
#define SOFTMAX 3
#define LAYER_EVOLVE_WEIGHTS (1<<0)
#define LAYER_EVOLVE_NEURONS (1<<1)
#define LAYER_EVOLVE_ETA (1<<2)
#define LAYER_EVOLVE_FUNCTIONS (1<<3)
#define LAYER_SGD_WEIGHTS (1<<4)
Typedefs
typedef struct LAYER LAYER
Neural network layer data structure.
Functions
static size_t layer_save (const XCSF *xcsf, const LAYER *l, FILE *fp)
static size_t layer_load (const XCSF *xcsf, LAYER *l, FILE *fp)
static double * layer_output (const XCSF *xcsf, const LAYER *l)
static void layer_forward (const XCSF *xcsf, const LAYER *l, const double *input)
static void layer_backward (const XCSF *xcsf, const LAYER *l, const NET *net)
static void layer_update (const XCSF *xcsf, const LAYER *l)
static _Bool layer_mutate (const XCSF *xcsf, LAYER *l)
static void layer_resize (const XCSF *xcsf, LAYER *l, const LAYER *prev)
static LAYER * layer_copy (const XCSF *xcsf, const LAYER *from)
static void layer_free (const XCSF *xcsf, const LAYER *l)
static void layer_rand (const XCSF *xcsf, const LAYER *l)
static void layer_print (const XCSF *xcsf, const LAYER *l, _Bool print_weights)
void neural_layer_set_vptr (LAYER *l)
Sets a neural network layer's functions to the implementations.
Detailed Description
Interface for neural network layers.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file neural_layer.h.
Macro Definition Documentation
CONNECTED
#define CONNECTED 0
Definition at line 28 of file neural_layer.h.
Referenced by neural_layer_connected_init(), and neural_layer_set_vptr().
DROPOUT
#define DROPOUT 1
Definition at line 29 of file neural_layer.h.
Referenced by neural_layer_dropout_init(), and neural_layer_set_vptr().
LAYER_EVOLVE_ETA
#define LAYER_EVOLVE_ETA (1<<2)
Definition at line 35 of file neural_layer.h.
Referenced by neural_layer_connected_init(), neural_layer_connected_mutate(), and pred_neural_lopt().
LAYER_EVOLVE_FUNCTIONS
#define LAYER_EVOLVE_FUNCTIONS (1<<3)
Definition at line 36 of file neural_layer.h.
Referenced by cond_neural_lopt(), neural_layer_connected_mutate(), pred_neural_lopt(), and rule_neural_lopt().
LAYER_EVOLVE_NEURONS
#define LAYER_EVOLVE_NEURONS (1<<1)
Definition at line 34 of file neural_layer.h.
Referenced by cond_neural_init(), cond_neural_lopt(), neural_layer_connected_mutate(), pred_neural_init(), pred_neural_lopt(), rule_neural_cond_init(), and rule_neural_lopt().
LAYER_EVOLVE_WEIGHTS
#define LAYER_EVOLVE_WEIGHTS (1<<0)
Definition at line 33 of file neural_layer.h.
Referenced by cond_neural_lopt(), neural_layer_connected_mutate(), pred_neural_lopt(), and rule_neural_lopt().
LAYER_SGD_WEIGHTS
#define LAYER_SGD_WEIGHTS (1<<4)
Definition at line 37 of file neural_layer.h.
Referenced by neural_layer_connected_backward(), neural_layer_connected_update(), and pred_neural_lopt().
NOISE
#define NOISE 2
Definition at line 30 of file neural_layer.h.
Referenced by neural_layer_noise_init(), and neural_layer_set_vptr().
SOFTMAX
#define SOFTMAX 3
Definition at line 31 of file neural_layer.h.
Referenced by neural_layer_set_vptr(), and neural_layer_softmax_init().
Typedef Documentation
LAYER
typedef struct LAYER LAYER
Neural network layer data structure.
Function Documentation
layer_backward()
static void layer_backward (const XCSF * xcsf, const LAYER * l, const NET * net) inline static
Definition at line 172 of file neural_layer.h.
References LayerVtbl::layer_impl_backward, and LAYER::layer_vptr.
Referenced by neural_learn().
layer_copy()
static LAYER* layer_copy (const XCSF * xcsf, const LAYER * from) inline static
Definition at line 188 of file neural_layer.h.
References LayerVtbl::layer_impl_copy, and LAYER::layer_vptr.
Referenced by neural_copy().
layer_forward()
static void layer_forward (const XCSF * xcsf, const LAYER * l, const double * input) inline static
Definition at line 168 of file neural_layer.h.
References LayerVtbl::layer_impl_forward, and LAYER::layer_vptr.
Referenced by neural_propagate().
layer_free()
static void layer_free (const XCSF * xcsf, const LAYER * l) inline static
Definition at line 192 of file neural_layer.h.
References LayerVtbl::layer_impl_free, and LAYER::layer_vptr.
Referenced by neural_free(), and neural_layer_remove().
layer_load()
static size_t layer_load (const XCSF * xcsf, LAYER * l, FILE * fp) inline static
Definition at line 160 of file neural_layer.h.
References LayerVtbl::layer_impl_load, and LAYER::layer_vptr.
Referenced by neural_load().
layer_mutate()
static _Bool layer_mutate (const XCSF * xcsf, LAYER * l) inline static
Definition at line 180 of file neural_layer.h.
References LayerVtbl::layer_impl_mutate, and LAYER::layer_vptr.
Referenced by neural_mutate().
layer_output()
static double* layer_output (const XCSF * xcsf, const LAYER * l) inline static
Definition at line 164 of file neural_layer.h.
References LayerVtbl::layer_impl_output, and LAYER::layer_vptr.
Referenced by neural_output(), and neural_propagate().
layer_print()
static void layer_print (const XCSF * xcsf, const LAYER * l, _Bool print_weights) inline static
Definition at line 200 of file neural_layer.h.
References LayerVtbl::layer_impl_print, LAYER::layer_vptr, and neural_layer_set_vptr().
Referenced by neural_print().
layer_rand()
static void layer_rand (const XCSF * xcsf, const LAYER * l) inline static
Definition at line 196 of file neural_layer.h.
References LayerVtbl::layer_impl_rand, and LAYER::layer_vptr.
Referenced by neural_rand().
layer_resize()
static void layer_resize (const XCSF * xcsf, LAYER * l, const LAYER * prev) inline static
Definition at line 184 of file neural_layer.h.
References LayerVtbl::layer_impl_resize, and LAYER::layer_vptr.
Referenced by neural_mutate().
layer_save()
static size_t layer_save (const XCSF * xcsf, const LAYER * l, FILE * fp) inline static
Definition at line 156 of file neural_layer.h.
References LayerVtbl::layer_impl_save, and LAYER::layer_vptr.
Referenced by neural_save().
layer_update()
static void layer_update (const XCSF * xcsf, const LAYER * l) inline static
Definition at line 176 of file neural_layer.h.
References LayerVtbl::layer_impl_update, and LAYER::layer_vptr.
Referenced by neural_learn().
neural_layer_set_vptr()
void neural_layer_set_vptr (LAYER * l)
Sets a neural network layer's functions to the implementations.
Parameters
l The neural network layer to set.
Definition at line 44 of file neural_layer.c.
References CONNECTED, DROPOUT, layer_connected_vtbl, layer_dropout_vtbl, layer_noise_vtbl, layer_softmax_vtbl, LAYER::layer_type, LAYER::layer_vptr, NOISE, and SOFTMAX.
Referenced by layer_print(), and neural_load().