XCSF: neural.c File Reference
neural.c File Reference
An implementation of a multi-layer perceptron neural network.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <float.h>
#include "xcsf.h"
#include "utils.h"
#include "neural_activations.h"
#include "neural.h"
#include "neural_layer.h"
#include "neural_layer_connected.h"
#include "neural_layer_dropout.h"
#include "neural_layer_noise.h"
#include "neural_layer_softmax.h"
Functions
void neural_init (const XCSF *xcsf, NET *net)
Initialises an empty neural network.
void neural_layer_insert (const XCSF *xcsf, NET *net, LAYER *l, int p)
Inserts a layer into a neural network.
void neural_layer_remove (const XCSF *xcsf, NET *net, int p)
Removes a layer from a neural network.
void neural_copy (const XCSF *xcsf, NET *to, NET *from)
Copies a neural network.
void neural_free (const XCSF *xcsf, NET *net)
Frees a neural network.
void neural_rand (const XCSF *xcsf, NET *net)
Randomises the layers within a neural network.
_Bool neural_mutate (const XCSF *xcsf, NET *net)
Mutates a neural network.
void neural_propagate (const XCSF *xcsf, NET *net, const double *input)
Forward propagates a neural network.
void neural_learn (const XCSF *xcsf, NET *net, const double *truth, const double *input)
Performs a gradient descent update on a neural network.
double neural_output (const XCSF *xcsf, NET *net, int i)
Returns the output of a specified neuron in the output layer of a neural network.
void neural_print (const XCSF *xcsf, NET *net, _Bool print_weights)
Prints a neural network.
int neural_size (const XCSF *xcsf, NET *net)
Returns the total number of neurons in a neural network.
size_t neural_save (const XCSF *xcsf, NET *net, FILE *fp)
Writes a neural network to a binary file.
size_t neural_load (const XCSF *xcsf, NET *net, FILE *fp)
Reads a neural network from a binary file.
Detailed Description
An implementation of a multi-layer perceptron neural network.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2012–2020.
Definition in file neural.c.
Function Documentation
neural_copy()
void neural_copy (const XCSF * xcsf, NET * to, NET * from)
Copies a neural network.
Parameters
xcsf The const XCSF data structure.
to The destination neural network.
from The source neural network.
Definition at line 151 of file neural.c.
References layer_copy(), neural_init(), neural_layer_insert(), LLIST::prev, and NET::tail.
Referenced by cond_neural_copy(), pred_neural_copy(), and rule_neural_cond_copy().
neural_free()
void neural_free (const XCSF * xcsf, NET * net)
Frees a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to free.
Definition at line 168 of file neural.c.
References LLIST::layer, layer_free(), NET::num_layers, LLIST::prev, and NET::tail.
Referenced by cond_neural_free(), pred_neural_free(), and rule_neural_cond_free().
neural_init()
void neural_init (const XCSF * xcsf, NET * net)
Initialises an empty neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to initialise.
Definition at line 45 of file neural.c.
References NET::head, NET::num_inputs, NET::num_layers, NET::num_outputs, and NET::tail.
Referenced by cond_neural_init(), neural_copy(), neural_load(), pred_neural_init(), and rule_neural_cond_init().
neural_layer_insert()
void neural_layer_insert (const XCSF * xcsf, NET * net, LAYER * l, int p)
Inserts a layer into a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network receiving the layer.
l The layer to insert.
p The position in the network to insert the layer.
Definition at line 62 of file neural.c.
References NET::head, LLIST::layer, LLIST::next, NET::num_inputs, LAYER::num_inputs, NET::num_layers, NET::num_outputs, LAYER::num_outputs, LLIST::prev, and NET::tail.
Referenced by cond_neural_init(), neural_copy(), neural_load(), pred_neural_init(), and rule_neural_cond_init().
neural_layer_remove()
void neural_layer_remove (const XCSF * xcsf, NET * net, int p)
Removes a layer from a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network removing the layer.
p The position of the layer in the network to be removed.
Definition at line 114 of file neural.c.
References NET::head, LLIST::layer, layer_free(), LLIST::next, NET::num_layers, LLIST::prev, and NET::tail.
neural_learn()
void neural_learn (const XCSF * xcsf, NET * net, const double * truth, const double * input)
Performs a gradient descent update on a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to be updated.
truth The desired network output.
input The input state.
Definition at line 238 of file neural.c.
References NET::delta, LAYER::delta, NET::head, NET::input, LLIST::layer, layer_backward(), layer_update(), LLIST::next, LAYER::num_outputs, LAYER::output, LLIST::prev, and NET::tail.
Referenced by pred_neural_update().
neural_load()
size_t neural_load (const XCSF * xcsf, NET * net, FILE * fp)
Reads a neural network from a binary file.
Parameters
xcsf The const XCSF data structure.
net The neural network to load.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 352 of file neural.c.
References layer_load(), LAYER::layer_type, neural_init(), neural_layer_insert(), and neural_layer_set_vptr().
Referenced by cond_neural_load(), pred_neural_load(), and rule_neural_cond_load().
neural_mutate()
_Bool neural_mutate (const XCSF * xcsf, NET * net)
Mutates a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to mutate.
Returns
Whether any alterations were made.
Definition at line 199 of file neural.c.
References layer_mutate(), layer_resize(), LAYER::num_inputs, LAYER::num_outputs, LLIST::prev, and NET::tail.
Referenced by cond_neural_mutate(), pred_neural_mutate(), and rule_neural_cond_mutate().
neural_output()
double neural_output (const XCSF * xcsf, NET * net, int i)
Returns the output of a specified neuron in the output layer of a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to output.
i Which neuron in the output layer to return.
Returns
The output of the specified neuron.
Definition at line 282 of file neural.c.
References XCSF::COND_MAX, XCSF::COND_MIN, constrain(), NET::head, LLIST::layer, layer_output(), and NET::num_outputs.
Referenced by cond_neural_match(), pred_neural_compute(), rule_neural_act_compute(), and rule_neural_cond_match().
neural_print()
void neural_print (const XCSF * xcsf, NET * net, _Bool print_weights)
Prints a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to print.
print_weights Whether to print the weights in each layer.
Definition at line 299 of file neural.c.
References layer_print(), LLIST::prev, and NET::tail.
Referenced by cond_neural_print(), pred_neural_print(), and rule_neural_cond_print().
neural_propagate()
void neural_propagate (const XCSF * xcsf, NET * net, const double * input)
Forward propagates a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to propagate.
input The input state.
Definition at line 223 of file neural.c.
References layer_forward(), layer_output(), LLIST::prev, and NET::tail.
Referenced by cond_neural_match(), pred_neural_compute(), and rule_neural_cond_match().
neural_rand()
void neural_rand (const XCSF * xcsf, NET * net)
Randomises the layers within a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to randomise.
Definition at line 186 of file neural.c.
References layer_rand(), LLIST::prev, and NET::tail.
Referenced by cond_neural_rand(), and rule_neural_cond_rand().
neural_save()
size_t neural_save (const XCSF * xcsf, NET * net, FILE * fp)
Writes a neural network to a binary file.
Parameters
xcsf The const XCSF data structure.
net The neural network to save.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 332 of file neural.c.
References layer_save(), NET::num_inputs, NET::num_layers, NET::num_outputs, LLIST::prev, and NET::tail.
Referenced by cond_neural_save(), pred_neural_save(), and rule_neural_cond_save().
neural_size()
int neural_size (const XCSF * xcsf, NET * net)
Returns the total number of neurons in a neural network.
Parameters
xcsf The const XCSF data structure.
net The neural network to calculate the number of neurons.
Returns
The total number of neurons.
Definition at line 315 of file neural.c.
References LLIST::prev, and NET::tail.
Referenced by cond_neural_size(), pred_neural_size(), and rule_neural_cond_size().