XCSF: neural_activations.h File Reference
neural_activations.h File Reference
Neural network activation functions.
#include <math.h>
Macros
#define LOGISTIC 0
#define RELU 1
#define TANH 2
#define IDENTITY 3
#define GAUSSIAN 4
#define SIN 5
#define COS 6
#define SOFT_PLUS 7
#define LEAKY 8
#define SELU 9
#define NUM_ACTIVATIONS 10
Functions
double neural_activate (int function, double state)
Returns the result from applying a specified activation function.
double neural_gradient (int function, double state)
Returns the derivative from applying a specified activation function.
const char * activation_string (int function)
Returns the name of a specified activation function.
static double logistic_activate (double x)
static double logistic_gradient (double x)
static double gaussian_activate (double x)
static double gaussian_gradient (double x)
static double relu_activate (double x)
static double relu_gradient (double x)
static double selu_activate (double x)
static double selu_gradient (double x)
static double identity_activate (double x)
static double identity_gradient (double x)
static double soft_plus_activate (double x)
static double soft_plus_gradient (double x)
static double tanh_activate (double x)
static double tanh_gradient (double x)
static double leaky_activate (double x)
static double leaky_gradient (double x)
static double sin_activate (double x)
static double sin_gradient (double x)
static double cos_activate (double x)
static double cos_gradient (double x)
Detailed Description
Neural network activation functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2012–2020.
Definition in file neural_activations.h.
Macro Definition Documentation
COS
#define COS 6
Definition at line 34 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
GAUSSIAN
#define GAUSSIAN 4
Definition at line 32 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
IDENTITY
#define IDENTITY 3
Definition at line 31 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
LEAKY
#define LEAKY 8
Definition at line 36 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
LOGISTIC
#define LOGISTIC 0
Definition at line 28 of file neural_activations.h.
Referenced by activation_string(), cond_neural_init(), neural_activate(), neural_gradient(), pred_neural_init(), and rule_neural_cond_init().
NUM_ACTIVATIONS
#define NUM_ACTIVATIONS 10
Definition at line 38 of file neural_activations.h.
Referenced by mutate_functions().
RELU
#define RELU 1
Definition at line 29 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
SELU
#define SELU 9
Definition at line 37 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
SIN
#define SIN 5
Definition at line 33 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
SOFT_PLUS
#define SOFT_PLUS 7
Definition at line 35 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
TANH
#define TANH 2
Definition at line 30 of file neural_activations.h.
Referenced by activation_string(), neural_activate(), and neural_gradient().
Function Documentation
activation_string()
const char* activation_string (int function)
Returns the name of a specified activation function.
Parameters
function The activation function.
Returns
The name of the activation function.
Definition at line 83 of file neural_activations.c.
References COS, GAUSSIAN, IDENTITY, LEAKY, LOGISTIC, RELU, SELU, SIN, SOFT_PLUS, and TANH.
Referenced by neural_layer_connected_print().
cos_activate()
static double cos_activate (double x) inline static
Definition at line 62 of file neural_activations.h.
Referenced by neural_activate().
cos_gradient()
static double cos_gradient (double x) inline static
Definition at line 63 of file neural_activations.h.
Referenced by neural_gradient().
gaussian_activate()
static double gaussian_activate (double x) inline static
Definition at line 46 of file neural_activations.h.
Referenced by neural_activate().
gaussian_gradient()
static double gaussian_gradient (double x) inline static
Definition at line 47 of file neural_activations.h.
Referenced by neural_gradient().
identity_activate()
static double identity_activate (double x) inline static
Definition at line 52 of file neural_activations.h.
Referenced by neural_activate().
identity_gradient()
static double identity_gradient (double x) inline static
Definition at line 53 of file neural_activations.h.
Referenced by neural_gradient().
leaky_activate()
static double leaky_activate (double x) inline static
Definition at line 58 of file neural_activations.h.
Referenced by neural_activate().
leaky_gradient()
static double leaky_gradient (double x) inline static
Definition at line 59 of file neural_activations.h.
Referenced by neural_gradient().
logistic_activate()
static double logistic_activate (double x) inline static
Definition at line 44 of file neural_activations.h.
Referenced by neural_activate().
logistic_gradient()
static double logistic_gradient (double x) inline static
Definition at line 45 of file neural_activations.h.
Referenced by neural_gradient().
neural_activate()
double neural_activate (int function, double state)
Returns the result from applying a specified activation function.
Parameters
function The activation function to apply.
state The input to the activation function.
Returns
The result from applying the activation function.
Definition at line 34 of file neural_activations.c.
References COS, cos_activate(), GAUSSIAN, gaussian_activate(), IDENTITY, identity_activate(), LEAKY, leaky_activate(), LOGISTIC, logistic_activate(), RELU, relu_activate(), SELU, selu_activate(), SIN, sin_activate(), SOFT_PLUS, soft_plus_activate(), TANH, and tanh_activate().
Referenced by neural_layer_connected_forward().
neural_gradient()
double neural_gradient (int function, double state)
Returns the derivative from applying a specified activation function.
Parameters
function The activation function applied.
state The input to the activation function.
Returns
The derivative from applying the activation function.
Definition at line 59 of file neural_activations.c.
References COS, cos_gradient(), GAUSSIAN, gaussian_gradient(), IDENTITY, identity_gradient(), LEAKY, leaky_gradient(), LOGISTIC, logistic_gradient(), RELU, relu_gradient(), SELU, selu_gradient(), SIN, sin_gradient(), SOFT_PLUS, soft_plus_gradient(), TANH, and tanh_gradient().
Referenced by neural_layer_connected_backward().
relu_activate()
static double relu_activate (double x) inline static
Definition at line 48 of file neural_activations.h.
Referenced by neural_activate().
relu_gradient()
static double relu_gradient (double x) inline static
Definition at line 49 of file neural_activations.h.
Referenced by neural_gradient().
selu_activate()
static double selu_activate (double x) inline static
Definition at line 50 of file neural_activations.h.
Referenced by neural_activate().
selu_gradient()
static double selu_gradient (double x) inline static
Definition at line 51 of file neural_activations.h.
Referenced by neural_gradient().
sin_activate()
static double sin_activate (double x) inline static
Definition at line 60 of file neural_activations.h.
Referenced by neural_activate().
sin_gradient()
static double sin_gradient (double x) inline static
Definition at line 61 of file neural_activations.h.
Referenced by neural_gradient().
soft_plus_activate()
static double soft_plus_activate (double x) inline static
Definition at line 54 of file neural_activations.h.
Referenced by neural_activate().
soft_plus_gradient()
static double soft_plus_gradient (double x) inline static
Definition at line 55 of file neural_activations.h.
Referenced by neural_gradient().
tanh_activate()
static double tanh_activate (double x) inline static
Definition at line 56 of file neural_activations.h.
Referenced by neural_activate().
tanh_gradient()
static double tanh_gradient (double x) inline static
Definition at line 57 of file neural_activations.h.
Referenced by neural_gradient().