XCSF: neural_layer_connected.h File Reference
neural_layer_connected.h File Reference
An implementation of a fully-connected layer of perceptrons.
Functions
LAYER * neural_layer_connected_init (const XCSF *xcsf, int in, int n_init, int n_max, int f, uint32_t o)
LAYER * neural_layer_connected_copy (const XCSF *xcsf, const LAYER *from)
void neural_layer_connected_rand (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_forward (const XCSF *xcsf, const LAYER *l, const double *input)
void neural_layer_connected_backward (const XCSF *xcsf, const LAYER *l, const NET *net)
void neural_layer_connected_update (const XCSF *xcsf, const LAYER *l)
void neural_layer_connected_print (const XCSF *xcsf, const LAYER *l, _Bool print_weights)
_Bool neural_layer_connected_mutate (const XCSF *xcsf, LAYER *l)
void neural_layer_connected_free (const XCSF *xcsf, const LAYER *l)
double * neural_layer_connected_output (const XCSF *xcsf, const LAYER *l)
size_t neural_layer_connected_save (const XCSF *xcsf, const LAYER *l, FILE *fp)
size_t neural_layer_connected_load (const XCSF *xcsf, LAYER *l, FILE *fp)
void neural_layer_connected_resize (const XCSF *xcsf, LAYER *l, const LAYER *prev)
Variables
static struct LayerVtbl const layer_connected_vtbl
Detailed Description
An implementation of a fully-connected layer of perceptrons.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file neural_layer_connected.h.
Function Documentation
neural_layer_connected_backward()
void neural_layer_connected_backward (const XCSF * xcsf, const LAYER * l, const NET * net)
Definition at line 148 of file neural_layer_connected.c.
References LAYER::bias_updates, blas_axpy(), blas_gemm(), NET::delta, LAYER::delta, LAYER::function, NET::input, LAYER_SGD_WEIGHTS, LAYER::n_inputs, LAYER::n_outputs, neural_gradient_array(), LAYER::options, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_copy()
LAYER* neural_layer_connected_copy (const XCSF * xcsf, const LAYER * from)
Definition at line 81 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::eta, LAYER::function, LAYER::layer_type, LAYER::layer_vptr, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_forward()
void neural_layer_connected_forward (const XCSF * xcsf, const LAYER * l, const double * input)
Definition at line 132 of file neural_layer_connected.c.
References LAYER::biases, blas_gemm(), LAYER::function, LAYER::n_inputs, LAYER::n_outputs, neural_activate_array(), LAYER::output, LAYER::state, and LAYER::weights.
neural_layer_connected_free()
void neural_layer_connected_free (const XCSF * xcsf, const LAYER * l)
Definition at line 108 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::mu, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_init()
LAYER* neural_layer_connected_init (const XCSF * xcsf, int in, int n_init, int n_max, int f, uint32_t o)
Definition at line 49 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, CONNECTED, LAYER::delta, LAYER::eta, ETA_MAX, ETA_MIN, LAYER::function, layer_connected_vtbl, LAYER_EVOLVE_ETA, LAYER::layer_type, LAYER::layer_vptr, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, XCSF::PRED_ETA, rand_normal(), rand_uniform(), sam_init(), LAYER::state, LAYER::weight_updates, and LAYER::weights.
Referenced by cond_neural_init(), pred_neural_expand(), pred_neural_init(), and rule_neural_cond_init().
neural_layer_connected_load()
size_t neural_layer_connected_load (const XCSF * xcsf, LAYER * l, FILE * fp)
Definition at line 423 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::delta, LAYER::eta, LAYER::function, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::output, LAYER::state, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_mutate()
_Bool neural_layer_connected_mutate (const XCSF * xcsf, LAYER * l)
Definition at line 214 of file neural_layer_connected.c.
References LAYER_EVOLVE_ETA, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, LAYER::mu, mutate_eta(), mutate_functions(), mutate_neurons(), mutate_weights(), N_MU, LAYER::options, and sam_adapt().
neural_layer_connected_output()
double* neural_layer_connected_output (const XCSF * xcsf, const LAYER * l)
Definition at line 378 of file neural_layer_connected.c.
References LAYER::output.
neural_layer_connected_print()
void neural_layer_connected_print (const XCSF * xcsf, const LAYER * l, _Bool print_weights)
Definition at line 384 of file neural_layer_connected.c.
References LAYER::biases, LAYER::function, LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, neural_activation_string(), and LAYER::weights.
neural_layer_connected_rand()
void neural_layer_connected_rand (const XCSF * xcsf, const LAYER * l)
Definition at line 121 of file neural_layer_connected.c.
References LAYER::biases, LAYER::n_outputs, LAYER::n_weights, rand_normal(), and LAYER::weights.
neural_layer_connected_resize()
void neural_layer_connected_resize (const XCSF * xcsf, LAYER * l, const LAYER * prev)
Definition at line 186 of file neural_layer_connected.c.
References LAYER::n_inputs, LAYER::n_outputs, LAYER::n_weights, rand_normal(), LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_save()
size_t neural_layer_connected_save (const XCSF * xcsf, const LAYER * l, FILE * fp)
Definition at line 404 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, LAYER::eta, LAYER::function, LAYER::max_outputs, LAYER::mu, LAYER::n_inputs, N_MU, LAYER::n_outputs, LAYER::n_weights, LAYER::options, LAYER::weight_updates, and LAYER::weights.
neural_layer_connected_update()
void neural_layer_connected_update (const XCSF * xcsf, const LAYER * l)
Definition at line 176 of file neural_layer_connected.c.
References LAYER::bias_updates, LAYER::biases, blas_axpy(), blas_scal(), LAYER::eta, LAYER_SGD_WEIGHTS, LAYER::n_outputs, LAYER::n_weights, LAYER::options, XCSF::PRED_MOMENTUM, LAYER::weight_updates, and LAYER::weights.
Variable Documentation
layer_connected_vtbl
struct LayerVtbl const layer_connected_vtbl static
Initial value:
= {
    &neural_layer_connected_mutate,
    &neural_layer_connected_resize,
    &neural_layer_connected_copy,
    &neural_layer_connected_free,
    &neural_layer_connected_rand,
    &neural_layer_connected_print,
    &neural_layer_connected_update,
    &neural_layer_connected_backward,
    &neural_layer_connected_forward,
    &neural_layer_connected_output,
    &neural_layer_connected_save,
    &neural_layer_connected_load,
}
Definition at line 40 of file neural_layer_connected.h.
Referenced by neural_layer_connected_init(), and neural_layer_set_vptr().