XCSF: pa.h File Reference
pa.h File Reference
Prediction array functions.
Functions
void pa_build (const XCSF *xcsf, const double *x)
Builds the prediction array for the specified input.
double pa_best_val (const XCSF *xcsf)
Returns the highest value in the prediction array.
double pa_val (const XCSF *xcsf, int act)
Returns the value of a specified action in the prediction array.
int pa_best_action (const XCSF *xcsf)
Returns the best action in the prediction array.
int pa_rand_action (const XCSF *xcsf)
Returns a random action from the prediction array.
void pa_init (XCSF *xcsf)
Initialises the prediction array.
void pa_free (const XCSF *xcsf)
Frees the prediction array.
Detailed Description
Prediction array functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pa.h.
Function Documentation
pa_best_action()
int pa_best_action (const XCSF * xcsf)
Returns the best action in the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
The best action.
Definition at line 74 of file pa.c.
References XCSF::n_actions, and XCSF::pa.
Referenced by xcs_multi_decision(), and xcs_single_decision().
pa_best_val()
double pa_best_val (const XCSF * xcsf)
Returns the highest value in the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
The highest value in the prediction array.
Definition at line 104 of file pa.c.
References XCSF::n_actions, and XCSF::pa.
Referenced by xcs_multi_trial(), and xcs_single_error().
pa_build()
void pa_build (const XCSF * xcsf, const double * x)
Builds the prediction array for the specified input.
Parameters
xcsf The XCSF data structure.
x The input state.
Definition at line 48 of file pa.c.
References cl_predict(), SET::list, XCSF::mset, XCSF::n_actions, CLIST::next, XCSF::nr, and XCSF::pa.
Referenced by xcs_multi_decision(), and xcs_single_decision().
pa_free()
void pa_free (const XCSF * xcsf)
Frees the prediction array.
Parameters
xcsf The XCSF data structure.
Definition at line 134 of file pa.c.
References XCSF::nr, and XCSF::pa.
Referenced by xcs_multi_step_exp(), and xcs_single_step_exp().
pa_init()
void pa_init (XCSF * xcsf)
Initialises the prediction array.
Parameters
xcsf The XCSF data structure.
Definition at line 37 of file pa.c.
References XCSF::n_actions, XCSF::nr, and XCSF::pa.
Referenced by XCS::XCS(), xcs_multi_step_exp(), and xcs_single_step_exp().
pa_rand_action()
int pa_rand_action (const XCSF * xcsf)
Returns a random action from the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
A random action.
Definition at line 90 of file pa.c.
References irand_uniform(), XCSF::n_actions, and XCSF::nr.
Referenced by xcs_multi_decision(), and xcs_single_decision().
pa_val()
double pa_val (const XCSF * xcsf, int action)
Returns the value of a specified action in the prediction array.
Parameters
xcsf The XCSF data structure.
action The specified action.
Returns
The value of the action in the prediction array.
Definition at line 121 of file pa.c.
References XCSF::pa.
Referenced by xcs_multi_trial().