XCSF: /home/unknown/work/current/xcsf/xcsf/pa.c File Reference
pa.c File Reference
Prediction array functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "cl_set.h"
#include "pa.h"
Functions
void pa_init (XCSF *xcsf)
Initialises the prediction array.
void pa_build (XCSF *xcsf, SET *set, double *x)
Builds the prediction array for the specified input.
int pa_best_action (XCSF *xcsf)
Returns the best action in the prediction array.
int pa_rand_action (XCSF *xcsf)
Returns a random action from the prediction array.
double pa_best_val (XCSF *xcsf)
Returns the highest value in the prediction array.
double pa_val (XCSF *xcsf, int action)
Returns the value of a specified action in the prediction array.
void pa_free (XCSF *xcsf)
Frees the prediction array.
Detailed Description
Prediction array functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file pa.c.
Function Documentation
pa_best_action()
int pa_best_action (XCSF * xcsf)
Returns the best action in the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
The best action.
Definition at line 76 of file pa.c.
References XCSF::num_actions, and XCSF::pa.
Referenced by xcs_multi_exploit(), xcs_multi_explore(), xcs_single_exploit(), and xcs_single_explore().
pa_best_val()
double pa_best_val (XCSF * xcsf)
Returns the highest value in the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
The highest value in the prediction array.
Definition at line 106 of file pa.c.
References XCSF::num_actions, and XCSF::pa.
Referenced by xcs_multi_exploit(), xcs_multi_explore(), and xcs_single_exploit().
pa_build()
void pa_build (XCSF * xcsf, SET * set, double * x)
Builds the prediction array for the specified input.
Parameters
xcsf The XCSF data structure.
set The set used to construct the array (typically the match set).
x The input state.
Definition at line 50 of file pa.c.
References cl_predict(), CLIST::next, XCSF::nr, XCSF::num_actions, and XCSF::pa.
Referenced by xcs_multi_exploit(), xcs_multi_explore(), xcs_single_exploit(), and xcs_single_explore().
pa_free()
void pa_free (XCSF * xcsf)
Frees the prediction array.
Parameters
xcsf The XCSF data structure.
Definition at line 135 of file pa.c.
References XCSF::nr, and XCSF::pa.
Referenced by xcs_multi_step_exp(), and xcs_single_step_exp().
pa_init()
void pa_init (XCSF * xcsf)
Initialises the prediction array.
Parameters
xcsf The XCSF data structure.
Definition at line 38 of file pa.c.
References XCSF::nr, XCSF::num_actions, and XCSF::pa.
Referenced by xcs_multi_step_exp(), and xcs_single_step_exp().
pa_rand_action()
int pa_rand_action (XCSF * xcsf)
Returns a random action from the prediction array.
Parameters
xcsf The XCSF data structure.
Returns
A random action.
Definition at line 92 of file pa.c.
References irand_uniform(), XCSF::nr, and XCSF::num_actions.
Referenced by xcs_multi_explore(), and xcs_single_explore().
pa_val()
double pa_val (XCSF * xcsf, int action)
Returns the value of a specified action in the prediction array.
Parameters
xcsf The XCSF data structure.
action The specified action.
Returns
The value of the action in the prediction array.
Definition at line 123 of file pa.c.
References XCSF::pa.
Referenced by xcs_multi_exploit().