XCSF: perf.c File Reference
perf.c File Reference
System performance printing and plotting with Gnuplot.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
#include <errno.h>
#include "xcsf.h"
#include "cl.h"
#include "clset.h"
#include "perf.h"
Functions
void gplot_init (const XCSF *xcsf)
Dummy init function if Gnuplot not defined.
void gplot_free (const XCSF *xcsf)
Dummy free function if Gnuplot not defined.
void disp_perf1 (const XCSF *xcsf, double error, int trial)
Displays the current training performance (additionally redraws Gnuplot if defined.)
void disp_perf2 (const XCSF *xcsf, double error, double terror, int trial)
Displays the current training and test performance (additionally redraws Gnuplot if defined.)
Detailed Description
System performance printing and plotting with Gnuplot.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file perf.c.
Function Documentation
disp_perf1()
void disp_perf1 (const XCSF * xcsf, double error, int trial)
Displays the current training performance (additionally redraws Gnuplot if defined.)
Parameters
xcsf The XCSF data structure.
error The current training error.
trial The number of learning trials executed.
Definition at line 232 of file perf.c.
References clset_mean_mut(), XCSF::pset, XCSF::SAM_NUM, and SET::size.
Referenced by xcsf_fit2().
disp_perf2()
void disp_perf2 (const XCSF * xcsf, double error, double terror, int trial)
Displays the current training and test performance (additionally redraws Gnuplot if defined.)
Parameters
xcsf The XCSF data structure.
error The current training error.
terror The current testing error.
trial The number of learning trials executed.
Definition at line 253 of file perf.c.
References clset_mean_mut(), XCSF::pset, XCSF::SAM_NUM, and SET::size.
Referenced by xcs_multi_step_exp(), xcs_single_step_exp(), and xcsf_fit2().
gplot_free()
void gplot_free (const XCSF * xcsf)
Dummy free function if Gnuplot not defined.
Parameters
xcsf The XCSF data structure.
Definition at line 50 of file perf.c.
References clset_mean_mut(), XCSF::COND_TYPE, COND_TYPE_DGP, COND_TYPE_DUMMY, COND_TYPE_GP, COND_TYPE_HYPERELLIPSOID, COND_TYPE_HYPERRECTANGLE, COND_TYPE_NEURAL, COND_TYPE_TERNARY, gplot_free(), gplot_init(), XCSF::num_actions, XCSF::POP_SIZE, XCSF::PRED_TYPE, PRED_TYPE_CONSTANT, PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, PRED_TYPE_RLS_QUADRATIC, XCSF::pset, RULE_TYPE_DGP, RULE_TYPE_NEURAL, XCSF::SAM_NUM, and SET::size.
Referenced by gplot_free(), xcs_multi_step_exp(), xcs_single_step_exp(), and xcsf_fit2().
gplot_init()
void gplot_init (const XCSF * xcsf)
Dummy init function if Gnuplot not defined.
Parameters
xcsf The XCSF data structure.
Definition at line 41 of file perf.c.
Referenced by gplot_free(), xcs_multi_step_exp(), xcs_single_step_exp(), and xcsf_fit2().