XCSF: perf.h File Reference
perf.h File Reference
System performance printing and plotting with Gnuplot.
Functions
void disp_perf1 (XCSF *xcsf, double error, int trial)
void disp_perf2 (XCSF *xcsf, double error, double terror, int trial)
void gplot_init (XCSF *xcsf)
void gplot_free (XCSF *xcsf)
Detailed Description
System performance printing and plotting with Gnuplot.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file perf.h.
Function Documentation
disp_perf1()
void disp_perf1 (XCSF * xcsf, double error, int trial)
Definition at line 189 of file perf.c.
References XCSF::pset, XCSF::SAM_NUM, set_avg_mut(), and SET::size.
Referenced by xcsf_fit1().
disp_perf2()
void disp_perf2 (XCSF * xcsf, double error, double terror, int trial)
Definition at line 202 of file perf.c.
References XCSF::pset, XCSF::SAM_NUM, set_avg_mut(), and SET::size.
Referenced by xcs_multi_step_exp(), xcs_single_step_exp(), and xcsf_fit2().
gplot_free()
void gplot_free (XCSF * xcsf)
Definition at line 42 of file perf.c.
References XCSF::COND_TYPE, gplot_free(), gplot_init(), XCSF::num_actions, XCSF::POP_SIZE, XCSF::PRED_TYPE, XCSF::pset, XCSF::SAM_NUM, set_avg_mut(), and SET::size.
Referenced by gplot_free(), xcs_multi_step_exp(), xcs_single_step_exp(), xcsf_fit1(), and xcsf_fit2().
gplot_init()
void gplot_init (XCSF * xcsf)
Definition at line 37 of file perf.c.
Referenced by gplot_free(), xcs_multi_step_exp(), xcs_single_step_exp(), xcsf_fit1(), and xcsf_fit2().