XCSF: pred_nlms.c File Reference
pred_nlms.c File Reference
Normalised least mean squares prediction functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "xcsf.h"
#include "utils.h"
#include "blas.h"
#include "sam.h"
#include "cl.h"
#include "prediction.h"
#include "pred_nlms.h"
Macros
#define N_MU 1
Number of self-adaptive mutation rates.
#define ETA_MAX 0.1
Maximum gradient descent rate.
#define ETA_MIN 0.0001
Minimum gradient descent rate.
Functions
void pred_nlms_init (const XCSF *xcsf, CL *c)
void pred_nlms_copy (const XCSF *xcsf, CL *dest, const CL *src)
void pred_nlms_free (const XCSF *xcsf, const CL *c)
void pred_nlms_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
void pred_nlms_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_nlms_print (const XCSF *xcsf, const CL *c)
_Bool pred_nlms_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_nlms_mutate (const XCSF *xcsf, const CL *c)
int pred_nlms_size (const XCSF *xcsf, const CL *c)
size_t pred_nlms_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t pred_nlms_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Normalised least mean squares prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pred_nlms.c.
Macro Definition Documentation
ETA_MAX
#define ETA_MAX 0.1
Maximum gradient descent rate.
Definition at line 37 of file pred_nlms.c.
Referenced by pred_nlms_init(), and pred_nlms_mutate().
ETA_MIN
#define ETA_MIN 0.0001
Minimum gradient descent rate.
Definition at line 38 of file pred_nlms.c.
Referenced by pred_nlms_init(), and pred_nlms_mutate().
N_MU
#define N_MU 1
Number of self-adaptive mutation rates.
Definition at line 36 of file pred_nlms.c.
Referenced by pred_nlms_copy(), pred_nlms_init(), pred_nlms_load(), pred_nlms_mutate(), and pred_nlms_save().
Function Documentation
pred_nlms_compute()
void pred_nlms_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 105 of file pred_nlms.c.
References blas_dot(), PRED_NLMS::n, CL::pred, pred_transform_input(), CL::prediction, PRED_NLMS::tmp_input, PRED_NLMS::weights, and XCSF::y_dim.
pred_nlms_copy()
void pred_nlms_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 70 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, N_MU, PRED_NLMS::n_weights, CL::pred, pred_nlms_init(), and PRED_NLMS::weights.
pred_nlms_crossover()
_Bool pred_nlms_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 128 of file pred_nlms.c.
pred_nlms_free()
void pred_nlms_free (const XCSF * xcsf, const CL * c)
Definition at line 80 of file pred_nlms.c.
References PRED_NLMS::mu, CL::pred, PRED_NLMS::tmp_input, and PRED_NLMS::weights.
pred_nlms_init()
void pred_nlms_init (const XCSF * xcsf, CL * c)
Definition at line 40 of file pred_nlms.c.
References blas_fill(), PRED_NLMS::eta, ETA_MAX, ETA_MIN, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_TYPE, PRED_TYPE_NLMS_QUADRATIC, XCSF::PRED_X0, rand_uniform(), sam_init(), PRED_NLMS::tmp_input, PRED_NLMS::weights, XCSF::x_dim, and XCSF::y_dim.
Referenced by pred_nlms_copy(), and pred_nlms_load().
pred_nlms_load()
size_t pred_nlms_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 169 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, pred_nlms_init(), and PRED_NLMS::weights.
pred_nlms_mutate()
_Bool pred_nlms_mutate (const XCSF * xcsf, const CL * c)
Definition at line 134 of file pred_nlms.c.
References clamp(), PRED_NLMS::eta, ETA_MAX, ETA_MIN, PRED_NLMS::mu, N_MU, CL::pred, XCSF::PRED_EVOLVE_ETA, rand_normal(), and sam_adapt().
pred_nlms_print()
void pred_nlms_print (const XCSF * xcsf, const CL * c)
Definition at line 115 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::n, CL::pred, PRED_NLMS::weights, and XCSF::y_dim.
pred_nlms_save()
size_t pred_nlms_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 156 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, and PRED_NLMS::weights.
pred_nlms_size()
int pred_nlms_size (const XCSF * xcsf, const CL * c)
Definition at line 149 of file pred_nlms.c.
References PRED_NLMS::n_weights, and CL::pred.
pred_nlms_update()
void pred_nlms_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 90 of file pred_nlms.c.
References blas_axpy(), blas_dot(), PRED_NLMS::eta, PRED_NLMS::n, CL::pred, XCSF::PRED_X0, CL::prediction, PRED_NLMS::tmp_input, PRED_NLMS::weights, XCSF::x_dim, and XCSF::y_dim.