XCSF: pred_rls.c File Reference
pred_rls.c File Reference
Recursive least mean squares prediction functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "prediction.h"
#include "pred_rls.h"
Data Structures
struct PRED_RLS
Recursive least mean squares prediction data structure.
Typedefs
typedef struct PRED_RLS PRED_RLS
Recursive least mean squares prediction data structure.
Functions
static void matrix_matrix_multiply (const double *srca, const double *srcb, double *dest, int n)
static void matrix_vector_multiply (const double *srcm, const double *srcv, double *dest, int n)
static void init_matrix (const XCSF *xcsf, double *matrix, int n)
void pred_rls_init (const XCSF *xcsf, CL *c)
void pred_rls_copy (const XCSF *xcsf, CL *to, const CL *from)
void pred_rls_free (const XCSF *xcsf, const CL *c)
void pred_rls_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
const double * pred_rls_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_rls_print (const XCSF *xcsf, const CL *c)
_Bool pred_rls_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_rls_mutate (const XCSF *xcsf, const CL *c)
int pred_rls_size (const XCSF *xcsf, const CL *c)
size_t pred_rls_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t pred_rls_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Recursive least mean squares prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pred_rls.c.
Typedef Documentation
PRED_RLS
typedef struct PRED_RLS PRED_RLS
Recursive least mean squares prediction data structure.
Function Documentation
init_matrix()
static void init_matrix (const XCSF * xcsf, double * matrix, int n) static
Definition at line 87 of file pred_rls.c.
References XCSF::PRED_RLS_SCALE_FACTOR.
Referenced by pred_rls_init().
matrix_matrix_multiply()
static void matrix_matrix_multiply (const double * srca, const double * srcb, double * dest, int n) static
Definition at line 220 of file pred_rls.c.
Referenced by pred_rls_update().
matrix_vector_multiply()
static void matrix_vector_multiply (const double * srcm, const double * srcv, double * dest, int n) static
Definition at line 232 of file pred_rls.c.
Referenced by pred_rls_update().
pred_rls_compute()
const double* pred_rls_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 184 of file pred_rls.c.
References CL::pred, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, CL::prediction, PRED_RLS::weights, XCSF::x_dim, and XCSF::y_dim.
pred_rls_copy()
void pred_rls_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 101 of file pred_rls.c.
References CL::pred, pred_rls_init(), PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_crossover()
_Bool pred_rls_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 242 of file pred_rls.c.
pred_rls_free()
void pred_rls_free (const XCSF * xcsf, const CL * c)
Definition at line 112 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, and XCSF::y_dim.
pred_rls_init()
void pred_rls_init (const XCSF * xcsf, CL * c)
Definition at line 52 of file pred_rls.c.
References init_matrix(), PRED_RLS::matrix, CL::pred, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, PRED_RLS::weights_length, XCSF::x_dim, and XCSF::y_dim.
Referenced by pred_rls_copy(), and pred_rls_load().
pred_rls_load()
size_t pred_rls_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 274 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, pred_rls_init(), PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_mutate()
_Bool pred_rls_mutate (const XCSF * xcsf, const CL * c)
Definition at line 248 of file pred_rls.c.
pred_rls_print()
void pred_rls_print (const XCSF * xcsf, const CL * c)
Definition at line 208 of file pred_rls.c.
References CL::pred, PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_save()
size_t pred_rls_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 261 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_size()
int pred_rls_size (const XCSF * xcsf, const CL * c)
Definition at line 254 of file pred_rls.c.
References CL::pred, and PRED_RLS::weights_length.
pred_rls_update()
void pred_rls_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 127 of file pred_rls.c.
References PRED_RLS::matrix, matrix_matrix_multiply(), matrix_vector_multiply(), CL::pred, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, CL::prediction, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, PRED_RLS::weights_length, XCSF::x_dim, and XCSF::y_dim.