XCSF: prediction.h File Reference
prediction.h File Reference
Interface for classifier predictions.
Data Structures
struct PredVtbl
Prediction interface data structure.
Functions
void prediction_set (const XCSF *xcsf, CL *c)
Sets a classifier's prediction functions to the implementations.
static size_t pred_save (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the prediction to a binary file.
static size_t pred_load (const XCSF *xcsf, CL *c, FILE *fp)
Reads the prediction from a binary file.
static int pred_size (const XCSF *xcsf, const CL *c)
Returns the size of the classifier prediction.
static _Bool pred_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier prediction crossover.
static _Bool pred_mutate (const XCSF *xcsf, const CL *c)
Performs classifier prediction mutation.
static void pred_compute (const XCSF *xcsf, const CL *c, const double *x)
Computes the current classifier prediction using the input.
static void pred_copy (const XCSF *xcsf, CL *dest, const CL *src)
Copies the prediction from one classifier to another.
static void pred_free (const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier prediction.
static void pred_init (const XCSF *xcsf, CL *c)
Initialises a classifier's prediction.
static void pred_print (const XCSF *xcsf, const CL *c)
Prints the classifier prediction.
static void pred_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Updates the classifier's prediction.
static void pred_transform_input (const XCSF *xcsf, const double *x, double *tmp_input)
Prepares the input state for least squares computation.
Detailed Description
Interface for classifier predictions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file prediction.h.
Function Documentation
pred_compute()
static void pred_compute (const XCSF * xcsf, const CL * c, const double * x) inline static
Computes the current classifier prediction using the input.
Parameters
xcsf The XCSF data structure.
c The classifier calculating the prediction.
x The input state.
Definition at line 105 of file prediction.h.
References PredVtbl::pred_impl_compute, and CL::pred_vptr.
Referenced by cl_predict().
pred_copy()
static void pred_copy (const XCSF * xcsf, CL * dest, const CL * src) inline static
Copies the prediction from one classifier to another.
Parameters
xcsf The XCSF data structure.
dest The destination classifier.
src The source classifier.
Definition at line 115 of file prediction.h.
References PredVtbl::pred_impl_copy, and CL::pred_vptr.
Referenced by cl_copy().
pred_crossover()
static _Bool pred_crossover (const XCSF * xcsf, const CL * c1, const CL * c2) inline static
Performs classifier prediction crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier whose prediction is being crossed.
c2 The second classifier whose prediction is being crossed.
Returns
Whether any alterations were made.
Definition at line 85 of file prediction.h.
References PredVtbl::pred_impl_crossover, and CL::pred_vptr.
Referenced by cl_crossover().
pred_free()
static void pred_free (const XCSF * xcsf, const CL * c) inline static
Frees the memory used by the classifier prediction.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be freed.
Definition at line 124 of file prediction.h.
References PredVtbl::pred_impl_free, and CL::pred_vptr.
Referenced by cl_free().
pred_init()
static void pred_init (const XCSF * xcsf, CL * c) inline static
Initialises a classifier's prediction.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be initialised.
Definition at line 133 of file prediction.h.
References PredVtbl::pred_impl_init, and CL::pred_vptr.
Referenced by cl_copy(), and cl_rand().
pred_load()
static size_t pred_load (const XCSF * xcsf, CL * c, FILE * fp) inline static
Reads the prediction from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 64 of file prediction.h.
References PredVtbl::pred_impl_load, and CL::pred_vptr.
Referenced by cl_load().
pred_mutate()
static _Bool pred_mutate (const XCSF * xcsf, const CL * c) inline static
Performs classifier prediction mutation.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is being mutated.
Returns
Whether any alterations were made.
Definition at line 95 of file prediction.h.
References PredVtbl::pred_impl_mutate, and CL::pred_vptr.
Referenced by cl_mutate().
pred_print()
static void pred_print (const XCSF * xcsf, const CL * c) inline static
Prints the classifier prediction.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be printed.
Definition at line 142 of file prediction.h.
References PredVtbl::pred_impl_print, and CL::pred_vptr.
Referenced by cl_print().
pred_save()
static size_t pred_save (const XCSF * xcsf, const CL * c, FILE * fp) inline static
Writes the prediction to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 53 of file prediction.h.
References PredVtbl::pred_impl_save, and CL::pred_vptr.
Referenced by cl_save().
pred_size()
static int pred_size (const XCSF * xcsf, const CL * c) inline static
Returns the size of the classifier prediction.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction size to return.
Returns
The size of the prediction.
Definition at line 74 of file prediction.h.
References PredVtbl::pred_impl_size, and CL::pred_vptr.
Referenced by cl_pred_size().
pred_transform_input()
static void pred_transform_input (const XCSF * xcsf, const double * x, double * tmp_input) inline static
Prepares the input state for least squares computation.
Parameters
xcsf The XCSF data structure.
x The input state.
tmp_input The transformed input (set by this function).
Definition at line 164 of file prediction.h.
References XCSF::PRED_TYPE, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, and XCSF::x_dim.
Referenced by pred_nlms_compute(), and pred_rls_compute().
pred_update()
static void pred_update (const XCSF * xcsf, const CL * c, const double * x, const double * y) inline static
Updates the classifier's prediction.
Assumes the prediction has been computed for the current state.
Parameters
xcsf The XCSF data structure.
c The classifier whose prediction is to be updated.
x The input state.
y The payoff value.
Definition at line 154 of file prediction.h.
References PredVtbl::pred_impl_update, and CL::pred_vptr.
Referenced by cl_update().
prediction_set()
void prediction_set (const XCSF * xcsf, CL * c)
Sets a classifier's prediction functions to the implementations.
Parameters
xcsf The XCSF data structure.
c The classifier to set.
Definition at line 41 of file prediction.c.
References pred_constant_vtbl, pred_neural_vtbl, pred_nlms_vtbl, pred_rls_vtbl, XCSF::PRED_TYPE, PRED_TYPE_CONSTANT, PRED_TYPE_NEURAL, PRED_TYPE_NLMS_LINEAR, PRED_TYPE_NLMS_QUADRATIC, PRED_TYPE_RLS_LINEAR, PRED_TYPE_RLS_QUADRATIC, and CL::pred_vptr.
Referenced by cl_load(), and cl_rand().