XCSF: pred_neural.h File Reference
pred_neural.h File Reference
Multi-layer perceptron neural network prediction functions.
Functions
_Bool pred_neural_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_neural_mutate (const XCSF *xcsf, const CL *c)
double pred_neural_eta (const XCSF *xcsf, const CL *c, int layer)
int pred_neural_layers (const XCSF *xcsf, const CL *c)
int pred_neural_neurons (const XCSF *xcsf, const CL *c, int layer)
int pred_neural_size (const XCSF *xcsf, const CL *c)
size_t pred_neural_load (const XCSF *xcsf, CL *c, FILE *fp)
size_t pred_neural_save (const XCSF *xcsf, const CL *c, FILE *fp)
void pred_neural_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_neural_copy (const XCSF *xcsf, CL *to, const CL *from)
void pred_neural_free (const XCSF *xcsf, const CL *c)
void pred_neural_init (const XCSF *xcsf, CL *c)
void pred_neural_print (const XCSF *xcsf, const CL *c)
void pred_neural_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
void pred_neural_expand (const XCSF *xcsf, const CL *c)
Variables
static struct PredVtbl const pred_neural_vtbl
Multi-layer perceptron neural network prediction implemented functions.
Detailed Description
Multi-layer perceptron neural network prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file pred_neural.h.
Function Documentation
pred_neural_compute()
void pred_neural_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 125 of file pred_neural.c.
References PRED_NEURAL::net, neural_output(), neural_propagate(), CL::pred, CL::prediction, and XCSF::y_dim.
pred_neural_copy()
void pred_neural_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 109 of file pred_neural.c.
References PRED_NEURAL::net, neural_copy(), and CL::pred.
pred_neural_crossover()
_Bool pred_neural_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 140 of file pred_neural.c.
pred_neural_eta()
double pred_neural_eta (const XCSF * xcsf, const CL * c, int layer)
Definition at line 173 of file pred_neural.c.
References PRED_NEURAL::net, CL::pred, LLIST::prev, and NET::tail.
Referenced by clset_mean_eta().
pred_neural_expand()
void pred_neural_expand (const XCSF * xcsf, const CL * c)
Definition at line 210 of file pred_neural.c.
References NET::head, irand_uniform(), LLIST::layer, layer_resize(), LAYER::n_inputs, NET::n_layers, LAYER::n_outputs, PRED_NEURAL::net, neural_layer_connected_init(), neural_layer_insert(), CL::pred, XCSF::PRED_HIDDEN_ACTIVATION, pred_neural_lopt(), LLIST::prev, and NET::tail.
pred_neural_free()
void pred_neural_free (const XCSF * xcsf, const CL * c)
Definition at line 102 of file pred_neural.c.
References PRED_NEURAL::net, neural_free(), and CL::pred.
pred_neural_init()
void pred_neural_init (const XCSF * xcsf, CL * c)
Definition at line 52 of file pred_neural.c.
References LAYER_EVOLVE_NEURONS, neural_init(), neural_layer_connected_init(), neural_layer_insert(), CL::pred, XCSF::PRED_HIDDEN_ACTIVATION, XCSF::PRED_MAX_NEURONS, pred_neural_lopt(), XCSF::PRED_NUM_NEURONS, XCSF::PRED_OUTPUT_ACTIVATION, XCSF::x_dim, and XCSF::y_dim.
pred_neural_layers()
int pred_neural_layers (const XCSF * xcsf, const CL * c)
Definition at line 202 of file pred_neural.c.
References NET::n_layers, PRED_NEURAL::net, and CL::pred.
Referenced by clset_mean_layers().
pred_neural_load()
size_t pred_neural_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 165 of file pred_neural.c.
References neural_load(), and CL::pred.
pred_neural_mutate()
_Bool pred_neural_mutate (const XCSF * xcsf, const CL * c)
Definition at line 146 of file pred_neural.c.
References PRED_NEURAL::net, neural_mutate(), and CL::pred.
pred_neural_neurons()
int pred_neural_neurons (const XCSF * xcsf, const CL * c, int layer)
Definition at line 187 of file pred_neural.c.
References NET::n_outputs, PRED_NEURAL::net, CL::pred, LLIST::prev, and NET::tail.
Referenced by clset_mean_neurons().
pred_neural_print()
void pred_neural_print (const XCSF * xcsf, const CL * c)
Definition at line 134 of file pred_neural.c.
References PRED_NEURAL::net, neural_print(), and CL::pred.
pred_neural_save()
size_t pred_neural_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 158 of file pred_neural.c.
References PRED_NEURAL::net, neural_save(), and CL::pred.
pred_neural_size()
int pred_neural_size (const XCSF * xcsf, const CL * c)
Definition at line 152 of file pred_neural.c.
References PRED_NEURAL::net, neural_size(), and CL::pred.
pred_neural_update()
void pred_neural_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 117 of file pred_neural.c.
References PRED_NEURAL::net, neural_learn(), CL::pred, and XCSF::PRED_SGD_WEIGHTS.
Variable Documentation
pred_neural_vtbl
struct PredVtbl const pred_neural_vtbl static
Initial value:
= {
    &pred_neural_crossover,
    &pred_neural_mutate,
    &pred_neural_compute,
    &pred_neural_copy,
    &pred_neural_free,
    &pred_neural_init,
    &pred_neural_print,
    &pred_neural_update,
    &pred_neural_size,
    &pred_neural_save,
    &pred_neural_load
}
Multi-layer perceptron neural network prediction implemented functions.
Definition at line 45 of file pred_neural.h.
Referenced by prediction_set().