XCSF: pred_nlms.h File Reference
pred_nlms.h File Reference
Normalised least mean squares prediction functions.
Functions
_Bool pred_nlms_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_nlms_mutate (const XCSF *xcsf, const CL *c)
int pred_nlms_size (const XCSF *xcsf, const CL *c)
size_t pred_nlms_load (const XCSF *xcsf, CL *c, FILE *fp)
size_t pred_nlms_save (const XCSF *xcsf, const CL *c, FILE *fp)
void pred_nlms_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_nlms_copy (const XCSF *xcsf, CL *dest, const CL *src)
void pred_nlms_free (const XCSF *xcsf, const CL *c)
void pred_nlms_init (const XCSF *xcsf, CL *c)
void pred_nlms_print (const XCSF *xcsf, const CL *c)
void pred_nlms_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Variables
static struct PredVtbl const pred_nlms_vtbl
Normalised least mean squares prediction implemented functions.
Detailed Description
Normalised least mean squares prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pred_nlms.h.
Function Documentation
pred_nlms_compute()
void pred_nlms_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 115 of file pred_nlms.c.
References blas_dot(), PRED_NLMS::n, CL::pred, pred_transform_input(), CL::prediction, PRED_NLMS::tmp_input, PRED_NLMS::weights, and XCSF::y_dim.
pred_nlms_copy()
void pred_nlms_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 81 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, N_MU, PRED_NLMS::n_weights, CL::pred, pred_nlms_init(), and PRED_NLMS::weights.
pred_nlms_crossover()
_Bool pred_nlms_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 138 of file pred_nlms.c.
pred_nlms_free()
void pred_nlms_free (const XCSF * xcsf, const CL * c)
Definition at line 91 of file pred_nlms.c.
References CL::pred, PRED_NLMS::tmp_input, and PRED_NLMS::weights.
pred_nlms_init()
void pred_nlms_init (const XCSF * xcsf, CL * c)
Definition at line 52 of file pred_nlms.c.
References blas_fill(), PRED_NLMS::eta, ETA_MAX, ETA_MIN, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_TYPE, PRED_TYPE_NLMS_QUADRATIC, XCSF::PRED_X0, rand_uniform(), sam_init(), PRED_NLMS::tmp_input, PRED_NLMS::weights, XCSF::x_dim, and XCSF::y_dim.
Referenced by pred_nlms_copy(), and pred_nlms_load().
pred_nlms_load()
size_t pred_nlms_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 179 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, pred_nlms_init(), and PRED_NLMS::weights.
pred_nlms_mutate()
_Bool pred_nlms_mutate (const XCSF * xcsf, const CL * c)
Definition at line 144 of file pred_nlms.c.
References constrain(), PRED_NLMS::eta, ETA_MAX, ETA_MIN, PRED_NLMS::mu, N_MU, CL::pred, XCSF::PRED_EVOLVE_ETA, rand_normal(), and sam_adapt().
pred_nlms_print()
void pred_nlms_print (const XCSF * xcsf, const CL * c)
Definition at line 125 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::n, CL::pred, PRED_NLMS::weights, and XCSF::y_dim.
pred_nlms_save()
size_t pred_nlms_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 166 of file pred_nlms.c.
References PRED_NLMS::eta, PRED_NLMS::mu, PRED_NLMS::n, N_MU, PRED_NLMS::n_weights, CL::pred, and PRED_NLMS::weights.
pred_nlms_size()
int pred_nlms_size (const XCSF * xcsf, const CL * c)
Definition at line 159 of file pred_nlms.c.
References PRED_NLMS::n_weights, and CL::pred.
pred_nlms_update()
void pred_nlms_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 100 of file pred_nlms.c.
References blas_axpy(), blas_dot(), PRED_NLMS::eta, PRED_NLMS::n, CL::pred, XCSF::PRED_X0, CL::prediction, PRED_NLMS::tmp_input, PRED_NLMS::weights, XCSF::x_dim, and XCSF::y_dim.
Variable Documentation
pred_nlms_vtbl
struct PredVtbl const pred_nlms_vtbl static
Initial value:
= {
    &pred_nlms_crossover,
    &pred_nlms_mutate,
    &pred_nlms_compute,
    &pred_nlms_copy,
    &pred_nlms_free,
    &pred_nlms_init,
    &pred_nlms_print,
    &pred_nlms_update,
    &pred_nlms_size,
    &pred_nlms_save,
    &pred_nlms_load
}
Normalised least mean squares prediction implemented functions.
Definition at line 41 of file pred_nlms.h.
Referenced by prediction_set().