XCSF: pred_rls.h File Reference
pred_rls.h File Reference
Recursive least mean squares prediction functions.
Functions
_Bool pred_rls_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_rls_mutate (const XCSF *xcsf, const CL *c)
int pred_rls_size (const XCSF *xcsf, const CL *c)
size_t pred_rls_load (const XCSF *xcsf, CL *c, FILE *fp)
size_t pred_rls_save (const XCSF *xcsf, const CL *c, FILE *fp)
void pred_rls_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_rls_copy (const XCSF *xcsf, CL *to, const CL *from)
void pred_rls_free (const XCSF *xcsf, const CL *c)
void pred_rls_init (const XCSF *xcsf, CL *c)
void pred_rls_print (const XCSF *xcsf, const CL *c)
void pred_rls_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Variables
static struct PredVtbl const pred_rls_vtbl
Recursive least mean squares prediction implemented functions.
Detailed Description
Recursive least mean squares prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file pred_rls.h.
Function Documentation
pred_rls_compute()
void pred_rls_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 184 of file pred_rls.c.
References CL::pred, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, CL::prediction, PRED_RLS::weights, XCSF::x_dim, and XCSF::y_dim.
pred_rls_copy()
void pred_rls_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 101 of file pred_rls.c.
References CL::pred, pred_rls_init(), PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_crossover()
_Bool pred_rls_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 241 of file pred_rls.c.
pred_rls_free()
void pred_rls_free (const XCSF * xcsf, const CL * c)
Definition at line 112 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, and XCSF::y_dim.
pred_rls_init()
void pred_rls_init (const XCSF * xcsf, CL * c)
Definition at line 52 of file pred_rls.c.
References init_matrix(), PRED_RLS::matrix, CL::pred, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, PRED_RLS::weights_length, XCSF::x_dim, and XCSF::y_dim.
Referenced by pred_rls_copy(), and pred_rls_load().
pred_rls_load()
size_t pred_rls_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 273 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, pred_rls_init(), PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_mutate()
_Bool pred_rls_mutate (const XCSF * xcsf, const CL * c)
Definition at line 247 of file pred_rls.c.
pred_rls_print()
void pred_rls_print (const XCSF * xcsf, const CL * c)
Definition at line 207 of file pred_rls.c.
References CL::pred, PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_save()
size_t pred_rls_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 260 of file pred_rls.c.
References PRED_RLS::matrix, CL::pred, PRED_RLS::weights, PRED_RLS::weights_length, and XCSF::y_dim.
pred_rls_size()
int pred_rls_size (const XCSF * xcsf, const CL * c)
Definition at line 253 of file pred_rls.c.
References CL::pred, and PRED_RLS::weights_length.
pred_rls_update()
void pred_rls_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 127 of file pred_rls.c.
References PRED_RLS::matrix, matrix_matrix_multiply(), matrix_vector_multiply(), CL::pred, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_TYPE, PRED_TYPE_RLS_QUADRATIC, XCSF::PRED_X0, CL::prediction, PRED_RLS::tmp_input, PRED_RLS::tmp_matrix1, PRED_RLS::tmp_matrix2, PRED_RLS::tmp_vec, PRED_RLS::weights, PRED_RLS::weights_length, XCSF::x_dim, and XCSF::y_dim.
Variable Documentation
pred_rls_vtbl
struct PredVtbl const pred_rls_vtbl static
Initial value:
= {
    &pred_rls_crossover,
    &pred_rls_mutate,
    &pred_rls_compute,
    &pred_rls_copy,
    &pred_rls_free,
    &pred_rls_init,
    &pred_rls_print,
    &pred_rls_update,
    &pred_rls_size,
    &pred_rls_save,
    &pred_rls_load
}
Recursive least mean squares prediction implemented functions.
Definition at line 41 of file pred_rls.h.
Referenced by prediction_set().