XCSF: pred_neural.c File Reference
pred_neural.c File Reference
Multi-layer perceptron neural network prediction functions.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "neural_activations.h"
#include "neural.h"
#include "neural_layer.h"
#include "neural_layer_connected.h"
#include "neural_layer_dropout.h"
#include "neural_layer_noise.h"
#include "neural_layer_softmax.h"
#include "prediction.h"
#include "pred_neural.h"
Data Structures
struct PRED_NEURAL
Multi-layer perceptron neural network prediction data structure.
Typedefs
typedef struct PRED_NEURAL PRED_NEURAL
Multi-layer perceptron neural network prediction data structure.
Functions
static uint32_t pred_neural_lopt (const XCSF *xcsf)
void pred_neural_init (const XCSF *xcsf, CL *c)
void pred_neural_free (const XCSF *xcsf, const CL *c)
void pred_neural_copy (const XCSF *xcsf, CL *to, const CL *from)
void pred_neural_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
const double * pred_neural_compute (const XCSF *xcsf, const CL *c, const double *x)
void pred_neural_print (const XCSF *xcsf, const CL *c)
_Bool pred_neural_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool pred_neural_mutate (const XCSF *xcsf, const CL *c)
int pred_neural_size (const XCSF *xcsf, const CL *c)
size_t pred_neural_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t pred_neural_load (const XCSF *xcsf, CL *c, FILE *fp)
double pred_neural_eta (const XCSF *xcsf, const CL *c, int layer)
int pred_neural_neurons (const XCSF *xcsf, const CL *c, int layer)
int pred_neural_layers (const XCSF *xcsf, const CL *c)
Detailed Description
Multi-layer perceptron neural network prediction functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
Definition in file pred_neural.c.
Typedef Documentation
PRED_NEURAL
typedef struct PRED_NEURAL PRED_NEURAL
Multi-layer perceptron neural network prediction data structure.
Function Documentation
pred_neural_compute()
const double* pred_neural_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 125 of file pred_neural.c.
References PRED_NEURAL::net, neural_output(), neural_propagate(), CL::pred, CL::prediction, and XCSF::y_dim.
pred_neural_copy()
void pred_neural_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 109 of file pred_neural.c.
References PRED_NEURAL::net, neural_copy(), and CL::pred.
pred_neural_crossover()
_Bool pred_neural_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 141 of file pred_neural.c.
pred_neural_eta()
double pred_neural_eta (const XCSF * xcsf, const CL * c, int layer)
Definition at line 174 of file pred_neural.c.
References PRED_NEURAL::net, CL::pred, LLIST::prev, and NET::tail.
Referenced by clset_mean_eta().
pred_neural_free()
void pred_neural_free (const XCSF * xcsf, const CL * c)
Definition at line 102 of file pred_neural.c.
References PRED_NEURAL::net, neural_free(), and CL::pred.
pred_neural_init()
void pred_neural_init (const XCSF * xcsf, CL * c)
Definition at line 52 of file pred_neural.c.
References LAYER_EVOLVE_NEURONS, neural_init(), neural_layer_connected_init(), neural_layer_insert(), CL::pred, XCSF::PRED_HIDDEN_ACTIVATION, XCSF::PRED_MAX_NEURONS, pred_neural_lopt(), XCSF::PRED_NUM_NEURONS, XCSF::PRED_OUTPUT_ACTIVATION, XCSF::x_dim, and XCSF::y_dim.
pred_neural_layers()
int pred_neural_layers (const XCSF * xcsf, const CL * c)
Definition at line 204 of file pred_neural.c.
References PRED_NEURAL::net, NET::num_layers, and CL::pred.
Referenced by clset_mean_layers().
pred_neural_load()
size_t pred_neural_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 166 of file pred_neural.c.
References neural_load(), and CL::pred.
pred_neural_lopt()
static uint32_t pred_neural_lopt (const XCSF * xcsf) static
Definition at line 81 of file pred_neural.c.
References LAYER_EVOLVE_ETA, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, LAYER_SGD_WEIGHTS, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, and XCSF::PRED_SGD_WEIGHTS.
Referenced by pred_neural_init().
pred_neural_mutate()
_Bool pred_neural_mutate (const XCSF * xcsf, const CL * c)
Definition at line 147 of file pred_neural.c.
References PRED_NEURAL::net, neural_mutate(), and CL::pred.
pred_neural_neurons()
int pred_neural_neurons (const XCSF * xcsf, const CL * c, int layer)
Definition at line 189 of file pred_neural.c.
References PRED_NEURAL::net, NET::num_outputs, CL::pred, LLIST::prev, and NET::tail.
Referenced by clset_mean_neurons().
pred_neural_print()
void pred_neural_print (const XCSF * xcsf, const CL * c)
Definition at line 135 of file pred_neural.c.
References PRED_NEURAL::net, neural_print(), and CL::pred.
pred_neural_save()
size_t pred_neural_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 159 of file pred_neural.c.
References PRED_NEURAL::net, neural_save(), and CL::pred.
pred_neural_size()
int pred_neural_size (const XCSF * xcsf, const CL * c)
Definition at line 153 of file pred_neural.c.
References PRED_NEURAL::net, neural_size(), and CL::pred.
pred_neural_update()
void pred_neural_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 117 of file pred_neural.c.
References PRED_NEURAL::net, neural_learn(), CL::pred, and XCSF::PRED_SGD_WEIGHTS.