XCSF: pybind_wrapper.cpp File Reference
pybind_wrapper.cpp File Reference
Python library wrapper functions.
#include "../pybind11/include/pybind11/pybind11.h"
#include "../pybind11/include/pybind11/numpy.h"
#include <stdbool.h>
#include "xcsf.h"
#include "xcs_single_step.h"
#include "pa.h"
#include "config.h"
#include "utils.h"
#include "loss.h"
#include "clset.h"
Data Structures
class XCS
Functions
void xcs_init (const char *filename)
static void pybind11_init_xcsf (pybind11::module &)
static PyObject * pybind11_init_wrapper ()
C __attribute__ ((visibility("default"))) void initxcsf()
Detailed Description
Python library wrapper functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2020.
Definition in file pybind_wrapper.cpp.
Function Documentation
__attribute__()
C __attribute__ ((visibility("default")))
Definition at line 468 of file pybind_wrapper.cpp.
pybind11_init_wrapper()
PyObject * pybind11_init_wrapper () static
Definition at line 468 of file pybind_wrapper.cpp.
pybind11_init_xcsf()
void pybind11_init_xcsf (pybind11::module & m) static
Definition at line 468 of file pybind_wrapper.cpp.
References XCS::fit(), XCS::get_act_type(), XCS::get_alpha(), XCS::get_beta(), XCS::get_cond_bits(), XCS::get_cond_eta(), XCS::get_cond_evolve_functions(), XCS::get_cond_evolve_neurons(), XCS::get_cond_evolve_weights(), XCS::get_cond_hidden_activation(), XCS::get_cond_max_neurons(), XCS::get_cond_num_neurons(), XCS::get_cond_output_activation(), XCS::get_cond_smin(), XCS::get_cond_type(), XCS::get_delta(), XCS::get_dgp_num_nodes(), XCS::get_ea_select_size(), XCS::get_ea_select_type(), XCS::get_ea_subsumption(), XCS::get_eps_0(), XCS::get_err_reduc(), XCS::get_fit_reduc(), XCS::get_gamma(), XCS::get_gp_init_depth(), XCS::get_gp_num_cons(), XCS::get_init_error(), XCS::get_init_fitness(), XCS::get_lambda(), XCS::get_loss_func(), XCS::get_m_probation(), XCS::get_max_con(), XCS::get_max_k(), XCS::get_max_neuron_mod(), XCS::get_max_t(), XCS::get_max_trials(), XCS::get_mfrac(), XCS::get_min_con(), XCS::get_msetsize(), XCS::get_n_actions(), XCS::get_nu(), XCS::get_omp_num_threads(), XCS::get_p_crossover(), XCS::get_p_explore(), XCS::get_perf_trials(), XCS::get_pop_init(), XCS::get_pop_max_size(), XCS::get_pop_mean_cond_size(), XCS::get_pop_mean_pred_eta(), XCS::get_pop_mean_pred_layers(), XCS::get_pop_mean_pred_neurons(), XCS::get_pop_mean_pred_size(), XCS::get_pop_num(), XCS::get_pop_size(), XCS::get_pred_eta(), XCS::get_pred_evolve_eta(), XCS::get_pred_evolve_functions(), XCS::get_pred_evolve_neurons(), XCS::get_pred_evolve_weights(), XCS::get_pred_hidden_activation(), XCS::get_pred_max_neurons(), XCS::get_pred_momentum(), XCS::get_pred_num_neurons(), XCS::get_pred_output_activation(), XCS::get_pred_reset(), XCS::get_pred_rls_lambda(), XCS::get_pred_rls_scale_factor(), XCS::get_pred_sgd_weights(), XCS::get_pred_type(), XCS::get_pred_x0(), XCS::get_reset_states(), XCS::get_sam_type(), XCS::get_set_subsumption(), XCS::get_teletransportation(), XCS::get_theta_del(), XCS::get_theta_ea(), XCS::get_theta_sub(), XCS::get_time(), XCS::get_x_dim(), XCS::get_y_dim(), XCS::load(), XCS::predict(), XCS::print_pop(), random_init(), XCS::save(), XCS::score(), XCS::set_act_type(), XCS::set_alpha(), XCS::set_beta(), XCS::set_cond_bits(), XCS::set_cond_eta(), XCS::set_cond_evolve_functions(), XCS::set_cond_evolve_neurons(), XCS::set_cond_evolve_weights(), XCS::set_cond_hidden_activation(), XCS::set_cond_max_neurons(), XCS::set_cond_num_neurons(), XCS::set_cond_output_activation(), XCS::set_cond_smin(), XCS::set_cond_type(), XCS::set_delta(), XCS::set_dgp_num_nodes(), XCS::set_ea_select_size(), XCS::set_ea_select_type(), XCS::set_ea_subsumption(), XCS::set_eps_0(), XCS::set_err_reduc(), XCS::set_fit_reduc(), XCS::set_gamma(), XCS::set_gp_init_depth(), XCS::set_gp_num_cons(), XCS::set_init_error(), XCS::set_init_fitness(), XCS::set_lambda(), XCS::set_loss_func(), XCS::set_m_probation(), XCS::set_max_con(), XCS::set_max_k(), XCS::set_max_neuron_mod(), XCS::set_max_t(), XCS::set_max_trials(), XCS::set_min_con(), XCS::set_nu(), XCS::set_omp_num_threads(), XCS::set_p_crossover(), XCS::set_p_explore(), XCS::set_perf_trials(), XCS::set_pop_init(), XCS::set_pop_max_size(), XCS::set_pred_eta(), XCS::set_pred_evolve_eta(), XCS::set_pred_evolve_functions(), XCS::set_pred_evolve_neurons(), XCS::set_pred_evolve_weights(), XCS::set_pred_hidden_activation(), XCS::set_pred_max_neurons(), XCS::set_pred_momentum(), XCS::set_pred_num_neurons(), XCS::set_pred_output_activation(), XCS::set_pred_reset(), XCS::set_pred_rls_lambda(), XCS::set_pred_rls_scale_factor(), XCS::set_pred_sgd_weights(), XCS::set_pred_type(), XCS::set_pred_x0(), XCS::set_reset_states(), XCS::set_sam_type(), XCS::set_set_subsumption(), XCS::set_teletransportation(), XCS::set_theta_del(), XCS::set_theta_ea(), XCS::set_theta_sub(), XCS::single_decision(), XCS::single_error(), XCS::single_reset(), XCS::single_update(), and XCS::version().
xcs_init()
void xcs_init (const char * filename)