XCSF: rule_neural.h File Reference
rule_neural.h File Reference
Neural network rule (condition + action) functions.
Functions
_Bool rule_neural_cond_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_neural_cond_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_neural_cond_match (const XCSF *xcsf, CL *c, const double *x)
_Bool rule_neural_cond_mutate (const XCSF *xcsf, CL *c)
void rule_neural_cond_copy (const XCSF *xcsf, CL *to, const CL *from)
void rule_neural_cond_cover (const XCSF *xcsf, CL *c, const double *x)
void rule_neural_cond_free (const XCSF *xcsf, const CL *c)
void rule_neural_cond_init (const XCSF *xcsf, CL *c)
void rule_neural_cond_print (const XCSF *xcsf, const CL *c)
void rule_neural_cond_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
int rule_neural_cond_size (const XCSF *xcsf, const CL *c)
size_t rule_neural_cond_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_neural_cond_load (const XCSF *xcsf, CL *c, FILE *fp)
_Bool rule_neural_act_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_neural_act_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_neural_act_mutate (const XCSF *xcsf, CL *c)
int rule_neural_act_compute (const XCSF *xcsf, CL *c, const double *x)
void rule_neural_act_copy (const XCSF *xcsf, CL *to, const CL *from)
void rule_neural_act_cover (const XCSF *xcsf, CL *c, const double *x, int action)
void rule_neural_act_free (const XCSF *xcsf, const CL *c)
void rule_neural_act_init (const XCSF *xcsf, CL *c)
void rule_neural_act_print (const XCSF *xcsf, const CL *c)
void rule_neural_act_rand (const XCSF *xcsf, CL *c)
void rule_neural_act_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
size_t rule_neural_act_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_neural_act_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const rule_neural_cond_vtbl
Neural network rule condition implemented functions.
static struct ActVtbl const rule_neural_act_vtbl
Neural network rule action implemented functions.
Detailed Description
Neural network rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file rule_neural.h.
Function Documentation
rule_neural_act_compute()
int rule_neural_act_compute (const XCSF * xcsf, CL * c, const double * x)
Definition at line 221 of file rule_neural.c.
References CL::action, CL::cond, iconstrain(), RULE_NEURAL::net, neural_output(), XCSF::num_actions, and RULE_NEURAL::num_outputs.
Referenced by rule_neural_act_cover().
rule_neural_act_copy()
void rule_neural_act_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 198 of file rule_neural.c.
rule_neural_act_cover()
void rule_neural_act_cover (const XCSF * xcsf, CL * c, const double * x, int action)
Definition at line 213 of file rule_neural.c.
References rule_neural_act_compute(), rule_neural_cond_match(), and rule_neural_cond_rand().
rule_neural_act_crossover()
_Bool rule_neural_act_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 240 of file rule_neural.c.
rule_neural_act_free()
void rule_neural_act_free (const XCSF * xcsf, const CL * c)
Definition at line 193 of file rule_neural.c.
rule_neural_act_general()
_Bool rule_neural_act_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 246 of file rule_neural.c.
rule_neural_act_init()
void rule_neural_act_init (const XCSF * xcsf, CL * c)
Definition at line 188 of file rule_neural.c.
rule_neural_act_load()
size_t rule_neural_act_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 264 of file rule_neural.c.
rule_neural_act_mutate()
_Bool rule_neural_act_mutate (const XCSF * xcsf, CL * c)
Definition at line 252 of file rule_neural.c.
rule_neural_act_print()
void rule_neural_act_print (const XCSF * xcsf, const CL * c)
Definition at line 203 of file rule_neural.c.
rule_neural_act_rand()
void rule_neural_act_rand (const XCSF * xcsf, CL * c)
Definition at line 208 of file rule_neural.c.
rule_neural_act_save()
size_t rule_neural_act_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 258 of file rule_neural.c.
rule_neural_act_update()
void rule_neural_act_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 235 of file rule_neural.c.
rule_neural_cond_copy()
void rule_neural_cond_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 102 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, neural_copy(), and RULE_NEURAL::num_outputs.
rule_neural_cond_cover()
void rule_neural_cond_cover (const XCSF * xcsf, CL * c, const double * x)
Definition at line 117 of file rule_neural.c.
rule_neural_cond_crossover()
_Bool rule_neural_cond_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 146 of file rule_neural.c.
rule_neural_cond_free()
void rule_neural_cond_free (const XCSF * xcsf, const CL * c)
Definition at line 95 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_free().
rule_neural_cond_general()
_Bool rule_neural_cond_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 152 of file rule_neural.c.
rule_neural_cond_init()
void rule_neural_cond_init (const XCSF * xcsf, CL * c)
Definition at line 54 of file rule_neural.c.
References CL::cond, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX_HIDDEN_NEURONS, XCSF::COND_NUM_HIDDEN_NEURONS, irand_uniform(), LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, LAYER_EVOLVE_WEIGHTS, LOGISTIC, neural_init(), neural_layer_connected_init(), neural_layer_insert(), XCSF::num_actions, and XCSF::num_x_vars.
rule_neural_cond_load()
size_t rule_neural_cond_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 177 of file rule_neural.c.
References CL::cond, neural_load(), and XCSF::num_actions.
rule_neural_cond_match()
_Bool rule_neural_cond_match (const XCSF * xcsf, CL * c, const double * x)
Definition at line 127 of file rule_neural.c.
References CL::cond, CL::m, RULE_NEURAL::net, neural_output(), and neural_propagate().
Referenced by rule_neural_act_cover().
rule_neural_cond_mutate()
_Bool rule_neural_cond_mutate (const XCSF * xcsf, CL * c)
Definition at line 140 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_mutate().
rule_neural_cond_print()
void rule_neural_cond_print (const XCSF * xcsf, const CL * c)
Definition at line 158 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_print().
rule_neural_cond_save()
size_t rule_neural_cond_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 170 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_save().
rule_neural_cond_size()
int rule_neural_cond_size (const XCSF * xcsf, const CL * c)
Definition at line 164 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_size().
rule_neural_cond_update()
void rule_neural_cond_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 122 of file rule_neural.c.
Variable Documentation
rule_neural_act_vtbl
struct ActVtbl const rule_neural_act_vtbl static
Initial value:
= {
    &rule_neural_act_general,
    &rule_neural_act_crossover,
    &rule_neural_act_mutate,
    &rule_neural_act_compute,
    &rule_neural_act_copy,
    &rule_neural_act_cover,
    &rule_neural_act_free,
    &rule_neural_act_init,
    &rule_neural_act_rand,
    &rule_neural_act_print,
    &rule_neural_act_update,
    &rule_neural_act_save,
    &rule_neural_act_load
}
Neural network rule action implemented functions.
Definition at line 76 of file rule_neural.h.
Referenced by condition_set().
rule_neural_cond_vtbl
struct CondVtbl const rule_neural_cond_vtbl static
Initial value:
= {
    &rule_neural_cond_crossover,
    &rule_neural_cond_general,
    &rule_neural_cond_match,
    &rule_neural_cond_mutate,
    &rule_neural_cond_copy,
    &rule_neural_cond_cover,
    &rule_neural_cond_free,
    &rule_neural_cond_init,
    &rule_neural_cond_print,
    &rule_neural_cond_update,
    &rule_neural_cond_size,
    &rule_neural_cond_save,
    &rule_neural_cond_load
}
Neural network rule condition implemented functions.
Definition at line 43 of file rule_neural.h.
Referenced by condition_set().