XCSF: rule_dgp.c File Reference
rule_dgp.c File Reference
Dynamical GP graph rule (condition + action) functions.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "dgp.h"
#include "condition.h"
#include "action.h"
#include "rule_dgp.h"
Data Structures
struct RULE_DGP
Dynamical GP graph rule data structure.
Typedefs
typedef struct RULE_DGP RULE_DGP
Dynamical GP graph rule data structure.
Functions
static void rule_dgp_cond_rand (const XCSF *xcsf, const CL *c)
void rule_dgp_cond_init (const XCSF *xcsf, CL *c)
void rule_dgp_cond_free (const XCSF *xcsf, const CL *c)
void rule_dgp_cond_copy (const XCSF *xcsf, CL *dest, const CL *src)
void rule_dgp_cond_cover (const XCSF *xcsf, const CL *c, const double *x)
void rule_dgp_cond_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool rule_dgp_cond_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool rule_dgp_cond_mutate (const XCSF *xcsf, const CL *c)
_Bool rule_dgp_cond_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_dgp_cond_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void rule_dgp_cond_print (const XCSF *xcsf, const CL *c)
int rule_dgp_cond_size (const XCSF *xcsf, const CL *c)
size_t rule_dgp_cond_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_dgp_cond_load (const XCSF *xcsf, CL *c, FILE *fp)
void rule_dgp_act_init (const XCSF *xcsf, CL *c)
void rule_dgp_act_free (const XCSF *xcsf, const CL *c)
void rule_dgp_act_copy (const XCSF *xcsf, CL *dest, const CL *src)
void rule_dgp_act_print (const XCSF *xcsf, const CL *c)
void rule_dgp_act_rand (const XCSF *xcsf, const CL *c)
void rule_dgp_act_cover (const XCSF *xcsf, const CL *c, const double *x, int action)
int rule_dgp_act_compute (const XCSF *xcsf, const CL *c, const double *x)
void rule_dgp_act_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool rule_dgp_act_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_dgp_act_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_dgp_act_mutate (const XCSF *xcsf, const CL *c)
size_t rule_dgp_act_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_dgp_act_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Dynamical GP graph rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file rule_dgp.c.
Typedef Documentation
RULE_DGP
typedef struct RULE_DGP RULE_DGP
Dynamical GP graph rule data structure.
Function Documentation
rule_dgp_act_compute()
int rule_dgp_act_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 186 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, graph_output(), iconstrain(), XCSF::n_actions, and RULE_DGP::n_outputs.
Referenced by rule_dgp_act_cover().
rule_dgp_act_copy()
void rule_dgp_act_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 163 of file rule_dgp.c.
rule_dgp_act_cover()
void rule_dgp_act_cover (const XCSF * xcsf, const CL * c, const double * x, int action)
Definition at line 178 of file rule_dgp.c.
References rule_dgp_act_compute(), rule_dgp_cond_match(), and rule_dgp_cond_rand().
rule_dgp_act_crossover()
_Bool rule_dgp_act_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 205 of file rule_dgp.c.
rule_dgp_act_free()
void rule_dgp_act_free (const XCSF * xcsf, const CL * c)
Definition at line 158 of file rule_dgp.c.
rule_dgp_act_general()
_Bool rule_dgp_act_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 211 of file rule_dgp.c.
rule_dgp_act_init()
void rule_dgp_act_init (const XCSF * xcsf, CL * c)
Definition at line 153 of file rule_dgp.c.
rule_dgp_act_load()
size_t rule_dgp_act_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 229 of file rule_dgp.c.
rule_dgp_act_mutate()
_Bool rule_dgp_act_mutate (const XCSF * xcsf, const CL * c)
Definition at line 217 of file rule_dgp.c.
rule_dgp_act_print()
void rule_dgp_act_print (const XCSF * xcsf, const CL * c)
Definition at line 168 of file rule_dgp.c.
rule_dgp_act_rand()
void rule_dgp_act_rand (const XCSF * xcsf, const CL * c)
Definition at line 173 of file rule_dgp.c.
rule_dgp_act_save()
size_t rule_dgp_act_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 223 of file rule_dgp.c.
rule_dgp_act_update()
void rule_dgp_act_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 200 of file rule_dgp.c.
rule_dgp_cond_copy()
void rule_dgp_cond_copy (const XCSF * xcsf, CL * dest, const CL * src)
Definition at line 65 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, graph_copy(), graph_init(), GRAPH::n, and RULE_DGP::n_outputs.
rule_dgp_cond_cover()
void rule_dgp_cond_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 81 of file rule_dgp.c.
rule_dgp_cond_crossover()
_Bool rule_dgp_cond_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 109 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_crossover().
rule_dgp_cond_free()
void rule_dgp_cond_free (const XCSF * xcsf, const CL * c)
Definition at line 58 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_free().
rule_dgp_cond_general()
_Bool rule_dgp_cond_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 116 of file rule_dgp.c.
rule_dgp_cond_init()
void rule_dgp_cond_init (const XCSF * xcsf, CL * c)
Definition at line 48 of file rule_dgp.c.
References CL::cond, XCSF::DGP_NUM_NODES, graph_init(), graph_rand(), and XCSF::n_actions.
rule_dgp_cond_load()
size_t rule_dgp_cond_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 142 of file rule_dgp.c.
References CL::cond, graph_load(), and XCSF::n_actions.
rule_dgp_cond_match()
_Bool rule_dgp_cond_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 91 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, graph_output(), and graph_update().
Referenced by rule_dgp_act_cover().
rule_dgp_cond_mutate()
_Bool rule_dgp_cond_mutate (const XCSF * xcsf, const CL * c)
Definition at line 103 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_mutate().
rule_dgp_cond_print()
void rule_dgp_cond_print (const XCSF * xcsf, const CL * c)
Definition at line 122 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_print().
rule_dgp_cond_rand()
static void rule_dgp_cond_rand (const XCSF * xcsf, const CL * c) static
Definition at line 75 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_rand().
Referenced by rule_dgp_act_cover().
rule_dgp_cond_save()
size_t rule_dgp_cond_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 135 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_save().
rule_dgp_cond_size()
int rule_dgp_cond_size (const XCSF * xcsf, const CL * c)
Definition at line 128 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and GRAPH::n.
rule_dgp_cond_update()
void rule_dgp_cond_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 86 of file rule_dgp.c.