XCSF: rule_neural.c File Reference
rule_neural.c File Reference
Neural network rule (condition + action) functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "neural_activations.h"
#include "neural.h"
#include "neural_layer.h"
#include "neural_layer_connected.h"
#include "neural_layer_dropout.h"
#include "cl.h"
#include "condition.h"
#include "action.h"
#include "rule_neural.h"
Data Structures
struct RULE_NEURAL
Neural network rule data structure.
Typedefs
typedef struct RULE_NEURAL RULE_NEURAL
Neural network rule data structure.
Functions
static void rule_neural_cond_rand (const XCSF *xcsf, const CL *c)
static uint32_t rule_neural_lopt (const XCSF *xcsf)
void rule_neural_cond_init (const XCSF *xcsf, CL *c)
void rule_neural_cond_free (const XCSF *xcsf, const CL *c)
void rule_neural_cond_copy (const XCSF *xcsf, CL *to, const CL *from)
void rule_neural_cond_cover (const XCSF *xcsf, const CL *c, const double *x)
void rule_neural_cond_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool rule_neural_cond_match (const XCSF *xcsf, const CL *c, const double *x)
_Bool rule_neural_cond_mutate (const XCSF *xcsf, const CL *c)
_Bool rule_neural_cond_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_neural_cond_general (const XCSF *xcsf, const CL *c1, const CL *c2)
void rule_neural_cond_print (const XCSF *xcsf, const CL *c)
int rule_neural_cond_size (const XCSF *xcsf, const CL *c)
size_t rule_neural_cond_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_neural_cond_load (const XCSF *xcsf, CL *c, FILE *fp)
void rule_neural_act_init (const XCSF *xcsf, CL *c)
void rule_neural_act_free (const XCSF *xcsf, const CL *c)
void rule_neural_act_copy (const XCSF *xcsf, CL *to, const CL *from)
void rule_neural_act_print (const XCSF *xcsf, const CL *c)
void rule_neural_act_rand (const XCSF *xcsf, const CL *c)
void rule_neural_act_cover (const XCSF *xcsf, const CL *c, const double *x, int action)
int rule_neural_act_compute (const XCSF *xcsf, const CL *c, const double *x)
void rule_neural_act_update (const XCSF *xcsf, const CL *c, const double *x, const double *y)
_Bool rule_neural_act_crossover (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_neural_act_general (const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool rule_neural_act_mutate (const XCSF *xcsf, const CL *c)
size_t rule_neural_act_save (const XCSF *xcsf, const CL *c, FILE *fp)
size_t rule_neural_act_load (const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Neural network rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file rule_neural.c.
Typedef Documentation
RULE_NEURAL
typedef struct RULE_NEURAL RULE_NEURAL
Neural network rule data structure.
Function Documentation
rule_neural_act_compute()
int rule_neural_act_compute (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 226 of file rule_neural.c.
References CL::cond, iconstrain(), RULE_NEURAL::net, neural_output(), XCSF::num_actions, and RULE_NEURAL::num_outputs.
Referenced by rule_neural_act_cover().
rule_neural_act_copy()
void rule_neural_act_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 203 of file rule_neural.c.
rule_neural_act_cover()
void rule_neural_act_cover (const XCSF * xcsf, const CL * c, const double * x, int action)
Definition at line 218 of file rule_neural.c.
References rule_neural_act_compute(), rule_neural_cond_match(), and rule_neural_cond_rand().
rule_neural_act_crossover()
_Bool rule_neural_act_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 245 of file rule_neural.c.
rule_neural_act_free()
void rule_neural_act_free (const XCSF * xcsf, const CL * c)
Definition at line 198 of file rule_neural.c.
rule_neural_act_general()
_Bool rule_neural_act_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 251 of file rule_neural.c.
rule_neural_act_init()
void rule_neural_act_init (const XCSF * xcsf, CL * c)
Definition at line 193 of file rule_neural.c.
rule_neural_act_load()
size_t rule_neural_act_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 269 of file rule_neural.c.
rule_neural_act_mutate()
_Bool rule_neural_act_mutate (const XCSF * xcsf, const CL * c)
Definition at line 257 of file rule_neural.c.
rule_neural_act_print()
void rule_neural_act_print (const XCSF * xcsf, const CL * c)
Definition at line 208 of file rule_neural.c.
rule_neural_act_rand()
void rule_neural_act_rand (const XCSF * xcsf, const CL * c)
Definition at line 213 of file rule_neural.c.
rule_neural_act_save()
size_t rule_neural_act_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 263 of file rule_neural.c.
rule_neural_act_update()
void rule_neural_act_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 240 of file rule_neural.c.
rule_neural_cond_copy()
void rule_neural_cond_copy (const XCSF * xcsf, CL * to, const CL * from)
Definition at line 108 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, neural_copy(), and RULE_NEURAL::num_outputs.
rule_neural_cond_cover()
void rule_neural_cond_cover (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 123 of file rule_neural.c.
rule_neural_cond_crossover()
_Bool rule_neural_cond_crossover (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 151 of file rule_neural.c.
rule_neural_cond_free()
void rule_neural_cond_free (const XCSF * xcsf, const CL * c)
Definition at line 101 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_free().
rule_neural_cond_general()
_Bool rule_neural_cond_general (const XCSF * xcsf, const CL * c1, const CL * c2)
Definition at line 157 of file rule_neural.c.
rule_neural_cond_init()
void rule_neural_cond_init (const XCSF * xcsf, CL * c)
Definition at line 55 of file rule_neural.c.
References CL::cond, XCSF::COND_HIDDEN_ACTIVATION, XCSF::COND_MAX_NEURONS, XCSF::COND_NUM_NEURONS, XCSF::COND_OUTPUT_ACTIVATION, LAYER_EVOLVE_NEURONS, neural_init(), neural_layer_connected_init(), neural_layer_insert(), XCSF::num_actions, XCSF::num_x_vars, and rule_neural_lopt().
rule_neural_cond_load()
size_t rule_neural_cond_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 182 of file rule_neural.c.
References CL::cond, neural_load(), and XCSF::num_actions.
rule_neural_cond_match()
_Bool rule_neural_cond_match (const XCSF * xcsf, const CL * c, const double * x)
Definition at line 133 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, neural_output(), and neural_propagate().
Referenced by rule_neural_act_cover().
rule_neural_cond_mutate()
_Bool rule_neural_cond_mutate (const XCSF * xcsf, const CL * c)
Definition at line 145 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_mutate().
rule_neural_cond_print()
void rule_neural_cond_print (const XCSF * xcsf, const CL * c)
Definition at line 163 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_print().
rule_neural_cond_rand()
static void rule_neural_cond_rand (const XCSF * xcsf, const CL * c) static
Definition at line 117 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_rand().
Referenced by rule_neural_act_cover().
rule_neural_cond_save()
size_t rule_neural_cond_save (const XCSF * xcsf, const CL * c, FILE * fp)
Definition at line 175 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_save().
rule_neural_cond_size()
int rule_neural_cond_size (const XCSF * xcsf, const CL * c)
Definition at line 169 of file rule_neural.c.
References CL::cond, RULE_NEURAL::net, and neural_size().
rule_neural_cond_update()
void rule_neural_cond_update (const XCSF * xcsf, const CL * c, const double * x, const double * y)
Definition at line 128 of file rule_neural.c.
rule_neural_lopt()
static uint32_t rule_neural_lopt (const XCSF * xcsf) static
Definition at line 86 of file rule_neural.c.
References XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, LAYER_EVOLVE_FUNCTIONS, LAYER_EVOLVE_NEURONS, and LAYER_EVOLVE_WEIGHTS.
Referenced by rule_neural_cond_init().