XCSF: rule_dgp.h File Reference
rule_dgp.h File Reference
Dynamical GP graph rule (condition + action) functions.
Functions
_Bool rule_dgp_cond_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_dgp_cond_general (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_dgp_cond_match (const XCSF *xcsf, CL *c, const double *x)
_Bool rule_dgp_cond_mutate (const XCSF *xcsf, CL *c)
void rule_dgp_cond_copy (const XCSF *xcsf, CL *to, CL *from)
void rule_dgp_cond_cover (const XCSF *xcsf, CL *c, const double *x)
void rule_dgp_cond_free (const XCSF *xcsf, CL *c)
void rule_dgp_cond_init (const XCSF *xcsf, CL *c)
void rule_dgp_cond_print (const XCSF *xcsf, CL *c)
void rule_dgp_cond_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
int rule_dgp_cond_size (const XCSF *xcsf, CL *c)
size_t rule_dgp_cond_save (const XCSF *xcsf, CL *c, FILE *fp)
size_t rule_dgp_cond_load (const XCSF *xcsf, CL *c, FILE *fp)
_Bool rule_dgp_act_crossover (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_dgp_act_general (const XCSF *xcsf, CL *c1, CL *c2)
_Bool rule_dgp_act_mutate (const XCSF *xcsf, CL *c)
int rule_dgp_act_compute (const XCSF *xcsf, CL *c, const double *x)
void rule_dgp_act_copy (const XCSF *xcsf, CL *to, CL *from)
void rule_dgp_act_cover (const XCSF *xcsf, CL *c, const double *x, int action)
void rule_dgp_act_free (const XCSF *xcsf, CL *c)
void rule_dgp_act_init (const XCSF *xcsf, CL *c)
void rule_dgp_act_print (const XCSF *xcsf, CL *c)
void rule_dgp_act_rand (const XCSF *xcsf, CL *c)
void rule_dgp_act_update (const XCSF *xcsf, CL *c, const double *x, const double *y)
size_t rule_dgp_act_save (const XCSF *xcsf, CL *c, FILE *fp)
size_t rule_dgp_act_load (const XCSF *xcsf, CL *c, FILE *fp)
Variables
static struct CondVtbl const rule_dgp_cond_vtbl
Dynamical GP rule condition implemented functions.
static struct ActVtbl const rule_dgp_act_vtbl
Dynamical GP rule action implemented functions.
Detailed Description
Dynamical GP graph rule (condition + action) functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file rule_dgp.h.
Function Documentation
rule_dgp_act_compute()
int rule_dgp_act_compute (const XCSF * xcsf, CL * c, const double * x)
Definition at line 188 of file rule_dgp.c.
References CL::action, CL::cond, RULE_DGP::dgp, graph_output(), iconstrain(), XCSF::num_actions, and RULE_DGP::num_outputs.
Referenced by rule_dgp_act_cover().
rule_dgp_act_copy()
void rule_dgp_act_copy (const XCSF * xcsf, CL * to, CL * from)
Definition at line 165 of file rule_dgp.c.
rule_dgp_act_cover()
void rule_dgp_act_cover (const XCSF * xcsf, CL * c, const double * x, int action)
Definition at line 180 of file rule_dgp.c.
References rule_dgp_act_compute(), rule_dgp_cond_match(), and rule_dgp_cond_rand().
rule_dgp_act_crossover()
_Bool rule_dgp_act_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 207 of file rule_dgp.c.
rule_dgp_act_free()
void rule_dgp_act_free (const XCSF * xcsf, CL * c)
Definition at line 160 of file rule_dgp.c.
rule_dgp_act_general()
_Bool rule_dgp_act_general (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 213 of file rule_dgp.c.
rule_dgp_act_init()
void rule_dgp_act_init (const XCSF * xcsf, CL * c)
Definition at line 155 of file rule_dgp.c.
rule_dgp_act_load()
size_t rule_dgp_act_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 231 of file rule_dgp.c.
rule_dgp_act_mutate()
_Bool rule_dgp_act_mutate (const XCSF * xcsf, CL * c)
Definition at line 219 of file rule_dgp.c.
rule_dgp_act_print()
void rule_dgp_act_print (const XCSF * xcsf, CL * c)
Definition at line 170 of file rule_dgp.c.
rule_dgp_act_rand()
void rule_dgp_act_rand (const XCSF * xcsf, CL * c)
Definition at line 175 of file rule_dgp.c.
rule_dgp_act_save()
size_t rule_dgp_act_save (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 225 of file rule_dgp.c.
rule_dgp_act_update()
void rule_dgp_act_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 202 of file rule_dgp.c.
rule_dgp_cond_copy()
void rule_dgp_cond_copy (const XCSF * xcsf, CL * to, CL * from)
Definition at line 66 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, graph_copy(), graph_init(), GRAPH::n, and RULE_DGP::num_outputs.
rule_dgp_cond_cover()
void rule_dgp_cond_cover (const XCSF * xcsf, CL * c, const double * x)
Definition at line 82 of file rule_dgp.c.
rule_dgp_cond_crossover()
_Bool rule_dgp_cond_crossover (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 111 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_crossover().
rule_dgp_cond_free()
void rule_dgp_cond_free (const XCSF * xcsf, CL * c)
Definition at line 59 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_free().
rule_dgp_cond_general()
_Bool rule_dgp_cond_general (const XCSF * xcsf, CL * c1, CL * c2)
Definition at line 118 of file rule_dgp.c.
rule_dgp_cond_init()
void rule_dgp_cond_init (const XCSF * xcsf, CL * c)
Definition at line 49 of file rule_dgp.c.
References CL::cond, XCSF::DGP_NUM_NODES, graph_init(), graph_rand(), and XCSF::num_actions.
rule_dgp_cond_load()
size_t rule_dgp_cond_load (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 144 of file rule_dgp.c.
References CL::cond, graph_load(), and XCSF::num_actions.
rule_dgp_cond_match()
_Bool rule_dgp_cond_match (const XCSF * xcsf, CL * c, const double * x)
Definition at line 92 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, graph_output(), graph_update(), and CL::m.
Referenced by rule_dgp_act_cover().
rule_dgp_cond_mutate()
_Bool rule_dgp_cond_mutate (const XCSF * xcsf, CL * c)
Definition at line 105 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_mutate().
rule_dgp_cond_print()
void rule_dgp_cond_print (const XCSF * xcsf, CL * c)
Definition at line 124 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_print().
rule_dgp_cond_save()
size_t rule_dgp_cond_save (const XCSF * xcsf, CL * c, FILE * fp)
Definition at line 137 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and graph_save().
rule_dgp_cond_size()
int rule_dgp_cond_size (const XCSF * xcsf, CL * c)
Definition at line 130 of file rule_dgp.c.
References CL::cond, RULE_DGP::dgp, and GRAPH::n.
rule_dgp_cond_update()
void rule_dgp_cond_update (const XCSF * xcsf, CL * c, const double * x, const double * y)
Definition at line 87 of file rule_dgp.c.
Variable Documentation
rule_dgp_act_vtbl
struct ActVtbl const rule_dgp_act_vtbl static
Initial value:
= {
    &rule_dgp_act_general,
    &rule_dgp_act_crossover,
    &rule_dgp_act_mutate,
    &rule_dgp_act_compute,
    &rule_dgp_act_copy,
    &rule_dgp_act_cover,
    &rule_dgp_act_free,
    &rule_dgp_act_init,
    &rule_dgp_act_rand,
    &rule_dgp_act_print,
    &rule_dgp_act_update,
    &rule_dgp_act_save,
    &rule_dgp_act_load
}
Dynamical GP rule action implemented functions.
Definition at line 76 of file rule_dgp.h.
Referenced by condition_set().
rule_dgp_cond_vtbl
struct CondVtbl const rule_dgp_cond_vtbl static
Initial value:
= {
    &rule_dgp_cond_crossover,
    &rule_dgp_cond_general,
    &rule_dgp_cond_match,
    &rule_dgp_cond_mutate,
    &rule_dgp_cond_copy,
    &rule_dgp_cond_cover,
    &rule_dgp_cond_free,
    &rule_dgp_cond_init,
    &rule_dgp_cond_print,
    &rule_dgp_cond_update,
    &rule_dgp_cond_size,
    &rule_dgp_cond_save,
    &rule_dgp_cond_load
}
Dynamical GP rule condition implemented functions.
Definition at line 43 of file rule_dgp.h.
Referenced by condition_set().