XCSF: sam.c File Reference
sam.c File Reference
Self-adaptive mutation functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "sam.h"
Macros
#define NUM_RATES 10
number of selectable mutation rates for rate selection adaptation
Functions
static void sam_log_normal_init (const XCSF *xcsf, double **mu)
Initialises log normal self-adaptive mutation rates.
static void sam_log_normal_adapt (const XCSF *xcsf, double *mu)
Performs log normal self-adaptation.
static void sam_rate_selection_init (const XCSF *xcsf, double **mu)
Initialises rate selection self-adaptive mutation.
static void sam_rate_selection_adapt (const XCSF *xcsf, double *mu)
Performs self-adaptation via a rate selection mechanism.
void sam_init (const XCSF *xcsf, double **mu)
Initialises a classifier's self-adaptive mutation rates.
void sam_adapt (const XCSF *xcsf, double *mu)
Self-adapts a classifier's mutation rates.
void sam_copy (const XCSF *xcsf, double *to, double *from)
Copies self-adaptive mutation rates.
void sam_free (const XCSF *xcsf, double *mu)
Frees the self-adaptive mutation rates.
void sam_print (const XCSF *xcsf, double *mu)
Prints the self-adaptive mutation rates.
Variables
static const double mrates [10] = {0.0001,0.001,0.002,0.005,0.01,0.01,0.02,0.05,0.1,1.0}
Detailed Description
Self-adaptive mutation functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file sam.c.
Macro Definition Documentation
NUM_RATES
#define NUM_RATES 10
number of selectable mutation rates for rate selection adaptation
Definition at line 36 of file sam.c.
Referenced by sam_rate_selection_adapt(), and sam_rate_selection_init().
Function Documentation
sam_adapt()
void sam_adapt (const XCSF * xcsf, double * mu)
Self-adapts a classifier's mutation rates.
Parameters
xcsf The XCSF data structure.
mu The classifier's mutation rates.
Definition at line 64 of file sam.c.
References sam_log_normal_adapt(), sam_rate_selection_adapt(), and XCSF::SAM_TYPE.
Referenced by ea().
sam_copy()
void sam_copy (const XCSF * xcsf, double * to, double * from)
Copies self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
to Destination mutation rates.
from Source mutation rates.
Definition at line 80 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_copy().
sam_free()
void sam_free (const XCSF * xcsf, double * mu)
Frees the self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to free.
Definition at line 92 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_free().
sam_init()
void sam_init (const XCSF * xcsf, double ** mu)
Initialises a classifier's self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The classifier's mutation rates.
Definition at line 46 of file sam.c.
References sam_log_normal_init(), XCSF::SAM_NUM, sam_rate_selection_init(), and XCSF::SAM_TYPE.
Referenced by cl_init().
sam_log_normal_adapt()
static void sam_log_normal_adapt (const XCSF * xcsf, double * mu) static
Performs log normal self-adaptation.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to adapt.
Definition at line 130 of file sam.c.
References rand_normal(), XCSF::SAM_MIN, and XCSF::SAM_NUM.
Referenced by sam_adapt().
sam_log_normal_init()
static void sam_log_normal_init (const XCSF * xcsf, double ** mu) static
Initialises log normal self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to initialise.
Definition at line 118 of file sam.c.
References rand_uniform(), and XCSF::SAM_NUM.
Referenced by sam_init().
sam_print()
void sam_print (const XCSF * xcsf, double * mu)
Prints the self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to print.
Definition at line 104 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_print().
sam_rate_selection_adapt()
static void sam_rate_selection_adapt (const XCSF * xcsf, double * mu) static
Performs self-adaptation via a rate selection mechanism.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to adapt.
With 10% probability, randomly selects one of the possible rates.
Definition at line 162 of file sam.c.
References irand_uniform(), mrates, NUM_RATES, rand_uniform(), and XCSF::SAM_NUM.
Referenced by sam_adapt().
sam_rate_selection_init()
static void sam_rate_selection_init (const XCSF * xcsf, double ** mu) static
Initialises rate selection self-adaptive mutation.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to initialise.
Definition at line 148 of file sam.c.
References irand_uniform(), mrates, NUM_RATES, and XCSF::SAM_NUM.
Referenced by sam_init().
Variable Documentation
mrates
const double mrates[10] = {0.0001,0.001,0.002,0.005,0.01,0.01,0.02,0.05,0.1,1.0} static
Definition at line 37 of file sam.c.
Referenced by sam_rate_selection_adapt(), and sam_rate_selection_init().