XCSF: sam.h File Reference
sam.h File Reference
Self-adaptive mutation functions.
Functions
void sam_adapt (const XCSF *xcsf, double *mu)
Self-adapts a classifier's mutation rates.
void sam_copy (const XCSF *xcsf, double *to, const double *from)
Copies self-adaptive mutation rates.
void sam_free (const XCSF *xcsf, double *mu)
Frees the self-adaptive mutation rates.
void sam_init (const XCSF *xcsf, double **mu)
Initialises a classifier's self-adaptive mutation rates.
void sam_print (const XCSF *xcsf, const double *mu)
Prints the self-adaptive mutation rates.
void sam_reset (const XCSF *xcsf, double **mu)
Resets a classifier's self-adaptive mutation rates.
Detailed Description
Self-adaptive mutation functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file sam.h.
Function Documentation
sam_adapt()
void sam_adapt (const XCSF * xcsf, double * mu)
Self-adapts a classifier's mutation rates.
Parameters
xcsf The XCSF data structure.
mu The classifier's mutation rates.
Definition at line 76 of file sam.c.
References sam_log_normal_adapt(), sam_rate_selection_adapt(), and XCSF::SAM_TYPE.
Referenced by ea().
sam_copy()
void sam_copy (const XCSF * xcsf, double * to, const double * from)
Copies self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
to Destination mutation rates.
from Source mutation rates.
Definition at line 92 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_copy().
sam_free()
void sam_free (const XCSF * xcsf, double * mu)
Frees the self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to free.
Definition at line 104 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_free().
sam_init()
void sam_init (const XCSF * xcsf, double ** mu)
Initialises a classifier's self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The classifier's mutation rates.
Definition at line 46 of file sam.c.
References XCSF::SAM_NUM, and sam_reset().
Referenced by cl_init().
sam_print()
void sam_print (const XCSF * xcsf, const double * mu)
Prints the self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The mutation rates to print.
Definition at line 116 of file sam.c.
References XCSF::SAM_NUM.
Referenced by cl_print().
sam_reset()
void sam_reset (const XCSF * xcsf, double ** mu)
Resets a classifier's self-adaptive mutation rates.
Parameters
xcsf The XCSF data structure.
mu The classifier's mutation rates.
Definition at line 59 of file sam.c.
References sam_log_normal_init(), XCSF::SAM_NUM, sam_rate_selection_init(), and XCSF::SAM_TYPE.
Referenced by sam_init().