XCSF: XCS Struct Reference
XCS Struct Reference
Python XCSF data structure.
Public Member Functions
XCS (int num_x_vars, int num_actions, _Bool multistep)
Constructor for single-step reinforcement learning.
XCS (int num_x_vars, int num_y_vars)
Constructor for supervised learning with default config.
XCS (int num_x_vars, int num_y_vars, const char *filename)
Constructor for supervised learning with a specified config.
void xcs_init (const char *filename)
Initialises python XCS structure.
double version ()
size_t save (char *fname)
size_t load (char *fname)
void single_reset ()
int single_decision (np::ndarray &input, _Bool explore)
void single_update (double reward)
double single_error (double reward)
double fit (np::ndarray &train_X, np::ndarray &train_Y, _Bool shuffle)
double fit (np::ndarray &train_X, np::ndarray &train_Y, np::ndarray &test_X, np::ndarray &test_Y, _Bool shuffle)
np::ndarray predict (np::ndarray &T)
double score (np::ndarray &test_X, np::ndarray &test_Y)
void print_pop (_Bool printc, _Bool printa, _Bool printp)
p::list get_cond_num_neurons ()
p::list get_cond_max_neurons ()
p::list get_pred_num_neurons ()
p::list get_pred_max_neurons ()
int get_omp_num_threads ()
_Bool get_pop_init ()
int get_max_trials ()
int get_perf_avg_trials ()
int get_pop_max_size ()
int get_loss_func ()
double get_alpha ()
double get_beta ()
double get_delta ()
double get_eps_0 ()
double get_err_reduc ()
double get_fit_reduc ()
double get_init_error ()
double get_init_fitness ()
double get_nu ()
int get_m_probation ()
int get_theta_del ()
int get_act_type ()
int get_cond_type ()
int get_pred_type ()
double get_p_crossover ()
double get_p_mutation ()
double get_f_mutation ()
double get_e_mutation ()
double get_s_mutation ()
double get_theta_ea ()
int get_lambda ()
int get_ea_select_type ()
double get_ea_select_size ()
double get_sam_min ()
int get_sam_num ()
int get_sam_type ()
double get_max_con ()
double get_min_con ()
double get_cond_smin ()
double get_cond_bits ()
_Bool get_cond_evolve_weights ()
_Bool get_cond_evolve_neurons ()
_Bool get_cond_evolve_functions ()
int get_cond_output_activation ()
int get_cond_hidden_activation ()
int get_pred_output_activation ()
int get_pred_hidden_activation ()
double get_pred_momentum ()
_Bool get_pred_evolve_weights ()
_Bool get_pred_evolve_neurons ()
_Bool get_pred_evolve_functions ()
_Bool get_pred_evolve_eta ()
_Bool get_pred_sgd_weights ()
_Bool get_pred_reset ()
int get_max_neuron_mod ()
int get_dgp_num_nodes ()
_Bool get_reset_states ()
int get_max_k ()
int get_max_t ()
int get_gp_num_cons ()
int get_gp_init_depth ()
double get_pred_eta ()
double get_cond_eta ()
double get_pred_x0 ()
double get_pred_rls_scale_factor ()
double get_pred_rls_lambda ()
int get_theta_sub ()
_Bool get_ea_subsumption ()
_Bool get_set_subsumption ()
int get_pop_size ()
int get_pop_num ()
int get_time ()
double get_num_x_vars ()
double get_num_y_vars ()
double get_num_actions ()
double get_pop_mean_mu (int m)
double get_pop_mean_cond_size ()
double get_pop_mean_pred_size ()
double get_pop_mean_pred_eta (int layer)
double get_pop_mean_pred_neurons (int layer)
double get_pop_mean_pred_layers ()
double get_msetsize ()
double get_mfrac ()
int get_teletransportation ()
double get_gamma ()
double get_p_explore ()
void set_omp_num_threads (int a)
void set_cond_num_neurons (p::list &a)
void set_cond_max_neurons (p::list &a)
void set_pred_num_neurons (p::list &a)
void set_pred_max_neurons (p::list &a)
void set_pop_init (_Bool a)
void set_max_trials (int a)
void set_perf_avg_trials (int a)
void set_pop_max_size (int a)
void set_loss_func (int a)
void set_alpha (double a)
void set_beta (double a)
void set_delta (double a)
void set_eps_0 (double a)
void set_err_reduc (double a)
void set_fit_reduc (double a)
void set_init_error (double a)
void set_init_fitness (double a)
void set_nu (double a)
void set_m_probation (int a)
void set_theta_del (int a)
void set_act_type (int a)
void set_cond_type (int a)
void set_pred_type (int a)
void set_p_crossover (double a)
void set_p_mutation (double a)
void set_f_mutation (double a)
void set_e_mutation (double a)
void set_s_mutation (double a)
void set_theta_ea (double a)
void set_lambda (int a)
void set_ea_select_type (int a)
void set_ea_select_size (double a)
void set_sam_min (double a)
void set_sam_num (int a)
void set_sam_type (int a)
void set_max_con (double a)
void set_min_con (double a)
void set_cond_smin (double a)
void set_cond_bits (double a)
void set_cond_evolve_weights (_Bool a)
void set_cond_evolve_neurons (_Bool a)
void set_cond_evolve_functions (_Bool a)
void set_cond_output_activation (int a)
void set_cond_hidden_activation (int a)
void set_pred_output_activation (int a)
void set_pred_hidden_activation (int a)
void set_pred_momentum (double a)
void set_pred_evolve_weights (_Bool a)
void set_pred_evolve_neurons (_Bool a)
void set_pred_evolve_functions (_Bool a)
void set_pred_evolve_eta (_Bool a)
void set_pred_sgd_weights (_Bool a)
void set_pred_reset (_Bool a)
void set_max_neuron_mod (int a)
void set_dgp_num_nodes (int a)
void set_reset_states (_Bool a)
void set_max_k (int a)
void set_max_t (int a)
void set_gp_num_cons (int a)
void set_gp_init_depth (int a)
void set_pred_eta (double a)
void set_cond_eta (double a)
void set_pred_x0 (double a)
void set_pred_rls_scale_factor (double a)
void set_pred_rls_lambda (double a)
void set_theta_sub (int a)
void set_ea_subsumption (_Bool a)
void set_set_subsumption (_Bool a)
void set_teletransportation (int a)
void set_gamma (double a)
void set_p_explore (double a)
Data Fields
XCSF xcs
XCSF data structure.
SET mset
Match set for RL.
SET aset
Action set for RL.
SET kset
Kill set for RL.
double * state
Current input state for RL.
int action
Current action for RL.
INPUT * train_data
Current training data for supervised learning.
INPUT * test_data
Currrent test data for supervised learning.
Detailed Description
Python XCSF data structure.
Definition at line 52 of file python_wrapper.cpp.
Constructor & Destructor Documentation
XCS() [1/3]
XCS::XCS (int num_x_vars, int num_actions, _Bool multistep) inline
Constructor for single-step reinforcement learning.
Definition at line 66 of file python_wrapper.cpp.
References XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, pa_init(), and xcs_init().
XCS() [2/3]
XCS::XCS (int num_x_vars, int num_y_vars) inline
Constructor for supervised learning with default config.
Definition at line 78 of file python_wrapper.cpp.
XCS() [3/3]
XCS::XCS (int num_x_vars, int num_y_vars, const char * filename) inline
Constructor for supervised learning with a specified config.
Definition at line 84 of file python_wrapper.cpp.
References XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, and xcs_init().
Member Function Documentation
fit() [1/2]
double XCS::fit (np::ndarray & train_X, np::ndarray & train_Y, _Bool shuffle) inline
Definition at line 165 of file python_wrapper.cpp.
References clset_pop_init(), INPUT::rows, XCSF::time, INPUT::x, INPUT::x_cols, xcsf_fit1(), INPUT::y, and INPUT::y_cols.
Referenced by BOOST_PYTHON_MODULE().
fit() [2/2]
double XCS::fit (np::ndarray & train_X, np::ndarray & train_Y, np::ndarray & test_X, np::ndarray & test_Y, _Bool shuffle) inline
Definition at line 185 of file python_wrapper.cpp.
References clset_pop_init(), INPUT::rows, XCSF::time, INPUT::x, INPUT::x_cols, xcsf_fit2(), INPUT::y, and INPUT::y_cols.
get_act_type()
int XCS::get_act_type () inline
Definition at line 307 of file python_wrapper.cpp.
References XCSF::ACT_TYPE.
Referenced by BOOST_PYTHON_MODULE().
get_alpha()
double XCS::get_alpha () inline
Definition at line 296 of file python_wrapper.cpp.
References XCSF::ALPHA.
Referenced by BOOST_PYTHON_MODULE().
get_beta()
double XCS::get_beta () inline
Definition at line 297 of file python_wrapper.cpp.
References XCSF::BETA.
Referenced by BOOST_PYTHON_MODULE().
get_cond_bits()
double XCS::get_cond_bits () inline
Definition at line 325 of file python_wrapper.cpp.
References XCSF::COND_BITS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_eta()
double XCS::get_cond_eta () inline
Definition at line 348 of file python_wrapper.cpp.
References XCSF::COND_ETA.
Referenced by BOOST_PYTHON_MODULE().
get_cond_evolve_functions()
_Bool XCS::get_cond_evolve_functions () inline
Definition at line 328 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_FUNCTIONS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_evolve_neurons()
_Bool XCS::get_cond_evolve_neurons () inline
Definition at line 327 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_evolve_weights()
_Bool XCS::get_cond_evolve_weights () inline
Definition at line 326 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_hidden_activation()
int XCS::get_cond_hidden_activation () inline
Definition at line 330 of file python_wrapper.cpp.
References XCSF::COND_HIDDEN_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
get_cond_max_neurons()
p::list XCS::get_cond_max_neurons () inline
Definition at line 266 of file python_wrapper.cpp.
References XCSF::COND_MAX_NEURONS, and MAX_LAYERS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_num_neurons()
p::list XCS::get_cond_num_neurons () inline
Definition at line 258 of file python_wrapper.cpp.
References XCSF::COND_NUM_NEURONS, and MAX_LAYERS.
Referenced by BOOST_PYTHON_MODULE().
get_cond_output_activation()
int XCS::get_cond_output_activation () inline
Definition at line 329 of file python_wrapper.cpp.
References XCSF::COND_OUTPUT_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
get_cond_smin()
double XCS::get_cond_smin () inline
Definition at line 324 of file python_wrapper.cpp.
References XCSF::COND_SMIN.
Referenced by BOOST_PYTHON_MODULE().
get_cond_type()
int XCS::get_cond_type () inline
Definition at line 308 of file python_wrapper.cpp.
References XCSF::COND_TYPE.
Referenced by BOOST_PYTHON_MODULE().
get_delta()
double XCS::get_delta () inline
Definition at line 298 of file python_wrapper.cpp.
References XCSF::DELTA.
Referenced by BOOST_PYTHON_MODULE().
get_dgp_num_nodes()
int XCS::get_dgp_num_nodes () inline
Definition at line 341 of file python_wrapper.cpp.
References XCSF::DGP_NUM_NODES.
Referenced by BOOST_PYTHON_MODULE().
get_e_mutation()
double XCS::get_e_mutation () inline
Definition at line 313 of file python_wrapper.cpp.
References XCSF::E_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
get_ea_select_size()
double XCS::get_ea_select_size () inline
Definition at line 318 of file python_wrapper.cpp.
References XCSF::EA_SELECT_SIZE.
Referenced by BOOST_PYTHON_MODULE().
get_ea_select_type()
int XCS::get_ea_select_type () inline
Definition at line 317 of file python_wrapper.cpp.
References XCSF::EA_SELECT_TYPE.
Referenced by BOOST_PYTHON_MODULE().
get_ea_subsumption()
_Bool XCS::get_ea_subsumption () inline
Definition at line 353 of file python_wrapper.cpp.
References XCSF::EA_SUBSUMPTION.
Referenced by BOOST_PYTHON_MODULE().
get_eps_0()
double XCS::get_eps_0 () inline
Definition at line 299 of file python_wrapper.cpp.
References XCSF::EPS_0.
Referenced by BOOST_PYTHON_MODULE().
get_err_reduc()
double XCS::get_err_reduc () inline
Definition at line 300 of file python_wrapper.cpp.
References XCSF::ERR_REDUC.
Referenced by BOOST_PYTHON_MODULE().
get_f_mutation()
double XCS::get_f_mutation () inline
Definition at line 312 of file python_wrapper.cpp.
References XCSF::F_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
get_fit_reduc()
double XCS::get_fit_reduc () inline
Definition at line 301 of file python_wrapper.cpp.
References XCSF::FIT_REDUC.
Referenced by BOOST_PYTHON_MODULE().
get_gamma()
double XCS::get_gamma () inline
Definition at line 370 of file python_wrapper.cpp.
References XCSF::GAMMA.
Referenced by BOOST_PYTHON_MODULE().
get_gp_init_depth()
int XCS::get_gp_init_depth () inline
Definition at line 346 of file python_wrapper.cpp.
References XCSF::GP_INIT_DEPTH.
Referenced by BOOST_PYTHON_MODULE().
get_gp_num_cons()
int XCS::get_gp_num_cons () inline
Definition at line 345 of file python_wrapper.cpp.
References XCSF::GP_NUM_CONS.
Referenced by BOOST_PYTHON_MODULE().
get_init_error()
double XCS::get_init_error () inline
Definition at line 302 of file python_wrapper.cpp.
References XCSF::INIT_ERROR.
Referenced by BOOST_PYTHON_MODULE().
get_init_fitness()
double XCS::get_init_fitness () inline
Definition at line 303 of file python_wrapper.cpp.
References XCSF::INIT_FITNESS.
Referenced by BOOST_PYTHON_MODULE().
get_lambda()
int XCS::get_lambda () inline
Definition at line 316 of file python_wrapper.cpp.
References XCSF::LAMBDA.
Referenced by BOOST_PYTHON_MODULE().
get_loss_func()
int XCS::get_loss_func () inline
Definition at line 295 of file python_wrapper.cpp.
References XCSF::LOSS_FUNC.
Referenced by BOOST_PYTHON_MODULE().
get_m_probation()
int XCS::get_m_probation () inline
Definition at line 305 of file python_wrapper.cpp.
References XCSF::M_PROBATION.
Referenced by BOOST_PYTHON_MODULE().
get_max_con()
double XCS::get_max_con () inline
Definition at line 322 of file python_wrapper.cpp.
References XCSF::COND_MAX.
Referenced by BOOST_PYTHON_MODULE().
get_max_k()
int XCS::get_max_k () inline
Definition at line 343 of file python_wrapper.cpp.
References XCSF::MAX_K.
Referenced by BOOST_PYTHON_MODULE().
get_max_neuron_mod()
int XCS::get_max_neuron_mod () inline
Definition at line 340 of file python_wrapper.cpp.
References XCSF::MAX_NEURON_MOD.
Referenced by BOOST_PYTHON_MODULE().
get_max_t()
int XCS::get_max_t () inline
Definition at line 344 of file python_wrapper.cpp.
References XCSF::MAX_T.
Referenced by BOOST_PYTHON_MODULE().
get_max_trials()
int XCS::get_max_trials () inline
Definition at line 292 of file python_wrapper.cpp.
References XCSF::MAX_TRIALS.
Referenced by BOOST_PYTHON_MODULE().
get_mfrac()
double XCS::get_mfrac () inline
Definition at line 368 of file python_wrapper.cpp.
References XCSF::mfrac.
Referenced by BOOST_PYTHON_MODULE().
get_min_con()
double XCS::get_min_con () inline
Definition at line 323 of file python_wrapper.cpp.
References XCSF::COND_MIN.
Referenced by BOOST_PYTHON_MODULE().
get_msetsize()
double XCS::get_msetsize () inline
Definition at line 367 of file python_wrapper.cpp.
References XCSF::msetsize.
Referenced by BOOST_PYTHON_MODULE().
get_nu()
double XCS::get_nu () inline
Definition at line 304 of file python_wrapper.cpp.
References XCSF::NU.
Referenced by BOOST_PYTHON_MODULE().
get_num_actions()
double XCS::get_num_actions () inline
Definition at line 360 of file python_wrapper.cpp.
References XCSF::num_actions.
Referenced by BOOST_PYTHON_MODULE().
get_num_x_vars()
double XCS::get_num_x_vars () inline
Definition at line 358 of file python_wrapper.cpp.
References XCSF::num_x_vars.
Referenced by BOOST_PYTHON_MODULE().
get_num_y_vars()
double XCS::get_num_y_vars () inline
Definition at line 359 of file python_wrapper.cpp.
References XCSF::num_y_vars.
Referenced by BOOST_PYTHON_MODULE().
get_omp_num_threads()
int XCS::get_omp_num_threads () inline
Definition at line 290 of file python_wrapper.cpp.
References XCSF::OMP_NUM_THREADS.
Referenced by BOOST_PYTHON_MODULE().
get_p_crossover()
double XCS::get_p_crossover () inline
Definition at line 310 of file python_wrapper.cpp.
References XCSF::P_CROSSOVER.
Referenced by BOOST_PYTHON_MODULE().
get_p_explore()
double XCS::get_p_explore () inline
Definition at line 371 of file python_wrapper.cpp.
References XCSF::P_EXPLORE.
Referenced by BOOST_PYTHON_MODULE().
get_p_mutation()
double XCS::get_p_mutation () inline
Definition at line 311 of file python_wrapper.cpp.
References XCSF::P_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
get_perf_avg_trials()
int XCS::get_perf_avg_trials () inline
Definition at line 293 of file python_wrapper.cpp.
References XCSF::PERF_AVG_TRIALS.
Referenced by BOOST_PYTHON_MODULE().
get_pop_init()
_Bool XCS::get_pop_init () inline
Definition at line 291 of file python_wrapper.cpp.
References XCSF::POP_INIT.
Referenced by BOOST_PYTHON_MODULE().
get_pop_max_size()
int XCS::get_pop_max_size () inline
Definition at line 294 of file python_wrapper.cpp.
References XCSF::POP_SIZE.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_cond_size()
double XCS::get_pop_mean_cond_size () inline
Definition at line 362 of file python_wrapper.cpp.
References clset_mean_cond_size(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_mu()
double XCS::get_pop_mean_mu (int m) inline
Definition at line 361 of file python_wrapper.cpp.
References clset_mean_mut(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_pred_eta()
double XCS::get_pop_mean_pred_eta (int layer) inline
Definition at line 364 of file python_wrapper.cpp.
References clset_mean_eta(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_pred_layers()
double XCS::get_pop_mean_pred_layers () inline
Definition at line 366 of file python_wrapper.cpp.
References clset_mean_layers(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_pred_neurons()
double XCS::get_pop_mean_pred_neurons (int layer) inline
Definition at line 365 of file python_wrapper.cpp.
References clset_mean_neurons(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_mean_pred_size()
double XCS::get_pop_mean_pred_size () inline
Definition at line 363 of file python_wrapper.cpp.
References clset_mean_pred_size(), and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_num()
int XCS::get_pop_num () inline
Definition at line 356 of file python_wrapper.cpp.
References SET::num, and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
get_pop_size()
int XCS::get_pop_size () inline
Definition at line 355 of file python_wrapper.cpp.
References XCSF::pset, and SET::size.
Referenced by BOOST_PYTHON_MODULE().
get_pred_eta()
double XCS::get_pred_eta () inline
Definition at line 347 of file python_wrapper.cpp.
References XCSF::PRED_ETA.
Referenced by BOOST_PYTHON_MODULE().
get_pred_evolve_eta()
_Bool XCS::get_pred_evolve_eta () inline
Definition at line 337 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_ETA.
Referenced by BOOST_PYTHON_MODULE().
get_pred_evolve_functions()
_Bool XCS::get_pred_evolve_functions () inline
Definition at line 336 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_FUNCTIONS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_evolve_neurons()
_Bool XCS::get_pred_evolve_neurons () inline
Definition at line 335 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_evolve_weights()
_Bool XCS::get_pred_evolve_weights () inline
Definition at line 334 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_hidden_activation()
int XCS::get_pred_hidden_activation () inline
Definition at line 332 of file python_wrapper.cpp.
References XCSF::PRED_HIDDEN_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
get_pred_max_neurons()
p::list XCS::get_pred_max_neurons () inline
Definition at line 282 of file python_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_MAX_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_momentum()
double XCS::get_pred_momentum () inline
Definition at line 333 of file python_wrapper.cpp.
References XCSF::PRED_MOMENTUM.
Referenced by BOOST_PYTHON_MODULE().
get_pred_num_neurons()
p::list XCS::get_pred_num_neurons () inline
Definition at line 274 of file python_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_NUM_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_output_activation()
int XCS::get_pred_output_activation () inline
Definition at line 331 of file python_wrapper.cpp.
References XCSF::PRED_OUTPUT_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
get_pred_reset()
_Bool XCS::get_pred_reset () inline
Definition at line 339 of file python_wrapper.cpp.
References XCSF::PRED_RESET.
Referenced by BOOST_PYTHON_MODULE().
get_pred_rls_lambda()
double XCS::get_pred_rls_lambda () inline
Definition at line 351 of file python_wrapper.cpp.
References XCSF::PRED_RLS_LAMBDA.
Referenced by BOOST_PYTHON_MODULE().
get_pred_rls_scale_factor()
double XCS::get_pred_rls_scale_factor () inline
Definition at line 350 of file python_wrapper.cpp.
References XCSF::PRED_RLS_SCALE_FACTOR.
Referenced by BOOST_PYTHON_MODULE().
get_pred_sgd_weights()
_Bool XCS::get_pred_sgd_weights () inline
Definition at line 338 of file python_wrapper.cpp.
References XCSF::PRED_SGD_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
get_pred_type()
int XCS::get_pred_type () inline
Definition at line 309 of file python_wrapper.cpp.
References XCSF::PRED_TYPE.
Referenced by BOOST_PYTHON_MODULE().
get_pred_x0()
double XCS::get_pred_x0 () inline
Definition at line 349 of file python_wrapper.cpp.
References XCSF::PRED_X0.
Referenced by BOOST_PYTHON_MODULE().
get_reset_states()
_Bool XCS::get_reset_states () inline
Definition at line 342 of file python_wrapper.cpp.
References XCSF::RESET_STATES.
Referenced by BOOST_PYTHON_MODULE().
get_s_mutation()
double XCS::get_s_mutation () inline
Definition at line 314 of file python_wrapper.cpp.
References XCSF::S_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
get_sam_min()
double XCS::get_sam_min () inline
Definition at line 319 of file python_wrapper.cpp.
References XCSF::SAM_MIN.
Referenced by BOOST_PYTHON_MODULE().
get_sam_num()
int XCS::get_sam_num () inline
Definition at line 320 of file python_wrapper.cpp.
References XCSF::SAM_NUM.
Referenced by BOOST_PYTHON_MODULE().
get_sam_type()
int XCS::get_sam_type () inline
Definition at line 321 of file python_wrapper.cpp.
References XCSF::SAM_TYPE.
Referenced by BOOST_PYTHON_MODULE().
get_set_subsumption()
_Bool XCS::get_set_subsumption () inline
Definition at line 354 of file python_wrapper.cpp.
References XCSF::SET_SUBSUMPTION.
Referenced by BOOST_PYTHON_MODULE().
get_teletransportation()
int XCS::get_teletransportation () inline
Definition at line 369 of file python_wrapper.cpp.
References XCSF::TELETRANSPORTATION.
Referenced by BOOST_PYTHON_MODULE().
get_theta_del()
int XCS::get_theta_del () inline
Definition at line 306 of file python_wrapper.cpp.
References XCSF::THETA_DEL.
Referenced by BOOST_PYTHON_MODULE().
get_theta_ea()
double XCS::get_theta_ea () inline
Definition at line 315 of file python_wrapper.cpp.
References XCSF::THETA_EA.
Referenced by BOOST_PYTHON_MODULE().
get_theta_sub()
int XCS::get_theta_sub () inline
Definition at line 352 of file python_wrapper.cpp.
References XCSF::THETA_SUB.
Referenced by BOOST_PYTHON_MODULE().
get_time()
int XCS::get_time () inline
Definition at line 357 of file python_wrapper.cpp.
References XCSF::time.
Referenced by BOOST_PYTHON_MODULE().
load()
size_t XCS::load (char * fname) inline
Definition at line 123 of file python_wrapper.cpp.
References xcsf_load().
Referenced by BOOST_PYTHON_MODULE().
predict()
np::ndarray XCS::predict (np::ndarray & T) inline
Definition at line 224 of file python_wrapper.cpp.
References XCSF::num_y_vars, and xcsf_predict().
Referenced by BOOST_PYTHON_MODULE().
print_pop()
void XCS::print_pop (_Bool printc, _Bool printa, _Bool printp) inline
Definition at line 252 of file python_wrapper.cpp.
References xcsf_print_pop().
Referenced by BOOST_PYTHON_MODULE().
save()
size_t XCS::save (char * fname) inline
Definition at line 122 of file python_wrapper.cpp.
References xcsf_save().
Referenced by BOOST_PYTHON_MODULE().
score()
double XCS::score (np::ndarray & test_X, np::ndarray & test_Y) inline
Definition at line 238 of file python_wrapper.cpp.
References INPUT::rows, INPUT::x, INPUT::x_cols, xcsf_score(), INPUT::y, and INPUT::y_cols.
Referenced by BOOST_PYTHON_MODULE().
set_act_type()
void XCS::set_act_type (int a) inline
Definition at line 426 of file python_wrapper.cpp.
References XCSF::ACT_TYPE.
Referenced by BOOST_PYTHON_MODULE().
set_alpha()
void XCS::set_alpha (double a) inline
Definition at line 415 of file python_wrapper.cpp.
References XCSF::ALPHA.
Referenced by BOOST_PYTHON_MODULE().
set_beta()
void XCS::set_beta (double a) inline
Definition at line 416 of file python_wrapper.cpp.
References XCSF::BETA.
Referenced by BOOST_PYTHON_MODULE().
set_cond_bits()
void XCS::set_cond_bits (double a) inline
Definition at line 444 of file python_wrapper.cpp.
References XCSF::COND_BITS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_eta()
void XCS::set_cond_eta (double a) inline
Definition at line 467 of file python_wrapper.cpp.
References XCSF::COND_ETA.
Referenced by BOOST_PYTHON_MODULE().
set_cond_evolve_functions()
void XCS::set_cond_evolve_functions (_Bool a) inline
Definition at line 447 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_FUNCTIONS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_evolve_neurons()
void XCS::set_cond_evolve_neurons (_Bool a) inline
Definition at line 446 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_evolve_weights()
void XCS::set_cond_evolve_weights (_Bool a) inline
Definition at line 445 of file python_wrapper.cpp.
References XCSF::COND_EVOLVE_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_hidden_activation()
void XCS::set_cond_hidden_activation (int a) inline
Definition at line 449 of file python_wrapper.cpp.
References XCSF::COND_HIDDEN_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
set_cond_max_neurons()
void XCS::set_cond_max_neurons (p::list & a) inline
Definition at line 389 of file python_wrapper.cpp.
References XCSF::COND_MAX_NEURONS, and MAX_LAYERS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_num_neurons()
void XCS::set_cond_num_neurons (p::list & a) inline
Definition at line 382 of file python_wrapper.cpp.
References XCSF::COND_NUM_NEURONS, and MAX_LAYERS.
Referenced by BOOST_PYTHON_MODULE().
set_cond_output_activation()
void XCS::set_cond_output_activation (int a) inline
Definition at line 448 of file python_wrapper.cpp.
References XCSF::COND_OUTPUT_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
set_cond_smin()
void XCS::set_cond_smin (double a) inline
Definition at line 443 of file python_wrapper.cpp.
References XCSF::COND_SMIN.
Referenced by BOOST_PYTHON_MODULE().
set_cond_type()
void XCS::set_cond_type (int a) inline
Definition at line 427 of file python_wrapper.cpp.
References XCSF::COND_TYPE.
Referenced by BOOST_PYTHON_MODULE().
set_delta()
void XCS::set_delta (double a) inline
Definition at line 417 of file python_wrapper.cpp.
References XCSF::DELTA.
Referenced by BOOST_PYTHON_MODULE().
set_dgp_num_nodes()
void XCS::set_dgp_num_nodes (int a) inline
Definition at line 460 of file python_wrapper.cpp.
References XCSF::DGP_NUM_NODES.
Referenced by BOOST_PYTHON_MODULE().
set_e_mutation()
void XCS::set_e_mutation (double a) inline
Definition at line 432 of file python_wrapper.cpp.
References XCSF::E_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
set_ea_select_size()
void XCS::set_ea_select_size (double a) inline
Definition at line 437 of file python_wrapper.cpp.
References XCSF::EA_SELECT_SIZE.
Referenced by BOOST_PYTHON_MODULE().
set_ea_select_type()
void XCS::set_ea_select_type (int a) inline
Definition at line 436 of file python_wrapper.cpp.
References XCSF::EA_SELECT_TYPE.
Referenced by BOOST_PYTHON_MODULE().
set_ea_subsumption()
void XCS::set_ea_subsumption (_Bool a) inline
Definition at line 472 of file python_wrapper.cpp.
References XCSF::EA_SUBSUMPTION.
Referenced by BOOST_PYTHON_MODULE().
set_eps_0()
void XCS::set_eps_0 (double a) inline
Definition at line 418 of file python_wrapper.cpp.
References XCSF::EPS_0.
Referenced by BOOST_PYTHON_MODULE().
set_err_reduc()
void XCS::set_err_reduc (double a) inline
Definition at line 419 of file python_wrapper.cpp.
References XCSF::ERR_REDUC.
Referenced by BOOST_PYTHON_MODULE().
set_f_mutation()
void XCS::set_f_mutation (double a) inline
Definition at line 431 of file python_wrapper.cpp.
References XCSF::F_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
set_fit_reduc()
void XCS::set_fit_reduc (double a) inline
Definition at line 420 of file python_wrapper.cpp.
References XCSF::FIT_REDUC.
Referenced by BOOST_PYTHON_MODULE().
set_gamma()
void XCS::set_gamma (double a) inline
Definition at line 475 of file python_wrapper.cpp.
References XCSF::GAMMA.
Referenced by BOOST_PYTHON_MODULE().
set_gp_init_depth()
void XCS::set_gp_init_depth (int a) inline
Definition at line 465 of file python_wrapper.cpp.
References XCSF::GP_INIT_DEPTH.
Referenced by BOOST_PYTHON_MODULE().
set_gp_num_cons()
void XCS::set_gp_num_cons (int a) inline
Definition at line 464 of file python_wrapper.cpp.
References XCSF::GP_NUM_CONS.
Referenced by BOOST_PYTHON_MODULE().
set_init_error()
void XCS::set_init_error (double a) inline
Definition at line 421 of file python_wrapper.cpp.
References XCSF::INIT_ERROR.
Referenced by BOOST_PYTHON_MODULE().
set_init_fitness()
void XCS::set_init_fitness (double a) inline
Definition at line 422 of file python_wrapper.cpp.
References XCSF::INIT_FITNESS.
Referenced by BOOST_PYTHON_MODULE().
set_lambda()
void XCS::set_lambda (int a) inline
Definition at line 435 of file python_wrapper.cpp.
References XCSF::LAMBDA.
Referenced by BOOST_PYTHON_MODULE().
set_loss_func()
void XCS::set_loss_func (int a) inline
Definition at line 414 of file python_wrapper.cpp.
References XCSF::LOSS_FUNC, and loss_set_func().
Referenced by BOOST_PYTHON_MODULE().
set_m_probation()
void XCS::set_m_probation (int a) inline
Definition at line 424 of file python_wrapper.cpp.
References XCSF::M_PROBATION.
Referenced by BOOST_PYTHON_MODULE().
set_max_con()
void XCS::set_max_con (double a) inline
Definition at line 441 of file python_wrapper.cpp.
References XCSF::COND_MAX.
Referenced by BOOST_PYTHON_MODULE().
set_max_k()
void XCS::set_max_k (int a) inline
Definition at line 462 of file python_wrapper.cpp.
References XCSF::MAX_K.
Referenced by BOOST_PYTHON_MODULE().
set_max_neuron_mod()
void XCS::set_max_neuron_mod (int a) inline
Definition at line 459 of file python_wrapper.cpp.
References XCSF::MAX_NEURON_MOD.
Referenced by BOOST_PYTHON_MODULE().
set_max_t()
void XCS::set_max_t (int a) inline
Definition at line 463 of file python_wrapper.cpp.
References XCSF::MAX_T.
Referenced by BOOST_PYTHON_MODULE().
set_max_trials()
void XCS::set_max_trials (int a) inline
Definition at line 411 of file python_wrapper.cpp.
References XCSF::MAX_TRIALS.
Referenced by BOOST_PYTHON_MODULE().
set_min_con()
void XCS::set_min_con (double a) inline
Definition at line 442 of file python_wrapper.cpp.
References XCSF::COND_MIN.
Referenced by BOOST_PYTHON_MODULE().
set_nu()
void XCS::set_nu (double a) inline
Definition at line 423 of file python_wrapper.cpp.
References XCSF::NU.
Referenced by BOOST_PYTHON_MODULE().
set_omp_num_threads()
void XCS::set_omp_num_threads (int a) inline
Definition at line 375 of file python_wrapper.cpp.
References XCSF::OMP_NUM_THREADS.
Referenced by BOOST_PYTHON_MODULE().
set_p_crossover()
void XCS::set_p_crossover (double a) inline
Definition at line 429 of file python_wrapper.cpp.
References XCSF::P_CROSSOVER.
Referenced by BOOST_PYTHON_MODULE().
set_p_explore()
void XCS::set_p_explore (double a) inline
Definition at line 476 of file python_wrapper.cpp.
References XCSF::P_EXPLORE.
Referenced by BOOST_PYTHON_MODULE().
set_p_mutation()
void XCS::set_p_mutation (double a) inline
Definition at line 430 of file python_wrapper.cpp.
References XCSF::P_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
set_perf_avg_trials()
void XCS::set_perf_avg_trials (int a) inline
Definition at line 412 of file python_wrapper.cpp.
References XCSF::PERF_AVG_TRIALS.
Referenced by BOOST_PYTHON_MODULE().
set_pop_init()
void XCS::set_pop_init (_Bool a) inline
Definition at line 410 of file python_wrapper.cpp.
References XCSF::POP_INIT.
Referenced by BOOST_PYTHON_MODULE().
set_pop_max_size()
void XCS::set_pop_max_size (int a) inline
Definition at line 413 of file python_wrapper.cpp.
References XCSF::POP_SIZE.
Referenced by BOOST_PYTHON_MODULE().
set_pred_eta()
void XCS::set_pred_eta (double a) inline
Definition at line 466 of file python_wrapper.cpp.
References XCSF::PRED_ETA.
Referenced by BOOST_PYTHON_MODULE().
set_pred_evolve_eta()
void XCS::set_pred_evolve_eta (_Bool a) inline
Definition at line 456 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_ETA.
Referenced by BOOST_PYTHON_MODULE().
set_pred_evolve_functions()
void XCS::set_pred_evolve_functions (_Bool a) inline
Definition at line 455 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_FUNCTIONS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_evolve_neurons()
void XCS::set_pred_evolve_neurons (_Bool a) inline
Definition at line 454 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_evolve_weights()
void XCS::set_pred_evolve_weights (_Bool a) inline
Definition at line 453 of file python_wrapper.cpp.
References XCSF::PRED_EVOLVE_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_hidden_activation()
void XCS::set_pred_hidden_activation (int a) inline
Definition at line 451 of file python_wrapper.cpp.
References XCSF::PRED_HIDDEN_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
set_pred_max_neurons()
void XCS::set_pred_max_neurons (p::list & a) inline
Definition at line 403 of file python_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_MAX_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_momentum()
void XCS::set_pred_momentum (double a) inline
Definition at line 452 of file python_wrapper.cpp.
References XCSF::PRED_MOMENTUM.
Referenced by BOOST_PYTHON_MODULE().
set_pred_num_neurons()
void XCS::set_pred_num_neurons (p::list & a) inline
Definition at line 396 of file python_wrapper.cpp.
References MAX_LAYERS, and XCSF::PRED_NUM_NEURONS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_output_activation()
void XCS::set_pred_output_activation (int a) inline
Definition at line 450 of file python_wrapper.cpp.
References XCSF::PRED_OUTPUT_ACTIVATION.
Referenced by BOOST_PYTHON_MODULE().
set_pred_reset()
void XCS::set_pred_reset (_Bool a) inline
Definition at line 458 of file python_wrapper.cpp.
References XCSF::PRED_RESET.
Referenced by BOOST_PYTHON_MODULE().
set_pred_rls_lambda()
void XCS::set_pred_rls_lambda (double a) inline
Definition at line 470 of file python_wrapper.cpp.
References XCSF::PRED_RLS_LAMBDA.
Referenced by BOOST_PYTHON_MODULE().
set_pred_rls_scale_factor()
void XCS::set_pred_rls_scale_factor (double a) inline
Definition at line 469 of file python_wrapper.cpp.
References XCSF::PRED_RLS_SCALE_FACTOR.
Referenced by BOOST_PYTHON_MODULE().
set_pred_sgd_weights()
void XCS::set_pred_sgd_weights (_Bool a) inline
Definition at line 457 of file python_wrapper.cpp.
References XCSF::PRED_SGD_WEIGHTS.
Referenced by BOOST_PYTHON_MODULE().
set_pred_type()
void XCS::set_pred_type (int a) inline
Definition at line 428 of file python_wrapper.cpp.
References XCSF::PRED_TYPE.
Referenced by BOOST_PYTHON_MODULE().
set_pred_x0()
void XCS::set_pred_x0 (double a) inline
Definition at line 468 of file python_wrapper.cpp.
References XCSF::PRED_X0.
Referenced by BOOST_PYTHON_MODULE().
set_reset_states()
void XCS::set_reset_states (_Bool a) inline
Definition at line 461 of file python_wrapper.cpp.
References XCSF::RESET_STATES.
Referenced by BOOST_PYTHON_MODULE().
set_s_mutation()
void XCS::set_s_mutation (double a) inline
Definition at line 433 of file python_wrapper.cpp.
References XCSF::S_MUTATION.
Referenced by BOOST_PYTHON_MODULE().
set_sam_min()
void XCS::set_sam_min (double a) inline
Definition at line 438 of file python_wrapper.cpp.
References XCSF::SAM_MIN.
Referenced by BOOST_PYTHON_MODULE().
set_sam_num()
void XCS::set_sam_num (int a) inline
Definition at line 439 of file python_wrapper.cpp.
References XCSF::SAM_NUM.
Referenced by BOOST_PYTHON_MODULE().
set_sam_type()
void XCS::set_sam_type (int a) inline
Definition at line 440 of file python_wrapper.cpp.
References XCSF::SAM_TYPE.
Referenced by BOOST_PYTHON_MODULE().
set_set_subsumption()
void XCS::set_set_subsumption (_Bool a) inline
Definition at line 473 of file python_wrapper.cpp.
References XCSF::SET_SUBSUMPTION.
Referenced by BOOST_PYTHON_MODULE().
set_teletransportation()
void XCS::set_teletransportation (int a) inline
Definition at line 474 of file python_wrapper.cpp.
References XCSF::TELETRANSPORTATION.
Referenced by BOOST_PYTHON_MODULE().
set_theta_del()
void XCS::set_theta_del (int a) inline
Definition at line 425 of file python_wrapper.cpp.
References XCSF::THETA_DEL.
Referenced by BOOST_PYTHON_MODULE().
set_theta_ea()
void XCS::set_theta_ea (double a) inline
Definition at line 434 of file python_wrapper.cpp.
References XCSF::THETA_EA.
Referenced by BOOST_PYTHON_MODULE().
set_theta_sub()
void XCS::set_theta_sub (int a) inline
Definition at line 471 of file python_wrapper.cpp.
References XCSF::THETA_SUB.
Referenced by BOOST_PYTHON_MODULE().
single_decision()
int XCS::single_decision (np::ndarray & input, _Bool explore) inline
Definition at line 148 of file python_wrapper.cpp.
References action, XCSF::train, and xcs_single_decision().
Referenced by BOOST_PYTHON_MODULE().
single_error()
double XCS::single_error (double reward) inline
Definition at line 159 of file python_wrapper.cpp.
References xcs_single_error().
Referenced by BOOST_PYTHON_MODULE().
single_reset()
void XCS::single_reset () inline
Definition at line 127 of file python_wrapper.cpp.
References clset_free(), clset_init(), clset_kill(), clset_pop_init(), SET::list, and XCSF::pset.
Referenced by BOOST_PYTHON_MODULE().
single_update()
void XCS::single_update (double reward) inline
Definition at line 155 of file python_wrapper.cpp.
References xcs_single_update().
Referenced by BOOST_PYTHON_MODULE().
version()
double XCS::version () inline
Definition at line 121 of file python_wrapper.cpp.
References xcsf_version().
Referenced by BOOST_PYTHON_MODULE().
xcs_init()
void XCS::xcs_init (const char * filename) inline
Initialises python XCS structure.
Definition at line 94 of file python_wrapper.cpp.
References clset_init(), config_init(), XCSF::OMP_NUM_THREADS, XCSF::pset, INPUT::rows, XCSF::time, INPUT::x, INPUT::x_cols, INPUT::y, and INPUT::y_cols.
Referenced by XCS().
Field Documentation
action
int XCS::action
Current action for RL.
Definition at line 59 of file python_wrapper.cpp.
Referenced by single_decision().
aset
SET XCS::aset
Action set for RL.
Definition at line 56 of file python_wrapper.cpp.
kset
SET XCS::kset
Kill set for RL.
Definition at line 57 of file python_wrapper.cpp.
mset
SET XCS::mset
Match set for RL.
Definition at line 55 of file python_wrapper.cpp.
state
double* XCS::state
Current input state for RL.
Definition at line 58 of file python_wrapper.cpp.
test_data
INPUT* XCS::test_data
Currrent test data for supervised learning.
Definition at line 61 of file python_wrapper.cpp.
train_data
INPUT* XCS::train_data
Current training data for supervised learning.
Definition at line 60 of file python_wrapper.cpp.
xcs
XCSF XCS::xcs
XCSF data structure.
Definition at line 54 of file python_wrapper.cpp.
The documentation for this struct was generated from the following file:
python_wrapper.cpp