XCSF: LayerVtbl Struct Reference
LayerVtbl Struct Reference
Neural network layer interface data structure.
#include <neural_layer.h>
Data Fields
_Bool(* layer_impl_mutate)(const XCSF *xcsf, LAYER *l, const double *mu)
Performs layer mutation.
void(* layer_impl_resize)(const XCSF *xcsf, LAYER *l, const LAYER *prev)
Resizes a layer using the previous layer's inputs.
LAYER *(* layer_impl_copy)(const XCSF *xcsf, const LAYER *from)
Creates and returns a copy of a specified layer.
void(* layer_impl_free)(const XCSF *xcsf, const LAYER *l)
Frees the memory used by the layer.
void(* layer_impl_rand)(const XCSF *xcsf, const LAYER *l)
Randomises a layer.
void(* layer_impl_print)(const XCSF *xcsf, const LAYER *l, _Bool print_weights)
Prints the layer.
void(* layer_impl_update)(const XCSF *xcsf, const LAYER *l, double eta)
Updates the weights and biases of a layer.
void(* layer_impl_backward)(const XCSF *xcsf, const LAYER *l, const NET *net)
Backward propagates the error through a layer.
void(* layer_impl_forward)(const XCSF *xcsf, const LAYER *l, const double *input)
Forward propagates an input through the layer.
double *(* layer_impl_output)(const XCSF *xcsf, const LAYER *l)
Returns the outputs of a layer.
size_t(* layer_impl_save)(const XCSF *xcsf, const LAYER *l, FILE *fp)
Writes the layer to a binary file.
size_t(* layer_impl_load)(const XCSF *xcsf, LAYER *l, FILE *fp)
Reads the layer from a binary file.
Detailed Description
Neural network layer interface data structure.
Neural network layer implementations must implement these functions.
Definition at line 66 of file neural_layer.h.
Field Documentation
layer_impl_backward
void(* LayerVtbl::layer_impl_backward) (const XCSF *xcsf, const LAYER *l, const NET *net)
Backward propagates the error through a layer.
Parameters
xcsf The XCSF data structure.
l The layer to be backward propagated.
net The network being backward propagated.
Definition at line 120 of file neural_layer.h.
Referenced by layer_backward().
layer_impl_copy
LAYER*(* LayerVtbl::layer_impl_copy) (const XCSF *xcsf, const LAYER *from)
Creates and returns a copy of a specified layer.
Parameters
xcsf The XCSF data structure.
from The source layer.
Returns
A new copied layer.
Definition at line 88 of file neural_layer.h.
Referenced by layer_copy().
layer_impl_forward
void(* LayerVtbl::layer_impl_forward) (const XCSF *xcsf, const LAYER *l, const double *input)
Forward propagates an input through the layer.
Parameters
xcsf The XCSF data structure.
l The layer to be forward propagated.
input The input to the layer.
Definition at line 127 of file neural_layer.h.
Referenced by layer_forward().
layer_impl_free
void(* LayerVtbl::layer_impl_free) (const XCSF *xcsf, const LAYER *l)
Frees the memory used by the layer.
Parameters
xcsf The XCSF data structure.
l The layer to be freed.
Definition at line 94 of file neural_layer.h.
Referenced by layer_free().
layer_impl_load
size_t(* LayerVtbl::layer_impl_load) (const XCSF *xcsf, LAYER *l, FILE *fp)
Reads the layer from a binary file.
Parameters
xcsf The XCSF data structure.
l The layer to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 150 of file neural_layer.h.
Referenced by layer_load().
layer_impl_mutate
_Bool(* LayerVtbl::layer_impl_mutate) (const XCSF *xcsf, LAYER *l, const double *mu)
Performs layer mutation.
Parameters
xcsf The XCSF data structure.
l The layer to mutate.
Returns
Whether any alterations were made.
Definition at line 73 of file neural_layer.h.
Referenced by layer_mutate().
layer_impl_output
double*(* LayerVtbl::layer_impl_output) (const XCSF *xcsf, const LAYER *l)
Returns the outputs of a layer.
Parameters
xcsf The XCSF data structure.
l The layer whose outputs are to be returned.
Returns
The layer outputs.
Definition at line 134 of file neural_layer.h.
Referenced by layer_output().
layer_impl_print
void(* LayerVtbl::layer_impl_print) (const XCSF *xcsf, const LAYER *l, _Bool print_weights)
Prints the layer.
Parameters
xcsf The XCSF data structure.
l The layer to be printed.
print_weights Whether to print the weights.
Definition at line 107 of file neural_layer.h.
Referenced by layer_print().
layer_impl_rand
void(* LayerVtbl::layer_impl_rand) (const XCSF *xcsf, const LAYER *l)
Randomises a layer.
Parameters
xcsf The XCSF data structure.
l The layer to be randomised.
Definition at line 100 of file neural_layer.h.
Referenced by layer_rand().
layer_impl_resize
void(* LayerVtbl::layer_impl_resize) (const XCSF *xcsf, LAYER *l, const LAYER *prev)
Resizes a layer using the previous layer's inputs.
Parameters
xcsf The XCSF data structure.
l The layer to mutate.
prev The layer prior to the one being mutated.
Returns
Whether any alterations were made.
Definition at line 81 of file neural_layer.h.
Referenced by layer_resize().
layer_impl_save
size_t(* LayerVtbl::layer_impl_save) (const XCSF *xcsf, const LAYER *l, FILE *fp)
Writes the layer to a binary file.
Parameters
xcsf The XCSF data structure.
l The layer to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 142 of file neural_layer.h.
Referenced by layer_save().
layer_impl_update
void(* LayerVtbl::layer_impl_update) (const XCSF *xcsf, const LAYER *l, double eta)
Updates the weights and biases of a layer.
Parameters
xcsf The XCSF data structure.
l The layer to be updated.
Definition at line 113 of file neural_layer.h.
Referenced by layer_update().
The documentation for this struct was generated from the following file:
neural_layer.h