XCSF: EnvVtbl Struct Reference
EnvVtbl Struct Reference
Built-in problem environment interface data structure.
#include <env.h>
Data Fields
_Bool(* env_impl_isreset)(XCSF *xcsf)
Returns whether the environment needs to be reset.
_Bool(* env_impl_multistep)(XCSF *xcsf)
Returns whether the environment is a multistep problem.
double(* env_impl_execute)(XCSF *xcsf, int action)
Executes the specified action and returns the payoff.
double(* env_impl_max_payoff)(XCSF *xcsf)
Returns the maximum payoff value possible in the environment.
double *(* env_impl_get_state)(XCSF *xcsf)
Returns the current environment perceptions.
void(* env_impl_free)(XCSF *xcsf)
Frees the environment.
void(* env_impl_reset)(XCSF *xcsf)
Resets the environment.
Detailed Description
Built-in problem environment interface data structure.
Environment implementations must implement these functions.
Definition at line 32 of file env.h.
Field Documentation
env_impl_execute
double(* EnvVtbl::env_impl_execute) (XCSF *xcsf, int action)
Executes the specified action and returns the payoff.
Parameters
xcsf The XCSF data structure.
action The action to perform.
Returns
The payoff from performing the action.
Definition at line 51 of file env.h.
Referenced by env_execute().
env_impl_free
void(* EnvVtbl::env_impl_free) (XCSF *xcsf)
Frees the environment.
Parameters
xcsf The XCSF data structure.
Definition at line 68 of file env.h.
Referenced by env_free().
env_impl_get_state
double*(* EnvVtbl::env_impl_get_state) (XCSF *xcsf)
Returns the current environment perceptions.
Parameters
xcsf The XCSF data structure.
Returns
The current perceptions.
Definition at line 63 of file env.h.
Referenced by env_get_state().
env_impl_isreset
_Bool(* EnvVtbl::env_impl_isreset) (XCSF *xcsf)
Returns whether the environment needs to be reset.
Parameters
xcsf The XCSF data structure.
Returns
Whether the environment needs to be reset.
Definition at line 38 of file env.h.
Referenced by env_is_reset().
env_impl_max_payoff
double(* EnvVtbl::env_impl_max_payoff) (XCSF *xcsf)
Returns the maximum payoff value possible in the environment.
Parameters
xcsf The XCSF data structure.
Returns
The maximum payoff.
Definition at line 57 of file env.h.
Referenced by env_max_payoff().
env_impl_multistep
_Bool(* EnvVtbl::env_impl_multistep) (XCSF *xcsf)
Returns whether the environment is a multistep problem.
Parameters
xcsf The XCSF data structure.
Returns
Whether the environment is multistep.
Definition at line 44 of file env.h.
Referenced by env_multistep().
env_impl_reset
void(* EnvVtbl::env_impl_reset) (XCSF *xcsf)
Resets the environment.
Parameters
xcsf The XCSF data structure.
Definition at line 73 of file env.h.
Referenced by env_reset().
The documentation for this struct was generated from the following file:
env.h