XCSF: DSFMT_T Struct Reference
DSFMT_T Struct Reference
#include <dSFMT.h>
Data Fields
w128_t status [((19937 - 128)/104+1)+1]
int idx
Detailed Description
the 128-bit internal state array
Definition at line 166 of file dSFMT.h.
Field Documentation
idx
int DSFMT_T::idx
Definition at line 168 of file dSFMT.h.
Referenced by dsfmt_chk_init_by_array(), dsfmt_chk_init_gen_rand(), dsfmt_genrand_close1_open2(), dsfmt_genrand_open_open(), and dsfmt_genrand_uint32().
status
w128_t DSFMT_T::status[((19937 - 128)/104+1)+1]
Definition at line 167 of file dSFMT.h.
Referenced by dsfmt_chk_init_by_array(), dsfmt_chk_init_gen_rand(), dsfmt_gen_rand_all(), dsfmt_genrand_close1_open2(), dsfmt_genrand_open_open(), dsfmt_genrand_uint32(), gen_rand_array_c0o1(), gen_rand_array_c1o2(), gen_rand_array_o0c1(), gen_rand_array_o0o1(), initial_mask(), and period_certification().
The documentation for this struct was generated from the following file:
dSFMT.h