XCSF: PredVtbl Struct Reference
PredVtbl Struct Reference
Prediction interface data structure.
#include <prediction.h>
Data Fields
_Bool(* pred_impl_crossover)(const XCSF *xcsf, const CL *c1, const CL *c2)
_Bool(* pred_impl_mutate)(const XCSF *xcsf, const CL *c)
void(* pred_impl_compute)(const XCSF *xcsf, const CL *c, const double *x)
void(* pred_impl_copy)(const XCSF *xcsf, CL *dest, const CL *src)
void(* pred_impl_free)(const XCSF *xcsf, const CL *c)
void(* pred_impl_init)(const XCSF *xcsf, CL *c)
void(* pred_impl_print)(const XCSF *xcsf, const CL *c)
void(* pred_impl_update)(const XCSF *xcsf, const CL *c, const double *x, const double *y)
int(* pred_impl_size)(const XCSF *xcsf, const CL *c)
size_t(* pred_impl_save)(const XCSF *xcsf, const CL *c, FILE *fp)
size_t(* pred_impl_load)(const XCSF *xcsf, CL *c, FILE *fp)
Detailed Description
Prediction interface data structure.
Prediction implementations must implement these functions.
Definition at line 32 of file prediction.h.
Field Documentation
pred_impl_compute
void(* PredVtbl::pred_impl_compute) (const XCSF *xcsf, const CL *c, const double *x)
Definition at line 35 of file prediction.h.
Referenced by pred_compute().
pred_impl_copy
void(* PredVtbl::pred_impl_copy) (const XCSF *xcsf, CL *dest, const CL *src)
Definition at line 36 of file prediction.h.
Referenced by pred_copy().
pred_impl_crossover
_Bool(* PredVtbl::pred_impl_crossover) (const XCSF *xcsf, const CL *c1, const CL *c2)
Definition at line 33 of file prediction.h.
Referenced by pred_crossover().
pred_impl_free
void(* PredVtbl::pred_impl_free) (const XCSF *xcsf, const CL *c)
Definition at line 37 of file prediction.h.
Referenced by pred_free().
pred_impl_init
void(* PredVtbl::pred_impl_init) (const XCSF *xcsf, CL *c)
Definition at line 38 of file prediction.h.
Referenced by pred_init().
pred_impl_load
size_t(* PredVtbl::pred_impl_load) (const XCSF *xcsf, CL *c, FILE *fp)
Definition at line 43 of file prediction.h.
Referenced by pred_load().
pred_impl_mutate
_Bool(* PredVtbl::pred_impl_mutate) (const XCSF *xcsf, const CL *c)
Definition at line 34 of file prediction.h.
Referenced by pred_mutate().
pred_impl_print
void(* PredVtbl::pred_impl_print) (const XCSF *xcsf, const CL *c)
Definition at line 39 of file prediction.h.
Referenced by pred_print().
pred_impl_save
size_t(* PredVtbl::pred_impl_save) (const XCSF *xcsf, const CL *c, FILE *fp)
Definition at line 42 of file prediction.h.
Referenced by pred_save().
pred_impl_size
int(* PredVtbl::pred_impl_size) (const XCSF *xcsf, const CL *c)
Definition at line 41 of file prediction.h.
Referenced by pred_size().
pred_impl_update
void(* PredVtbl::pred_impl_update) (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Definition at line 40 of file prediction.h.
Referenced by pred_update().
The documentation for this struct was generated from the following file:
prediction.h