XCSF: ActVtbl Struct Reference
ActVtbl Struct Reference
Action interface data structure.
#include <action.h>
Data Fields
_Bool(* act_impl_general)(const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the action of classifier c1 is more general than c2.
_Bool(* act_impl_crossover)(const XCSF *xcsf, CL *c1, CL *c2)
Performs classifier action crossover.
_Bool(* act_impl_mutate)(const XCSF *xcsf, CL *c)
Performs classifier action mutation.
int(* act_impl_compute)(const XCSF *xcsf, CL *c, const double *x)
Computes the current classifier action using the input.
void(* act_impl_copy)(const XCSF *xcsf, CL *to, const CL *from)
Copies the action from one classifier to another.
void(* act_impl_cover)(const XCSF *xcsf, CL *c, const double *x, int action)
Generates an action that matches the specified value.
void(* act_impl_free)(const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier action.
void(* act_impl_init)(const XCSF *xcsf, CL *c)
Initialises a classifier's action.
void(* act_impl_rand)(const XCSF *xcsf, CL *c)
Randomises a classifier's action.
void(* act_impl_print)(const XCSF *xcsf, const CL *c)
Prints the classifier action.
void(* act_impl_update)(const XCSF *xcsf, CL *c, const double *x, const double *y)
Updates the classifier's action.
size_t(* act_impl_save)(const XCSF *xcsf, const CL *c, FILE *fp)
Writes the action to a binary file.
size_t(* act_impl_load)(const XCSF *xcsf, CL *c, FILE *fp)
Reads the action from a binary file.
Detailed Description
Action interface data structure.
Action implementations must implement these functions.
Definition at line 32 of file action.h.
Field Documentation
act_impl_compute
int(* ActVtbl::act_impl_compute) (const XCSF *xcsf, CL *c, const double *x)
Computes the current classifier action using the input.
Parameters
xcsf The XCSF data structure.
c The classifier calculating the action.
x The input state.
Returns
The classifier's action.
Definition at line 63 of file action.h.
Referenced by act_compute().
act_impl_copy
void(* ActVtbl::act_impl_copy) (const XCSF *xcsf, CL *to, const CL *from)
Copies the action from one classifier to another.
Parameters
xcsf The XCSF data structure.
to The destination classifier.
from The source classifier.
Definition at line 70 of file action.h.
Referenced by act_copy().
act_impl_cover
void(* ActVtbl::act_impl_cover) (const XCSF *xcsf, CL *c, const double *x, int action)
Generates an action that matches the specified value.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is being covered.
x The input state to cover.
action The action to cover.
Definition at line 78 of file action.h.
Referenced by act_cover().
act_impl_crossover
_Bool(* ActVtbl::act_impl_crossover) (const XCSF *xcsf, CL *c1, CL *c2)
Performs classifier action crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier whose action is being crossed.
c2 The second classifier whose action is being crossed.
Returns
Whether any alterations were made.
Definition at line 48 of file action.h.
Referenced by act_crossover().
act_impl_free
void(* ActVtbl::act_impl_free) (const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be freed.
Definition at line 84 of file action.h.
Referenced by act_free().
act_impl_general
_Bool(* ActVtbl::act_impl_general) (const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the action of classifier c1 is more general than c2.
Parameters
xcsf The XCSF data structure.
c1 The classifier whose action is tested to be more general.
c2 The classifier whose action is tested to be more specific.
Returns
Whether the action of c1 is more general than c2.
Definition at line 40 of file action.h.
Referenced by act_general().
act_impl_init
void(* ActVtbl::act_impl_init) (const XCSF *xcsf, CL *c)
Initialises a classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be initialised.
Definition at line 90 of file action.h.
Referenced by act_init().
act_impl_load
size_t(* ActVtbl::act_impl_load) (const XCSF *xcsf, CL *c, FILE *fp)
Reads the action from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 126 of file action.h.
Referenced by act_load().
act_impl_mutate
_Bool(* ActVtbl::act_impl_mutate) (const XCSF *xcsf, CL *c)
Performs classifier action mutation.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is being mutated.
Returns
Whether any alterations were made.
Definition at line 55 of file action.h.
Referenced by act_mutate().
act_impl_print
void(* ActVtbl::act_impl_print) (const XCSF *xcsf, const CL *c)
Prints the classifier action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be printed.
Definition at line 102 of file action.h.
Referenced by act_print().
act_impl_rand
void(* ActVtbl::act_impl_rand) (const XCSF *xcsf, CL *c)
Randomises a classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be randomised.
Definition at line 96 of file action.h.
Referenced by act_rand().
act_impl_save
size_t(* ActVtbl::act_impl_save) (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the action to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 118 of file action.h.
Referenced by act_save().
act_impl_update
void(* ActVtbl::act_impl_update) (const XCSF *xcsf, CL *c, const double *x, const double *y)
Updates the classifier's action.
Parameters
xcsf The XCSF data structure.
c The classifier whose action is to be updated.
x The input state.
y The payoff value.
Definition at line 110 of file action.h.
Referenced by act_update().
The documentation for this struct was generated from the following file:
action.h