XCSF: CondVtbl Struct Reference
CondVtbl Struct Reference
Condition interface data structure.
#include <condition.h>
Data Fields
_Bool(* cond_impl_crossover)(const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier condition crossover.
_Bool(* cond_impl_general)(const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the condition of classifier c1 is more general than c2.
_Bool(* cond_impl_match)(const XCSF *xcsf, const CL *c, const double *x)
Calculates whether the condition matches the input.
_Bool(* cond_impl_mutate)(const XCSF *xcsf, const CL *c)
Performs classifier condition mutation.
void(* cond_impl_copy)(const XCSF *xcsf, CL *to, const CL *from)
Copies the condition from one classifier to another.
void(* cond_impl_cover)(const XCSF *xcsf, const CL *c, const double *x)
Generates a condition that matches the current input.
void(* cond_impl_free)(const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier condition.
void(* cond_impl_init)(const XCSF *xcsf, CL *c)
Initialises a classifier's condition.
void(* cond_impl_print)(const XCSF *xcsf, const CL *c)
Prints the classifier condition.
void(* cond_impl_update)(const XCSF *xcsf, const CL *c, const double *x, const double *y)
Updates the classifier's condition.
int(* cond_impl_size)(const XCSF *xcsf, const CL *c)
Returns the size of the classifier condition.
size_t(* cond_impl_save)(const XCSF *xcsf, const CL *c, FILE *fp)
Writes the condition to a binary file.
size_t(* cond_impl_load)(const XCSF *xcsf, CL *c, FILE *fp)
Reads the condition from a binary file.
Detailed Description
Condition interface data structure.
Condition implementations must implement these functions.
Definition at line 32 of file condition.h.
Field Documentation
cond_impl_copy
void(* CondVtbl::cond_impl_copy) (const XCSF *xcsf, CL *to, const CL *from)
Copies the condition from one classifier to another.
Parameters
xcsf The XCSF data structure.
to The destination classifier.
from The source classifier.
Definition at line 70 of file condition.h.
Referenced by cond_copy().
cond_impl_cover
void(* CondVtbl::cond_impl_cover) (const XCSF *xcsf, const CL *c, const double *x)
Generates a condition that matches the current input.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is being covered.
x The input state to cover.
Definition at line 77 of file condition.h.
Referenced by cond_cover().
cond_impl_crossover
_Bool(* CondVtbl::cond_impl_crossover) (const XCSF *xcsf, const CL *c1, const CL *c2)
Performs classifier condition crossover.
Parameters
xcsf The XCSF data structure.
c1 The first classifier whose condition is being crossed.
c2 The second classifier whose condition is being crossed.
Returns
Whether any alterations were made.
Definition at line 40 of file condition.h.
Referenced by cond_crossover().
cond_impl_free
void(* CondVtbl::cond_impl_free) (const XCSF *xcsf, const CL *c)
Frees the memory used by the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be freed.
Definition at line 83 of file condition.h.
Referenced by cond_free().
cond_impl_general
_Bool(* CondVtbl::cond_impl_general) (const XCSF *xcsf, const CL *c1, const CL *c2)
Returns whether the condition of classifier c1 is more general than c2.
Parameters
xcsf The XCSF data structure.
c1 The classifier whose condition is tested to be more general.
c2 The classifier whose condition is tested to be more specific.
Returns
Whether the condition of c1 is more general than c2.
Definition at line 48 of file condition.h.
Referenced by cond_general().
cond_impl_init
void(* CondVtbl::cond_impl_init) (const XCSF *xcsf, CL *c)
Initialises a classifier's condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be initialised.
Definition at line 89 of file condition.h.
Referenced by cond_init().
cond_impl_load
size_t(* CondVtbl::cond_impl_load) (const XCSF *xcsf, CL *c, FILE *fp)
Reads the condition from a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be read.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 126 of file condition.h.
Referenced by cond_load().
cond_impl_match
_Bool(* CondVtbl::cond_impl_match) (const XCSF *xcsf, const CL *c, const double *x)
Calculates whether the condition matches the input.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition to match.
x The input state.
Returns
Whether the condition matches the input.
Definition at line 56 of file condition.h.
Referenced by cond_match().
cond_impl_mutate
_Bool(* CondVtbl::cond_impl_mutate) (const XCSF *xcsf, const CL *c)
Performs classifier condition mutation.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is being mutated.
Returns
Whether any alterations were made.
Definition at line 63 of file condition.h.
Referenced by cond_mutate().
cond_impl_print
void(* CondVtbl::cond_impl_print) (const XCSF *xcsf, const CL *c)
Prints the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be printed.
Definition at line 95 of file condition.h.
Referenced by cond_print().
cond_impl_save
size_t(* CondVtbl::cond_impl_save) (const XCSF *xcsf, const CL *c, FILE *fp)
Writes the condition to a binary file.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be written.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 118 of file condition.h.
Referenced by cond_save().
cond_impl_size
int(* CondVtbl::cond_impl_size) (const XCSF *xcsf, const CL *c)
Returns the size of the classifier condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition size to return.
Returns
The size of the condition.
Definition at line 110 of file condition.h.
Referenced by cond_size().
cond_impl_update
void(* CondVtbl::cond_impl_update) (const XCSF *xcsf, const CL *c, const double *x, const double *y)
Updates the classifier's condition.
Parameters
xcsf The XCSF data structure.
c The classifier whose condition is to be updated.
x The input state.
y The payoff value.
Definition at line 103 of file condition.h.
Referenced by cond_update().
The documentation for this struct was generated from the following file:
condition.h