XCSF: utils.h File Reference
utils.h File Reference
Utility functions for random number handling, etc.
Functions
double rand_normal (double mu, double sigma)
Returns a normal random float with specified mean and standard deviation.
double constrain (double min, double max, double a)
Returns a float constrained within the specified range.
double rand_uniform (double min, double max)
Returns a uniform random float [min,max].
int iconstrain (int min, int max, int a)
Returns an integer constrained within the specified range.
int irand_uniform (int min, int max)
Returns a uniform random integer [min,max] not inclusive of max.
void random_init ()
Initialises the pseudo-random number generator.
void float_to_binary (double f, char *binary, int bits)
Generates a binary string from a float.
Detailed Description
Utility functions for random number handling, etc.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file utils.h.
Function Documentation
constrain()
double constrain (double min, double max, double a)
Returns a float constrained within the specified range.
Parameters
min Minimum value.
max Maximum value.
a The value to be constrained.
Returns
The constrained number.
Definition at line 114 of file utils.c.
Referenced by cond_ellipsoid_mutate(), cond_rectangle_mutate(), mutate_eta(), neural_layer_connected_forward(), neural_output(), and node_activate().
float_to_binary()
void float_to_binary (double f, char * binary, int bits)
Generates a binary string from a float.
Parameters
f The float to binarise.
binary The converted binary string (set by this function).
bits The number of bits to use for binarising.
Definition at line 141 of file utils.c.
Referenced by cond_ternary_cover(), and cond_ternary_match().
iconstrain()
int iconstrain (int min, int max, int a)
Returns an integer constrained within the specified range.
Parameters
min Minimum value.
max Maximum value.
a The value to be constrained.
Returns
The constrained number.
Definition at line 128 of file utils.c.
Referenced by rule_dgp_act_compute(), and rule_neural_act_compute().
irand_uniform()
int irand_uniform (int min, int max)
Returns a uniform random integer [min,max] not inclusive of max.
Returns
A random integer.
Definition at line 64 of file utils.c.
References rand_uniform().
Referenced by act_integer_mutate(), act_integer_rand(), ea_subsume(), env_maze_reset(), graph_mutate(), graph_rand(), mutate_functions(), mutate_neurons(), pa_rand_action(), sam_rate_selection_adapt(), sam_rate_selection_init(), tree_crossover(), tree_grow(), tree_mutate(), and xcsf_select_sample().
rand_normal()
double rand_normal (double mu, double sigma)
Returns a normal random float with specified mean and standard deviation.
Parameters
mu Mean.
sigma Standard deviation.
Returns
A random float.
Box-Muller transform.
Definition at line 86 of file utils.c.
References drand().
Referenced by cond_ellipsoid_mutate(), cond_rectangle_mutate(), mutate_eta(), mutate_weights(), neural_layer_connected_init(), neural_layer_connected_rand(), neural_layer_connected_resize(), neural_layer_noise_forward(), neuron_add(), and sam_log_normal_adapt().
rand_uniform()
double rand_uniform (double min, double max)
Returns a uniform random float [min,max].
Returns
A random float.
Definition at line 73 of file utils.c.
References drand().
Referenced by act_integer_mutate(), clset_pop_roulette(), cond_ellipsoid_cover(), cond_ellipsoid_crossover(), cond_ellipsoid_init(), cond_gp_crossover(), cond_gp_mutate(), cond_rectangle_cover(), cond_rectangle_crossover(), cond_rectangle_init(), cond_ternary_cover(), cond_ternary_crossover(), cond_ternary_mutate(), cond_ternary_rand(), ea_select_rw(), ea_select_tournament(), env_mux_get_state(), graph_crossover(), graph_mutate(), graph_rand(), irand_uniform(), mutate_functions(), mutate_neurons(), neural_layer_connected_init(), neural_layer_dropout_forward(), neural_layer_noise_forward(), sam_log_normal_init(), sam_rate_selection_adapt(), tree_init_cons(), tree_mutate(), xcs_multi_trial(), and xcs_single_decision().
random_init()
void random_init ()
Initialises the pseudo-random number generator.
Definition at line 38 of file utils.c.
References init_genrand64().
Referenced by BOOST_PYTHON_MODULE(), and main().