XCSF: xcs_single_step.c File Reference
xcs_single_step.c File Reference
Single-step reinforcement learning functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "clset.h"
#include "pa.h"
#include "ea.h"
#include "perf.h"
#include "xcs_single_step.h"
#include "env.h"
Functions
static double xcs_single_trial (XCSF *xcsf, double *perf, _Bool explore)
Executes a single-step trial using a built-in environment.
double xcs_single_step_exp (XCSF *xcsf)
Executes a single-step experiment.
int xcs_single_decision (XCSF *xcsf, SET *mset, SET *kset, const double *x)
Constructs the match set and selects an action to perform.
void xcs_single_update (XCSF *xcsf, const SET *mset, SET *aset, SET *kset, const double *x, int a, double r)
Creates the action set, updates the classifiers and runs the EA.
double xcs_single_error (const XCSF *xcsf, double reward)
Returns the system error.
Detailed Description
Single-step reinforcement learning functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file xcs_single_step.c.
Function Documentation
xcs_single_decision()
int xcs_single_decision (XCSF * xcsf, SET * mset, SET * kset, const double * x)
Constructs the match set and selects an action to perform.
Parameters
xcsf The XCSF data structure.
mset The match set.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
Returns
The selected action.
Definition at line 113 of file xcs_single_step.c.
References clset_match(), clset_mfrac(), XCSF::mfrac, XCSF::msetsize, XCSF::P_EXPLORE, pa_best_action(), pa_build(), pa_rand_action(), XCSF::PERF_AVG_TRIALS, rand_uniform(), SET::size, and XCSF::train.
Referenced by XCS::single_decision(), and xcs_single_trial().
xcs_single_error()
double xcs_single_error (const XCSF * xcsf, double reward)
Returns the system error.
Parameters
xcsf The XCSF data structure.
reward The reward from performing the action.
Returns
The system prediction error.
Definition at line 149 of file xcs_single_step.c.
References pa_best_val().
Referenced by XCS::single_error(), and xcs_single_trial().
xcs_single_step_exp()
double xcs_single_step_exp (XCSF * xcsf)
Executes a single-step experiment.
Parameters
xcsf The XCSF data structure.
Returns
The mean prediction error.
Definition at line 46 of file xcs_single_step.c.
References disp_perf2(), gplot_free(), gplot_init(), XCSF::MAX_TRIALS, pa_free(), pa_init(), XCSF::PERF_AVG_TRIALS, and xcs_single_trial().
Referenced by main().
xcs_single_trial()
static double xcs_single_trial (XCSF * xcsf, double * perf, _Bool explore) static
Executes a single-step trial using a built-in environment.
Parameters
xcsf The XCSF data structure.
perf The classification accuracy (set by this function).
explore Whether this is an exploration or exploitation trial.
Returns
The system prediction error.
Definition at line 78 of file xcs_single_step.c.
References clset_free(), clset_init(), clset_kill(), env_execute(), env_get_state(), XCSF::train, xcs_single_decision(), xcs_single_error(), and xcs_single_update().
Referenced by xcs_single_step_exp().
xcs_single_update()
void xcs_single_update (XCSF * xcsf, const SET * mset, SET * aset, SET * kset, const double * x, int a, double r)
Creates the action set, updates the classifiers and runs the EA.
Parameters
xcsf The XCSF data structure.
mset The match set.
aset The action set.
kset A set to store deleted macro-classifiers for later memory removal.
x The input state.
a The action selected.
r The reward from performing the action.
Definition at line 135 of file xcs_single_step.c.
References clset_action(), clset_update(), ea(), and XCSF::time.
Referenced by XCS::single_update(), and xcs_single_trial().