XCSF: xcs_multi_step.c File Reference
xcs_multi_step.c File Reference
Multi-step reinforcement learning functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include "xcsf.h"
#include "utils.h"
#include "cl.h"
#include "cl_set.h"
#include "pa.h"
#include "ea.h"
#include "perf.h"
#include "xcs_multi_step.h"
#include "env.h"
Functions
static int xcs_multi_explore (XCSF *xcsf)
Executes a multi-step explore trial.
static int xcs_multi_exploit (XCSF *xcsf, double *error)
Executes a multi-step exploit trial.
double xcs_multi_step_exp (XCSF *xcsf)
Executes a multi-step reinforcement learning experiment.
Detailed Description
Multi-step reinforcement learning functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2019.
Definition in file xcs_multi_step.c.
Function Documentation
xcs_multi_exploit()
static int xcs_multi_exploit (XCSF * xcsf, double * error) static
Executes a multi-step exploit trial.
Parameters
xcsf The XCSF data structure.
error The prediction error (set by this function).
Returns
The number of steps taken to reach the goal.
Definition at line 143 of file xcs_multi_step.c.
References XCSF::BETA, env_execute(), env_get_state(), env_is_reset(), env_max_payoff(), env_reset(), XCSF::GAMMA, SET::list, XCSF::msetsize, XCSF::num_x_vars, pa_best_action(), pa_best_val(), pa_build(), pa_val(), set_action(), set_free(), set_init(), set_kill(), set_match(), set_update(), set_validate(), SET::size, XCSF::TELETRANSPORTATION, and XCSF::train.
Referenced by xcs_multi_step_exp().
xcs_multi_explore()
static int xcs_multi_explore (XCSF * xcsf) static
Executes a multi-step explore trial.
Parameters
xcsf The XCSF data structure.
Returns
The number of steps taken to reach the goal.
Definition at line 73 of file xcs_multi_step.c.
References XCSF::BETA, ea(), env_execute(), env_get_state(), env_is_reset(), env_reset(), XCSF::GAMMA, SET::list, XCSF::msetsize, XCSF::num_x_vars, XCSF::P_EXPLORE, pa_best_action(), pa_best_val(), pa_build(), pa_rand_action(), rand_uniform(), set_action(), set_free(), set_init(), set_kill(), set_match(), set_update(), set_validate(), SET::size, XCSF::TELETRANSPORTATION, XCSF::time, and XCSF::train.
Referenced by xcs_multi_step_exp().
xcs_multi_step_exp()
double xcs_multi_step_exp (XCSF * xcsf)
Executes a multi-step reinforcement learning experiment.
Parameters
xcsf The XCSF data structure.
Returns
The mean prediction error.
Definition at line 47 of file xcs_multi_step.c.
References disp_perf2(), gplot_free(), gplot_init(), XCSF::MAX_TRIALS, pa_free(), pa_init(), XCSF::PERF_AVG_TRIALS, xcs_multi_exploit(), and xcs_multi_explore().
Referenced by classification().