XCSF: xcs_single_step.h File Reference
xcs_single_step.h File Reference
Single-step reinforcement learning functions.
Functions
double xcs_single_error (const XCSF *xcsf, double reward)
Returns the system error.
double xcs_single_step_exp (XCSF *xcsf)
Executes a single-step reinforcement learning experiment.
int xcs_single_decision (XCSF *xcsf, const double *x)
Constructs the match set and selects an action to perform.
void xcs_single_free (XCSF *xcsf)
Frees memory used by match, action, and kill sets.
void xcs_single_init (XCSF *xcsf)
Initialises match, action, and kill sets.
void xcs_single_update (XCSF *xcsf, const double *x, int action, double reward)
Creates the action set, updates the classifiers and runs the EA.
Detailed Description
Single-step reinforcement learning functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file xcs_single_step.h.
Function Documentation
xcs_single_decision()
int xcs_single_decision (XCSF * xcsf, const double * x)
Constructs the match set and selects an action to perform.
Parameters
xcsf The XCSF data structure.
x The input state.
Returns
The selected action.
Definition at line 113 of file xcs_single_step.c.
References clset_match(), XCSF::P_EXPLORE, pa_best_action(), pa_build(), pa_rand_action(), rand_uniform(), and XCSF::train.
Referenced by XCS::single_decision(), and xcs_single_trial().
xcs_single_error()
double xcs_single_error (const XCSF * xcsf, double reward)
Returns the system error.
Parameters
xcsf The XCSF data structure.
reward The reward from performing the action.
Returns
The system prediction error.
Definition at line 143 of file xcs_single_step.c.
References pa_best_val().
Referenced by XCS::single_error(), and xcs_single_trial().
xcs_single_free()
void xcs_single_free (XCSF * xcsf)
Frees memory used by match, action, and kill sets.
Parameters
xcsf The XCSF data structure.
Definition at line 100 of file xcs_single_step.c.
References XCSF::aset, clset_free(), clset_kill(), XCSF::kset, and XCSF::mset.
Referenced by XCS::single_reset(), and xcs_single_trial().
xcs_single_init()
void xcs_single_init (XCSF * xcsf)
Initialises match, action, and kill sets.
Parameters
xcsf The XCSF data structure.
Definition at line 90 of file xcs_single_step.c.
References XCSF::aset, clset_init(), XCSF::kset, and XCSF::mset.
Referenced by XCS::XCS(), and xcs_single_trial().
xcs_single_step_exp()
double xcs_single_step_exp (XCSF * xcsf)
Executes a single-step reinforcement learning experiment.
Parameters
xcsf The XCSF data structure.
Returns
The mean accuracy.
Definition at line 45 of file xcs_single_step.c.
References XCSF::MAX_TRIALS, pa_free(), pa_init(), perf_print(), and xcs_single_trial().
Referenced by main().
xcs_single_update()
void xcs_single_update (XCSF * xcsf, const double * x, int action, double reward)
Creates the action set, updates the classifiers and runs the EA.
Parameters
xcsf The XCSF data structure.
x The input state.
action The action selected.
reward The reward from performing the action.
Definition at line 130 of file xcs_single_step.c.
References XCSF::aset, clset_action(), clset_update(), and ea().
Referenced by XCS::single_update(), and xcs_single_trial().