XCSF: xcs_supervised.c File Reference
xcs_supervised.c File Reference
Supervised regression learning functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h>
#include "xcsf.h"
#include "utils.h"
#include "loss.h"
#include "perf.h"
#include "cl.h"
#include "clset.h"
#include "ea.h"
#include "xcs_supervised.h"
Functions
static int xcs_supervised_sample (const INPUT *data, int cnt, _Bool shuffle)
Selects a data sample for training or testing.
static void xcs_supervised_trial (XCSF *xcsf, double *pred, const double *x, const double *y)
Executes a single XCSF trial.
double xcs_supervised_fit (XCSF *xcsf, const INPUT *train_data, const INPUT *test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training data and test iterations using the test data.
void xcs_supervised_predict (XCSF *xcsf, const double *x, double *pred, int n_samples)
Calculates the XCSF predictions for the provided input.
double xcs_supervised_score (XCSF *xcsf, const INPUT *test_data)
Calculates the XCSF error for the input data.
Detailed Description
Supervised regression learning functions.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file xcs_supervised.c.
Function Documentation
xcs_supervised_fit()
double xcs_supervised_fit (XCSF * xcsf, const INPUT * train_data, const INPUT * test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training data and test iterations using the test data.
Parameters
xcsf The XCSF data structure.
train_data The input data to use for training.
test_data The input data to use for testing.
shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 50 of file xcs_supervised.c.
References XCSF::loss_ptr, XCSF::MAX_TRIALS, perf_print(), XCSF::train, INPUT::x, INPUT::x_dim, xcs_supervised_sample(), xcs_supervised_trial(), INPUT::y, XCSF::y_dim, and INPUT::y_dim.
Referenced by XCS::fit(), and main().
xcs_supervised_predict()
void xcs_supervised_predict (XCSF * xcsf, const double * x, double * pred, int n_samples)
Calculates the XCSF predictions for the provided input.
Parameters
xcsf The XCSF data structure.
x The input feature variables.
pred The calculated XCSF predictions (set by this function).
n_samples The number of instances.
Definition at line 89 of file xcs_supervised.c.
References XCSF::train, XCSF::x_dim, xcs_supervised_trial(), and XCSF::y_dim.
Referenced by XCS::predict().
xcs_supervised_sample()
static int xcs_supervised_sample (const INPUT * data, int cnt, _Bool shuffle) static
Selects a data sample for training or testing.
Parameters
data The input data.
cnt The current sequence counter.
shuffle Whether to select the sample randomly.
Returns
The row of the data sample selected.
Definition at line 125 of file xcs_supervised.c.
References irand_uniform(), and INPUT::n_samples.
Referenced by xcs_supervised_fit().
xcs_supervised_score()
double xcs_supervised_score (XCSF * xcsf, const INPUT * test_data)
Calculates the XCSF error for the input data.
Parameters
xcsf The XCSF data structure.
test_data The input data to calculate the error.
Returns
The average XCSF error using the loss function.
Definition at line 103 of file xcs_supervised.c.
References XCSF::loss_ptr, INPUT::n_samples, XCSF::train, INPUT::x, INPUT::x_dim, xcs_supervised_trial(), INPUT::y, XCSF::y_dim, and INPUT::y_dim.
Referenced by XCS::score().
xcs_supervised_trial()
static void xcs_supervised_trial (XCSF * xcsf, double * pred, const double * x, const double * y) static
Executes a single XCSF trial.
Parameters
xcsf The XCSF data structure.
pred The calculated XCSF prediction (set by this function).
x The feature variables.
y The labelled variables.
Definition at line 140 of file xcs_supervised.c.
References clset_free(), clset_init(), clset_kill(), clset_match(), clset_pred(), clset_update(), ea(), XCSF::kset, XCSF::mset, and XCSF::train.
Referenced by xcs_supervised_fit(), xcs_supervised_predict(), and xcs_supervised_score().