XCSF: xcsf.h File Reference
xcsf.h File Reference
XCSF data structures.
Data Structures
struct CL
Classifier data structure.
struct CLIST
Classifier linked list.
struct SET
Classifier set.
struct XCSF
XCSF data structure.
struct INPUT
Input data structure.
Macros
#define COND_TYPE_DUMMY 0
Condition type dummy.
#define COND_TYPE_HYPERRECTANGLE 1
Condition type hyperrectangle.
#define COND_TYPE_HYPERELLIPSOID 2
Condition type hyperellipsoid.
#define COND_TYPE_NEURAL 3
Condition type neural network.
#define COND_TYPE_GP 4
Condition type tree GP.
#define COND_TYPE_DGP 5
Condition type DGP.
#define COND_TYPE_TERNARY 6
Condition type ternary.
#define RULE_TYPE_DGP 11
Condition type and action type DGP.
#define RULE_TYPE_NEURAL 12
Condition type and action type neural.
#define ACT_TYPE_INTEGER 0
Action type integer.
#define PRED_TYPE_CONSTANT 0
Prediction type constant.
#define PRED_TYPE_NLMS_LINEAR 1
Prediction type linear nlms.
#define PRED_TYPE_NLMS_QUADRATIC 2
Prediction type quadratic nlms.
#define PRED_TYPE_RLS_LINEAR 3
Prediction type linear rls.
#define PRED_TYPE_RLS_QUADRATIC 4
Prediction type quadratic rls.
#define PRED_TYPE_NEURAL 5
Prediction type neural.
#define MAX_LAYERS 100
Maximum number of neural network layers.
Typedefs
typedef struct CL CL
Classifier data structure.
typedef struct CLIST CLIST
Classifier linked list.
typedef struct SET SET
Classifier set.
typedef struct XCSF XCSF
XCSF data structure.
typedef struct INPUT INPUT
Input data structure.
Functions
double xcsf_fit (XCSF *xcsf, const INPUT *train_data, const INPUT *test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training. data and test iterations using the test data.
double xcsf_score (XCSF *xcsf, const INPUT *test_data)
Calculates the XCSF error for the input data.
double xcsf_version ()
Returns the XCSF version number.
size_t xcsf_load (XCSF *xcsf, const char *fname)
Reads the state of XCSF from a binary file.
size_t xcsf_save (const XCSF *xcsf, const char *fname)
Writes the current state of XCSF to a binary file.
void xcsf_init (XCSF *xcsf)
Initialises XCSF with an empty population.
void xcsf_predict (XCSF *xcsf, const double *x, double *pred, int rows)
Calculates the XCSF predictions for the provided input.
void xcsf_print_pop (const XCSF *xcsf, _Bool printc, _Bool printa, _Bool printp)
Prints the current XCSF population.
Detailed Description
XCSF data structures.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2019–2020.
Definition in file xcsf.h.
Macro Definition Documentation
ACT_TYPE_INTEGER
#define ACT_TYPE_INTEGER 0
Action type integer.
Definition at line 36 of file xcsf.h.
Referenced by action_set().
COND_TYPE_DGP
#define COND_TYPE_DGP 5
Condition type DGP.
Definition at line 31 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_DUMMY
#define COND_TYPE_DUMMY 0
Condition type dummy.
Definition at line 26 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_GP
#define COND_TYPE_GP 4
Condition type tree GP.
Definition at line 30 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_HYPERELLIPSOID
#define COND_TYPE_HYPERELLIPSOID 2
Condition type hyperellipsoid.
Definition at line 28 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_HYPERRECTANGLE
#define COND_TYPE_HYPERRECTANGLE 1
Condition type hyperrectangle.
Definition at line 27 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_NEURAL
#define COND_TYPE_NEURAL 3
Condition type neural network.
Definition at line 29 of file xcsf.h.
Referenced by condition_set().
COND_TYPE_TERNARY
#define COND_TYPE_TERNARY 6
Condition type ternary.
Definition at line 32 of file xcsf.h.
Referenced by condition_set().
MAX_LAYERS
#define MAX_LAYERS 100
Maximum number of neural network layers.
Definition at line 45 of file xcsf.h.
Referenced by XCS::get_cond_max_neurons(), XCS::get_cond_num_neurons(), XCS::get_pred_max_neurons(), XCS::get_pred_num_neurons(), params_cl_condition(), params_cl_prediction(), XCS::set_cond_max_neurons(), XCS::set_cond_num_neurons(), XCS::set_pred_max_neurons(), XCS::set_pred_num_neurons(), xcsf_load_params(), and xcsf_save_params().
PRED_TYPE_CONSTANT
#define PRED_TYPE_CONSTANT 0
Prediction type constant.
Definition at line 38 of file xcsf.h.
Referenced by prediction_set().
PRED_TYPE_NEURAL
#define PRED_TYPE_NEURAL 5
Prediction type neural.
Definition at line 43 of file xcsf.h.
Referenced by prediction_set().
PRED_TYPE_NLMS_LINEAR
#define PRED_TYPE_NLMS_LINEAR 1
Prediction type linear nlms.
Definition at line 39 of file xcsf.h.
Referenced by prediction_set().
PRED_TYPE_NLMS_QUADRATIC
#define PRED_TYPE_NLMS_QUADRATIC 2
Prediction type quadratic nlms.
Definition at line 40 of file xcsf.h.
Referenced by pred_nlms_compute(), pred_nlms_init(), pred_nlms_update(), and prediction_set().
PRED_TYPE_RLS_LINEAR
#define PRED_TYPE_RLS_LINEAR 3
Prediction type linear rls.
Definition at line 41 of file xcsf.h.
Referenced by prediction_set().
PRED_TYPE_RLS_QUADRATIC
#define PRED_TYPE_RLS_QUADRATIC 4
Prediction type quadratic rls.
Definition at line 42 of file xcsf.h.
Referenced by pred_rls_compute(), pred_rls_init(), pred_rls_update(), and prediction_set().
RULE_TYPE_DGP
#define RULE_TYPE_DGP 11
Condition type and action type DGP.
Definition at line 33 of file xcsf.h.
Referenced by condition_set().
RULE_TYPE_NEURAL
#define RULE_TYPE_NEURAL 12
Condition type and action type neural.
Definition at line 34 of file xcsf.h.
Referenced by condition_set().
Typedef Documentation
CL
typedef struct CL CL
Classifier data structure.
CLIST
typedef struct CLIST CLIST
Classifier linked list.
INPUT
typedef struct INPUT INPUT
Input data structure.
SET
typedef struct SET SET
Classifier set.
XCSF
typedef struct XCSF XCSF
XCSF data structure.
Function Documentation
xcsf_fit()
double xcsf_fit (XCSF * xcsf, const INPUT * train_data, const INPUT * test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training. data and test iterations using the test data.
Parameters
xcsf The XCSF data structure.
train_data The input data to use for training.
test_data The input data to use for testing.
shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 66 of file xcsf.c.
References XCSF::loss_ptr, XCSF::MAX_TRIALS, perf_print(), XCSF::train, INPUT::x, INPUT::x_cols, xcsf_select_sample(), xcsf_trial(), INPUT::y, INPUT::y_cols, and XCSF::y_dim.
Referenced by XCS::fit(), and main().
xcsf_init()
void xcsf_init (XCSF * xcsf)
Initialises XCSF with an empty population.
Parameters
xcsf The XCSF data structure.
Definition at line 49 of file xcsf.c.
References clset_init(), XCSF::mfrac, XCSF::msetsize, XCSF::pset, and XCSF::time.
Referenced by main(), and XCS::xcs_init().
xcsf_load()
size_t xcsf_load (XCSF * xcsf, const char * fname)
Reads the state of XCSF from a binary file.
Parameters
xcsf The XCSF data structure.
fname The name of the input file.
Returns
The total number of elements read.
Definition at line 210 of file xcsf.c.
References clset_init(), clset_kill(), clset_pop_load(), XCSF::pset, SET::size, VERSION, and xcsf_load_params().
Referenced by XCS::load(), and main().
xcsf_predict()
void xcsf_predict (XCSF * xcsf, const double * x, double * pred, int rows)
Calculates the XCSF predictions for the provided input.
Parameters
xcsf The XCSF data structure.
x The input feature variables.
pred The calculated XCSF predictions (set by this function).
rows The number of instances.
Definition at line 142 of file xcsf.c.
References XCSF::train, XCSF::x_dim, xcsf_trial(), and XCSF::y_dim.
Referenced by XCS::predict().
xcsf_print_pop()
void xcsf_print_pop (const XCSF * xcsf, _Bool printc, _Bool printa, _Bool printp)
Prints the current XCSF population.
Parameters
xcsf The XCSF data structure.
printc Whether to print condition structures.
printa Whether to print action structures.
printp Whether to print prediction structures.
Definition at line 178 of file xcsf.c.
References clset_print(), and XCSF::pset.
Referenced by XCS::print_pop().
xcsf_save()
size_t xcsf_save (const XCSF * xcsf, const char * fname)
Writes the current state of XCSF to a binary file.
Parameters
xcsf The XCSF data structure.
fname The name of the output file.
Returns
The total number of elements written.
Definition at line 189 of file xcsf.c.
References clset_pop_save(), VERSION, and xcsf_save_params().
Referenced by XCS::save().
xcsf_score()
double xcsf_score (XCSF * xcsf, const INPUT * test_data)
Calculates the XCSF error for the input data.
Parameters
xcsf The XCSF data structure.
test_data The input data to calculate the error.
Returns
The average XCSF error using the loss function.
Definition at line 156 of file xcsf.c.
References XCSF::loss_ptr, INPUT::rows, XCSF::train, INPUT::x, INPUT::x_cols, xcsf_trial(), INPUT::y, INPUT::y_cols, and XCSF::y_dim.
Referenced by XCS::score().
xcsf_version()
double xcsf_version ()
Returns the XCSF version number.
Returns
version number.
Definition at line 418 of file xcsf.c.
References VERSION.
Referenced by XCS::version().