XCSF: xcsf.c File Reference
xcsf.c File Reference
High level XCSF functions for executing training, predicting, saving and reloading the system from persistent storage, etc.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h>
#include "xcsf.h"
#include "utils.h"
#include "loss.h"
#include "perf.h"
#include "cl.h"
#include "clset.h"
#include "ea.h"
Functions
static double xcsf_learn_trial (XCSF *xcsf, double *pred, const double *x, const double *y)
Executes a single XCSF learning trial.
static double xcsf_test_trial (XCSF *xcsf, double *pred, const double *x, const double *y)
Executes a single XCSF testing trial.
static size_t xcsf_load_params (XCSF *xcsf, FILE *fp)
Reads the XCSF data structure from a binary file.
static size_t xcsf_save_params (const XCSF *xcsf, FILE *fp)
Writes the XCSF data structure to a binary file.
double xcsf_fit1 (XCSF *xcsf, const INPUT *train_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training data.
double xcsf_fit2 (XCSF *xcsf, const INPUT *train_data, const INPUT *test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training. data and test iterations using the test data.
void xcsf_predict (XCSF *xcsf, const double *x, double *pred, int rows)
Calculates the XCSF predictions for the provided input.
double xcsf_score (XCSF *xcsf, const INPUT *test_data)
Calculates the XCSF error for the input data.
void xcsf_print_pop (const XCSF *xcsf, _Bool printc, _Bool printa, _Bool printp)
Prints the current XCSF population.
void xcsf_print_match_set (XCSF *xcsf, const double *x, _Bool printc, _Bool printa, _Bool printp)
Prints the XCSF match set for the supplied input.
size_t xcsf_save (const XCSF *xcsf, const char *fname)
Writes the current state of XCSF to a binary file.
size_t xcsf_load (XCSF *xcsf, const char *fname)
Reads the state of XCSF from a binary file.
double xcsf_version ()
Returns the XCSF version number.
Variables
static const double VERSION = 1.06
XCSF version number.
Detailed Description
High level XCSF functions for executing training, predicting, saving and reloading the system from persistent storage, etc.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file xcsf.c.
Function Documentation
xcsf_fit1()
double xcsf_fit1 (XCSF * xcsf, const INPUT * train_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training data.
Parameters
xcsf The XCSF data structure.
train_data The input data to use for training.
shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 53 of file xcsf.c.
References xcsf_fit2().
Referenced by XCS::fit().
xcsf_fit2()
double xcsf_fit2 (XCSF * xcsf, const INPUT * train_data, const INPUT * test_data, _Bool shuffle)
Executes MAX_TRIALS number of XCSF learning iterations using the training. data and test iterations using the test data.
Parameters
xcsf The XCSF data structure.
train_data The input data to use for training.
test_data The input data to use for testing.
shuffle Whether to randomise the instances during training.
Returns
The average XCSF training error using the loss function.
Definition at line 68 of file xcsf.c.
References disp_perf1(), disp_perf2(), gplot_free(), gplot_init(), irand_uniform(), XCSF::MAX_TRIALS, XCSF::num_y_vars, XCSF::PERF_AVG_TRIALS, INPUT::rows, XCSF::train, INPUT::x, INPUT::x_cols, xcsf_learn_trial(), xcsf_test_trial(), INPUT::y, and INPUT::y_cols.
Referenced by XCS::fit(), main(), and xcsf_fit1().
xcsf_learn_trial()
static double xcsf_learn_trial (XCSF * xcsf, double * pred, const double * x, const double * y) static
Executes a single XCSF learning trial.
Parameters
xcsf The XCSF data structure.
pred The calculated XCSF prediction (set by this function).
x The feature variables.
y The labelled variables.
Returns
The XCSF training error using the loss function.
Definition at line 131 of file xcsf.c.
References XCSF::BETA, clset_free(), clset_init(), clset_kill(), clset_match(), clset_pred(), clset_update(), ea(), XCSF::loss_ptr, XCSF::msetsize, SET::size, and XCSF::time.
Referenced by xcsf_fit2().
xcsf_load()
size_t xcsf_load (XCSF * xcsf, const char * fname)
Reads the state of XCSF from a binary file.
Parameters
xcsf The XCSF data structure.
fname The name of the input file.
Returns
The total number of elements read.
Definition at line 271 of file xcsf.c.
References clset_init(), clset_kill(), clset_pop_load(), XCSF::pset, SET::size, VERSION, and xcsf_load_params().
Referenced by XCS::load(), and main().
xcsf_load_params()
static size_t xcsf_load_params (XCSF * xcsf, FILE * fp) static
Reads the XCSF data structure from a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the input file.
Returns
The total number of elements read.
Definition at line 385 of file xcsf.c.
References XCSF::ACT_TYPE, XCSF::ALPHA, XCSF::BETA, XCSF::COND_BITS, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX, XCSF::COND_MAX_HIDDEN_NEURONS, XCSF::COND_MIN, XCSF::COND_NUM_HIDDEN_NEURONS, XCSF::COND_SMIN, XCSF::COND_TYPE, XCSF::DELTA, XCSF::DGP_NUM_NODES, XCSF::E_MUTATION, XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::EA_SUBSUMPTION, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::F_MUTATION, XCSF::FIT_REDUC, XCSF::gp_cons, XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LAMBDA, XCSF::LOSS_FUNC, loss_set_func(), XCSF::MAX_K, XCSF::MAX_T, XCSF::MAX_TRIALS, XCSF::msetsize, XCSF::NU, XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, XCSF::OMP_NUM_THREADS, XCSF::P_CROSSOVER, XCSF::P_MUTATION, XCSF::PERF_AVG_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_NEURON_ACTIVATION, XCSF::PRED_MAX_HIDDEN_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_HIDDEN_NEURONS, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, XCSF::PRED_X0, XCSF::RESET_STATES, XCSF::S_MUTATION, XCSF::SAM_MIN, XCSF::SAM_NUM, XCSF::SAM_TYPE, XCSF::SET_SUBSUMPTION, XCSF::THETA_DEL, XCSF::THETA_EA, XCSF::THETA_SUB, XCSF::time, and XCSF::train.
Referenced by xcsf_load().
xcsf_predict()
void xcsf_predict (XCSF * xcsf, const double * x, double * pred, int rows)
Calculates the XCSF predictions for the provided input.
Parameters
xcsf The XCSF data structure.
x The input feature variables.
pred The calculated XCSF predictions (set by this function).
rows The number of instances.
Definition at line 177 of file xcsf.c.
References clset_free(), clset_init(), clset_kill(), clset_match(), clset_pred(), XCSF::num_x_vars, XCSF::num_y_vars, and XCSF::train.
Referenced by XCS::predict().
xcsf_print_match_set()
void xcsf_print_match_set (XCSF * xcsf, const double * x, _Bool printc, _Bool printa, _Bool printp)
Prints the XCSF match set for the supplied input.
Parameters
xcsf The XCSF data structure.
x The input features to perform matching.
printc Whether to print condition structures.
printa Whether to print action structures.
printp Whether to print prediction structures.
Definition at line 232 of file xcsf.c.
References clset_free(), clset_init(), clset_kill(), clset_match(), and clset_print().
Referenced by XCS::print_match_set().
xcsf_print_pop()
void xcsf_print_pop (const XCSF * xcsf, _Bool printc, _Bool printa, _Bool printp)
Prints the current XCSF population.
Parameters
xcsf The XCSF data structure.
printc Whether to print condition structures.
printa Whether to print action structures.
printp Whether to print prediction structures.
Definition at line 219 of file xcsf.c.
References clset_print(), and XCSF::pset.
Referenced by XCS::print_pop().
xcsf_save()
size_t xcsf_save (const XCSF * xcsf, const char * fname)
Writes the current state of XCSF to a binary file.
Parameters
xcsf The XCSF data structure.
fname The name of the output file.
Returns
The total number of elements written.
Definition at line 250 of file xcsf.c.
References clset_pop_save(), VERSION, and xcsf_save_params().
Referenced by XCS::save().
xcsf_save_params()
static size_t xcsf_save_params (const XCSF * xcsf, FILE * fp) static
Writes the XCSF data structure to a binary file.
Parameters
xcsf The XCSF data structure.
fp Pointer to the output file.
Returns
The total number of elements written.
Definition at line 302 of file xcsf.c.
References XCSF::ACT_TYPE, XCSF::ALPHA, XCSF::BETA, XCSF::COND_BITS, XCSF::COND_ETA, XCSF::COND_EVOLVE_FUNCTIONS, XCSF::COND_EVOLVE_NEURONS, XCSF::COND_EVOLVE_WEIGHTS, XCSF::COND_HIDDEN_NEURON_ACTIVATION, XCSF::COND_MAX, XCSF::COND_MAX_HIDDEN_NEURONS, XCSF::COND_MIN, XCSF::COND_NUM_HIDDEN_NEURONS, XCSF::COND_SMIN, XCSF::COND_TYPE, XCSF::DELTA, XCSF::DGP_NUM_NODES, XCSF::E_MUTATION, XCSF::EA_SELECT_SIZE, XCSF::EA_SELECT_TYPE, XCSF::EA_SUBSUMPTION, XCSF::EPS_0, XCSF::ERR_REDUC, XCSF::F_MUTATION, XCSF::FIT_REDUC, XCSF::gp_cons, XCSF::GP_INIT_DEPTH, XCSF::GP_NUM_CONS, XCSF::INIT_ERROR, XCSF::INIT_FITNESS, XCSF::LAMBDA, XCSF::LOSS_FUNC, XCSF::MAX_K, XCSF::MAX_T, XCSF::MAX_TRIALS, XCSF::msetsize, XCSF::NU, XCSF::num_actions, XCSF::num_x_vars, XCSF::num_y_vars, XCSF::OMP_NUM_THREADS, XCSF::P_CROSSOVER, XCSF::P_MUTATION, XCSF::PERF_AVG_TRIALS, XCSF::POP_INIT, XCSF::POP_SIZE, XCSF::PRED_ETA, XCSF::PRED_EVOLVE_ETA, XCSF::PRED_EVOLVE_FUNCTIONS, XCSF::PRED_EVOLVE_NEURONS, XCSF::PRED_EVOLVE_WEIGHTS, XCSF::PRED_HIDDEN_NEURON_ACTIVATION, XCSF::PRED_MAX_HIDDEN_NEURONS, XCSF::PRED_MOMENTUM, XCSF::PRED_NUM_HIDDEN_NEURONS, XCSF::PRED_RLS_LAMBDA, XCSF::PRED_RLS_SCALE_FACTOR, XCSF::PRED_SGD_WEIGHTS, XCSF::PRED_TYPE, XCSF::PRED_X0, XCSF::RESET_STATES, XCSF::S_MUTATION, XCSF::SAM_MIN, XCSF::SAM_NUM, XCSF::SAM_TYPE, XCSF::SET_SUBSUMPTION, XCSF::THETA_DEL, XCSF::THETA_EA, XCSF::THETA_SUB, XCSF::time, and XCSF::train.
Referenced by xcsf_save().
xcsf_score()
double xcsf_score (XCSF * xcsf, const INPUT * test_data)
Calculates the XCSF error for the input data.
Parameters
xcsf The XCSF data structure.
test_data The input data to calculate the error.
Returns
The average XCSF error using the loss function.
Definition at line 198 of file xcsf.c.
References XCSF::num_y_vars, INPUT::rows, XCSF::train, INPUT::x, INPUT::x_cols, xcsf_test_trial(), INPUT::y, and INPUT::y_cols.
Referenced by XCS::score().
xcsf_test_trial()
static double xcsf_test_trial (XCSF * xcsf, double * pred, const double * x, const double * y) static
Executes a single XCSF testing trial.
Parameters
xcsf The XCSF data structure.
pred The calculated XCSF prediction (set by this function).
x The feature variables.
y The labelled variables.
Returns
The XCSF testing error using the loss function.
Definition at line 156 of file xcsf.c.
References XCSF::BETA, clset_free(), clset_init(), clset_kill(), clset_match(), clset_pred(), XCSF::loss_ptr, XCSF::msetsize, and SET::size.
Referenced by xcsf_fit2(), and xcsf_score().
xcsf_version()
double xcsf_version ()
Returns the XCSF version number.
Returns
version number.
Definition at line 469 of file xcsf.c.
References VERSION.
Referenced by XCS::version().
Variable Documentation
VERSION
const double VERSION = 1.06 static
XCSF version number.
Definition at line 38 of file xcsf.c.
Referenced by xcsf_load(), xcsf_save(), and xcsf_version().