XCSF: env.h File Reference
env.h File Reference
Built-in problem environment interface.
Data Structures
struct EnvVtbl
Built-in problem environment interface data structure.
Functions
void env_init (XCSF *xcsf, char **argv)
Initialises a built-in problem environment.
static _Bool env_is_reset (const XCSF *xcsf)
static _Bool env_multistep (const XCSF *xcsf)
static double env_execute (const XCSF *xcsf, int action)
static double env_max_payoff (const XCSF *xcsf)
static const double * env_get_state (const XCSF *xcsf)
static void env_free (const XCSF *xcsf)
static void env_reset (const XCSF *xcsf)
Detailed Description
Built-in problem environment interface.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2015–2020.
Definition in file env.h.
Function Documentation
env_execute()
static double env_execute (const XCSF * xcsf, int action) inline static
Definition at line 84 of file env.h.
References EnvVtbl::env_impl_execute, and XCSF::env_vptr.
Referenced by xcs_multi_trial(), and xcs_single_trial().
env_free()
static void env_free (const XCSF * xcsf) inline static
Definition at line 96 of file env.h.
References EnvVtbl::env_impl_free, and XCSF::env_vptr.
Referenced by main().
env_get_state()
static const double* env_get_state (const XCSF * xcsf) inline static
Definition at line 92 of file env.h.
References EnvVtbl::env_impl_get_state, and XCSF::env_vptr.
Referenced by xcs_multi_trial(), and xcs_single_trial().
env_init()
void env_init (XCSF * xcsf, char ** argv)
Initialises a built-in problem environment.
Parameters
xcsf The XCSF data structure.
argv The command line arguments.
Definition at line 42 of file env.c.
References env_csv_init(), env_csv_vtbl, env_maze_init(), env_maze_vtbl, env_mux_init(), env_mux_vtbl, and XCSF::env_vptr.
Referenced by main().
env_is_reset()
static _Bool env_is_reset (const XCSF * xcsf) inline static
Definition at line 76 of file env.h.
References EnvVtbl::env_impl_isreset, and XCSF::env_vptr.
Referenced by xcs_multi_trial().
env_max_payoff()
static double env_max_payoff (const XCSF * xcsf) inline static
Definition at line 88 of file env.h.
References EnvVtbl::env_impl_max_payoff, and XCSF::env_vptr.
Referenced by xcs_multi_trial().
env_multistep()
static _Bool env_multistep (const XCSF * xcsf) inline static
Definition at line 80 of file env.h.
References EnvVtbl::env_impl_multistep, and XCSF::env_vptr.
Referenced by main().
env_reset()
static void env_reset (const XCSF * xcsf) inline static
Definition at line 100 of file env.h.
References EnvVtbl::env_impl_reset, and XCSF::env_vptr.
Referenced by xcs_multi_trial().