XCSF: gp.c File Reference
gp.c File Reference
An implementation of GP trees based upon TinyGP.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include "xcsf.h"
#include "utils.h"
#include "gp.h"
Macros
#define GP_MAX_LEN 10000
Maximum length of a GP tree.
#define GP_NUM_FUNC 4
Number of selectable GP functions.
#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3
Functions
static int tree_grow (const XCSF *xcsf, int *buffer, int p, int max, int depth)
Grows a random GP tree of specified max length and depth.
static int tree_traverse (int *tree, int p)
Traverses a GP tree.
void tree_init_cons (XCSF *xcsf)
Initialises the constants shared among all GP trees.
void tree_free_cons (const XCSF *xcsf)
Frees the constants shared among all GP trees.
void tree_rand (const XCSF *xcsf, GP_TREE *gp)
Creates a random GP tree.
void tree_free (const XCSF *xcsf, const GP_TREE *gp)
Frees a GP tree.
double tree_eval (const XCSF *xcsf, GP_TREE *gp, const double *x)
Evaluates a GP tree.
int tree_print (const XCSF *xcsf, const GP_TREE *gp, int p)
Prints a GP tree.
void tree_copy (const XCSF *xcsf, GP_TREE *to, const GP_TREE *from)
Copies a GP tree.
void tree_crossover (const XCSF *xcsf, GP_TREE *p1, GP_TREE *p2)
Performs sub-tree crossover.
void tree_mutate (const XCSF *xcsf, const GP_TREE *gp, double rate)
Performs point mutation on a GP tree.
size_t tree_save (const XCSF *xcsf, const GP_TREE *gp, FILE *fp)
Writes the GP tree to a binary file.
size_t tree_load (const XCSF *xcsf, GP_TREE *gp, FILE *fp)
Reads a GP tree from a binary file.
Detailed Description
An implementation of GP trees based upon TinyGP.
Author
Richard Preen rpree.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om
Copyright
The Authors.
Date
2016–2020.
For a more detailed description see: Poli, R., Langdon, W. B., and McPhee, N. F. (2008) "A Field Guide to Genetic Programming"
See also
https://dces.essex.ac.uk/staff/rpoli/gp-field-guide/A_Field_Guide_to_Genetic_Programming.pdf
Definition in file gp.c.
Macro Definition Documentation
ADD
#define ADD 0
Definition at line 40 of file gp.c.
Referenced by tree_eval(), tree_grow(), tree_print(), and tree_traverse().
DIV
#define DIV 3
Definition at line 43 of file gp.c.
Referenced by tree_eval(), tree_grow(), tree_print(), and tree_traverse().
GP_MAX_LEN
#define GP_MAX_LEN 10000
Maximum length of a GP tree.
Definition at line 38 of file gp.c.
Referenced by tree_rand().
GP_NUM_FUNC
#define GP_NUM_FUNC 4
Number of selectable GP functions.
Definition at line 39 of file gp.c.
Referenced by tree_eval(), tree_grow(), tree_mutate(), tree_print(), and tree_traverse().
MUL
#define MUL 2
Definition at line 42 of file gp.c.
Referenced by tree_eval(), tree_grow(), tree_print(), and tree_traverse().
SUB
#define SUB 1
Definition at line 41 of file gp.c.
Referenced by tree_eval(), tree_grow(), tree_print(), and tree_traverse().
Function Documentation
tree_copy()
void tree_copy (const XCSF * xcsf, GP_TREE * to, const GP_TREE * from)
Copies a GP tree.
Parameters
xcsf The XCSF data structure.
to The destination GP tree.
from The source GP tree.
Definition at line 232 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_copy().
tree_crossover()
void tree_crossover (const XCSF * xcsf, GP_TREE * p1, GP_TREE * p2)
Performs sub-tree crossover.
Parameters
xcsf The XCSF data structure.
p1 The first GP tree to perform crossover.
p2 The second GP tree to perform crossover.
Definition at line 247 of file gp.c.
References irand_uniform(), GP_TREE::len, GP_TREE::tree, tree_free(), and tree_traverse().
Referenced by cond_gp_crossover().
tree_eval()
double tree_eval (const XCSF * xcsf, GP_TREE * gp, const double * x)
Evaluates a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to evaluate.
x The input state.
Returns
The result from evaluating the GP tree.
Definition at line 152 of file gp.c.
References ADD, DIV, XCSF::gp_cons, XCSF::GP_NUM_CONS, GP_NUM_FUNC, MUL, GP_TREE::p, SUB, GP_TREE::tree, and tree_eval().
Referenced by cond_gp_match(), and tree_eval().
tree_free()
void tree_free (const XCSF * xcsf, const GP_TREE * gp)
Frees a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to free.
Definition at line 90 of file gp.c.
References GP_TREE::tree.
Referenced by cond_gp_free(), cond_gp_rand(), and tree_crossover().
tree_free_cons()
void tree_free_cons (const XCSF * xcsf)
Frees the constants shared among all GP trees.
Parameters
xcsf The XCSF data structure.
Definition at line 64 of file gp.c.
References XCSF::gp_cons.
Referenced by config_free().
tree_grow()
static int tree_grow (const XCSF * xcsf, int * buffer, int p, int max, int depth) static
Grows a random GP tree of specified max length and depth.
Parameters
xcsf The XCSF data structure.
buffer Buffer to hold the flattened GP tree generated.
p The position from which to traverse (start at 0).
max Maximum tree length.
depth Maximum tree depth.
Returns
The position after traversal (i.e., tree length).
Only used to create an initial tree.
Definition at line 107 of file gp.c.
References ADD, DIV, XCSF::GP_NUM_CONS, GP_NUM_FUNC, irand_uniform(), MUL, XCSF::num_x_vars, and SUB.
Referenced by tree_rand().
tree_init_cons()
void tree_init_cons (XCSF * xcsf)
Initialises the constants shared among all GP trees.
Parameters
xcsf The XCSF data structure.
Definition at line 52 of file gp.c.
References XCSF::COND_MAX, XCSF::COND_MIN, XCSF::gp_cons, XCSF::GP_NUM_CONS, and rand_uniform().
Referenced by config_init().
tree_load()
size_t tree_load (const XCSF * xcsf, GP_TREE * gp, FILE * fp)
Reads a GP tree from a binary file.
Parameters
xcsf The XCSF data structure.
gp The GP tree to load.
fp Pointer to the file to be read.
Returns
The number of elements read.
Definition at line 345 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_load().
tree_mutate()
void tree_mutate (const XCSF * xcsf, const GP_TREE * gp, double rate)
Performs point mutation on a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to be mutated.
rate The per allele rate of mutation.
Definition at line 279 of file gp.c.
References XCSF::GP_NUM_CONS, GP_NUM_FUNC, irand_uniform(), GP_TREE::len, XCSF::num_x_vars, rand_uniform(), and GP_TREE::tree.
Referenced by cond_gp_mutate().
tree_print()
int tree_print (const XCSF * xcsf, const GP_TREE * gp, int p)
Prints a GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree to print.
p The position from which to traverse (start at 0).
Returns
The position after traversal.
Definition at line 193 of file gp.c.
References ADD, DIV, XCSF::gp_cons, XCSF::GP_NUM_CONS, GP_NUM_FUNC, MUL, SUB, GP_TREE::tree, and tree_print().
Referenced by cond_gp_print(), and tree_print().
tree_rand()
void tree_rand (const XCSF * xcsf, GP_TREE * gp)
Creates a random GP tree.
Parameters
xcsf The XCSF data structure.
gp The GP tree being randomised.
Definition at line 74 of file gp.c.
References XCSF::GP_INIT_DEPTH, GP_MAX_LEN, GP_TREE::len, GP_TREE::tree, and tree_grow().
Referenced by cond_gp_init(), and cond_gp_rand().
tree_save()
size_t tree_save (const XCSF * xcsf, const GP_TREE * gp, FILE * fp)
Writes the GP tree to a binary file.
Parameters
xcsf The XCSF data structure.
gp The GP tree to save.
fp Pointer to the file to be written.
Returns
The number of elements written.
Definition at line 328 of file gp.c.
References GP_TREE::len, GP_TREE::p, and GP_TREE::tree.
Referenced by cond_gp_save().
tree_traverse()
static int tree_traverse (int * tree, int p) static
Traverses a GP tree.
Parameters
tree The tree to traverse.
p The position from which to traverse.
Returns
The position after traversal.
Definition at line 302 of file gp.c.
References ADD, DIV, GP_NUM_FUNC, MUL, and SUB.
Referenced by tree_crossover().